### ISSUE TITLE
[Playground Widget] "Data Service" example return data needs to improve

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-dev-website#100]
**Description:**
Need to update the DB with some realistic information data.

![image](https://user-images.githubusercontent.com/7569427/40899414-7f0b042c-67e4-11e8-816c-05de0cbdabe7.png)

**Affected Product Version:**
v0.9.016
 
**OS, DB, other environment details and versions:**
All

**Steps to reproduce:**
1. Navigate to home page
2. On the playground widget select Data Service and click "Run"

**Comment by praneesha** [comment]
Closing since we do not have the playground widget in the new B.io design[1].

[1] https://ballerina.io/
