### ISSUE TITLE
[Quick Start] some improvement for docker related steps focusing on Ubuntu OS

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-dev-website#102]
**Description:**
Its good if the following can be updated on the document to support ubuntu platforms
1.The document should state that the docker commands has to be run as sudo

2.The command [a] can also be run without  -p 9090:9090. If we run the command on the document we get an error as[b]. We could mention that -p is optional 
[a] sudo docker run -d -p 9090:9090 registry.hub.docker.com/helloworld:v1.0

[b] Error starting userland proxy: listen tcp 0.0.0.0:9090: bind: address already in use.

3.The output from[c] is shown in the document as` ID:991212870376534016` but it should be` Hello Ballerina!`. Please check this point again

[c]curl -d "Hello Ballerina" -X POST localhost:9090

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since the suggestions are not applicable to the revamped new Quick Tour[1].

[1] https://ballerina.io/learn/quick-tour/
