### ISSUE TITLE
Type system examples on https://ballerina.io/philosophy/ seems very dense and without any guidelines as comments

### ISSUE THREAD

**Issue by chintana-zz** [ballerina-platform/ballerina-dev-website#103]
**Description:**
Is it possible to have some comments explaining type system statements we have in https://ballerina.io/philosophy/?

<img width="584" alt="screen shot 2018-05-01 at 12 57 20 pm" src="https://user-images.githubusercontent.com/27903/39490923-69bbe1e6-4d3f-11e8-8802-86b2e975a2c1.png">

I think if we can reduce font size, have comments explaining types and have some line breaks this can be much more readable.

Something like this,

<img width="581" alt="screen shot 2018-05-01 at 1 51 59 pm" src="https://user-images.githubusercontent.com/27903/39493219-e4d4a0be-4d46-11e8-9666-2777568697fd.png">

**Comment by praneesha** [comment]
Closing as this is not applicable to the the new design[1].

[1] https://ballerina.io/
