### ISSUE TITLE
Entire page scrolls when scolling inside example code block

### ISSUE THREAD

**Issue by chintana-zz** [ballerina-platform/ballerina-dev-website#104]
**Description:**
When scrolling the code in  example block on home page, the entire page scrolls as well. This is a bit distracting. See below,

![bio-scroll-issue](https://user-images.githubusercontent.com/27903/39333748-dadfa822-4960-11e8-90be-2a69157a721d.gif)

**OS, DB, other environment details and versions:**    

Firefox 59.0.2

**Comment by praneesha** [comment]
Closing since this is not applicable now with the new B.io design[1].

[1] https://ballerina.io/
