### ISSUE TITLE
Google searches returns invalid pages

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#108]
A lot of people tend to google for finding API docs etc. related to Ballerina. And most of the top results tend to be old links which don't exist anymore and hence returns 404. Is there something we can do about this, to ensure the old pages are removed from the indexing? Or does this have to happen in time?

**Comment by praneesha** [comment]
For example, if you search in Google for "ballerina HTTP" the first search result gives a 404 Error as shown below:

<img width="884" alt="Screenshot 2019-11-27 at 12 16 51" src="https://user-images.githubusercontent.com/11707273/69700193-df7e4f00-110f-11ea-8fb1-605b1ffa553e.png">
<img width="1680" alt="Screenshot 2019-11-27 at 12 17 01" src="https://user-images.githubusercontent.com/11707273/69700194-e016e580-110f-11ea-9cbb-fff1a0f75749.png">

**Comment by praneesha** [comment]
Closing as this is fixed now.
