### ISSUE TITLE
SwanLake BBE - Copy to clipboard button issue

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#1104]
**Description:**
In Swan lake version of BBEs , when we click on copy to clip board button it copies output text as well. (Not only the source code)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chamil321** [comment]
Adding more to the issue, this behavior is seen only for the swan-lake

**Comment by praneesha** [comment]
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/288.
