### ISSUE TITLE
Add Line Numbers in Code Snippets

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1117]
**Description:**
We do not have line numbers applied in code snippets when the new syntax highlighter implementation is used.

New implementation (in dev site):
<img width="1085" alt="current" src="https://user-images.githubusercontent.com/11707273/88918907-e7d2ef00-d287-11ea-9e91-f830ad00db2f.png">

Previous implementation (in live site):

<img width="1081" alt="old" src="https://user-images.githubusercontent.com/11707273/88918944-f4574780-d287-11ea-9107-8b43fe6a9d43.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
Fixed.
<img width="1427" alt="Screen Shot 2020-08-06 at 6 59 13 PM" src="https://user-images.githubusercontent.com/6144466/89537459-03557100-d817-11ea-8146-56726d947ae5.png">
