### ISSUE TITLE
Fix the Different Style in Code Snippets in Why Ballerina Pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1118]
**Description:**
Need to fix the different style below (the teal color border, font size, and border padding) applied in the code snippets in "Why Ballerina" pages when compared to the Learn pages (the grey color border, font size,  and border padding).

**Why Ballerina pages:**

<img width="1090" alt="new" src="https://user-images.githubusercontent.com/11707273/88919540-e48c3300-d288-11ea-9956-5dec86c5f8b0.png">

**Learn pages:**

<img width="793" alt="Screenshot 2020-07-30 at 17 20 35" src="https://user-images.githubusercontent.com/11707273/88919599-02f22e80-d289-11ea-9396-25dc45d01ce8.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
Fixed

<img width="1410" alt="Screen Shot 2020-08-06 at 6 56 48 PM" src="https://user-images.githubusercontent.com/6144466/89537233-a8bc1500-d816-11ea-9098-37d0163181c2.png">
![Screenshot_2020-08-06 Ballerina - The Network in the Language](https://user-images.githubusercontent.com/6144466/89537255-b1145000-d816-11ea-9f72-e43faf7052c6.png)
