### ISSUE TITLE
The Layout in BBE Pages Between the Code and Output Appear to be Broken 

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1119]
**Description:**
The layout in BBE Pages between the code and output appear to be broken after the new syntax highlighter implementation.

**New implementation:**

![new](https://user-images.githubusercontent.com/11707273/88920505-9bd57980-d28a-11ea-92af-74e83c2c39d4.png)

**Previous implementation:**

![old](https://user-images.githubusercontent.com/11707273/88920694-e48d3280-d28a-11ea-81bc-7713a94c0e62.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
Fixed.
![Screenshot_2020-08-06 Ballerina - Server Streaming](https://user-images.githubusercontent.com/6144466/89537762-6515db00-d817-11ea-85a7-a9f20928b34b.png)
