### ISSUE TITLE
All table query examples giving 404s except the first

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#116]
**Description:**
In the site all table query examples except for the first one is giving me 404s : https://ballerina.io/learn/by-example/

**Comment by praneesha** [comment]
The below links are broken.

<img width="1141" alt="Screenshot 2019-11-29 at 15 07 06" src="https://user-images.githubusercontent.com/11707273/69859414-227c2600-12ba-11ea-82d0-5bf04bda4a6e.png">

**Comment by praneesha** [comment]
Checked the links and now they are being directed properly to the respective BBEs.
