### ISSUE TITLE
Layout of All the BBEs in Bio v1.0 are Broken

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1170]
**Description:**
Need to fix the layout of all the V1.0 BBEs on Bio. Currently, they look like in the example shown below.

![1 0-bbe](https://user-images.githubusercontent.com/11707273/90337772-57740880-e002-11ea-967b-af2dd3639a35.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
Fixed 
![screencapture-dev-ballerina-io-1-0-learn-by-example-xml-access-html-2020-08-17-21_13_12](https://user-images.githubusercontent.com/6144466/90415380-a1c2bb80-e0ce-11ea-87bc-8521b24a2867.png)
