### ISSUE TITLE
 Add a Spell Checker to the Pre-Prod Site as a GitHub Action

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1178]
**Description:**
We can add a Spell Checker such as [1] to the Dev Site via GitHub Actions. Or add a spell checker plugin like [2] with a dictionary such as [3].

[1] https://github.com/marketplace/actions/check-spelling
[2] https://www.cloudbees.com/blog/improve-documentation-by-automating-spelling-and-grammar-checks
[3] http://hunspell.github.io/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Need to check on adding a hunspell-based spell checker to the documentation local build of Bio.

**Comment by anupama-pathirage** [comment]
Looping @keizer619 and @sm1990 for prioritization of this.

**Comment by sm1990** [comment]
I think a better solution would be to review the `md` and `js` files using a workflow.

**Comment by keizer619** [comment]
> I think a better solution would be to review the `md` and `js` files using a workflow.

+1 Lets include in source level

**Comment by sm1990** [comment]
Closing this as we have decided to review the content in the source level. 
The new effort will be captured via https://github.com/ballerina-platform/ballerina-dev-website/issues/9536
