### ISSUE TITLE
Fix the Alignment Issue in the Learn Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#119]
**Description:**
We need to fix the below alignment issue introduced by the fix done in [1] in the Learn page.

<img width="1104" alt="69853107-f9ed2f80-12ab-11ea-9ab1-336e9863d5b9" src="https://user-images.githubusercontent.com/11707273/69853592-500ea280-12ad-11ea-87e6-8b817496f4c8.png">

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/53/files#r352014582

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
@praneesha : IMO, The sentence is too long, Can we consider having a shorter but catchy sentence as in the previous two boxes?

https://github.com/ballerina-platform/ballerina-dev-website/pull/53/files#r352016229

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/126/files as shown below.

<img width="1192" alt="Screenshot 2019-12-02 at 13 16 02" src="https://user-images.githubusercontent.com/11707273/69939569-2bf9ce00-1506-11ea-8635-7230d0a94bbc.png">
