### ISSUE TITLE
Need to Support Multiple Repos in the Edit on GitHub Option of BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1194]
**Description:**
Currently, the Go Tool, which is used to generate BBEs has the base URL of the Edit on GitHub options of all BBEs (in both Swan Lake and 1.2.x) are hard coded as follows.

<img width="1680" alt="Screenshot 2020-08-21 at 10 21 22" src="https://user-images.githubusercontent.com/11707273/90853543-154b1e00-e398-11ea-8406-46139f6fd36c.png">

Since now we are moving standard library modules to independent repos, we need to edit the implementation of the Go Tool to pick different repos for the Edit on GitHub base URL when generating the BBEs.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
I've done a fix for this now, where we can now mention the GitHub link by specifying the property "githubLink" in the index.json/all-bbes.json. Example:-

```
[{
        "title": "Hello World",
        "column": 0,
        "category": "Language concepts",
        "samples": [
            {
                "name": "Hello World Main",
                "url": "hello-world"
            },
            {
                "name": "Hello World Client",
                "url": "hello-world-client"
            }
        ]
    },
 	{
        "title": "Ballerina Basics",
        "column": 0,
        "category": "Language concepts",
        "samples": [
            {
                "name": "Functions",
                "url": "functions",
                "githubLink": "https://github.com/ballerina-platform/ballerina-lang/tree/ballerina-1.2.x/examples/functions/"
            }
        ]
    }
]
```

The BBEs which does not have the "githubLink" property, it will use the default GitHub link location from "https://github.com/ballerina-platform/ballerina-distribution/tree/master".
