### ISSUE TITLE
Need to Differentiate BBEs that Cannot be Run via the Playground

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1255]
**Description:**
Need to add a way to differentiate the BBEs that cannot be run via the Playground when the Play button is clicked in those BBEs. For instance, MySQL connector BBE[1], needs a running MySQL server to run properly. 

One way would be to add an error message page such as [2].

[1] http://dev.ballerina.io/swan-lake/learn/by-example/mysql-init-options.html
[2] https://ballerina.io/1.1/page-not-available.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
Now, individual BBEs can be configured to disable the playground link generation, by setting "disablePlayground": false in the BBE metadata in index.json. Example:-

```json
{
        "title": "Ballerina Basics",
        "column": 0,
        "category": "Language concepts",
        "samples": [
            {
                "name": "Functions",
                "url": "functions",
                "githubLink": "https://github.com/ballerina-platform/ballerina-lang/tree/ballerina-1.2.x/examples/functions/",
                "disablePlayground": true
            }
        ]
}
```
