### ISSUE TITLE
Add a page for contributing guide in b.io

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#128]
**Description:**

We have linked "Contributor Guide" [1] from the Ballerina "Community"[2] page. But that guide points to a .md file in the github repo. IMO, this should be converted to a page in ballerina.io. 

For example, check the the other languages like rust, go lang

[1] https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md
[2] https://ballerina.io/community/
[3] https://prev.rust-lang.org/en-US/contribute.html
[4] https://golang.org/doc/contribute.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is done via https://github.com/ballerina-platform/ballerina-dev-website/pull/177.
