### ISSUE TITLE
Improve existing redirection when navigating from an unavailable BBE in Swan Lake to the same BBE  available in 1.2

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-dev-website#1321]
**Description:**
Follow the following steps
1. Go to https://dev.ballerina.io/learn/by-example/xa-transactions.html 
2. Change the version to swan lake - This gives page-not-available (as expected)
3. Then change the version back to 1.2 - This currently gives a 404
Here `XA Transactions` BBE is available for 1.2 version while it's not available in Swan Lake. It would be better if we could redirect the user to the `XA Transactions` BBE for 1.2 version since it's available for that version rather than giving a 404. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
The issue here is when the 404 error is presented the URL doesn get changed but when the "Page not available" page gets displayed, the URL gets changed preventing the ability to jump to another version via the version drop down menu.

**Comment by praneesha** [comment]
The discussed fix is to hide the version picker in the "Page Not Available" error page. Will be done via https://github.com/ballerina-platform/ballerina-dev-website/issues/1687.

**Comment by praneesha** [comment]
The "Go Back" link is added via https://github.com/ballerina-platform/ballerina-dev-website/pull/1690.

**Comment by praneesha** [comment]
The version picker is hidden in both the "404" and "Page Not Available" pages via [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1803
