### ISSUE TITLE
Remove the unnecessary tools and ides page from b.io

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#136]
**Description:**

Currently, we have a page in b.io named "Tools and IDEs"[1] which is not directly linked from the learn page.

We have separate pages for VSCode[2] and IDEA plugins[3] and testerina and openAPI stuff are already covered with BBEs. So this page is redundant.  

With this change, we need to do the followings as well.

- Remove all "Tools and IDEs" bullet from the "What's next" section of each vscode feature page[4],[5],[6],[7]. 
<img width="850" alt="image" src="https://user-images.githubusercontent.com/16300038/70029425-1b605b00-15cd-11ea-94cd-0bcb8b64c9c9.png">

- Consider moving VSCode[2] and IDEA plugins[3] directly under ttps://ballerina.io/learn/ page. Otherwise, url will cause issues.
<img width="398" alt="image" src="https://user-images.githubusercontent.com/16300038/70029520-4f3b8080-15cd-11ea-84ed-bbd8cd0c4ca1.png">

[1] https://ballerina.io/learn/tools-ides/
[2] https://ballerina.io/learn/tools-ides/vscode-plugin/#using-the-vs-code-editor
[3] https://ballerina.io/learn/tools-ides/intellij-plugin/
[4] https://ballerina.io/learn/tools-ides/vscode-plugin/language-intelligence
[5] https://ballerina.io/learn/tools-ides/vscode-plugin/run-and-debug
[6]https://ballerina.io/learn/tools-ides/vscode-plugin/graphical-editor
[7] https://ballerina.io/learn/tools-ides/vscode-plugin/documentation-viewer

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
We might need this page if the design will be changed in the future to add a Tooling section in the Learn page or as a top-menu item.

Therefore, +1 for the other changes without deleting/removing the Tools & IDEs page.

**Comment by anupama-pathirage** [comment]
Can't we add it later if we decide in future?. Right now we are keeping some unwanted stuff which doesn't have any direct link as well.

**Comment by praneesha** [comment]
Removing it would be feasible if we have another location to move it for future use. If not, the effort on rewriting the content from scratch later is an overhead, IMO. It is just one page that we are keeping and I believe the revamping would happen pretty soon.

**Comment by anupama-pathirage** [comment]
We don't need to write from scratch as we can use git history to get the content back. IMO, even though it is one page it is not good from an external user's point of view.

**Comment by praneesha** [comment]
+1 Will remove the page.

**Comment by praneesha** [comment]
@anupama-pathirage - Why do we need to move docs on VSCode and IDEA plugins directly under https://ballerina.io/learn?

IMO, it that URL appears to be more structured to have this under this folder and also helps to maintain scalability when we add more tools or plugins in the future. WDYT?

**Comment by anupama-pathirage** [comment]
@praneesha As already pointed out in the original issue description, the reason is having a page [1]. IINM, this page was supposed to remove from the website. Reasons are:

- All the content other than VSCode and IDEA plugin (Docerina, API generator, testerina) are already covered by BBEs.
- This page is not directly linked from anywhere in the b.io. Can be accessed only by removing the IDE part from those urls.

So IMO, keeping this page is not needed.

[1] https://ballerina.io/v1-1/learn/tools-ides/

**Comment by praneesha** [comment]
@anupama-pathirage As mentioned above, I am +1 to remove the Tooling page from B.io. My doubt was about why we should remove the `tools-and-ides` folder from the folder structure of the `ballerina-dev-website` GitHib repo. IMO, we need it for scalability and clarity when adding more tools in the future. Also, I don't think that affects the URL.

WDYT?

**Comment by anupama-pathirage** [comment]
As long as the pages are properly linked and redirection added to to the old links ,  I don't have any objection on keeping the folder structure as it is.

**Comment by praneesha** [comment]
+1 I have done the redirections in https://github.com/ballerina-platform/ballerina-dev-website/pull/182. 

Thanks!
