### ISSUE TITLE
Add link to newsletter page from footer

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#1361]
**Description:**
Add a link to this https://ballerina.io/community/newsletter/ from the footer

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Done as shown below.

<img width="1018" alt="Screenshot 2021-01-06 at 21 08 26" src="https://user-images.githubusercontent.com/11707273/103787273-62880d80-5063-11eb-906f-219b6d904e8c.png">
