### ISSUE TITLE
Ballerina playground doesn't work

### ISSUE THREAD

**Issue by rumeshmadhusanka** [ballerina-platform/ballerina-dev-website#1372]
**Description:**
Ballerina playground doesn't produce an output if the given hello world code is altered by even a white-space. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Ballerina Playground

**OS, Browser, other environment details and versions:**    
Chrome browser

**Steps to reproduce:**
1. Change the code on [https://play.ballerina.io/](https://play.ballerina.io/) by adding some code line or white-space. 
2. Hit 'Run'.

**Related Issues:**

**Comment by praneesha** [comment]
This is fixed now as shown below.

<img width="713" alt="Screenshot 2020-12-03 at 21 09 31" src="https://user-images.githubusercontent.com/11707273/101051814-e3a73d00-35ab-11eb-8556-e3e6698e6778.png">

**Comment by praneesha** [comment]
The above issue seems to be there again after migrating the Playground to Swan Lake.

**Comment by praneesha** [comment]
Closing since this is fixed now.
