### ISSUE TITLE
BBE Sub header without any BBEs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#138]
**Description:**
$subject for the "Listener" header in BBEs [1]

<img width="554" alt="image" src="https://user-images.githubusercontent.com/16300038/70031334-fec62200-15d0-11ea-8f5c-387bac5ae5d1.png">

[1] https://ballerina.io/learn/by-example/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by wggihan** [comment]
Sent a PR to the master https://github.com/ballerina-platform/ballerina-lang/pull/20177
Will manually fix the live B.io.

**Comment by wggihan** [comment]
PR got merged to master and live B.io was updated.
