### ISSUE TITLE
Enable Adding Comments in "blog.io"

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1382]
**Description:**
It would be better if we can open up the Ballerina blog[1] for comments.

This is done in similar communities for example in [2] and [3].

[1] https://blog.ballerina.io/
[2] https://blog.golang.org/generics-next-step
[3] https://blog.jetbrains.com/kotlin/2020/09/the-dark-secrets-of-fast-compilation-for-kotlin/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Need to check on using Utterances for this.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority.
