### ISSUE TITLE
Bullet points are not rendering properly in Quick tour page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#1434]
**Description:**

$subject for [1]

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/16300038/97069207-39bbb480-15ec-11eb-88b3-8e4c1972d9f0.png">

[1] https://ballerina.io/swan-lake/learn/quick-tour/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/1405 and appears correct in the dev site[2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1405
[2] https://dev.ballerina.io/swan-lake/learn/quick-tour/
