### ISSUE TITLE
Fix the indentation of the "Star" and "Watch" Buttons in the "Quick Tour"

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1435]
**Description:**
Fix the indentation of the "Star" and "Watch" Buttons in the "Quick Tour". They should be indented under the second bullet point.

<img width="1061" alt="Screenshot 2020-10-24 at 11 35 40" src="https://user-images.githubusercontent.com/11707273/97069465-46d9a300-15ee-11eb-83bb-42d2534d345a.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
<img width="1041" alt="Screen Shot 2020-10-24 at 12 05 27 PM" src="https://user-images.githubusercontent.com/6144466/97069921-4d1d4e80-15f1-11eb-833a-0c0856c2256c.png">
This is fine.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/1440.
