### ISSUE TITLE
is there any documentation on remote debugging for IntelliJ plugin

### ISSUE THREAD

**Issue by ramith** [ballerina-platform/ballerina-dev-website#1472]
**Description:**

Is this supported for the IntelliJ plugin?
if so, is there any documentation?

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
Mac, JDK 1.8
**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
 @NipunaRanasinghe

**Comment by praneesha** [comment]
Closing this since now the IntelliJ plugin is a project supported by the community.
