### ISSUE TITLE
Ballerina time search - first result link broken

### ISSUE THREAD

**Issue by chanukaranaba** [ballerina-platform/ballerina-dev-website#149]
<img width="1025" alt="Screenshot 2019-12-09 at 16 45 47" src="https://user-images.githubusercontent.com/3981543/70431594-65e94800-1aa3-11ea-9c73-b2d3b6665103.png">
<img width="1440" alt="Screenshot 2019-12-09 at 16 43 52" src="https://user-images.githubusercontent.com/3981543/70431596-6681de80-1aa3-11ea-8203-b592db241abe.png">

**Comment by praneesha** [comment]
This is the old version of Ballerina PAI docs. This can be found in the new Standard Library docs in [1].

[1] https://ballerina.io/v1-1/learn/api-docs/ballerina/time/index.html
