### ISSUE TITLE
Unable to Download the Windows and macOS Installers

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1497]
**Description:**
It is unable to download the Windows and macOS installers by clicking the respective buttons. It's required to right-click and select "Open in New Tab" to download the artifacts. 

<img width="1128" alt="Screenshot 2020-11-10 at 19 57 29" src="https://user-images.githubusercontent.com/11707273/98686830-0a000100-238f-11eb-89e6-e59a851626d6.png">

This is there only in the [dev site](https://dev.ballerina.io/downloads/) and is fixed in the [live site](https://ballerina.io/downloads/).

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praveennadarajah** [comment]
The same issue is there with macOS installer as well.
