### ISSUE TITLE
Remove the Pipe Symbol in the TOC of the Quick Tour Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1525]
**Description:**
Need to remove the pipe symbol in the TOC of the Quick Tour page.

<img width="1195" alt="Screenshot 2020-11-26 at 17 13 23" src="https://user-images.githubusercontent.com/11707273/100347137-ec779c00-300a-11eb-9665-a162caf2b1eb.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/pull/1623

**Comment by praneesha** [comment]
Fixed via [1] and [2].

[1] #1623
[2] #1626
