### ISSUE TITLE
Remove function mocks from the Testerina documentation

### ISSUE THREAD

**Issue by gigara** [ballerina-platform/ballerina-dev-website#153]
**Description:**
Function mocks should be removed from the Testerina documentation because mock functions testing are not available in the current Ballerina version.
[https://ballerina.io/learn/how-to-test-ballerina-code/](https://ballerina.io/learn/how-to-test-ballerina-code/)

**Suggested Assignees:**
@praneesha 

**Affected Product Version:**
1.1.0

**Comment by grainier** [comment]
ref: Function mocks section of ballerina-dev-website/learn/how-to-test-ballerina-code.md

**Comment by grainier** [comment]
@hevayo , @hemikak Is this functionality got removed in 1.1.0-RC?
