### ISSUE TITLE
A List of existing production deployments/usages 

### ISSUE THREAD

**Issue by bhagyas** [ballerina-platform/ballerina-dev-website#1599]
**Description:**

Requesting a list of existing production deployments and usages of Ballerina language.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This information will be shared and added later once the production-ready deployments are ready and available.
