### ISSUE TITLE
Link to install from zip not working

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#1602]
The link to download the zip archive for slp versions is broken. It doesn't navigate to the relevant section in the installing ballerina page.

https://ballerina.io/downloads/

**Comment by praneesha** [comment]
Closing since this is fixed now.

**Comment by pubudu91** [comment]
Reopening this since this issue is still there.

**Comment by pubudu91** [comment]
Maybe this is due to an issue with the link? The link in the download page seems to be referring to an outdated URL and gets redirected. 
The URL in the download page: https://ballerina.io/learn/getting-started/installing-ballerina/#installing-via-the-ballerina-language-zip-file
The actual URL: https://ballerina.io/learn/user-guide/getting-started/setting-up-ballerina/installation-options/#installing-via-the-ballerina-language-zip-file
