### ISSUE TITLE
Drop down is not updated to match the URL

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-dev-website#1607]
<img width="955" alt="Screenshot 2020-12-18 at 4 52 14 PM" src="https://user-images.githubusercontent.com/1686124/102609529-aa490280-4151-11eb-9be9-399c08fb0464.png">
 
If I go to https://ballerina.io/swan-lake/learn/coding-conventions/top-level-definitions/ it still shows 1.2 selected in the drop down.

Also drop down is not prominent enough.

**Comment by praneesha** [comment]
Closing since this is fixed now. Checked in Chrome, Firefox, and Safari
