### ISSUE TITLE
"Coding Conventions/Top-Level Definitions" page needs to be updated for Swan lake

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-dev-website#1608]
**Description:**
Deprecated `object` syntax shown under the swan-lake coding convention page

https://ballerina.io/swan-lake/learn/coding-conventions/top-level-definitions/

**Comment by praneesha** [comment]
We need to check and update all sub-pages of the Coding Conventions Guide.

**Comment by praneesha** [comment]
Closing since this is done now.
