### ISSUE TITLE
Swan lake Docker samples does not compatible with new service definition

### ISSUE THREAD

**Issue by madushadhanushka** [ballerina-platform/ballerina-dev-website#1639]
**Description:**
There are a few service definitions found in [1, 2] to demonstrate the Docker deployment. All of the samples given contain service definitions with older implementation. These samples are not get compiled as it does not support the older version of the service definition.

[1] https://ballerina.io/swan-lake/learn/deployment/docker/
[2] https://ballerina.io/swan-lake/learn/deployment/code-to-cloud/samples/

**Comment by anuruddhal** [comment]
The samples are updated.
