### ISSUE TITLE
Cannot Switch to the 1.2 Branch in BBE page

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-dev-website#1675]
**Description:**

When we switch to SwanLake in the BBEs page, the button still shows a tick on the `1.2` in the version dropdown list.
When I tried to switch back to the `1.2` branch, it does not switch to the `1.2` branch back, it stays in the SwanLake, even though the tick is on the `1.2` version.

**OS, Browser, other environment details and versions:**    
Browser: Safari 14.0.2
OS: macOS BigSur 

**Steps to reproduce:**
Check the BBE page (This might occur on the other pages as well).

**Comment by praneesha** [comment]
This is fixed in the dev site[1] now.

[1] https://dev.ballerina.io/1.0/learn/by-example/
