### ISSUE TITLE
Need docs on how to debug tests

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#1737]
**Description:**
We couldn't find out about how to debug tests from the docs. It would be nice to have docs on this.

**Affected Product Version:**
Ballerina swan lake alpha

**OS, DB, other environment details and versions:**    
Ubuntu 20.04

**Steps to reproduce:**

**Comment by NipunaRanasinghe** [comment]
Closing as the debugger guide is updated with the test debugging section
