### ISSUE TITLE
Line Numbers Break When Code Snippets are Indented

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1745]
**Description:**
When the code snippets are being indented to add them under a numbered bullet point, the line numbers break as shown below.

<img width="1093" alt="Screenshot 2021-01-26 at 14 26 26" src="https://user-images.githubusercontent.com/11707273/105822972-a034e200-5fe2-11eb-8886-14bd5edd6bbb.png">

For example, see[1].

[1] http://ballerina.io/downloads/swan-lake-release-notes/#changes-to-casting-with-errors

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by iamsameeraliyanage** [comment]
![image](https://user-images.githubusercontent.com/67787442/123757099-414dfe80-d8db-11eb-898f-bf13455c6fcd.png)
