### ISSUE TITLE
No direct link to learn about tooling

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#1748]
**Description:**
To learn about tooling in the website we have to go to Learn->Quickstart. It would be very useful if the site provides an easier way to refer about tooling.

**Affected Product Version:**
Swan lake alpha
**OS, Browser, other environment details and versions:**    
Ubuntu 20.04
**Steps to reproduce:**

**Comment by praneesha** [comment]
Fixed with the Tooling Guide.
