### ISSUE TITLE
Local variables not suggested for func invocation

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#1750]
**Description:**
![local_var](https://user-images.githubusercontent.com/15815199/105454774-73ae5c80-5ca8-11eb-8ff9-d254039bcca6.gif)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
We have set this as the default configuration in https://github.com/ballerina-platform/plugin-vscode/issues/212
