### ISSUE TITLE
Need an article on how to achieve CI/CD using Ballerina

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-dev-website#1848]
At the moment only the FAQ page discusses about CI/CD in Ballerina. But it would be great to have some doc which explains how to achieve this for at least certain scenarios. Mainly, because nowadays CI/CD is a must for any new project.

**Comment by praneesha** [comment]
Closing as this will be captured under the Ballerina marketing tasks.
