### ISSUE TITLE
An Exception is Thrown When BBE Description Has a Colon

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1864]
**Description:**
An exception gets thrown when there is a colon included in the description of a BBE. For example, the BBEs below has a column in their descriptions.

1. JSON Objects
2. JSON Arrays

The exception below gets thrown when the BBEs are generated using the gen Tool and they are added to the dev site.

<img width="1440" alt="Screenshot 2021-02-18 at 17 41 06" src="https://user-images.githubusercontent.com/11707273/108369837-026bb600-7222-11eb-8b5e-3d07d945b598.png">

However, the same has been rendered fine before in both Swan Lake and 1.2 ([1] & [2]). Therefore, it seems like some recent change done in the site is causing this.

For example, see the image below.

<img width="1085" alt="Screenshot 2021-02-18 at 19 48 24" src="https://user-images.githubusercontent.com/11707273/108370173-5d9da880-7222-11eb-9843-123a878e2705.png">

[1]https://dev.ballerina.io/1.2/learn/by-example/json-objects.html
[2] https://dev.ballerina.io/1.2/learn/by-example/json-arrays.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-release/pull/95.

**Comment by praneesha** [comment]
Closing since this is fixed now.
