### ISSUE TITLE
BBE Generation Gives "Slice Bounds Out of Range" Error

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1865]
**Description:**
When trying to generate BBEs using the Go Tool, the error below occurs in several BBEs skipping the generation of them:

<img width="1352" alt="Screenshot 2021-02-18 at 20 02 05" src="https://user-images.githubusercontent.com/11707273/108371855-31832700-7224-11eb-8713-a5505ef0ac5d.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
This is coming because the .metatags entries are not contained in a single line, each line should have the format "key: value" and the whole value should be in a single line, and it cannot have a line break and go to the next line.
