### ISSUE TITLE
Enable Retrigering the BBE Gen Workflow

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1904]
**Description:**
It should be able to manually retrigger the automated Workflow of generating the BBEs using the distribution ZIP file and the Gen Tool. The corresponding workflow file is [1].

It should enable the "Run Workflow" option as shown below in [2] for example.

<img width="1440" alt="Screenshot 2021-02-24 at 14 13 15" src="https://user-images.githubusercontent.com/11707273/108985504-22362a80-76b7-11eb-9eaa-86fdfc822cc6.png">

Normally, this can be configured via the below `workflow-dispatch` property. Although this is already added in the workflow YAML file, it is still not enabled.

```on:
  workflow_dispatch:
  push:
```

[1] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/sw_update_ballerina_by_example.yml
[2] https://github.com/ballerina-platform/ballerina-lang/actions/workflows/publish_release.yml

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lafernando** [comment]
I can already see that this is enabled there. Check the attached screenshot.
![1](https://user-images.githubusercontent.com/2379767/109067024-d2e5ff00-76a2-11eb-9f0e-eec84a8203e9.png)

**Comment by praneesha** [comment]
Closing since this is already enabled.
