### ISSUE TITLE
Add Docs on env configuration of debugger

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-dev-website#1908]
**Description:**
Add documentation on `env` configuration of VSCode plugin debugger introduced with https://github.com/ballerina-platform/plugin-vscode/issues/3

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
Closing as the debugger guide is updated with the configurations related documentation
