### ISSUE TITLE
404 issue in link in auth module API docs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#1909]
**Description:**
Following link in [1] gives 404 error.

https://ballerina.io/learn/by-example/secured-service-with-basic-auth-file-user-store.html

<img width="855" alt="image" src="https://user-images.githubusercontent.com/16300038/109198220-f94f8b80-77c3-11eb-91cd-77c77ab5175b.png">

[1] https://ballerina.io/learn/api-docs/ballerina/#/ballerina/auth/1.1.0-alpha4

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This was removed in Alpha2 and will be added back in Alpha3.
