### ISSUE TITLE
Need a Way to Gen Redirections via the BBE Gen Tool

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1917]
**Description:**
We need to improve the [BBE Gen Tool](https://github.com/ballerina-platform/ballerina-release/blob/master/ballerinaByExample/tools/generate.go) to read a "redirections" file and generate the redirections as front matter in the generated BBE HTML files.

For example, when a BBE is renamed/moved, the old and the new URLs should be added in a "redirections" file (maybe, we can use the `[index.json](https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/index.json)` or `[meta.json](https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/meta.json)` files we already have for this purpose), and the Tool should able to read the redirections and add them to the HTML files once generated.  

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
We need to add the bulk redirection via a script to redirect all 404 BBEs to the BBE landing page on the new website.

**Comment by sm1990** [comment]
In the new rewrite we have removed all the redirections to improve SEO. However any 404s reached due to BBEs will be redirected to BBE landing page.
