### ISSUE TITLE
Improve the BBE Gen Workflow to Gen BBEs from Snapshot Versions

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1918]
**Description:**
Currently, the BBE Gen Workflow in the dev site is used to automate generating the BBEs using the ZIP file in the dist-server releases.

We need to change it to add the ability to automate generating BBEs using the snapshots packs as well.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
The snapshot versions can be found in e.g., https://github.com/ballerina-platform/ballerina-distribution/actions/runs/591381861.

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-platform/ballerina-dev-website/pull/2335
