### ISSUE TITLE
Suggestion: render the sequence diagram with ZenUML sequence diagram renderer

### ISSUE THREAD

**Issue by MrCoder** [ballerina-platform/ballerina-dev-website#1926]
**Description:**
This is Peng. I am the creator of ZenUML (https://ZenUML.com). I like the idea of ballerina and especially the bidirectional mapping between the code and the visual representation.

ZenUML is a diagram-as-code solution that renders text (DSL) as sequence diagrams. I noticed that the sequence diagram on the website (https://ballerina.io/why-ballerina/sequence-diagrams-for-programming/) does not align with the UML specification. I wonder if you are interested in rendering it with ZenUML.

ZenUML uses a similar syntax for the DSL. Here is an example:
![Example](https://i.stack.imgur.com/X6klD.jpg)

You can also try it out at https://app.zenuml.com

I will be happy to help with the integration.

**Comment by hevayo** [comment]
Hi @MrCoder 

Is ZenUML opensource ?

Currently the Ballerina diagram is modeled on top of the AST and semantic information derived from the Ballerina source code. This gives us the ability to have the bidirectional mapping. Meaning if we construct the AST model we can generate the diagram or the source code. This will give us diagram editing capability.

I believe ZenUML must be using some model underneath to draw the diagram, in that case it would be difficult to do the mapping from ZenUML model to Ballerina AST.

Also the Ballerina's sequence diagram is more than the UML specification. 

Considering above I doubt ZenUML be a good fit for Ballerina. 

Regards

**Comment by praneesha** [comment]
Closing since the answer is provided above. Please reopen for further discussion.

**Comment by MrCoder** [comment]
Hi @hevayo and @praneesha,

Very sorry that it took me two years to come back. It completely splipped off my radar. To answer your questions:

> Is ZenUML opensource ?
It is open-sourced under MIT license. You can find the code here: https://github.com/mermaid-js/zenuml-core.

> Currently the Ballerina diagram is modeled on top of the AST and semantic information derived from the Ballerina source code. This gives us the ability to have the bidirectional mapping. Meaning if we construct the AST model we can generate the diagram or the source code. This will give us diagram editing capability.

ZenUML takes a similar (looks the same but I am not 100% sure) approach. The DSL is first parsed into AST and then draw the diagram. We also have the bidirectional mapping. User already can edit the DSL from the diagram.

Let me know if you need more information. Thanks.

**Comment by anupama-pathirage** [comment]
Thanks, @MrCoder, for the information. But clsoing as this is currently not feasible for Ballerina.
