### ISSUE TITLE
Improve the Security Page in Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#1957]
**Description:**
Need to update more information on the security researcher acknowledgment & public disclosure process.

- [x] Update the security key as mentioned in https://github.com/ballerina-platform/ballerina-dev-website/pull/3095#discussion_r760479614
- [x] Update the components covered by the WSO2 Ack program as per https://github.com/ballerina-platform/ballerina-dev-website/pull/3095#discussion_r760905228
- [x] Get the WSO2 Ack program doc updated for Ballerina by removing the link to the vulnerability section and the last section on the guidelines.
- [x] Reopen and merge https://github.com/ballerina-platform/ballerina-dev-website/pull/3095  (after addressing all the comments) to incorporate the feedback given by Dakshitha.
- [x] Get the internal docs updated on the information on how a reported vulnerability will be handled internally.
- [x] Add a section on the B.io security page to list the security advisories (as a list or a table) similar to how it is done in https://docs.wso2.com/display/Security/Security+Advisories.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ldclakmal** [comment]
Came up with a sample process [1] for this requirement. Need to revisit and finalize this and update the website content.

[1] https://docs.google.com/document/d/1VDfRG_Prmlms1HSSPPgN78sOdWnN0_UXoDbcA7tk7b4/edit?usp=sharing

**Comment by praneesha** [comment]
Closing since this is done now.
