### ISSUE TITLE
Add YouTube icon to website footer

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#1962]
**Description:**
Add a YouTube icon linking to the Ballerinalang YouTube channel: https://www.youtube.com/channel/UCBMvET-T1YshLrJRLpuKJ5g

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since this is done.
