### ISSUE TITLE
Add section for case studies in community page when we have user stories

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#1963]
**Description:**
When we have production users, write case studies and add a section for logos in the community page

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing as this will not be considered in the near future. Can reopen or create the issue later when the requirement is solid.
