### ISSUE TITLE
Inavlid URLs in TCP and UDP BBEs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2000]
**Description:**
Invalid URLs in TCP and UDP BBEs.

https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/tcp-client/tcp_client.description#L4
This url is incorrect. Should be https://docs.central.ballerina.io/ballerina/tcp/latest
So this gives 404 for the link in the description of all tcp and udp BBEs
Ex:
https://ballerina.io/learn/by-example/tcp-client.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is fixed in the ballerina-distribution repo via https://github.com/ballerina-platform/ballerina-distribution/pull/1464.
