### ISSUE TITLE
Swan lake alpha 2 vsix file is served in "Installing the VS Code Extension" page

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#2001]
**Description:**

Although Swan lake Alpha 3 is released, the download button in "Installing the VS Code Extension" page still serves Alpha 2 Vsix file

https://ballerina.io/learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extension/

**Comment by praneesha** [comment]
This is fixed via [1] and [2] now.

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1999
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/1994
