### ISSUE TITLE
BBEs are not readable when Window size is small

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-dev-website#2002]
**Description:**

When browser window size is small the code example breaks in to multiple section each with it's own drop shadow making it very hard to read.
e.g. 

![image](https://user-images.githubusercontent.com/6542630/112096127-b49cf180-8bc3-11eb-9af3-3b9cebbf813e.png)

There is a lot of empty white space on the top.
![image](https://user-images.githubusercontent.com/6542630/112096166-c41c3a80-8bc3-11eb-880a-496ffada388b.png)

Expectation from the Rust lang learn examples: https://doc.rust-lang.org/rust-by-example/std/hash.html

![image](https://user-images.githubusercontent.com/6542630/112096258-ef068e80-8bc3-11eb-9142-deba0e6739c9.png)

**Suggested Labels:**

Ballerina Swan Lake - Alpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    
Firefox browser

**Steps to reproduce:**

**Related Issues:**

**Comment by ruvi-d** [comment]
Original issue has been resolved, but the BBEs are still not readable when the window width is small. e.g. when 540p
![image](https://user-images.githubusercontent.com/6542630/121219751-a8126600-c8a1-11eb-9ca9-7dff88ef4803.png)
The left hand side menu is "hiding" the BBE contents

**Comment by praneesha** [comment]
Currently, we need to scroll the entire menu down to access the selected BBE on the mobile view.

https://user-images.githubusercontent.com/11707273/122866712-11848100-d346-11eb-8553-d59dd90dab89.mov

1. We need to fix the mobile view to introduce a hamburger menu for the BBE navigation.
2. We need to fix the BBE layout on the mobile view.
