### ISSUE TITLE
BBE main Page WebSub section is broken

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#2003]
**Description:**
BBE main Page WebSub section is broken

<img width="1150" alt="Screenshot 2021-03-23 at 10 40 26" src="https://user-images.githubusercontent.com/2918812/112096463-4efd3500-8bc4-11eb-93a7-11a36cf4b977.png">

https://ballerina.io/learn/by-example/

**Comment by ayeshLK** [comment]
This was an previously identified issue and it is fixed in followin PR [#1457](https://github.com/ballerina-platform/ballerina-distribution/pull/1457)

**Comment by praneesha** [comment]
This is fixed now.
