### ISSUE TITLE
Add an expandable index menu to learn-by-examples

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-dev-website#2004]
**Description:**

Suggestion to add an index menu similar to the one in Rust lang shown below:
![image](https://user-images.githubusercontent.com/6542630/112096737-dc408980-8bc4-11eb-85fd-df85ffb43529.png)

Navigating back to the main page with the all the examples is tedious  

**Suggested Labels:**

Ballerina Swan Lake - Alpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Fixed with the new BBE layout: https://dev.ballerina.io/learn/by-example/hello-world
