### ISSUE TITLE
Link to download Ballerina Zip from main download page is broken

### ISSUE THREAD

**Issue by ruvi-d** [ballerina-platform/ballerina-dev-website#2005]
**Description:**

Clicking on "Install from source" option in https://ballerina.io/downloads/ opens a new tab and takes you to the top of https://ballerina.io/learn/user-guide/getting-started/setting-up-ballerina/installation-options/ page.
Expected behavior is to stay on the same browser tab and go directly to the https://ballerina.io/learn/user-guide/getting-started/setting-up-ballerina/installation-options/#installing-via-the-ballerina-language-zip-file sub heading

**Suggested Labels:**

Ballerina Swan Lake - Alpha3

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    
Firefox browser

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since this is fixed now.

**Comment by praneesha** [comment]
Reopening since the issue still remains from the browser-level although it is fixed in the doc.
