### ISSUE TITLE
TCP Client API docs don't mention the 3rd parameter of initializer method 

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#2009]
**Description:**
TCP client takes 3 arguments in the `init` method; remote host, remote port and client configuration. The last parameter; `clientConfiguration` is missing in the [API docs](https://docs.central.ballerina.io/ballerina/tcp/0.8.0-alpha5/tcp/clients/Client)

**Suggested Labels:**
Version/SLAlpha3

**Affected Product Version:**
SLA 3

**Comment by shehan360** [comment]
This issue is now fixed. Hence closing the issue.
https://docs.central.ballerina.io/ballerina/tcp/latest/clients/Client
