### ISSUE TITLE
WebSub example is not linked  

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-dev-website#2010]
**Description:**
Websub examples are in a separate section and although it is listed as an example there is no URL linked. 
<img width="842" alt="Screenshot 2021-03-23 at 11 15 24" src="https://user-images.githubusercontent.com/39673615/112099573-c84b5680-8bc9-11eb-8f20-696ba2ab4b81.png">

**Comment by praneesha** [comment]
This is fixed now.
