### ISSUE TITLE
Link broken when switching to SwanLake

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-dev-website#2011]
**Description:**
When searching for `ballerina config` search engine suggests the https://ballerina.io/1.2/learn/by-example/config-api.html link. Once visited there; changing version into `Swan Lake` throws a 404.

**Comment by Ibaqu** [comment]
Drop down doesnt work properly for 1.2. 
For the lean pages, if you switch from `Swan lake` to `1.2`. it shows a 404. The link for the drop down is `https://dev.ballerina.io/1.2/learn/user-guide/testing-ballerina-code/testing-quick-start/`
`https://dev.ballerina.io/1.2/learn/testing-ballerina-code/testing-quick-start/` works however it does not follow the proper link format. 

TLDR : 
`https://dev.ballerina.io/learn/user-guide/testing-ballerina-code/testing-quick-start/` -<--- This works
`https://dev.ballerina.io/1.2/learn/user-guide/testing-ballerina-code/testing-quick-start/` -<--- this doesnt work

**Comment by praneesha** [comment]
The current design doesn't allow to jump to 1.2 from Swan Lake docs because that is not encouraged as 1.2 in considered obsolete now.
