### ISSUE TITLE
NATS module documentation cannot be accessed via nats by-examples

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-dev-website#2014]
**Description:**
NATS module documentation cannot be accessed using the link provided in the nats-streaming-client example page.

**Affected Product Version:**
alpha3

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**
1. Visit https://ballerina.io/learn/by-example/nats-streaming-client.html
2. Click on the link to the `NATS module` documentation.
3. Which redirects to `https://docs.central.ballerina.io/ballerinax/nats/*` a 404.

**Related Issues:**
n/a

**Comment by Kishanthan** [comment]
Accessing an old version works - https://docs.central.ballerina.io/ballerinax/nats/1.1.0-alpha3
