### ISSUE TITLE
Declaring Dependencies in a Package - wrong file indicated in website

### ISSUE THREAD

**Issue by suhand** [ballerina-platform/ballerina-dev-website#2016]
**Description:**
The dependencies are now declared in `Dependencies.toml` file. But the website still says it is declared in `Ballerina.toml` file.
This section should be updated accordingly.
URL: https://ballerina.io/learn/user-guide/structuring-ballerina-code/working-with-ballerina-modules/#declaring-dependencies-in-a-package

**Suggested Labels:**
Type/Bug, Version/SLAlpha3

**Suggested Assignees:**
keizer619

**Affected Product Version:**
SLAlpha3

**OS, Browser, other environment details and versions:**    
OS: macOS Big Sur V11.1 [latest]
Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64) [latest]

**Steps to reproduce:**
Follow the steps in page and build the package.
https://ballerina.io/learn/user-guide/structuring-ballerina-code/working-with-ballerina-modules
The dependency file is created as `Dependencies.toml` and dependencies are added to that file instead of `Ballerina.toml` file as indicated in the website.

**Ballerina.toml**
```
[package]
org = "wso2"
name = "winery"
version = "0.1.0"

[build-options]
observabilityIncluded = true
```

Dependencies.toml
```
[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"
```

**Related Issues:**
N/A

**Comment by azinneera** [comment]
Resolved with  https://github.com/ballerina-platform/ballerina-dev-website/pull/2116

**Comment by praneesha** [comment]
Closing as per the above comment.
