### ISSUE TITLE
Generate documentation - invalid index.html file location

### ISSUE THREAD

**Issue by suhand** [ballerina-platform/ballerina-dev-website#2019]
**Description:**
The current generated `index.html` file location is indicated as,
`target/apidocs/math` which is `target/apidocs/<package_name>`.
It should be corrected as `target/apidocs/<package_org>/<package_name>/<package_version>`
URL: https://ballerina.io/learn/user-guide/documenting-ballerina-code/#generating-ballerina-documentation

E.g. Ballerina.toml
```
[package]
org = "suhan"
name = "math"
version = "0.1.0"

```
Directory structure:
```
└── target
    ├── apidocs
    │   └── suhan
    │       └── math
    │           └── 0.1.0
    │               ├── index.html

```

**Suggested Labels:**
Type/Docs, Version/SLAlpha3

**Suggested Assignees:**
keizer619

**Affected Product Version:**
SLAlpha3

**OS, Browser, other environment details and versions:**    
OS: macOS Big Sur V11.1 [latest]
Browser: Chrome Version 89.0.4389.90 (Official Build) (x86_64) [latest]

**Steps to reproduce:**
Follow the steps in 
https://ballerina.io/learn/user-guide/documenting-ballerina-code/ till the end and find generated `index.html` file location.

**Related Issues:**
N/A

**Comment by shehan360** [comment]
This is fixed now. Hence closing the issue.
