### ISSUE TITLE
gRPC "Implementing Bi-Directional Streaming" content seems to be outdated

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#2020]
**Description:**
See https://ballerina.io/learn/user-guide/network-communication/grpc/performing-grpc-streaming/#implementing-bi-directional-streaming.

The example talks about a calculation/calculator service, but the diagram doesn't seem to be relevant to this?

**Affected Product Version:**
Swan Lake Alpha3

**Comment by MaryamZi** [comment]
Also, the code generated seems to be different from what is in the guide and some code results in compilation errors.

**Comment by praneesha** [comment]
This diagram is fixed via [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/2144
