### ISSUE TITLE
BBE for Check expression is misleading

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-dev-website#2025]
**Description:**
Check expression [BBE](https://ballerina.io/learn/by-example/check.html) has a statement that says `Hence, check can only be used in a function, which has error in its return type.` This convinces the reader that the check expression can only be used inside a function but the actual idea here is if the check is used inside a function it should has an error in its return type.

**Comment by dulajdilshan** [comment]
Here,
> if the check is used inside a function it should has an error in its return type
This is not true right? IMO, If a check is used inside or outside a function it should be used with a function that has `error` in its return type. isn't it?

Why do we need to mention  "used inside a function"? I think this would mislead the user. The thing that we need to mention here should be - **Check can be only used with a function, which may return an error** Isn't it?

**Comment by rdulmina** [comment]
What I understood by reading the BBE is `check` can only be used inside a function, which optionally returns an error. But `check` can be used in the module-level as well. Looping in @MaryamZi

**Comment by dulajdilshan** [comment]
@rdulmina Ah right, Got the point. I was looking from the usage view `checking-expression`.
