### ISSUE TITLE
The OpenAPI page contains outdated content

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#2029]
The OpenAPI page: https://ballerina.io/learn/tooling-guide/cli-tools/openapi/
This has content related to the `--service-name` option. While this option is still there in the plugin, we should remove references to this in content since in the new service design, there is no concept of a service name.

**Comment by lnash94** [comment]
yeah, In previously, we used this option to generate the service name and the generated file with the given name for the service name. Currently, it only takes to rename the generated file with the given name with the` --service-name` option. WDYT, if we change this `--service-name` option to `--file-name` for the user to rename the file?

**Comment by pubudu91** [comment]
Would that be confusing? We only name the file containing the service with that name right and generating multiple files? Do we need this option to name the file anyways?

**Comment by praneesha** [comment]
Removed the `--service-name` occurrences from the doc via [1] for the moment. This will be finalized and the Learn page will be updated for the Beta release later.

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/2142
