### ISSUE TITLE
Broken Link for java.arrays module from BBE

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-dev-website#2034]
**Description:**
The link for [java.arrays module](https://docs.central.ballerina.io/ballerina/java.arrays/latest/java.arrays) within the description text of [Java Arrays BBE](https://ballerina.io/learn/by-example/java-arrays.html) lands on a _404 Error page_.

**Suggested Labels:**
Version/SLAlpha3

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/1569.
