### ISSUE TITLE
Quoted string syntax should be highlighted the same way as normal strings in bbe examples

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-dev-website#2038]
**Description:**
Quoted string syntax should be highlighted the same way as normal strings in bbe examples.

<img width="821" alt="screenshot of https://ballerina.io/learn/by-example/async.html" src="https://user-images.githubusercontent.com/1686124/112149972-92c45e80-8c05-11eb-94dd-9526f4fa6abd.png">

**Comment by praneesha** [comment]
Fixed as follows for example:

<img width="1032" alt="Screenshot 2021-04-06 at 17 56 21" src="https://user-images.githubusercontent.com/11707273/113710512-70503c00-9701-11eb-9c19-6377e12c6bfc.png">
