### ISSUE TITLE
Add a section how `& readonly` can be used for variable isolation

### ISSUE THREAD

**Issue by Maninda** [ballerina-platform/ballerina-dev-website#2041]
**Description:**
In the https://ballerina.io/learn/by-example/isolated-variables.html example we can explain how `readonly` variables can be used to support isolation in functions.
A sample code is as follows.
```
isolated map<anydata & readonly> store = {};

isolated function add(string key, anydata & readonly value) {
    lock {
        store[key] = value;
    }
}

isolated function get(string key) returns anydata & readonly {
    lock {
        return store[key];
    }
}
```
Here instead of cloning every variable, `readonly` variables are used as both arguments and return types.

**Comment by MaryamZi** [comment]
This depends on the requirement, right? There could be cases where the values have to be mutable. 

IMO the BBE should be a generic example, and I think using immutable values here could be confusing to the user (they may think it has to be immutable?).

However, there was a fix that reduced the number of clone calls needed and I've updated the BBE in https://github.com/ballerina-platform/ballerina-distribution/pull/1570.
