### ISSUE TITLE
Building from source page is not uptodate with multi repo changes

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2048]
**Description:**
$subject and it assumes a mono repo as we had earlier.

https://ballerina.io/learn/user-guide/getting-started/setting-up-ballerina/installation-options/#building-from-source

Need to change it to match with the new multi repos.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is done in [1].

[1] https://dev.ballerina.io/learn/user-guide/getting-started/building-from-source/
