### ISSUE TITLE
Add BBE on testing simple http service

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/ballerina-dev-website#2053]
**Description:**
The current BBEs don't cover how to test a simple HTTP service.  We should add a BBE on how to test a simple HTTP
service.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
Swan-lake alpha3

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
@azinneera @Ibaqu @Dilhasha - WDYT?

**Comment by Ibaqu** [comment]
Adding a BBE specifically for Testing HTTP services is not ideal, as we mean to cover the basics of what the test framework offers in the BBE section. Testing services would make use of basic assertions or mocking which is already covered specifically in the BBEs. 

At the moment, we in the process of writing and updating our existing blog guides to be more specific about certain testing scenarios, which does include testing services and other best practices.

However, these 'guides' were purposely kept out of the learn/user-guides as they are very detailed and specific. The testing-ballerina-code guide only includes what the test framework is capable of including its features. 

@Dilhasha Would it make sense to include a section under the user-guides as well for certain testing scenarios?

**Comment by Dilhasha** [comment]
Agree with @Ibaqu and @chamil321.
IMO, we shouldn't complicate the BBEs any further as they already cover all the features in a simple manner. 
I'm +1 to add a section to the user guide to explain best practices when writing Ballerina tests. We can address the services specifically in that section. We'll focus on generic guidelines. WDYT?

**Comment by praneesha** [comment]
@Dilhasha @Ibaqu @chamil321 - +1 Thanks
