### ISSUE TITLE
Ballerina favicon is not available for all pages

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#211]
**Description:**
The fevicon is only shown in some pages and missing in others like the example pages:
![image](https://user-images.githubusercontent.com/8238078/73823406-2a0dfd00-481e-11ea-81c3-cf82b49522d2.png)
It is not shown in example pages like the following: https://ballerina.io/v1-1/learn/by-example/xml.html
But is shown in the main pages like: https://ballerina.io/learn/by-example/

**Affected Product Version:**
1.1
**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**
Go to the links mentioned in the description

**Related Issues:**
N/A

**Comment by praneesha** [comment]
Also, it is not shown for any of the API Docs pages.

**Comment by praneesha** [comment]
Closing since this will be fixed with the effort of applying the same Bio style templates to API Docs.
