### ISSUE TITLE
Update Information on Creating the `Dependecies.toml` File

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2149]
**Description:**
It is not clear in the current content in the doc whether the users have to create the `Dependencies.toml` file, whether it gets created automatically, and what's the actual purpose of it.

Therefore, we need to update the information in [1] on when and why users need to update the `Dependencies.toml` file as per the latest implementation.

This came up while [2] was being resolved.

[1] https://ballerina.io/learn/user-guide/structuring-ballerina-code/working-with-ballerina-modules/#declaring-dependencies-in-a-package
[2] https://github.com/ballerina-platform/ballerina-dev-website/issues/2016

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by azinneera** [comment]
This information is added in [Package Layout](https://dev.ballerina.io/learn/user-guide/ballerina-packages/package-layout/) and https://dev.ballerina.io/learn/user-guide/ballerina-packages/dependencies/#dependenciestoml
