### ISSUE TITLE
Improve keywords for user-guides

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-dev-website#2183]
**Description:**
Better if we can $title. We have used `keywords: ballerina, cli, command line interface, programming language` in several user guides.

**Affected Product Version:**
n/a

**OS, Browser, other environment details and versions:**    
n/a

**Steps to reproduce:**
n/a

**Related Issues:**
n/a

**Comment by praneesha** [comment]
Closing since this was covered in the recent content hackathon, which was done for the Swan lake GA release.
