### ISSUE TITLE
Wrong capitalization in learn page 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2187]
**Description:**

Should be `CLI` in [1]

[1] 

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/16300038/119081682-1f2eaa00-ba1a-11eb-8c53-f28f93d4ade9.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since this is fixed on the dev site now.

<img width="1214" alt="Screenshot 2021-05-29 at 17 29 36" src="https://user-images.githubusercontent.com/11707273/120069414-8ba54b00-c0a3-11eb-9f0d-e3c750bcfda1.png">
