### ISSUE TITLE
Fix issue with API Docs and Language Specification links in Learn Page  

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#2219]
**Description:**
https://dev.ballerina.io/learn/ 

There is an issue with API Docs and Language Specification links in the Learn page after they are clicked. The pages are opened in new tabs and the links remain underlined after they are clicked.

![image](https://user-images.githubusercontent.com/11885043/119773232-f1e07100-bedd-11eb-84a0-753316b24579.png)

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/2330.
