### ISSUE TITLE
Change the text under Graphical in the homepage

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#2221]
Change to: 

"Programs have both a textual syntax and an equivalent graphical form based on sequence diagrams."

This was changed on the Why doc last Friday and the changes are not reflected on the site. 

![image](https://user-images.githubusercontent.com/11885043/119853152-8f16c600-bf2d-11eb-93ff-e6cfe5963621.png)

**Comment by praneesha** [comment]
Closing since this is fixed on the dev site now.

<img width="1339" alt="Screenshot 2021-05-29 at 17 27 28" src="https://user-images.githubusercontent.com/11707273/120069355-379a6680-c0a3-11eb-9422-6fdfbf088c23.png">
