### ISSUE TITLE
Fix layout/alignment issues in the mobile version of the website

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#2223]
![image](https://user-images.githubusercontent.com/11885043/119857030-d94d7680-bf30-11eb-8881-ef7d07c4cd7a.png)

![image](https://user-images.githubusercontent.com/11885043/119857060-e10d1b00-bf30-11eb-94dc-8596582557dc.png)

**Comment by praneesha** [comment]
Fixed via [1] and [2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/2266
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/2320
