### ISSUE TITLE
Fix titles and descriptions in the learn page

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#2238]
![image](https://user-images.githubusercontent.com/11885043/120023828-fdca5100-c00b-11eb-9c71-ea06325916ab.png)

1. Keeping up with the rest of the pages in the site, let’s stick to title case: **Let’s Learn Ballerina!**

2.Change description to the following:
_Ballerina is a comprehensive language that’s easy to grasp for anyone with prior programming experience. Start learning with the material below._ 
 
3. Change the sub-sections (note that Language Specification was changed to Language Specifications) 
**User Guide** - _User Guide - Start programming with Ballerina._ 
**Ballerina by Example** - _Try out an extensive list of Ballerina code examples._ 
**API Documentation** - _Check out the Ballerina standard library APIs._
**Tooling Guide** - _Learn about using the VSCode plugin and other CLI tools._ 
**Language Concepts** - _Get an in-depth understanding of the language principles._ 
**Language Specifications** - _Read the formal specifications of the Ballerina language._

**Comment by praneesha** [comment]
1. Changed the **page description** to sound better like this: 
2. The current description of the **User Guide** sounds better and more meaningful rather than just saying to start programming: `Learn about all the features of the language and its capabilities.`
3. The current description of the **Ballerina By Example** sounds better and more meaningful: `Obtain a hands-on experience of the language and its key features.`
4. Changed the description to **API Documentation** to sound better like this: `Check out the Ballerina standard library APIs comprehensively.`
5. Changed the description to **Language Specification** to sound better like this: `Master Ballerina by reading its formal specifications.`

Since we refer to the spec as a single entity it should be the "Language Specification" and not "Language Specification**(s)**". @hasithaa - WDYT?

**Comment by dakshitha** [comment]
Please use the wording I've provided and change only the following : 

API Documentation - Read our comprehensive guide to Ballerina standard library APIs.
Tooling Guide - Learn how to use the VSCode plugin and other CLI tools.

Will add to this issue if we want to change anything again.

**Comment by praneesha** [comment]
I am +1 on the above API Documentation description. However, I am -1 on the rest of the changes as mentioned above. Let's get more feedback before changing. @sameerajayasoma @anupama-pathirage - WDYT about the 2 proposals?

**Proposal One:**
1. **Page Description** - _Ballerina is a comprehensive language that’s easy to grasp for anyone with prior programming experience. Start learning with the material below._
2. **User Guide** - _Start programming with Ballerina._
2. **Ballerina by Example** - _Try out an extensive list of Ballerina code examples._
3. **API Documentation** - Read our comprehensive guide to Ballerina standard library APIs.
4. **Tooling Guide** - Learn about _using_ the VSCode plugin and other CLI tools.
5. **Language Concepts** - Get an in-depth understanding of the language principles.
6. **Language Specifications** - _Read the formal specifications of the Ballerina language._

**Proposal Two:**
1. **Page Description** - _Ballerina is a comprehensive language that is easy to grasp for anyone with prior programming experience. Start learning with the resources below._
2. **User Guide** - _Learn about all the features of the language and its capabilities._
2. **Ballerina by Example** - _Obtain a hands-on experience of the language and its key features._
3. **API Documentation** - Read our comprehensive guide to Ballerina standard library APIs.
4. **Tooling Guide** - Learn about the VSCode plugin and other CLI tools of the platform.
5. **Language Concepts** - Get an in-depth understanding of the language principles.
6. **Language Specification** - _Master Ballerina by reading its formal specification._

**Comment by anupama-pathirage** [comment]
In overall: +1 for the proposal one

**Reasons are :**
1. Learning Material is better than Learning resources for me 
2. Current User guide doesn’t provide details about all the features about ballerina. It gives some help on starting on different capabilities. So proposal 1 is better
3. Hands on experience is not appropriate for a programming language IMO, try is a better option here. So proposal 1 is better
4. “Check out the Ballerina standard library APIs.” - Which was there in the first comment is better for me as we don’t need to say `our` specifically. We don’t use `our` in other places.
5. IMO we don’t need to say `CLI tools of the platform`. Instead just `CLI tools` is fine. It gives the meaning and we don’t use the word `platform` in other sections.
6.  +1 for the `Get an in-depth understanding of the language principles.`
7. We don’t need to say `master` here and `read` is better as it is upto the reader to master or not :) . And there can be more specifications in the future for different protocols, components. So not just one specification IMO.  @hasithaa Pls confirm.

**Comment by hasithaa** [comment]
> In overall: +1 for the proposal one
> 
> **Reasons are :**
> 1. Learning Material is better than Learning resources for me 
> 2. Current User guide doesn’t provide details about all the features about ballerina. It gives some help on starting on different capabilities. So proposal 1 is better
> 3. Hands on experience is not appropriate for a programming language IMO, try is a better option here. So proposal 1 is better
> 4. “Check out the Ballerina standard library APIs.” - Which was there in the first comment is better for me as we don’t need to say `our` specifically. We don’t use `our` in other places.
> 5. IMO we don’t need to say `CLI tools of the platform`. Instead just `CLI tools` is fine. It gives the meaning and we don’t use the word `platform` in other sections.
> 6.  +1 for the `Get an in-depth understanding of the language principles.`
> 7. We don’t need to say `master` here and `read` is better as it is upto the reader to master or not :) . And there can be more specifications in the future for different protocols, components. So not just one specification IMO.  @hasithaa Pls confirm.
> 

+1 for @anupama-pathirage  idea.
