### ISSUE TITLE
Incorrect capitalization in headings

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2282]
**Description:**
$subject.

Use title-style capitalization for page titles and sentence-style capitalization for all subsection headings. Check all the places and correct them.

For ex: refer [1] : Use title-style

[1] https://dev.ballerina.io/learn/user-guide/ballerina-packages/creating-your-first-ballerina-package/
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/16300038/120231752-b80dc280-c26f-11eb-8d86-ee0a796fc513.png">

Refer [2] : Use sentence-style

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/16300038/120240628-aed82200-c27e-11eb-8060-6eb41f190f70.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/2350.
