### ISSUE TITLE
Modules page gives 404 error

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2285]
**Description:**
$subject for Modules page when accessing from left navigation

Correct URL should be [1], but instead it goes to [2] and gives 404 error.

[1] https://dev.ballerina.io/learn/user-guide/ballerina-packages/modules/
[2] https://dev.ballerina.io/learn/user-guide/ballerina-packages/package-layout/learn/user-guide/ballerina-packages/modules/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by azinneera** [comment]
Resolved by https://github.com/ballerina-platform/ballerina-dev-website/pull/2284
