### ISSUE TITLE
Creating the launch.json file step is not mentioned in first sub topic of debugger page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2290]
**Description:**
$subject in [1]. To select the `Select Ballerina Debug as the Environment.` first we need to create the launch.json file and that step is not mentioned in [1]. But it is mentioned in sub topic [2].

So either we should move that part into subtopic 1 or reword sub topic 1 also to include the same.

[1] https://dev.ballerina.io/learn/tooling-guide/visual-studio-code-extension/debugging/#running-without-debugging
[2] https://dev.ballerina.io/learn/tooling-guide/visual-studio-code-extension/debugging/#starting-a-debug-session

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage Creating a `launch.json` file is not mandatory when running the programs in non-debug mode, as shown in the following sample.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/29032600/120304432-673caf00-c2ed-11eb-8221-5425f6c2d5fb.gif)

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage As per the offline discussion we had, we will restructure the debugging guide and move down the `running without debugging` section, to prioritize the main debugging options.
