### ISSUE TITLE
By-Example Side Navigation meant for Swan-lake is appearing for 1.2 as well

### ISSUE THREAD

**Issue by Ibaqu** [ballerina-platform/ballerina-dev-website#2316]
**Description:**
The side navigation panel with dropdowns that is meant for Swan Lake seems to be appearing for 1.2 as well. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since this is fixed in [1] now.

[1] https://dev.ballerina.io/1.2/learn/by-example/
