### ISSUE TITLE
The styling of the descriptions in the BBEs having unordered lists seem inconsistent

### ISSUE THREAD

**Issue by lasinicl** [ballerina-platform/ballerina-dev-website#2332]
**Description:**
$title

consider https://dev.ballerina.io/learn/by-example/isolated-functions BBE. 
The description that is immediately after the bulleted list seems to have different styling than the rest of the content. 

![Screenshot from 2021-06-01 22-00-03](https://user-images.githubusercontent.com/19838787/120359776-b1da1d80-c325-11eb-8ed3-94f7ef454312.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Fixed by adding the content after the bullet points in HTML. Fixed via [1] and [2].

[1] https://github.com/ballerina-platform/ballerina-distribution/pull/1916
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/2382
