### ISSUE TITLE
Support BBE generation tool to add images 

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-dev-website#2369]
**Description:**
We need to add a sequence diagram image to https://ballerina.io/learn/by-example/sequence-diagrams. I have tried to add an image in the same directory and add an HTML image tag in the description. Even HTML rendering work, BBE generation tool does not copy the images into final BBE web pages. 

I think we need to support copying images via BBE generation tool.

**Comment by praneesha** [comment]
We need to update the [BBE Gen Tool](https://github.com/ballerina-platform/ballerina-release/blob/master/ballerinaByExample/tools/generate.go) to support adding diagrams (PNG files) to BBE descriptions.

We need to add a diagram to make the explanation of the [Sequence Diagrams BBE](https://dev.ballerina.io/learn/by-example/sequence-diagrams.html) clearer.

**Comment by praneesha** [comment]
We can add images to BBEs now as shown below. The PNG files of the images should be added to the `<ballerina-distribution-repo>/examples/images/` directory.

<img width="1440" alt="Screenshot 2021-06-12 at 21 04 01" src="https://user-images.githubusercontent.com/11707273/121781637-647e6b80-cbc3-11eb-880a-7c918db71c60.png">
