### ISSUE TITLE
Update the Community page with Trademark related legal stuff

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2374]
**Description:**
$subject for the logos in [1]. It says following which is legally not enough for trademark:

`Download any file of the Ballerina logo to use for content or swag.` 

We need to update the above with exact clauses on how to use them. Please get support from the legal team.

[1] https://ballerina.io/community/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is done in [1] and added as a footer link.

[1] https://ballerina.io/trademark-usage-policy/
