### ISSUE TITLE
Update the Website Styles to Use the `index.json` file for the BBEs Layout

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2378]
**Description:**
Need to update the website styles to use the [`index.json` file](https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/index.json) in the `ballerina-distribution` repo for the left nav of the BBEs layout.

BBEs left nav is designed by the below files [1] and [2], and they need to updated to read the `index.json` file and populate the left nav items of the BBE layout.

[1] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/_data/bbenavswanlake.yml
[2] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/_layouts/ballerina-example-page.html
[3] https://ballerina.io/learn/by-example/hello-world

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This is fixed in following PR
https://github.com/ballerina-platform/ballerina-dev-website/pull/2412/files
