### ISSUE TITLE
Change the URL Thumbnail Image of Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2381]
**Description:**
Currently, the thumbnail icon of the ballerina.io URL is shown as follows.

<img width="792" alt="Screenshot 2021-06-04 at 17 00 50" src="https://user-images.githubusercontent.com/11707273/120794950-7bcfb000-c556-11eb-9aa6-abfd0615ada7.png">

Better if we can update it to an image may be similar to the one in the Twitter announcement as follows.

<img width="1390" alt="Screenshot 2021-06-03 at 00 04 28" src="https://user-images.githubusercontent.com/11707273/120795269-e54fbe80-c556-11eb-82a0-ae5ab674b547.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
@iamsameeraliyanage - We need to create a new thumbnail icon using the design of the one on Twitter above and by removing the hyperlinks.

**Comment by iamsameeraliyanage** [comment]
This is fixed. Tested on twitter , facebook and google meet chat.
![image (1)](https://user-images.githubusercontent.com/67787442/124796935-5415a280-df6f-11eb-9f77-51031a77a76f.png)
