### ISSUE TITLE
Add Algolia Search to Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2404]
**Description:**
Need to integrate the Algolia search[1] in Bio.

[1] https://docsearch.algolia.com/

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Related issue https://github.com/ballerina-platform/ballerina-dev-website/issues/2150

**Comment by anupama-pathirage** [comment]
Related issue https://github.com/ballerina-platform/ballerina-dev-website/issues/1580

**Comment by anupama-pathirage** [comment]
Related issue https://github.com/ballerina-platform/ballerina-dev-website/issues/1793

**Comment by praneesha** [comment]
Closing since this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/2491.
