### ISSUE TITLE
Add a Workflow to Automate Regenerating the BBEs for Any BBE Update

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2415]
**Description:**
Need to add a workflow to automatically regenerate the BBEs and update the dev site, either daily or once a change is done to any BBE folder in the `ballerina-distribution` repo.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
We have included a workflow in ballerina-distribution repo [1] to trigger any /examples directory changes to generate BBE generation workflow

[1] https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/trigger-bbe-generation.yml

[2] https://github.com/ballerina-platform/ballerina-dev-website/actions/workflows/update_ballerina_by_example_master.yml
