### ISSUE TITLE
Add a Workflow to Automate the "index.json" File Updates

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2417]
**Description:**
Need to add a new workflow in this `ballerina-distribution` repo to update the `all-bbes.json` file in the `ballerina-dev-website` repo, once the `index.json` file is updated.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
We have included a workflow in ballerina-distribution repo [1] to trigger any /examples directory changes to generate BBE generation workflow

[1] https://github.com/ballerina-platform/ballerina-distribution/actions/workflows/trigger-bbe-generation.yml

[2] https://github.com/ballerina-platform/ballerina-dev-website/actions/workflows/update_ballerina_by_example_master.yml
