### ISSUE TITLE
Rewrite the Left Navbar for More Improvements

### ISSUE THREAD

**Issue by iamsameeraliyanage** [ballerina-platform/ballerina-dev-website#2427]
**Description:**
If more improvements (more levels) are required it can be recommended to rewrite the HTML template and the javascript of the left navbar.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since all the current requirements are fully addressed with the current left nav implementation.

Will reopen if we get new requirements in the future.
