### ISSUE TITLE
Fix the Issues of the Bio Mobile View

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2444]
**Description:**
Need to fix the issues below on the Bio mobile view.

- BBEs are not loading for the Swan Lake Version.
- The teal color should be applied when hovering over the top menu links.
- The mobile version is not available for the Playground.
- The mobile version is not available for the Central.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by iamsameeraliyanage** [comment]
BBEs are not loading for the Swan Lake Version.

> BBEs are not loading for the Swan Lake Version. - Fixed with https://github.com/ballerina-platform/ballerina-dev-website/pull/2582
> The teal color should be applied when hovering over the top menu links. - There are no mouse over events for mobile devices. So this cant fix.
> The mobile version is not available for the Playground. - This issue happened because issue creator check with this desktop responsive browser(Inspect Tool) and page open with new tab and it opens with webs view. This is working when we test in real mobile device. 
> The mobile version is not available for the Central-.This issue happened because issue creator check with this desktop responsive browser(Inspect Tool) and page open with new tab and it opens with webs view. This is working when we test in real mobile device.
