### ISSUE TITLE
Can't access BBEs for v1.x.x releases

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-dev-website#2476]
**Description:**

$subject.

Seeing quite a few broken links on the website. e.g:

[1] https://ballerina.io/1.2/learn/by-example/introduction/

[2] https://ballerina.io/1.2/learn/by-example/

**Suggested Labels (optional):**
Priority/Highest

**Comment by praneesha** [comment]
Closing since this is fixed now.
