### ISSUE TITLE
Fix the Alignment Issue of the Cookie Policy Pop Up

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2483]
**Description:**
Fix the alignment issue of the Cookie Policy pop-up below on the Downloads page[1].

![image](https://user-images.githubusercontent.com/11707273/122756555-2c0e1a00-d2b4-11eb-87d5-e738f7ee10fe.png)

[1] https://dev.ballerina.io/downloads/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by iamsameeraliyanage** [comment]
![image](https://user-images.githubusercontent.com/67787442/123757301-75292400-d8db-11eb-829c-015b941d2082.png)
