### ISSUE TITLE
Cannot Run the Go Tool in Windows due to Path Recognition Issue

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2493]
**Description:**
The Go tool cannot be run on a Windows machine because the paths given with the forward-slash are not recognized in Windows. The paths should be given with the backward slash in the Windows environment.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by YasithD** [comment]
New JavaScript tool for BBE generation works, fine with Windows as well.
