### ISSUE TITLE
Fix the Table Width on the "Flexibly Typed" "Why Ballerina" Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2496]
**Description:**
Fix the table width on the "Flexibly Typed" "Why Ballerina" page[1].

![image (1)](https://user-images.githubusercontent.com/11707273/122869807-67f3be80-d34a-11eb-8ae4-f633b5b75317.png)

[1] Fix the Table Width on the "Flexibly Typed" "Why Ballerina" page

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by iamsameeraliyanage** [comment]
![image](https://user-images.githubusercontent.com/67787442/123125334-0cb6ee80-d466-11eb-93e3-bef16aa824a8.png)
