### ISSUE TITLE
Remove Edit on Github link on BBE home page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#250]
**Description:**

$subject for [1] as it gives 404. Also it doens't make sense to have edit link for that page as it get generated based on a .json file

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/16300038/75235186-d6ba1980-57e1-11ea-84a3-6b64e30eb06b.png">

[1] https://ballerina.io/v1-1/learn/by-example/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is fixed in [1]. need to generate BBEs to apply the change to this repo.

[1] https://github.com/NipunaMarcus/ballerina-www/pull/1

**Comment by praneesha** [comment]
Reopening as we have fixed this in the old ballerina-www repo via NipunaMarcus/ballerina-www#1. This should be fixed in the new BBE Generation tool.

**Comment by praneesha** [comment]
This is removed in all versions now.
