### ISSUE TITLE
`Try Ballerina` needs a list of samples.

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-dev-website#2535]
`Try Ballerina` needs a list of samples. It's unlikely people will be able to type hole programs without any help.
A drop down list of per-written samples would be good.

**Comment by praneesha** [comment]
Basically, if we are using existing examples, we need to add a drop-down and append the GIST URLs of the BBEs to it as shown in the example below.

`https://stg-play.ballerina.io/?gist=5d9a9543c3fc1cc94a450bb072e698a4&file=hello_world_parallel.bal`

<img width="1300" alt="bio-playground-widget" src="https://user-images.githubusercontent.com/11707273/117600551-c2a1d400-b169-11eb-8345-0bf14484740e.png">

**Comment by anupama-pathirage** [comment]
related to https://github.com/ballerina-platform/ballerina-dev-website/issues/3088

**Comment by praneesha** [comment]
Closing since this will be addressed via https://github.com/ballerina-platform/ballerina-dev-website/issues/3088.
