### ISSUE TITLE
Incorrect URLs generated for type referenced fields in API docs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#255]
**Description:**

Due to the $subject we have urls which give 404 for following urls [1] and [2].

StreamingListner - Link from the "Listeners" Section in https://ballerina.io/v1-1/learn/api-docs/ballerina/nats/index.html
[1] https://ballerina.io/v1-1/learn/api-docs/ballerina/nats/listeners/StreamingListener.html

MockListener - Link from the "Listeners" Section in https://ballerina.io/v1-1/learn/api-docs/ballerina/http/index.html page
[2] https://ballerina.io/v1-1/learn/api-docs/ballerina/http/listeners/MockListener.html

Related issue: 
https://github.com/ballerina-platform/ballerina-lang/issues/21082

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/254.
