### ISSUE TITLE
Enable Pushing Selected Changes to the Ballerina Live Site

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2559]
**Description:**
Need to find and implement the optimal way to enable pushing selected changes to the Ballerina live site.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
This will be handled with a process change. Master should have only the changes which should be deployed to live. All other changes should be done in relevant branches. To verify the those branches developers could run docker image locally
