### ISSUE TITLE
Having different font sizes in the text

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2568]
**Description:**
Although code highlighting is good , it results in different font sizes in the topic which looks odd

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/16300038/124170122-aa449a80-dac4-11eb-96d6-2761051c6c6b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This is fixed now as shown below.

<img width="1287" alt="Screenshot 2021-07-07 at 21 55 08" src="https://user-images.githubusercontent.com/11707273/124795778-0b111e80-df6e-11eb-9c4e-d629c5b2f998.png">
