### ISSUE TITLE
Add a Search Results Page to the Algolia Search in Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2588]
**Description:**
The current implementation of the Algolia search in Bio shows the search results on a drop-down menu, which appears near the search box.

It might be more user-friendly to direct users to a separate page, which lists the search results.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by iamsameeraliyanage** [comment]
I think current implementation is more user friendly. User doesn't need to redirected to another page and find his result and click the link is more clicks.
If needed the implementation codes are as follows
https://codesandbox.io/s/algolia-custom-search-fjb7q?file=/src/app.js

**Comment by praneesha** [comment]
Closing since this can be improved in the future using [1] as per the reply above.

[1] https://codesandbox.io/s/algolia-custom-search-fjb7q?file=/src/app.js
