### ISSUE TITLE
Add a Feedback Option in Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2592]
**Description:**
We can add a feedback option in Bio as done in [1].

<img width="1440" alt="Screenshot 2021-07-07 at 22 24 12" src="https://user-images.githubusercontent.com/11707273/124799403-22eaa180-df72-11eb-8912-e15e4eecc02c.png">

[1] https://developers.google.com/style/voice

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority.
