### ISSUE TITLE
Document Error Message Guidelines on the Dev Site Wiki

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2594]
**Description:**
Need to come up with and document error message guidelines on the Dev Site Wiki.

[1] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/learn/user-guide/getting-started/Installation-options.md#installing-on-linux

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is invalid
