### ISSUE TITLE
Document CLI Text Guidelines on the Dev Site Wiki

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2595]
**Description:**
Need to come up with and document error message guidelines on the Dev Site Wiki. Can use the Git Hub CLI text as a standard to follow.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is not needed.
