### ISSUE TITLE
Build a Docker Container for the Local Website Build

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2615]
**Description:**
We need to build a Docker container to build the website locally. We currently have Ruby version conflicts associated with building the dev site locally using the `bundle exec jekyll serve` command.

This is to avoid them and enable building the dev site locally.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/2627
