### ISSUE TITLE
Configure the Algolia Search to Support Cross Domain Searches

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2713]
**Description:**
From the Bio, we need to make it able to search sub domains such as blog.io and lib.io. This can be done with the open-source plan of Algolia by configuring the JSON file to provide the sitemap index as an input to it.
**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by iamsameeraliyanage** [comment]
This is working now. 
![image](https://user-images.githubusercontent.com/67787442/132129948-a6d11884-e43a-4b31-b89d-52b0f60abd8f.png)
![image](https://user-images.githubusercontent.com/67787442/132129991-b8b97515-9841-4d79-805c-1e755cc3c2c0.png)

**Comment by praneesha** [comment]
Closed as per the above comment.
