### ISSUE TITLE
Incorrect link text to refer VSCode extension quick start

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2733]
**Description:**
$subject in [1] as now it seems the page is renamed and the URL is redirected to a different topic named "Quick Start". We need to change the highlighted link text accordingly.

[1] https://dev.ballerina.io/learn/installing-ballerina/setting-up-ballerina/

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/16300038/130496254-f1ea3f45-98b1-43d0-af5c-cfa74c702a6b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Points/0.5

**Comment by praneesha** [comment]
Closing since this is fixed now.
