### ISSUE TITLE
Show the video series instead of the part 1 video

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2735]
**Description:**

$subject in [1]. Currently it is showing the part one only. Can we showcase all five parts in small boxes?

[1] https://dev.ballerina.io/learn/language-walkthrough/

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
2/Points
