### ISSUE TITLE
For ballerina central instad of contribute, we need to use publish

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2739]
**Description:**

$subject in [1]. It should be `Publish to Ballerina Central`. Also saying module is not correct and we need to change it to package.

[1] https://dev.ballerina.io/community/

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/16300038/130505889-48cda70c-8b4e-4631-8240-f0331a9d66f1.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Points/0.5
