### ISSUE TITLE
Font size is large on the report issues pop up page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2740]
**Description:**
$subject in [1]

[1] https://dev.ballerina.io/community/

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/16300038/130507097-261d1d43-a5dd-4408-a9be-02f49dbfeb90.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
