### ISSUE TITLE
Incorrect links in Report issues page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2741]
**Description:**

$subject in [1] 

1. Standard library -> Should change to https://github.com/ballerina-platform/ballerina-standard-library/issues/new/choose
2.  Language specification -> Should change to https://github.com/ballerina-platform/ballerina-spec/issues/new

[1] https://dev.ballerina.io/community/

<img width="650" alt="image" src="https://user-images.githubusercontent.com/16300038/130507242-f67d8af0-c82d-43ba-b090-5f8464c22d79.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Points 0.25.

**Comment by praneesha** [comment]
- Fixed in the `dev` beanch via https://github.com/ballerina-platform/ballerina-dev-website/pull/2776.

**Comment by praneesha** [comment]
Closing since this is fixed now.
