### ISSUE TITLE
BBE copy button copies duplicate content

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#2742]
**Description:**
https://dev.ballerina.io/learn/by-example/transaction-statement

**Steps to reproduce:**
Try copying using the copy button, and check the content.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is a duplicate f https://github.com/ballerina-platform/ballerina-dev-website/issues/2609.
