### ISSUE TITLE
New left navigation is shown for 1.2.x branch samples

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2780]
**Description:**
$subject see the steps below and the video

**Steps to reproduce:**

1. Go to home page and search for keyword. (For ex: `Stream`)
2. Click on the search result and it will load BBE in 1.2.x branch (See the breadcrumbs to confirm whether it is from 1.2.x branch)
3. Now the left navigation is loaded from the latest BBEs which is worng
4. If we directly go to the learn page and select 1.2.x from drop down and select the BBE from there, the new left navigation is not shown. (i.e. issue is not there.)

https://user-images.githubusercontent.com/16300038/132054997-f8650aec-cc9b-47d0-b932-8742ede8f521.mov

**Comment by praneesha** [comment]
Closing since these issues are fixed now.
