### ISSUE TITLE
Infinite cyclic redirections for some urls

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2781]
**Description:**
$subject . See [1]

[1] https://ballerina.io/learn/testing-ballerina-code/testing-services-and-clients/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
