### ISSUE TITLE
Old Website links are not getting redirected Properly

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-dev-website#280]
**Description:**
Old website links that does not have version in the URL does not not get redirected properly to the latest website.
https://ballerina.io/learn Gets redirected to https://ballerina.io/v1-1/learn/
https://ballerina.io/learn/by-example/ gives 404

**Steps to reproduce:**
Go to https://github.com/ballerina-platform/ballerina-lang
Click on Ballerina by Examples link

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-lang/pull/22125/files.
