### ISSUE TITLE
Do the Dev Site Generation Via a GitHub Action

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2836]
**Description:**
Currently, the static HTML pages are generated via running a Jekyll build on GitHub pages. It would be a better approach to generate the static HTML generation via a GitHub workflow. Then, there will be more control over the Jekyll versions that are being used in the build, can avoid the timeout caused by having the version folders etc.

If we are adding a new versioned folder to the site dir, that can cause a  timeout. But the dev should have it first since it's the same setup. Anyway, this level of changes should be watched out for in the upcoming releases.

Also since the site is growing, better to move this out of Git pages and run on a standalone Jekyll server.

Sometimes, the pre-prod site build fails due to timeouts caused by the content load. Currently, the content of older versions such as 1.1, 1.0, and 0.990 are converted to HTML as a temporary fix for this.

However, as a long-term, permanent solution, we need to implement a workflow, which generates HTML content from the MD files, and then passes them to GitHub pages to be served via Jekyll.

Out of Jekyll and the HTML static content, if it's with the Github pages Jekyll generation, we can use a Github action to generate and commit static webpages to the dev website repo. Since the timeout comes from the Github pages when running the Jekyll build, this suggestion would work best.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
This is invalid with new website revamp as we have completely replaced jekyll with nextjs and do the build with GitHub Actions
