### ISSUE TITLE
Loosing track of the left navigation panel item when loading in to a new page

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-dev-website#2844]
**Description:**
When navigating to a new tab in the site, for an example in the page below when navigated to `Error Reporting` to `Error Handling`, the left panel reloads and the bolded tab which is `Error Handling` is missing in the newly loaded window(should scroll down to track it). IMO the UX will improve if we can make the left panel static with the reload of a new page. 

![Screenshot from 2021-09-14 09-25-05](https://user-images.githubusercontent.com/46120162/133871491-1d9ccf81-35c9-477e-b7e1-751ad61d231f.png)

**Steps to reproduce:**
https://ballerina.io/learn/by-example/error-reporting

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since we will be removing the Learn By Examples view and will keep only one set of examples as "Ballerina By Examples" in B.io.
