### ISSUE TITLE
Incorrect link for Function as a service title in the left navigation

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2845]
**Description:**

$subject.
It points to https://ballerina.io/learn/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-samples/

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/16300038/133897740-45413c0b-399f-45fa-b7ef-8671f59ac408.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this ios fixed now.
