### ISSUE TITLE
BBE Copy button duplicates content

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-dev-website#2850]
**Description:**
Copy button on BBEs duplicates the copied content.

**Steps to reproduce:**
1. Click on the copy button on https://ballerina.io/learn/by-example/hello-world
2. Paste on a text editor

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
