### ISSUE TITLE
Inconsistencies in learn page home titles and page tiltes.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2861]
**Description:**

Refer to the below two links in learn page home [1]

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16300038/134967335-b583178c-a9ec-47ce-9438-1c7e171f7998.png">

**Case 1 :**  - This is incorrect and Should change the learn home page link text to `Installing Ballerina`
Link Title in above is : `Setting Up Ballerina`
But when we click and go to the page highlevel page title and breadcrumb title is `Installign Ballerina`

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/16300038/134967588-234bc427-e6fe-403d-8d28-d1fe5a4d0a36.png">

**Case 2:** This is correct
Both the home page link text, page title and breadcrumb text is `Hello World`

[1] https://ballerina.io/learn/

**Comment by praneesha** [comment]
Closing since this is fixed now.
