### ISSUE TITLE
Links in cloud learn page is not properly formatted

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2863]
**Description:**
$subject in [1] 
<img width="938" alt="image" src="https://user-images.githubusercontent.com/16300038/134970292-a3c7e163-462e-401c-a154-a8634f795de3.png">

[1] https://ballerina.io/learn/running-ballerina-programs-in-the-cloud/code-to-cloud-deployment/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
