### ISSUE TITLE
The calling java code from ballerina and vice versal page is too long.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2868]
**Description:**
$subject in [1]. Break properly.

[1] https://ballerina.io/learn/calling-java-code-from-ballerina-and-vice-versa/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/606.
