### ISSUE TITLE
Topics are not properly formatted in the bindgen tool page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2869]
**Description:**
$subject in [1]

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/16300038/134977246-0c98643f-1c88-4bce-a25e-8a899c99ac2d.png">

[1] https://ballerina.io/learn/calling-java-code-from-ballerina-and-vice-versa/#the-bindgen-tool

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
