### ISSUE TITLE
Copy icon does not work in BBEs

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-dev-website#287]
**Description:**
Copy the following  BBE, using the copy icon and paste it. 
https://ballerina.io/v1-1/learn/by-example/the-main-function.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.2.0 

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/ballerina-platform/ballerina-dev-website/issues/288 reports the same issue.

**Comment by praneesha** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/issues/288 reports the same issue.

**Comment by praneesha** [comment]
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/288.
