### ISSUE TITLE
Invalid set of bullet points in style guide page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2871]
**Description:**
$subject in [1] 

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/16300038/134978934-5c10fa73-68b4-4319-b42b-edd533642bfc.png">

[1] https://ballerina.io/learn/style-guide/top-level-definitions/#general-practices

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
