### ISSUE TITLE
`OpenAPI` is misspelled in left navigation.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2873]
**Description:**
$subject in [1]

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/16300038/134981249-ef628c47-10b3-471c-846a-13f54eea9769.png">

[1] https://ballerina.io/learn/cli-documentation/openapi/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
