### ISSUE TITLE
Create a mail group to receive notifications on b.io feedback forms and link it for forms

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#2891]
**Description:**
$subject for community call forms, and new community page forms (including community contributions)

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this needs to be added to the respective marketing tasks list.

**Comment by anupama-pathirage** [comment]
@praneesha What else need to be done from the marketing side for this? This issue is to add it to all community page forms. Did we complete that?

**Comment by anupama-pathirage** [comment]
Ok. please loop such issues before closing the issues next time.
