### ISSUE TITLE
Add a button for join as member to slack

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#2892]
**Description:**
In https://ballerina.io/community/slack/#if-not-join-us.

Please check this https://github.com/ballerina-platform/community/issues/13#issuecomment-929541653

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this will be addressed in the new Community page design via https://github.com/ballerina-platform/ballerina-dev-website/issues/3195.
