### ISSUE TITLE
Link Website Forms to an Email Group

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2898]
**Description:**
Need to link all the forms, which include user interactions (e.g., the forms on the new Community page and the "Subscribe to the Newsletter" footer Button etc.) to the `notify@ballerina.io` email group.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by Thimuth** [comment]
Updated the Ballerina subscribe form. 
New community forms will be updated once the page goes live.

**Comment by ashweni** [comment]
All forms are linked to Pardot
