### ISSUE TITLE
Create a Guideline for the Release Note

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2909]
**Description:**
Need to document a set of guidelines that are required when adding content to the release note. For example, to cover aspects such as [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/2897#discussion_r725854231

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as not needed.
