### ISSUE TITLE
Page navigation button is not placed properly

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#2910]
**Description:**
The page navigation button is placed bit below than where it should be in the following page.
https://ballerina.io/1.1/learn/by-example/secured-service-with-basic-auth.html

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
@udda1996 Thanks for reporting this. Will you be able to send a screenshot of the page by highlighting the issue? I am sorry, I am unable to identify it as shown below.

<img width="1005" alt="Screenshot 2021-10-18 at 07 44 21" src="https://user-images.githubusercontent.com/11707273/137658987-c57b9aeb-a00c-4575-9c32-18d7f7bf7d39.png">

**Comment by praneesha** [comment]
@udda1996 - Thank you very much for the response. Will get this fixed.

**Comment by praneesha** [comment]
Closing as this is BBE of version 1.1 and we do not have this issue in the new BBE design.
