### ISSUE TITLE
Fix the Numbered Bullets in the Observability Learn Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#2911]
**Description:**
Need to fix the numbered bullets in the observability Learn page.

This needs to be fixed after https://github.com/ballerina-platform/ballerina-dev-website/issues/2914 is fixed.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by kaneeldias** [comment]
Closing as issue was fixed with https://github.com/ballerina-platform/ballerina-dev-website/pull/3310
