### ISSUE TITLE
Past and upcoming calls google doc is outdated

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#2980]
**Description:**
Under **community call** section in the community page, the doc linked with **past and upcoming calls** (https://docs.google.com/document/d/1TPi0ktNvk-gQhVh46ckP5_LyhvwLJSQ3NJeSfv8459A/edit) is outdated and is missing the last few community call details.

**Comment by IMS94** [comment]
@dakshitha @praneesha Can you check on this?

**Comment by Samallama** [comment]
We have removed the working doc link from the site [1]. We didn't see much traffic to the doc and anyone interested in the call can sign up to get notified.

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/3077
