### ISSUE TITLE
Change website version from v1-1 to v1.1

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-platform/ballerina-dev-website#303]
**Description:**
Change the website version content path to be shown as v1.1 not as v1-1.
When doing this change the following places as well. Because these will break externally mentioned links.

- Ballerina lang repo docs
- Both Plugins' marketplace description docs
- Other repos in ballerina-platform org

**Comment by praneesha** [comment]
This could be connected to the change done in [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/341

**Comment by Thimuth** [comment]
URL structure is updated to have ballerina.io/1.1/<>
#412
