### ISSUE TITLE
Incorrect path for local file system cache of central repo

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3067]
**Description:**
$subject in https://ballerina.io/learn/managing-dependencies/

It should be `<USER_HOME>/.ballerina/repositories/central.ballerina.io/bala`

<img width="921" alt="image" src="https://user-images.githubusercontent.com/16300038/141366406-772d4c2f-7130-4f83-b309-c83735724d3d.png">

**Affected Versions:**

Ballerina Swan Lake Beta 3
Language specification 2021R1
Update Tool 1.3.6

**Comment by anupama-pathirage** [comment]
@azinneera  Please confirm the correct behaviour

**Comment by azinneera** [comment]
> @azinneera Please confirm the correct behaviour

This is correct.

**Comment by praneesha** [comment]
Closing since the URL mentioned in the doc is correct as per the above comment.

**Comment by anupama-pathirage** [comment]
@praneesha URL mentiond in the doc is not correct, hence re-opening the issue. @azinneera will fix it along with learn page revamp effort.
