### ISSUE TITLE
Introduce Dark Mode to the Ballerina Website

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3120]
**Description:**
Some users prefer to use the dark mode for applications/ websites, and thereby, most of the apps/websites support dark mode nowadays. Hence, users usually work with a high brightness setting on the monitor. However, with the increased brightness, UX becomes unsatisfactory with the light-themed websites. 

Therefore, it would be good to have a toggle button to switch between the bright and dark themes on B.io as done in  [4].

However, similar communities such as Python [1], Java [2], and Golang [3 ] official sites also do not support the inbuilt dark mode or have this switching implemented. Therefore, need to check the feasibility to add that feature on B.io. 

[1] https://www.python.org/ 
[2] https://www.java.com/en/ 
[3] https://go.dev/
[4] https://conf.reactjs.org/  

Appreciate any other suggestions as well.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dulajdilshan** [comment]
Convert the website into the dark mode with a third-party app. This is the look. 

![Screenshot from 2021-11-25 11-02-37](https://user-images.githubusercontent.com/25485997/143385219-4e193736-7fc8-4a4c-9668-3f7b3db755c2.png)

**Comment by praneesha** [comment]
@dulajdilshan - Good job! Thank you so much. Will check on this.

**Comment by praneesha** [comment]
An example of how the switching between the two themes can be provided by giving a toggle option on the top banner of B.io is as follows (as done by other similar communities).

![Screenshot 2021-12-03 at 10 46 33](https://user-images.githubusercontent.com/11707273/144731433-d12e775e-31c8-496f-a65b-3eb69375d8bd.png)

**Comment by sanjana** [comment]
> This is nice. Converted the website into dark mode with a third-party app. This is the look.
> 
> ![Screenshot from 2021-11-25 11-02-37](https://user-images.githubusercontent.com/25485997/143385219-4e193736-7fc8-4a4c-9668-3f7b3db755c2.png)

@dulajdilshan, you could try out enabling the flag at `chrome://flags/#enable-force-dark`, if using any Chromium browser.
I hope, it would be a better option compared to installing a third-party app to view in dark mode.

**Comment by praneesha** [comment]
@sm1990 - Shall we consider and evaluate the above options?
