### ISSUE TITLE
Empty box is shown for a `object` which doesn't have any methods

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-dev-website#3130]
**Description:**
There is an empty box (which is used to display methods of a `object`) even though the `object` doesn't have any methods.

Reference: https://lib.ballerina.io/ballerina/http/2.0.1/objectTypes/RequestInterceptor
![image](https://user-images.githubusercontent.com/9639050/143227162-0c2da335-89b8-46da-a355-0d97fc6ec1a4.png)

Reference: https://github.com/ballerina-platform/module-ballerina-http/blob/master/ballerina/http_interceptors.bal
```ballerina
# The HTTP request interceptor service object type
public type RequestInterceptor distinct service object {

};
```

**Comment by praneesha** [comment]
Closing since this issue was transferred to the corresponding repo.
