### ISSUE TITLE
Learn pages for 1.x versions are giving 404 when select from the version picker

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3136]
**Description:**

Learn pages for 1.x versions are giving 404 when select from the version picker. 
It seems the changes in titles is the issue. But it resolves correctly when we pick swan lake versions from 1.2.x. So the same should work for other way too. Refer to the video below.

**Steps to reproduce:**

Following flow works:

https://user-images.githubusercontent.com/16300038/143624704-4079b0b9-2d2b-4f7f-ba87-d2354cb3c914.mov

But the following flow gives the 404

https://user-images.githubusercontent.com/16300038/143624643-42cf5785-743a-488c-853f-e53f8b13beaa.mov

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/3150.
