### ISSUE TITLE
Report issues section of the community page should be updated with vscode plugin for tooling issues.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3145]
**Description:**
$subject for the repo https://github.com/wso2/ballerina-plugin-vscode/issues

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3166.
