### ISSUE TITLE
Removing redundant example word from BBE descriptions

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-dev-website#3154]
**Description:**
There is no need to use the word example again in the description as these are under the `BBE`.

<img width="228" alt="Screenshot 2021-06-28 at 11 52 46 AM" src="https://user-images.githubusercontent.com/12771261/123591860-23fd2f80-d80a-11eb-851b-95872a1e45e1.png">

We need to remove this usage from the following BBEs description

- [x] stan - @aashikam 
- [x] kafka - @dilanSachi 
- [x] RabbitMQ - @aashikam 
- [x] TCP Transport Security
- [x] IO
- [x] Time
- [x] XSLT

**Comment by Bhashinee** [comment]
TCP BBEs are fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/2630
