### ISSUE TITLE
Next / Previous Links at the bottom of examples 

### ISSUE THREAD

**Issue by ghp-dev** [ballerina-platform/ballerina-dev-website#3164]
**Description:**

Next / Previous Links at the bottom of an example allow for easier browsing.
A nicer UX means less reasons to abandon the site. 

**Describe your problem(s)**

When in scenarios with reduced screen real estate (e.g. half-screen width on a 13" notebook screen), The contents follow a single column layout - which is a good thing.

Unfortunatley this also means that the  menu icon for navigating to the next example scrolls out of view.

It is frustrating to
* scroll up
* expand the menu
* scroll down in the menu to the next entry
* click the entry
Just for saying "Next!"

**Describe your solution(s)**

Next / Previous Links as the last element in each example allows for easier browsing.

**Comment by YasithD** [comment]
This is fixed now with the new design.

![image](https://user-images.githubusercontent.com/59837420/181438020-ea8c4364-40b5-4e3b-9137-cc158bc03ba3.png)
