### ISSUE TITLE
No download links for archived versions of Ballerina

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#32]
Although we have a list of archived Ballerina verions at https://ballerina.io/downloads/archived, download links are only provided for the signature files of the distributions, not for the actual installers/distributions.

**Comment by praneesha** [comment]
The download links are added in [1] now as shown below.

<img width="1281" alt="Screenshot 2019-11-26 at 16 34 53" src="https://user-images.githubusercontent.com/11707273/69697718-46e4d080-1109-11ea-8da3-0719aa8198fc.png">


[1] https://ballerina.io/downloads/archived/
