### ISSUE TITLE
Syntax highlighting is not working in Hello World Page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3203]
**Description:**

$subject in 
https://ballerina.io/learn/hello-world/writing-your-first-ballerina-program/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is done in [1] now.

[1] http://pre-prod.ballerina.io/learn/hello-world/writing-your-first-ballerina-program/
