### ISSUE TITLE
Add The Talk on the Type System to Bio

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3245]
**Description:**
Need to add the talk on the type system[1] under the `Talks` section on the Learn page.

[1] https://www.youtube.com/watch?v=y3BXWq2GNWw

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dakshitha** [comment]
We need to add the talk and the slides together. We may be able to get the video to do some editing. The page should look like this - https://ballerina.io/learn/language-walkthrough/

Video link - https://www.youtube.com/watch?v=y3BXWq2GNWw (the link will change if we get the video)
Slides - https://docs.google.com/presentation/d/1dnkCf4U0HkTBXGKoSB2b3bNME7t98pmKVcD2nb_bO0M/edit#slide=id.p (convert to PDF)

**Comment by praneesha** [comment]
This is added in https://ballerina.io/community/resources/ now.
