### ISSUE TITLE
A log output displayed in the website is different from the actual log output

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-dev-website#3270]
**Description:**
https://ballerina.io/learn/hello-world/writing-your-first-ballerina-program
In the above link, under "Writing a Simple Service", it displays, if the service up and running, log output should be displayed as follows.
![1](https://user-images.githubusercontent.com/63797478/146496118-38194be6-eeb4-4f97-94d5-7b99d1c3d2f3.PNG)

But the actual log out displayed without **[ballerina/http] started HTTP/WS listener 0.0.0.0:9090** .

![2](https://user-images.githubusercontent.com/63797478/146496219-6102e3e7-128e-4289-ac6f-9d5731ab5734.PNG)

If **[ballerina/http] started HTTP/WS listener 0.0.0.0:9090**  part is not necessary, can you remove it from the website?

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3346.
