### ISSUE TITLE
[Download Page] Update command of Ballerina update tool still has the old command

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-dev-website#3274]
**Description:**
See the attached screenshot below, 

<img width="1189" alt="Screen Shot 2021-12-18 at 6 15 19 PM" src="https://user-images.githubusercontent.com/8402398/146641721-5ab0f4e6-4a90-4e34-81e6-7ac370880fd0.png">

Command `ballerina update` should change to `bal update`

**Comment by praneesha** [comment]
For Update Tool versions below 0.8.14, the command should be `ballerina-update` as it was changed to `bal update` only from 0.8.14 onwards.

@keizer619 - Please confirm.

**Comment by keizer619** [comment]
Previous versions from ` 0.8.14` had `ballerina` command. As we have `1.3.x` for a while and almost everyone uses `bal` shall we remove that line ?

**Comment by praneesha** [comment]
Closing this for now will remove the line with the Swan Lake GA release.
