### ISSUE TITLE
Missing a BBE for Object Type Definition

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-dev-website#3275]
**Description:**
Currently, the `object` section in the BBEs is pointing to [object creation by Classes](https://ballerina.io/learn/by-example/object.html).
Unable to find an example for object typedefs.

```
public type Foo object {
    int a;

    function fn();
};
```

Also, it would be better to indicate any differences between `object` and `record`.

**Comment by praneesha** [comment]
Will be fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/3099/.
