### ISSUE TITLE
Add documentation around `async send`, `sync-send`, `multiple-receive` and `flush` actions

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#3284]
**Description:**
Currently, BBEs do not reflect the usages of above cases (except `async-send-action`). Need to add some documentation around the above actions and their usages.

**Describe your problem(s)**
See description

**Comment by prakanth97** [comment]
`async-send`, `sync-send`, `flush` BBEs are added. `multiple-receive` is not supported yet. Hence closing the issue.
