### ISSUE TITLE
Ballerina installing via the ZIP file does not point to the latest version in 1.2.x

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-dev-website#3289]
**Description:**
In 1.2.x versions "Installing via the Ballerina Language ZIP File" [1] section does not point to the latest release, which is 1.2.23 at the moment. Currently it is pointed to 1.2.21, which is not updated for 1.2.22 and 1.2.23.

[1] https://ballerina.io/1.2/learn/installing-ballerina/#building-from-source

**Comment by praneesha** [comment]
Closing since this is fixed now.

**Comment by ldclakmal** [comment]
Re opening this issue, since it is there again. Please check [1] and "Download the Ballerina language ZIP file" does not points to v1.2.25 (latest 1.2.x as of now)

[1] https://ballerina.io/1.2/learn/installing-ballerina/#installing-via-the-ballerina-language-zip-file

**Comment by praneesha** [comment]
Closing as this is fixed now.
