### ISSUE TITLE
Navigating to non existing resources

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-dev-website#3290]
**Description:**
Please refer the following screen capture

https://user-images.githubusercontent.com/1329674/147038597-4e7ccf48-7d85-44a7-b7f4-1a804cb6b9ae.mp4

**Comment by praneesha** [comment]
Closing since this will be addressed via the below.

1. https://github.com/wso2-enterprise/ballerina-central/issues/605
2. https://github.com/ballerina-platform/ballerina-dev-website/issues/3293
3. https://github.com/ballerina-platform/ballerina-dev-website/issues/3178
