### ISSUE TITLE
Banner is inconsistence across versions.

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-dev-website#3301]
https://ballerina.io/1.2/ shows beta3 is here, But https://ballerina.io/ shows beta6 is here. 

![image](https://user-images.githubusercontent.com/1356214/147938605-66290865-0c30-4c15-b52d-04899805b6af.png)

![image](https://user-images.githubusercontent.com/1356214/147938625-e1aadb2e-a7ab-4e19-beb6-e87cee03de49.png)

**Comment by praneesha** [comment]
This is fixed in [1] now.

[1] http://pre-prod.ballerina.io/1.2/learn/
