### ISSUE TITLE
Oxford comma is not used in community page texts

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3379]
**Description:**

$subject in http://dev.ballerina.io/community/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
This is not fully fixed. @praneesha pls check and fix all

**Comment by ashweni** [comment]
Edits made

**Comment by ashweni** [comment]
Updated
