### ISSUE TITLE
Incorrect link to Privacy policy in  Subscribe to Newsletter 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3380]
**Description:**
$subject in http://dev.ballerina.io/community/ as it points to http://go.pardot.com/privacy-policy

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/16300038/150124238-3fd7c589-10cd-4986-8001-b08ba3a30138.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
This is done in Pardot
![image](https://user-images.githubusercontent.com/73055030/150283088-deb63e04-bf8c-4202-91c0-be154c8092aa.png)
