### ISSUE TITLE
Submit content form is not working properly for the second time

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3381]
**Description:**
It doens't allow to submit two content one after the other. The second time the form is not viewing all the fields.

http://dev.ballerina.io/community/resources/

**Try submit one after the other using below link**

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/16300038/150125242-f6d3fc4b-90d6-411d-a15b-c7118c926ac8.png">

**It get partially loaded as follows in the second time**

<img width="566" alt="image" src="https://user-images.githubusercontent.com/16300038/150125131-f030533a-faa7-4d84-bece-2f172b293750.png">

**Tested in firefox.**

**Comment by praneesha** [comment]
Closing since this is working now.
