### ISSUE TITLE
 Submit content form is not clearing cache

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3382]
**Description:**
$subject. Even after we close and reopen the form it gives some cached fields etc.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
This has fixed by Pardot using enabling Do not prefill  function
![image](https://user-images.githubusercontent.com/73055030/150320789-977507d8-f452-485f-8775-d71e229860ca.png)
