### ISSUE TITLE
Submit suggestion form for tech talk doesn't work at all 

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#3386]
Pressing the submit button gives no result. Keeps showing the form. 

![image](https://user-images.githubusercontent.com/11885043/150167864-37a20988-c071-4ead-88a4-504ef25761d6.png)

**Comment by dakshitha** [comment]
I believe the field names should be in title case.

**Comment by dinushan20** [comment]
Did you tick that captcha ? I tried now , For me it worked
![image](https://user-images.githubusercontent.com/73055030/150170649-51d793c0-2179-4f32-9d8b-b478128f1a31.png)
