### ISSUE TITLE
The `Monthly Tech talk`  link gives 404 error page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3391]
**Description:**

$subject with http://dev.ballerina.io/community/tech-talk/ when click from below

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/16300038/150298729-ae7424a5-4b64-427f-a1fc-d9496d0aeecf.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
Fixed with #3388
