### ISSUE TITLE
Links are not opening in a new tab for articles and other resources

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3393]
**Description:**

$subject in http://dev.ballerina.io/community/resources/. They should open in a new tab. 

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/16300038/150304510-759104a2-7db1-40c5-b570-71a129b5dc0b.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
Fixed with #3396 - c7f212f
