### ISSUE TITLE
Community page - Slack `Join Us` button works even if we don't tick the data policy clause

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3394]
**Description:**

$subject in http://dev.ballerina.io/community/

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/16300038/150304857-75ea2d2b-6ec1-49ad-9e91-594a96d09555.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
same issue is there for monthly tech talks as well

**Comment by dinushan20** [comment]
We can not keep this the data policy agreement  mandatory field due to GDPR policy.

**Comment by anupama-pathirage** [comment]
Then do we really need to add it under all forms? @dakshitha ?

**Comment by dinushan20** [comment]
We need to add it under the forms but as a optional field.

**Comment by anupama-pathirage** [comment]
What I really don't get is why we need a checkbox here? Do we internally check whether user has checked it? If not what is the real value of a check box?

What I suggested was simply a link under each form not a check box. For ex: something like below

https://wso2.com/newsletter/

<img width="683" alt="image" src="https://user-images.githubusercontent.com/16300038/150396695-85b414ee-3c88-42b0-a79b-750a1c0666ba.png">

**Comment by dinushan20** [comment]
@Thimuth Can you make suggestion on this?

**Comment by ashweni** [comment]
@anupama-pathirage - I believe it would be best to keep the check-box for the Newsletter/Tech Talk subscriptions, so if in the future we need to email the subscribers about something related to Ballerina (but not in a newsletter/event format) we would be legally able to do so.

@Thimuth - Will the checkboxes be needed for everything else? (Slack, forms etc...)

**Comment by Thimuth** [comment]
> @anupama-pathirage - I believe it would be best to keep the check-box for the Newsletter/Tech Talk subscriptions, so if in the future we need to email the subscribers about something related to Ballerina (but not in a newsletter/event format) we would be legally able to do so.
> 
> @Thimuth - Will the checkboxes be needed for everything else? (Slack, forms etc...)

@ashweni , If we are going to add the slack subscribers to the Ballerina interest group in Pardot and include them in future communications, then we need to have the consent box for those forms as well.

**Comment by ashweni** [comment]
Ack @Thimuth
