### ISSUE TITLE
Highlight the error message of the forms

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3395]
**Description:**

$subject as we can't identify the error easily. May be use red color fonts.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/16300038/150305321-cc19eea9-fd6b-48fb-a952-cab42d5ad661.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
@anupama-pathirage We can not use red color as it is not compatible with ballerina branding, Dark Grey is the best option, BTW I have removed that extra padding of error message in invalid CAPTCHA
![image](https://user-images.githubusercontent.com/73055030/151642675-4a664d71-ff83-4b14-8189-a3540ba07657.png)

**Comment by anupama-pathirage** [comment]
Ack +1 for the above

**Comment by dinushan20** [comment]
This was solved via Pardot form css updating.
