### ISSUE TITLE
Inconsistent wording to refer to slack community

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3398]
**Description:**

$subject in community page. Refer to below.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/16300038/150308353-49710ee5-5dc1-4bde-bc04-ea4fada03246.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
Fixed with #3396 - fc1e197
