### ISSUE TITLE
Update the Site Map of the "ballerina-dev-website" Repo

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#340]
**Description:**
We need to update the Site Map of the "ballerina-dev-website" Repo to avoid 0.991 results coming on top in the Google search results.

Also, we need to find a good tool to create the site map.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Samallama** [comment]
Thimuth has added the sitemap: https://github.com/ballerina-platform/ballerina-dev-website/blob/master/sitemap.xml
