### ISSUE TITLE
Time of tech talks is missing

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3405]
**Description:**
Add the time with zone info 

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/16300038/150400939-40578b85-a34f-4372-9734-4b5b86284de8.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
Fixed with #3407 - 9374436
