### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by sanjiva** [ballerina-platform/ballerina-dev-website#3411]
![image](https://user-images.githubusercontent.com/2355900/150479124-8b7d3d8e-309f-41b4-8fa4-1fe1123b791f.png)

The bottom list looks really weird .. like another menu. The L&F doesn't compel me at all :(.

**Comment by praneesha** [comment]
Closing as this is fixed in [1] now.

[1] http://dev.ballerina.io/community/
