### ISSUE TITLE
Remove Ballerina 1.2.x support tip on VS Code docs

### ISSUE THREAD

**Issue by prabushi** [ballerina-platform/ballerina-dev-website#3419]
**Description:**
Remove the tip about the Ballerin 1.2.x support of the VS Code extension.

Link https://ballerina.io/learn/visual-studio-code-extension/vs-code-quick-start/

<img width="847" alt="Screenshot 2022-01-24 at 10 32 56" src="https://user-images.githubusercontent.com/5234623/150724990-668d18b5-0800-4cef-88bc-11903bbf1838.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3432.
