### ISSUE TITLE
Distinctive Language Features link is broken 

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#3420]
**Description:**

$subject. I can't access Shyam's language guide on the dev site. 

![image](https://user-images.githubusercontent.com/11885043/150727870-3c242324-e9ed-4224-9f92-888477fc5082.png)

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3422.
