### ISSUE TITLE
1.1.x and 1.0.x Release notes links not working in archived versions page

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3440]
The links to release notes of 1.1.x versions not working in https://ballerina.io/downloads/1.2.x-archived/

RELEASE NOTES links are not working from 1.1.4 onward in [1]

[1] https://ballerina.io/downloads/1.2.x-archived/#1.1.4

**Comment by praneesha** [comment]
Closing as this will be fixed on the new website.
