### ISSUE TITLE
Remove `Building from source` section from website. 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3441]
**Description:**
$Subject  as it is for advanced users only

Consider adding it to Contributing.md or similar in https://github.com/ballerina-platform/ballerina-distribution
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/16300038/150969893-d31d6c48-6b5f-4dbe-9541-79dcf812d87a.png">

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing since this is fixed with #3453 and #3455

**Comment by anupama-pathirage** [comment]
Re-opening as still the left navigation links are available and they are giving 404 when clicking.

https://user-images.githubusercontent.com/16300038/151198826-73ffe862-79a3-4d47-9039-5553c5772292.mov
