### ISSUE TITLE
Remove `What is next` sections 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3442]
**Description:**

$subject for 

http://dev.ballerina.io/learn/installing-ballerina/setting-up-ballerina/#whats-next

and 

http://dev.ballerina.io/learn/installing-ballerina/installation-options/#whats-next

**Comment by udda1996** [comment]
Closing since this is fixed with #3451

**Comment by anupama-pathirage** [comment]
RE-opening as left navigation is still visible.

![Uploading image.png…]()

**Comment by udda1996** [comment]
fixed with #3483
