### ISSUE TITLE
Having `Trying Ballerina in the Playground` under `Installing Ballerina` is not correct

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3445]
**Description:**
$subject. 

Either 
1. we have to rename  the title `Installing Ballerina` to something else 

Or 

2. Add `Trying with Playground` to learn page landing page

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/16300038/150972878-4ddabcac-b3a7-484d-9973-ffa9a93b6bc7.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
@keizer619 @udda1996 - An info section will not work for this as discussed. Let's remove this section.

**Comment by udda1996** [comment]
closing as this is fixed with #3472
