### ISSUE TITLE
Can we make sub pages in left navigation clickable

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3447]
**Description:**

For ex: dev.ballerina.io/learn/installing-ballerina/setting-up-ballerina/ is a sub page. But the left navigation is not clickable. So we always have to go to internal title to refer to the entire sub page and remove the part after `#` to refer to the sub page

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/16300038/150973505-94255e09-8f1b-4ed7-b6dd-0356bb39fbca.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
Fixed in test site.
