### ISSUE TITLE
Invalid reference to `Quick Start`

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3452]
**Description:**

$subject in [1]. Now we don't have a page called Quick start. 

[1] http://dev.ballerina.io/learn/installing-ballerina/setting-up-ballerina/
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/16300038/150982178-66f6fbc1-7280-464a-902d-a1deab75558c.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by prabushi** [comment]
@praneesha As per @mohanvive we have decided to link the VS Code plugin [readme](https://github.com/wso2/ballerina-plugin-vscode/blob/main/README.md) file here. Can you have a look?
