### ISSUE TITLE
Inconsistent installer names 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3457]
**Description:**

$subject in [1] 

[1] http://dev.ballerina.io/learn/installing-ballerina/setting-up-ballerina/#downloading-ballerina

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/16300038/151026076-d49c56eb-d91f-447c-a7c2-ff1f9a70b077.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
is it possible to remove "Installer" word from both and reduce the button size and place all 4 buttons in a single row?
@praneesha

**Comment by praneesha** [comment]
This should be fixed on the Downloads page as well.
