### ISSUE TITLE
Is it  correct to say installer will uninstall older versions?

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3458]
**Description:**
$subject as we keep the distributiosn locally and users can switch `bal dist use`

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/16300038/151027203-d2357d68-fd39-4f52-a73e-1889a1ab9f1c.png">

[1] http://dev.ballerina.io/learn/installing-ballerina/installation-options/#installing-ballerina-via-installers

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing as this is fixed in #3467
