### ISSUE TITLE
Verify the usage of word `jBallerina`

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3460]
**Description:**

$subject in [1] as we are not using the term `jBallerina` in any other place when referring to Ballerina versions. 

[1] http://dev.ballerina.io/learn/installing-ballerina/installation-options/#updating-ballerina

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/16300038/151033050-f23d85a9-d554-4f66-943c-257ed4fc022f.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing as this is fixed in #3467
