### ISSUE TITLE
Repetitive `Updating Ballerina` sub sections

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3461]
**Description:**

$subject under `Setting up Ballerina` and  `Installation Options` . Conntent is different and that will confuse the users. 

We better have it only in one place with updated information.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/16300038/151032654-7c9c9332-2025-4736-976f-80de1cf98271.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing since this is fixed in #3468

**Comment by udda1996** [comment]
fixed in #3483
