### ISSUE TITLE
The `<VERSION>` part is missing in the command

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3462]
**Description:**
$subject in [1] 

Should be `bal dist remove <VERSION> `
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/16300038/151033351-762b5dff-fb31-4400-a563-023d3401c370.png">

[1] http://dev.ballerina.io/learn/installing-ballerina/installation-options/#uninstalling-ballerina

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by udda1996** [comment]
Closing since this is fixed in #3467

**Comment by anupama-pathirage** [comment]
Re-opening as the left nagigation link is still available.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/16300038/151199571-3a31c895-4917-4e86-9237-add218e38966.png">
