### ISSUE TITLE
Update the B.io Thumbnail Image for Swan Lake GA

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3465]
**Description:**
Need to update the B.io thumbnail image for the Swan Lake GA release.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
@dakshitha  Can I have the banner content for this? Thanks

**Comment by dinushan20** [comment]
As we already have one done by Amal, close this issue

**Comment by praneesha** [comment]
Reopening as this should be updated in the website.

**Comment by dinushan20** [comment]
Fixed via #3729
