### ISSUE TITLE
Clicking on the alpha2 release note, redirects to alpha5 release notes

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-dev-website#3466]
**Description:**
Refer the following

https://user-images.githubusercontent.com/1329674/151133544-186c3961-e285-4774-bcd8-d1c4af27a6f6.mp4

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3474.
