### ISSUE TITLE
Version Drop Down is Broken in the Downloads Page 

### ISSUE THREAD

**Issue by chanukaranaba** [ballerina-platform/ballerina-dev-website#349]
<img width="1210" alt="Screenshot 2020-04-01 at 19 44 49" src="https://user-images.githubusercontent.com/3981543/78147832-ace3ba80-7451-11ea-9996-84b1b4b851b7.png">

Changing the version will lead to a 404 page.

**Comment by Samallama** [comment]
The version drop-down has been removed from pages that don't need it.
