### ISSUE TITLE
Code blocks in tables are not rendered properly

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-dev-website#3500]
**Description:**
Visit [Cli Commands Page](http://dev.ballerina.io/learn/cli-documentation/cli-commands/#core-commands)

See screenshot below
![Screenshot from 2022-01-27 10-38-10](https://user-images.githubusercontent.com/18344003/151297424-29efb571-d5ac-4cc6-aba9-c8bd09c77b9a.png)

**Comment by dinushan20** [comment]
Content should be in following format to fix this 
(e.g., <code>bal help pull</code>).

Fixed for the above page via https://github.com/ballerina-platform/ballerina-dev-website/pull/3706
