### ISSUE TITLE
Complete the syntax highlighter for Ballerina docs

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#353]
**Description:**
Work with Joe to test and move the syntax highlighter implementation to the production site.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/952.
