### ISSUE TITLE
Text with backticks are not properly rendered in the left navigation.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3538]
**Description:**

$subject in [1] 

[1] http://dev.ballerina.io/learn/getting-started-with-ballerina/
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/16300038/151422098-0f964283-8ce7-4d16-83f8-2957ff1b554a.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this is fixed in [1] now.

[1] http://dev.ballerina.io/learn/getting-started-with-ballerina/
