### ISSUE TITLE
Move all functionality to GitHub pages

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#354]
**Description:**
We need to moving all the functionalities of the Bio to GitHub pages and remove the dependencies on other servers.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by shafreenAnfar** [comment]
We have done the $subject. Hence closing this issue.
