### ISSUE TITLE
Source code in "Try Ballerina" widget is not readable. 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#3540]
This may be a personal view on this, but I find the source code "Try Ballerina" box unreadable. It's hard for me to identify actual source code from comments. 

Here is a suggestion from me: 
![image](https://user-images.githubusercontent.com/2637328/151464240-a72eaf2a-8f7e-40fc-b3de-eacd23764248.png)

**Comment by praneesha** [comment]
Closing since comments will be removed.
