### ISSUE TITLE
The tutorial "Writing a RESTful API with Ballerina" is duplicated in the getting started section

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#3542]
<img width="1153" alt="Screen Shot 2022-01-27 at 4 27 26 PM" src="https://user-images.githubusercontent.com/2637328/151465754-c76c6577-f933-4dba-9cba-eecad96389b0.png">

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3521/files.
