### ISSUE TITLE
Incorrect layout in the Package References guide

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-dev-website#3544]
**Description:**
Seems like the `Organizing Ballerina Code` guide layout is still being used in the `Package References` guide.
<img width="1680" alt="Screen Shot 2022-01-27 at 8 05 35 PM" src="https://user-images.githubusercontent.com/17268934/151484186-6eace46d-c2ca-4ba3-8994-1325a57a64a7.png">

https://github.com/ballerina-platform/ballerina-dev-website/blob/3393fe34d9f74199ab59b3effcc36c1f32de5585/learn/references/package-references/package-layout.md?plain=1#L2

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since this is fixed now.
