### ISSUE TITLE
Clicking reference link doesn't activate the heading in nav-bar

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#3563]
**Description:**

https://user-images.githubusercontent.com/15815199/151561984-72124dc5-baec-42b9-943a-6c3aba17f91e.mov

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this is fixed now.
