### ISSUE TITLE
Incorrect Swan Lake version in the blog "Ballerina Swan Lake is on the Horizon"

### ISSUE THREAD

**Issue by aashikam** [ballerina-platform/ballerina-dev-website#3570]
**Description:**
In the blog, [Ballerina Swan Lake is on the Horizon](https://blog.ballerina.io/posts/ballerina-swan-lake-is-on-the-horizon/), the version of the second update looks incorrect, which I guess should be corrected as `2201.2.0`.
<img width="574" alt="Screen Shot 2022-01-27 at 10 58 45 AM" src="https://user-images.githubusercontent.com/39673615/151585541-52f1ca61-40ae-4f75-a86f-7e3d87d271b2.png">

**Comment by sameerajayasoma** [comment]
+1 for the suggested change. Copy-paste error. Thanks for catching that @aashikam :)

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/blog/pull/98.
