### ISSUE TITLE
Enable Viewing the Blog Repo Updates on the Pre-Prod Site

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3581]
**Description:**
Currently, soon after a PR is merged in the [blog](https://github.com/ballerina-platform/blog) repo, the change gets reflected in the B.io live site via `blog.ballerina.io`.

Instead, we should be able to view the changes first in the pre-prod site and then push the changes to the live site as we do in the `ballerina-dev-website` repo.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Since this required additional repo to host or should include draft support for current implementation. Since it takes significant effort better to continue with current approach
