### ISSUE TITLE
`Observing Your Application with Choreo` does not work as expected

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-dev-website#3587]
In the following guide, http://dev.ballerina.io/learn/observing-ballerina-programs/observing-your-application-with-choreo/#step-3---observing-the-ballerina-service, it should display the metrics in choreo. But following is the result i see.
![Screenshot from 2022-01-29 10-27-01](https://user-images.githubusercontent.com/35135122/151647986-7305676b-bcee-409b-88ad-cb0e367cc2f8.png)

**Comment by kaneeldias** [comment]
Guide has been removed with https://github.com/ballerina-platform/ballerina-dev-website/pull/3661 until Choreo support is added.
