### ISSUE TITLE
Why pages Titles and icons on home page are not aligned properly

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-dev-website#3588]
I checked this on the dev site.
![image](https://user-images.githubusercontent.com/9362271/151648627-df2deb41-f574-4832-a2f5-aa69007e1990.png)

Some icons seem center-aligned some are left-aligned. Good to have Titles and icons center-aligned.

**Comment by dinushan20** [comment]
![image](https://user-images.githubusercontent.com/73055030/151699433-c2005c95-2c35-4075-b174-029180eb6f01.png)
I see titles and icons are left aligned. @gimantha Can you explain your concern bit more ?

**Comment by gimantha** [comment]
> ![why-ballerina-allignement](https://user-images.githubusercontent.com/73055030/151699581-00b41d54-bc25-4cc0-b53b-124ac63ade4a.png)
> 
> I see titles and icons are left aligned. @gimantha Can you explain your concern bit more ?

I was wondering whether it should be center aligned.

**Comment by praneesha** [comment]
Closing as this is fixed now.
