### ISSUE TITLE
Add Copy to clipboard button to code snippets in everywhere possible

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-dev-website#3595]
For some code snippet, it would be easy for users to directly copy the code by clicking a button and try out the code. Some code snippets are lengthy and users may have to scroll the pages while copying the code manually. Something like we have in BBE pages

**Comment by anupama-pathirage** [comment]
This is done except for usecase pages. It is tracked via https://github.com/ballerina-platform/ballerina-dev-website/issues/6983, hence closing this issue.
