### ISSUE TITLE
Update Getting started guides with running commands and sample responses 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3601]
**Description:**

$subject for [1] and [2] It is not completed if we don't include some curl commands with samples at the end.

[1] http://dev.ballerina.io/learn/writing-a-graphql-api-with-ballerina/
[2] http://dev.ballerina.io/learn/writing-a-restful-api-with-ballerina/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3606.
