### ISSUE TITLE
Breadcrumbs are not working in `Testing Ballerina Code` and `configuring ballerina programs` pages

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3605]
**Description:**

$subject in [1]. It goes to a link with `structuring-the-tests/` and redirects to 0.0.0.0 too.
Same issue is there in [2] too

https://user-images.githubusercontent.com/16300038/151653636-51c5dff1-cafe-4082-bf09-429b5ce2a3d3.mov

[1] http://dev.ballerina.io/learn/testing-ballerina-code/quick-start-on-testing/
[2] http://dev.ballerina.io/learn/configuring-ballerina-programs/quick-start-on-configurable-variables

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/issues/3650.
