### ISSUE TITLE
Move the Tutorials to one line down

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3611]
**Description:**

$subject in learn landing page

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16300038/151655414-fe271525-d6ab-441d-a463-a0a4bba7b313.png">

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This is how it looks like with the suggestion.

![Screenshot 2022-01-30 at 17 31 15](https://user-images.githubusercontent.com/11707273/151698943-1b15ebc5-fdb0-488d-a003-b4a452124e6f.png)

**Comment by praneesha** [comment]
Closing as this will be addressed later by improving the design to have sub headings.
