### ISSUE TITLE
Update the Learn Page for the SL GA Release

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3617]
**Description:**
Need to do the below to update the Learn page for the SL GA release.

- [ ] Align the Ballerina logo with the other menu items 

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
Fixed via #3653
