### ISSUE TITLE
Revamp All BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#364]
**Description:**
We need to review and revamp all BBEs to adhere to the updated best practices of the Ballerina language.

For example, the error handling method in the "hello world service" BBE[1] does not present the updated best practices.

[1] https://ballerina.io/v1-2/learn/by-example/hello-world-service.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
@lafernando - I believe this is done. Can we close this now?

**Comment by lafernando** [comment]
Not yet, this is still being done.

**Comment by praneesha** [comment]
> Not yet, this is still being done.

Ack. Thanks!

**Comment by praneesha** [comment]
Done for Swan Lake Beta1
