### ISSUE TITLE
Userbility issue navigating among BBEs

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/ballerina-dev-website#3686]
**Description:**
**Scenario 1:**
You google _"ballerina json type bbe"_  and you get the following link as the first result.
https://ballerina.io/learn/by-example/json-type

Now you want to go to the next BBE. As you can see from screenshot_1, there is no `next` or `previous` button. Also, the scroll bar of the side navigation menu is at the top. So one has to scroll all the way down and select the next BBE. Repeating this is inconvenient.
<details>
  <summary>screenshot_1  (<i>click to expand</i>)</summary>

![Screenshot from 2022-01-31 14-13-27](https://user-images.githubusercontent.com/39232462/151763171-3f3d8a82-225f-45c4-b2b4-986c6e8bd88a.png)
</details>

In the side menu, two colors of the main and the subsections are barely distinguishable. For a second I thought this was a collapsed menu. 
<details>
  <summary>screenshot_2  (<i>click to expand</i>)</summary>

![Screenshot from 2022-01-31 14-22-50](https://user-images.githubusercontent.com/39232462/151764460-46e23487-b252-4ca8-873e-fc53a1358c6c.png)
</details>

**Scenario 2:**
You go to ballerina.io -> learn page -> Reference by Examples -> JSON type. Now you are directed to the following link.
https://ballerina.io/learn/by-example/json-type.html?is_ref_by_example=true

Now you want to jump to a BBE in another section. There is no side navigation bar like in the previous case. 
You have to click on learn ->  Reference by Examples and then pick the BBE in another section. 
<details>
  <summary>screenshot_3  (<i>click to expand</i>)</summary>

![Screenshot from 2022-01-31 14-35-33](https://user-images.githubusercontent.com/39232462/151766099-d491168c-e9f9-4610-b59a-aa7d68b76efc.png)
</details>

I think both scenarios should be consistent, and we need both the side navigation menu and the next/previous buttons to switch among BBEs seamlessly.

**Comment by praneesha** [comment]
Closing since we will be having only the Ballerina By Examples view from Swan Lake GA onwards.
