### ISSUE TITLE
Concurrent and Reliable, Maintainable should be two main topics in left nagivation window

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-dev-website#3687]
See the screenshot below
![image](https://user-images.githubusercontent.com/9362271/151768489-8ac02a38-4276-489d-a430-437c679d5f6f.png)

Now Reliable, Maintainable is placed as a sub topic of Concurrent.

**Comment by praneesha** [comment]
This is fixed in https://ballerina.io/why-ballerina/concurrent/ now.
