### ISSUE TITLE
Newsletter subscription says "Subscribe to Newsletter"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#3688]
**Description:**
$title.

Shouldn't this be one of the following?

```
Subscribe to the Newsletter
```

or

```
Subscribe to our Newsletter
```

**Comment by MaryamZi** [comment]
Seems to be the case only on the dev site btw. Applicable to both the footer and the newsletter section of the community page.

**Comment by dakshitha** [comment]
Let's change it to 'Subscribe to our Newsletter'

**Comment by MaryamZi** [comment]
The [community page](https://ballerina.io/community/) still says "Subscribe to Newsletter".

Noticed this in the [tweet](https://twitter.com/ballerinalang/status/1494145373828489216) about the community page.

**Comment by praneesha** [comment]
Closing as this is fixed in https://ballerina.io/community/ now.
