### ISSUE TITLE
</table> tag in Why Page - Flexible Typed

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#3712]
![image](https://user-images.githubusercontent.com/11885043/151815782-1a3cef94-590a-488a-9f78-25ee9a344b92.png)

Under Test Scenarios
http://pre-prod.ballerina.io/why-ballerina/flexibly-typed/

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/3714.
