### ISSUE TITLE
Back to top button not showing properly in `Writing a gRPC Service with Ballerina`

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-dev-website#3713]
**Description:**

navigate to following link

http://pre-prod.ballerina.io/learn/writing-a-grpc-service-with-ballerina/

![Screenshot from 2022-01-31 20-37-20](https://user-images.githubusercontent.com/31839712/151819185-66f43da9-3a15-4a2c-bc0b-b8c8f487349a.png)

**Comment by dinushan20** [comment]
Fixed via #3716
