### ISSUE TITLE
Change the description for `Examples` on the home page

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#3726]
**Description:**
$title.

Currently says "Testable examples in Ballerina.".

I'm assuming what we want to say is something that implies standalone runnable samples. Using "Testable" may not quite mean this (see [testability](https://en.wikipedia.org/wiki/Testability)).

**Comment by praneesha** [comment]
Closing since this is fixed in https://ballerina.io/ now.
