### ISSUE TITLE
The link to zip file points to the wrong file

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3745]
In the pre-prod site, with the GA update, the zip download link points to the wrong file. It's linked to `ballerina-2201.0.0.zip` while it should actually have been linked to `ballerina-2201.0.0-swan-lake.zip`

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/3747.
