### ISSUE TITLE
Add link to Tech blog from corporate blog

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#376]
**Description:**
Place some text (with an appropriate design) in the blog page [1] to link to the Ballerina Tech Blog [2].

[1] [https://blog.ballerina.io/](https://blog.ballerina.io/)
[2] [https://medium.com/ballerina-techblog](https://medium.com/ballerina-techblog)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Fixed via ballerina-platform/blog#47.
