### ISSUE TITLE
Updating the Jekyll Build to Run Without Git Pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#379]
**Description:**
We need to update the Jekyll Build of Bio to make it run without Git pages. This is to eliminate any Git Pages restrictions on the Gem plugins.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Thimuth** [comment]
We have migrated the server-side scripts to work as Lambda functions and automated other processes (BBE, API-Docs, download pages etc.) using Github workflows. So we can keep the Git Pages build as it is without adopting an independent Jekyll site build.
