### ISSUE TITLE
The `v 0.991` docs option is appearing in the website version dropdown

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3811]
**Description:**

$subject when we go to the 1.0 docs [1] and that gives `404 error too.

https://user-images.githubusercontent.com/16300038/152120327-47e65b18-ab1b-4839-a07f-d9550b066dfd.mov

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/16300038/152120151-066b638c-613d-49db-87a3-797e498c65bc.png">

[1] https://ballerina.io/1.0/learn/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
This is no longer valid as we have removed 1.0 docs (from the version picker also) in B.io now.
