### ISSUE TITLE
Redesign the Learn pages Left Navigation

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3812]
**Description:**
Since we have a lot of issues with the current Learn left nav, we need to revamp/redesign it. Need to address the issues below with the redesign.

- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3447
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4023
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4021
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4020
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4013
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3991
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3986
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4455
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4604

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sahil-MK2** [comment]
i want to fix this issue

**Comment by praneesha** [comment]
Closing as the sub-tasks are completed.
