### ISSUE TITLE
Events page does not redirect to community page

### ISSUE THREAD

**Issue by ldclakmal** [ballerina-platform/ballerina-dev-website#3822]
**Description:**
https://ballerina.io/events/ page gives 404 error after Swan Lake GA updates of the website. It should redirect to https://ballerina.io/community/ page. This is required since the https://con.ballerina.io subdomain is configured to redirect to https://ballerina.io/events/ page at the DNS level.

![image](https://user-images.githubusercontent.com/9639050/152292077-2793584d-fb3a-4d9d-91a3-8643728a04e7.png)

**Comment by praneesha** [comment]
Closing as this is fixed now.
