### ISSUE TITLE
Add nested record example for configurable learn page

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-dev-website#3833]
**Description:**
$subject

**Describe your problem(s)**
Since this use case is a common one, it would be better to have it in the examples for TOML syntax. 
Reference: https://ballerina-platform.slack.com/archives/C47EAELR1/p1643887439577829

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4536.
