### ISSUE TITLE
Use twitter handles of speakers instead of linkedin

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3844]
**Description:**
$subject as linkedin will mostly route to login page and will get marked as invalid links..

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/16300038/153700304-fcd6c5dc-c896-4934-977f-5cbd60e8a581.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ashweni** [comment]
All updated now

**Comment by praneesha** [comment]
Closing as per the above comment.
