### ISSUE TITLE
Fix the 1.2 Version Highlight on the Version Picker

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3860]
**Description:**
When 1.2 API Docs are selected in [1], the "1.2" label comes to the top of the version picker as shown below. 

![Screenshot 2022-02-15 at 14 28 01](https://user-images.githubusercontent.com/11707273/154027449-8612ac72-cfcb-4f0b-9a6d-dcd18170504f.png)

Need to fix this to have Swan lake at the top as shown below.

![Screenshot 2022-02-15 at 14 29 21](https://user-images.githubusercontent.com/11707273/154027722-1caf33a8-7228-4765-9b6d-263ac7dfe2f9.png)

[1] https://pre-prod.ballerina.io/1.2/learn/api-docs/ballerina/

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing since this is invalid. No version picker in API docs.

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/16300038/217180714-06ab2975-d335-4884-bbf1-157740a80b38.png">
