### ISSUE TITLE
Links in BBEs not formatted as hyperlinks

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3880]
See the underlined link in the following:
<img width="698" alt="Screenshot 2022-02-23 at 17 08 40" src="https://user-images.githubusercontent.com/6260009/155312646-1fe4b2ec-50d6-4047-9641-65cef5131578.png">
Shouldn't this be rendered as a proper hyperlink?

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/2644.

**Comment by praneesha** [comment]
Closing as this is fixed now.
