### ISSUE TITLE
Copy code behaviour not ideal when the BBE is spread across multiple files

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3881]
Consider for example https://ballerina.io/learn/by-example/grpc-simple.html

If you use the copy button in this case, it copies the code for both the service and the client. When pasted in a file, this doesn't produce a compilable Ballerina source file. Therefore, I think we need to reconsider the behaviour of the copy button. Shouldn't each code segment have its own copy button or something?

**Comment by YasithD** [comment]
With the new design `Copy to Clipboard` feature is available for individual code blocks.
