### ISSUE TITLE
Link to the gRPC user guide is broken

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3882]
In the API docs of gRPC module, it has a link to a gRPC user guide. This link is not working. It just goes back to the API docs page.
<img width="1147" alt="Screenshot 2022-02-23 at 17 28 40" src="https://user-images.githubusercontent.com/6260009/155315465-21aae8c3-666b-4da8-8857-e74dc002666b.png">

**Comment by daneshk** [comment]
@BuddhiWathsala Can you check
