### ISSUE TITLE
Minor typos in C2C BBE

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#3886]
Need to review the C2C BBE. There are a couple of minor typos. e.g., "Code to cloud" instead of "Code to Cloud"

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/2660.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/2660 and https://github.com/ballerina-platform/ballerina-distribution/pull/2661.
