### ISSUE TITLE
Search result doesn't have a space to seperate page titles

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3890]
**Description:**
<img width="812" alt="image" src="https://user-images.githubusercontent.com/16300038/155529282-7a78ea1e-cd93-45c5-bd19-9cd5e2fe5b1a.png">

**Comment by praneesha** [comment]
Closing as this is fixed now as shown below.

<img width="697" alt="Screen Shot 2022-03-24 at 1 55 41 PM" src="https://user-images.githubusercontent.com/11707273/159873845-3bfb5d0d-f912-48de-9a68-bfc6867664a1.png">
