### ISSUE TITLE
Revamp the Newsletter Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3891]
**Description:**
Need to revamp the Newsletter page to align it with the other community sub pages (e.g., events, resources, tech talk etc.,).

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
This was fixed via [#4234](https://github.com/ballerina-platform/ballerina-dev-website/pull/4234)
