### ISSUE TITLE
Algolia search is giving incorrect results

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3948]
**Description:**

$subject . Refer below. It goes to 404 page.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/16300038/156685972-9137f2a9-f0af-4cd8-acf1-5a328a8f8f81.png">

Thanks @vordimous for reporting this,

**Comment by praneesha** [comment]
Closing as this is fixed now with the reindexing of the Algolia search as shown below.

<img width="626" alt="Screen Shot 2022-03-24 at 2 21 16 PM" src="https://user-images.githubusercontent.com/11707273/159878493-62110708-f4a1-4916-bfd6-1a4c509c21a0.png">
