### ISSUE TITLE
404 page points to slack only, add report issues link also

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3949]
**Description:**

$subject in 404 page.

User faced https://github.com/ballerina-platform/ballerina-dev-website/issues/3948 and was hard to figure out where to report issues.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/16300038/156686424-f183169e-a4a7-428a-8f68-018fe0d95d16.png">

Also giving slack link directly is incorrect. We should point to the  `Ballerina Slack community` section in the https://ballerina.io/community/ page so that he can get an invite.

Thanks @vordimous for reporting this

**Comment by praneesha** [comment]
Closing as this is done.
