### ISSUE TITLE
Links to  sections on BBE landing page.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3961]
**Description:**

Can we have $subject as part  of new BBE tool revamp effort?

For example a linked like : https://ballerina.io/learn/by-example/#rabbitmq to direct to and highlight following area in the landing page.

Then it is very easier to point relevenat examples from other places  in the site and in general. Right now the first sample of the given category is linked.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/16300038/156912150-d184436b-a6a9-4373-97ad-1411a2f42fb3.png">

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5111.
