### ISSUE TITLE
Avoid getting $ copied when copying the command

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#3962]
**Description:**
Can we do the $subject for learn pages.

Refer to https://developers.google.com/style/code-syntax?hl=en

Copyign the command is not copying the $sign there

**Comment by praneesha** [comment]
The $sign doesn't get copied in [1] also.

[1] https://linuxize.com/post/how-to-configure-git-username-and-email/

**Comment by praneesha** [comment]
Will be addressed via https://github.com/ballerina-platform/ballerina-dev-website/issues/3595.
