### ISSUE TITLE
Automate the Removal of Old Events from the Community Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3976]
**Description:**
Need to automate the removal of old events from the Community page.
**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
This was fixed with https://github.com/ballerina-platform/ballerina-dev-website/pull/4445
