### ISSUE TITLE
Auto Generate the Left Nav from the Headings

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3991]
**Description:**
Auto generate the left nav from the headings. https://github.com/ballerina-platform/ballerina-dev-website/issues/4013 will also be addressed via this.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
Fixed in test site using a ballerina script to generate the left nav which will get the content from the md file itself.

**Comment by praneesha** [comment]
Closing as per the above comment.
