### ISSUE TITLE
Add the Subscribe via RSS button to the B.io footer 

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4004]
**Description:**
Add the Subscribe via RSS button of `blog.ballerina.io` to the main footer of B.io as well.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/
