### ISSUE TITLE
Add the Security Policy to the Blog Footer

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4006]
**Description:**
Need to add the Security Policy to the Blog footer.

However, this will not be applicable, if blog will be moved to the same B.io domain via https://github.com/ballerina-platform/ballerina-dev-website/issues/4002.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
This is already done, hence closing. 

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/16300038/217173127-1a3bb2b5-117f-48a0-9a28-f7e32550c34e.png">
