### ISSUE TITLE
Show the Diagram View in the Getting Started Guides

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4008]
**Description:**
Would be better if we can show the diagram view in the Getting Started guides.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is available in https://wso2.com/ballerina/vscode/docs/
