### ISSUE TITLE
Reorganize the Community Page Sub-Menu

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4011]
**Description:**
Check how we can reorganize the sub-menu.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
The entire community page needs to be redesigned, hence closing this issue.
