### ISSUE TITLE
Change the Input Type in the Newsletter and Tech Talk Forms

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4012]
**Description:**
Input type is text in the forms under newsletter & Ballerina tech talk. 

`input type="text"`

<img width="1680" alt="Screenshot 2022-06-29 at 16 48 44" src="https://user-images.githubusercontent.com/11707273/176424477-f32a002b-de71-49d6-b3ac-735c570e6cf9.png">

Need to change it to type email as done in the Slack form as shown below.

`input type="email"`

<img width="1680" alt="Screenshot 2022-06-29 at 16 51 00" src="https://user-images.githubusercontent.com/11707273/176424931-1a7fa350-860b-4ebd-8d44-fb5d1bf0532a.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by dinushan20** [comment]
For these forms we use pardot forms, So we can't add input type as email therefore.In pardot forms it has inbuilt feature to validate email,  so the form is validating email and give error message as showing below. So I close this issue 
![image](https://user-images.githubusercontent.com/73055030/176602209-ff13cb75-bd1b-41e0-8fa8-d890b4d323fa.png)
