### ISSUE TITLE
Make the Left Nav and Headings Consistent

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4013]
**Description:**
The text in left nav is in Title case, but the actual heading is sometimes in sentence case.

However, this will not be applicable once https://github.com/ballerina-platform/ballerina-dev-website/issues/3991 is done.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
Fixed in test site using a ballerina script to generate the left nav which will get the content from the md file itself.

**Comment by praneesha** [comment]
Closing as per the above comment.
