### ISSUE TITLE
Name the `Ballerina in Action` Sample Files

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4017]
**Description:**
Give an indication on which file is which. eg:- main.bal. If it is a continuation of the same file, indicate that.
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority.
