### ISSUE TITLE
Add Commands to Run the `Ballerina in Action` Samples

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4018]
**Description:**
Add some commands on how to run the file below. Either we can point to the README file in the sample repo or add like already done in BBEs.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority
