### ISSUE TITLE
Have an independent left navigation for each Learn topic

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4021]
**Description:**
Have an independent left navigation for each Learn topic.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
Fixed in test site by implementing an independent page toc

**Comment by praneesha** [comment]
Closing as per the above comment.
