### ISSUE TITLE
Redesign the Archived Versions Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4026]
**Description:**
Need to redesign the `Archived versions` page by merging the current `Archived versions` pages and adding a left nav similar to the `Release notes` page.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this will also be addressed via https://github.com/ballerina-platform/ballerina-dev-website/issues/4471.

**Comment by sm1990** [comment]
Tasks related to the 1st cut are now complete.
To do -
Group items in the left nav by major releases.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority
