### ISSUE TITLE
Redesign the Learn Landing Page 

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4027]
**Description:**
Check the organization of the content (e.g., whether the `Distinctive language features` should be moved to `Getting started` and whether there is anything else to move around and give prominence to in the `Getting started` section etc.)

Need to highlight the first 3 steps below in `Getting started` in a more prominent way.

- Installing Ballerina
- Getting started with Ballerina
- Language basics

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as done and invalid now.
