### ISSUE TITLE
Add More Learn Content on the Graphical Diagrams

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4029]
**Description:**
Add more learn content on no-code mode (graphical diagrams). This is other than the Why Ballerina page. As the Why Ballerina page is not easily navigable, its good to have this content in Learn also.

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Done with https://wso2.com/ballerina/vscode/docs/
