### ISSUE TITLE
Redesign the Home Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4037]
**Description:**
Redesign the Home page and address the below.

- [ ] Add the Home page sections
- [ ] Create the top menu with proper highlighting of the menu items once clicked
- [x] Design the home page footer
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3985
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4007

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as done.
