### ISSUE TITLE
Improve the `Ballerina in Action` Section

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4039]
**Description:**
Need to do the improvements below.

- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4018
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4017
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4016

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is just a issue with grouping, same can be achieved via labels.
