### ISSUE TITLE
Redesign the Blog

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4040]
**Description:**
This will include the following.

- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4002
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3257
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/1382
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/375
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4009
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4003
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4006
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4002

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is just a grouping of issues, which can be done via labels.
