### ISSUE TITLE
Redesign the Versions Picker

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4041]
**Description:**
Need to address the issues below.

- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3860
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3811
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3440

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as all the tasks are done.
