### ISSUE TITLE
Improve UI Elements of the Learn Pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4043]
**Description:**
Need to address the following.

- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/4030
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3996
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3995
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/3962
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/3595
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3197
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3192
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/2957

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this is just a grouping of issues.
