### ISSUE TITLE
Add New Global Features with the B.io Rewrite

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4044]
**Description:**
Need to address the following.

- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/3120
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/2592
- [ ] https://github.com/ballerina-platform/ballerina-dev-website/issues/1178

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Closing as this contains some random collection of issues.
