### ISSUE TITLE
Change the Hyperlink Color in `.out` files of BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4109]
**Description:**
Need to change the hyperlink color in the `.out` files of BBEs. The current color below doesn't match the Ballerina color theme. For example, see [1].

<img width="1281" alt="Screen Shot 2022-03-23 at 11 11 28 PM" src="https://user-images.githubusercontent.com/11707273/159762761-a3e4338a-5404-40f5-af20-69dc47eb7c01.png">

[1] http://pre-prod.ballerina.io/learn/by-example/grpc-simple.html

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by YasithD** [comment]
This is fixed with the new UI of the BBEs.

![image](https://user-images.githubusercontent.com/59837420/176157470-f95f7167-c190-4100-8047-fd2731e997d7.png)

**Comment by praneesha** [comment]
Closing as per the above comment.
