### ISSUE TITLE
OpenAPI support page has confusing annotation examples

### ISSUE THREAD

**Issue by janihur** [ballerina-platform/ballerina-dev-website#4136]
**Description:**
Confusing examples of  `@openapi:ServiceInfo` annotation in page: https://ballerina.io/learn/ballerina-openapi-support/

The documentation has the following examples that can be incorrectly read as real working code:
```
@openapi:ServiceInfo {
    [contract: "/path/to/openapi.json|yaml"],
    [title: "Store Management"],
    ['version: "0.1.0"]
} 
```

But in fact the `[]` are markers for optionality that is mentioned nowhere. The correct working code is in fact:
```
@openapi:ServiceInfo {
    contract: "/path/to/openapi.yaml",
    title: "Store Management",
    'version: "0.1.0"
} 
```

The examples have also:

```
[tags: "store"],
```

That should be 
```
[tags: ["store"]],
```

I.e. value of tags should be `string[]` not `string`.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4162.
