### ISSUE TITLE
Add the Report Issues Pop-up to the Blog

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4158]
**Description:**
Need to add the report issues pop-up in the below of the blog. Currently, it is linked to the corresponding section on the Community page instead.

- [ ] Report issues link on the blog footer
- [ ] Report issues link on the blog 404 page

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Clsoign as done.
