### ISSUE TITLE
Create a Workflow to Automate Adding BBE Updates for 2201.01.0

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4180]
**Description:**
Need to create a new workflow to automate adding BBE updates done on the `ballerina-distribution` repo for the 2201.01.0 release. The automated PR should be created to the release branch, which is for example, `release-2201.1.0` for the Update 1 release.

Currently, we have a workflow only to capture the BBE updates (hot fixes) done for patch releases in both `master` and `2201.0.x` branches of the `ballerina-distribution` repo .

**Related website/documentation area**

**Describe the problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
This will be addressed by new generation logic PR 
https://github.com/ballerina-platform/ballerina-dev-website/pull/4335
