### ISSUE TITLE
Remove Old Versions from Google Search Results

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4200]
## Description
Currently, content from old Ballerina version docs are coming in Google search results. For example, it gives [1] as the top result when searched for `ballerina http` in Google.

<img width="918" alt="Screen Shot 2022-04-18 at 8 51 37 AM" src="https://user-images.githubusercontent.com/11707273/163749411-73d44d29-48ad-40cf-9f5a-963897446154.png">

Need to check why the sitemap of the Jekyll plugin is not getting updated.

[1] https://ballerina.io/1.2/learn/api-docs/ballerina/http/index.html

## Related website/documentation area
> Add one of the following: `Area/BBEs`, `Area/HomePageSamples`, `Area/LearnPages`, `Area/Blog`, `Area/CommonPages`,` Area/Backend`, `Area/UIUX`, and `Area/Workflows`.

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-platform.github.io/pull/209.

**Comment by sm1990** [comment]
The older versions are now hidden from search results. 
![image](https://user-images.githubusercontent.com/7709843/166653635-b2cf018e-9042-4355-9ce4-c43a4f5053a6.png)
