### ISSUE TITLE
Incorrect naming convention?

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-dev-website#427]
**Description:**
In the standard library API documents, I see many places where referring `functions` as `methods`. Is this intended ? AFAIK, ballerina uses `function` as the convention, not `method`.

**Comment by praneesha** [comment]
@ThisaruGuruge - How can we find the exact occurrences? Can you give a few examples?

**Comment by ThisaruGuruge** [comment]
If you surf through the website, you'd find them.

**Comment by praneesha** [comment]
@ThisaruGuruge - What I meant was how can we find the exact occurrences in the Ballerina Standard Library Docs? Can we do a grep and replace those? Can you give some examples?

**Comment by ThisaruGuruge** [comment]
Here's one example.
https://ballerina.io/learn/api-docs/ballerina/kafka/clients/Producer.html

**Comment by praneesha** [comment]
> Here's one example.
> https://ballerina.io/learn/api-docs/ballerina/kafka/clients/Producer.html

Ack. Thanks!

**Comment by lafernando** [comment]
@ThisaruGuruge The example you gave is actually a remote "method"  not a function. In Ballerina, we have both functions and methods. See the spec: https://htmlpreview.github.io/?https://raw.githubusercontent.com/ballerina-platform/ballerina-spec/master/lang/spec.html for more info. @praneesha
