### ISSUE TITLE
Refine API Docs Google Search Results

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4317]
## Description
For all API Docs modules, it should be the API Docs URL that should coma at the top of the Google search results. E.g.,

1. For Ballerina modules ->  the respective `lib.ballerina.io` page of the module
2. For BallerinaX modules ->  the respective `lib.ballerina.io/ballerinax/` page of the module
3. For other Central modules ->  the respective `central.ballerina.io` page of the module

We need to deprioritise the other search results such as the respective Github repo of the module.

## Related website/documentation area
Area/Backend
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Better if we can prioritize the API Docs page of the respective module for each of them over the GitHub repo.

**Comment by sm1990** [comment]
We have added the `robots.txt` and `<meta name="robots" content="noindex">` to lower environments (staging/dev) to prevent them from being indexed by Google. The remaining work will be handled during the SEO improvements related tasks in future.

**Comment by praneesha** [comment]
Closing as per the above comment.
