### ISSUE TITLE
List down the active proposals in community page

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#4346]
## Description
> List down the active proposals in [community page](https://ballerina.io/community/) by listing issues `Type/Proposal` tag. Something similar in this [sample](https://anupama-pathirage.github.io/ballerina-proposals-bot/) has to be implemented

**Comment by anupama-pathirage** [comment]
[Sample bot ](https://anupama-pathirage.github.io/ballerina-proposals-bot/)is inspired by the model of https://rfcbot.rs/

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4960/.

**Comment by praneesha** [comment]
Done inhttps://pre-prod.ballerina.io/community/.
