### ISSUE TITLE
Update the Styling of Other Specs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4364]
## Description
Need to generate styles for other specs also in [1] similar to Lang specs (e.g., [2]). Currently. other specs are being pointed to the respective folder of the `ballerina-spec` GitHub repo.

[1] https://ballerina.io/learn/platform-specifications/
[2] https://ballerina.io/spec/lang/2022R1/

## Related website/documentation area
Area/LearnPages
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Since those are work in proposals it is fine to have them in the repo.

**Comment by anupama-pathirage** [comment]
Re-opening as these are related to specs, not work-in-progress proposals.

Check the validity of content before bringing them to the website.

**Comment by sm1990** [comment]
This is done.
