### ISSUE TITLE
Inconsistency in the remote method being called in the Consume Services example on the distinctive features page

### ISSUE THREAD

**Issue by SumayyaZiyad** [ballerina-platform/ballerina-dev-website#4369]
## Description
> The sendMessage remote method being called on the client object has been inconsistently defined as the sendEmailMessage method on the example explanation in [https://ballerina.io/learn/distinctive-language-features/network-interaction/#consume-services---client-objects](url)

----

<img width="876" alt="Consumer Services Client Object" src="https://user-images.githubusercontent.com/36619740/167990464-64d5a6af-e36e-4297-bd2e-782bfee07f12.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4376.
