### ISSUE TITLE
Confusion over Project vs Package

### ISSUE THREAD

**Issue by bhathiya** [ballerina-platform/ballerina-dev-website#4371]
## Description
In the Ballerina getting started doc[1], it uses the word "project" everywhere. But everywhere else, I can see the word "package" has been used.  This confuses first-tome users and they infer these 2 as 2 different terms, but without finding a difference mentioned anywhere. (I myself was confused as the Ballerina hackathon asked to create a package, but the getting started doc doesn't mention "package" at all.) So better to stick to one term everywhere.

[1] https://ballerina.io/learn/get-started-with-ballerina/

**Comment by praneesha** [comment]
@sameerajayasoma - Should we use `project` or `package` in all Learn content consistently?

**Comment by sameerajayasoma** [comment]
I intentionally used the term project in the getting started guide, because I didn't want to expose the package concept for first-time users. I guess I have rethink this approach. Will send a PR to imrove the get-started-guide.

**Comment by praneesha** [comment]
@sameerajayasoma - All the other get started guides also have the work `project` in them. 

However, I improved the `Get started` guide to explain the two terms in https://github.com/ballerina-platform/ballerina-dev-website/pull/4462. Please review.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4524.
