### ISSUE TITLE
Remove the Version Drop Down from Particular Bio Pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#438]
**Description:**
We need to remove the versions drop down from pages other than the Learn section. Examples on which it should be removed are the Downloads page and the Why Ballerina pages etc.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Samallama** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/pull/486
