### ISSUE TITLE
Mismatch in left nav  item and title in `Write a gRPC service with Ballerina`

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4387]
## Description

$subject  in [1]

https://ballerina.io/learn/write-a-grpc-service-with-ballerina/
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/16300038/168418821-1fc69944-3e6d-4e67-bf82-e21dee4b8887.png">

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4398.
