### ISSUE TITLE
Consider renaming the `Work with data in Ballerina` guide to include queries as well

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4388]
## Description
The title [Work with data in Ballerina](https://ballerina.io/learn/work-with-data-in-ballerina/) doesn't mention anything about queries, although it is the main intention of the guide. 

So can we consider renaming it to something like `Work with data using queries in Ballerina`? That will help users to locate the query-related docs easily on the learn landing page and will have an impact on SEO as well.

**Comment by praneesha** [comment]
@mohanvive - Any thoughts?

**Comment by mohanvive** [comment]
Yes, +1 to proceed with the change suggested by Anupama.

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/4456.
