### ISSUE TITLE
Add Keywords to the Header Content of the API Docs & BBEs to Improve SEO

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#439]
**Description:**
We need to add Keywords to the Header Content of the API Docs & BBE pages to improve SEO like we did in [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/339

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Samallama** [comment]
We have added meta keywords and descriptions to the BBEs. Will open a new issue specifically for API docs.
