### ISSUE TITLE
Simplify the Slack Invitation Process

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4442]
## Description
Need to improve the current Slack invitation process. For example, see the Slack `Get invite` link in [1].

There is no place to add an email and enter but it is redirecting to a Slack login page, which has single sign on.

[1] https://graphql.org/community/

## Related website/documentation area
Area/CommonPages

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
To simplify the Slack invitation process, we need to upgrade the Ballerina Slack plan. However, since we are moving towards Discord, we won't be upgrading it.

**Comment by praneesha** [comment]
Closing as per the above comment.
