### ISSUE TITLE
Inconsistancy between Style Guide Match Command Description and Example

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-dev-website#4453]
## Description
In the [Ballerina style guide match statement section](https://ballerina.io/learn/style-guide/statements/#match-statement) it says following about the statements within a pattern clause.

> If a pattern clause contains only one statement, place it in the same line as the pattern clause enclosing it with curly braces.

The provided example for that is,
``` ballerina
function foo(string|int|boolean a) returns string {
    match a {
        12 => {
            return "Value is '12'";
        }
    }
  
    return "Value is 'Default'";
}
```

But the above quoted description suggests that the line `return "Value is '12'"` should be in the same line as `12 => {` as below.
``` ballerina
function foo(string|int|boolean a) returns string {
    match a {
        12 => {return "Value is '12'";}
    }
  
    return "Value is 'Default'";
}
```

## Affected version(s)
Currently hosted version

## Related website/documentation area

Area/LearnPages

## Suggested label(s) (optional)
WebsiteRewrite, good first issue

**Comment by IrushiL** [comment]
Fixed with the mentioned PR.
