### ISSUE TITLE
Improve the AyncAPI Guide

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4484]
## Description
> A brief description of the improvement.

## Related website/documentation area
Area/LearnPages

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by HasithaAthukorala** [comment]
Task Description: We need to improve the AsyncAPI tool guide by focusing the developer more.

- Change the structure of the document
- Add more descriptions about the x-ballerina tags

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/4616.
