### ISSUE TITLE
Mention where to put `Config.toml` for test specific configuration

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#4511]
## Description
In [configurable related guide](https://ballerina.io/learn/configure-ballerina-programs/configure-a-sample-ballerina-service/) we should explicitly mention where to put `Config.toml` (it's inside the `tests` folder) for test specific configuration

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4536.
