### ISSUE TITLE
Issue in ```Use dependencies from the local repository```

### ISSUE THREAD

**Issue by sahanHe** [ballerina-platform/ballerina-dev-website#4539]
## Description
> When tried to publish a package to local ballerina central using the given [tutorial](https://ballerina.io/learn/manage-dependencies/#use-dependencies-from-the-local-repository), one command there seems to be not valid. When the following command is used, ```bal push -–repository local```  it gives the following error ```ballerina: unknown option: '-–repository'
Run 'bal help' for usage.```

The correct command should be 
```
bal push --repository local
```
as ```-–```  part uses an invalid symbol.
## Steps to reproduce
>follow the [tutorial](https://ballerina.io/learn/manage-dependencies/#use-dependencies-from-the-local-repository) ballerina docs for ballerina-io library and error can be observed after entering the command ```bal push -–repository local```

## Affected version(s)
> checked with 2201.1.0

## Related website/documentation area
> [https://ballerina.io/learn/manage-dependencies/#use-dependencies-from-the-local-repository](https://ballerina.io/learn/manage-dependencies/#use-dependencies-from-the-local-repository)
<img width="1033" alt="Screenshot 2022-06-09 at 09 35 34" src="https://user-images.githubusercontent.com/45299562/172761966-61adb78c-6137-4510-9873-9046902ec209.png">

**Comment by azinneera** [comment]
`bal push --repository local` is expected to work the same as `bal push --repository=local`. It works for me on ubuntu. @sahanHe can you specify the OS you are on?

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/4603.
