### ISSUE TITLE
Headings are not in sentence case

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#4540]
## Description
Headings in some of the policy related pages are not in sentence case [1].

![image](https://user-images.githubusercontent.com/7709843/172795452-6e2ee920-8409-445b-9c17-b1fd8f4a13b4.png)

[1] [https://ballerina.io/license-of-site/](https://ballerina.io/license-of-site/)

**Comment by praneesha** [comment]
Checked and fixed the titles in the pages below.

- [ ] Code license - Done via https://github.com/ballerina-platform/ballerina-lang/pull/36606.
- [ ] Site license

**Comment by praneesha** [comment]
Closing as this is done as per https://github.com/ballerina-platform/ballerina-dev-website/issues/4540#issuecomment-1159386677.
