### ISSUE TITLE
Need to Add `Star` and `Watch` Icons in the Quick Tour

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#46]
**Description:**
We need to replace the "Start" and "Watch" text with the respective icons in [1].

[1] https://ballerina.io/learn/quick-tour/
![Screenshot 2019-11-04 at 15 13 26](https://user-images.githubusercontent.com/11707273/68120127-9846d900-ff2a-11e9-863b-7faf5fd5ae93.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madhuramendis** [comment]
This is fixed now
