### ISSUE TITLE
Work on Unifying the Cookie Manager

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4601]
## Description
Need to work on unifying the Cookie Manager and the use of cookies in Bio similar to the WSO2 website.

Need to include CookiePro support for ballerina.io website.

## Related website/documentation area
Area/Backend

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-platform/ballerina-dev-website/pull/4794

**Comment by keizer619** [comment]
This is fixed for ballerina.io
