### ISSUE TITLE
Add the Docs on GCP Learn Content to B.io

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4602]
## Description
Need to add the docs on GCP Learn content[1] to B.io (the rewrite of the Ballerina microservices demo in Ballerina).

[1] https://github.com/ballerina-guides/gcp-microservices-demo

## Related website/documentation area
Area/LearnPages

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by xlight05** [comment]
We need to review the content we wrote for the [repo](https://github.com/ballerina-guides/gcp-microservices-demo) first before we start this task, afterwards we need to plan how we are gonna add the complete samples in the website then select which content we are going to add to the website .

**Comment by praneesha** [comment]
First, we will be bringing the examples that are currently there in each standard library repo under a `Use cases` section in B.io via https://github.com/ballerina-platform/ballerina-dev-website/issues/4409.

Next, we will consider adding this also in that section as a special use case with a broader scope than the standard library examples.

**Comment by anupama-pathirage** [comment]
Closing this as not needed. 
Reasons:

GCP Demo guide is now considered as one of ballerina standard demo. The details are there in the repo it self and no need to repeat those in b.io
