### ISSUE TITLE
Search in website is not updated with the latest BBE changes 

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-dev-website#4614]
## Description

With the Update 1 release, interceptor BBEs are replaced by a new set of BBEs. But the search in the website still suggests the old BBEs and following those links ends in the `Ballerina By Example` page. Ideally the search should suggest the new BBEs. 

## Steps to reproduce

Please refer the attached recording :

https://user-images.githubusercontent.com/63336800/176126867-0d01f828-119b-4997-94de-7e16b5ef703c.mov

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following.

**Comment by udda1996** [comment]
closing as this is fixed with #4622
