### ISSUE TITLE
Fix Rendering Issues in the New BBE Design

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4618]
## Description
Need to fix the rendering issues below in the new BBE design.

- [x] Indentations should be added after bullet points.
- [x] All files should be rendered properly.
- [x] Styles of bullet points text should be corrected.
- [x] Check the rendering of images.

<img width="1604" alt="Screenshot 2022-06-28 at 15 50 53" src="https://user-images.githubusercontent.com/11707273/176156156-3d9b4e47-1afd-46fa-95bf-3c12203f795a.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
Area/BBEs

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by YasithD** [comment]
Above fixes are completed with the following PRs.
https://github.com/ballerina-platform/ballerina-dev-website/pull/4624
https://github.com/ballerina-platform/ballerina-dev-website/pull/4632
https://github.com/ballerina-platform/ballerina-dev-website/pull/4627

**Comment by praneesha** [comment]
Closing as per the above comment.
