### ISSUE TITLE
Update Privacy Policy to Sentence Case in Community Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4628]
## Description
Need to update the below in the newsletter form to sentence case.

<img width="1247" alt="Screenshot 2022-06-29 at 16 54 29" src="https://user-images.githubusercontent.com/11707273/176425577-5163c3ea-3409-4276-91ec-1d332bf6132d.png">

This is done correctly in the Slack form as shown below.

<img width="1079" alt="Screenshot 2022-06-29 at 16 55 53" src="https://user-images.githubusercontent.com/11707273/176425810-b178e529-b5be-49bd-89bc-9523d13e914c.png">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by dinushan20** [comment]
This issue is fixed via Pardot. So I closed this issue
![image](https://user-images.githubusercontent.com/73055030/176602529-8f00db62-b195-4e0b-a7b6-fafe0222ed90.png)
