### ISSUE TITLE
Delete the `.description` files in BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4633]
## Description
Need to delete the `.description` files in BBEs as it is `.md` files that are used in the new BBE design.

This should be done only after these references are removed in Ballerina Shell via https://github.com/ballerina-platform/ballerina-lang/issues/36770.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DamithaSenevirathne** [comment]
Related PR : https://github.com/ballerina-platform/ballerina-distribution/pull/2962

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3077.

**Comment by DamithaSenevirathne** [comment]
Following PR's were sent to the relevant branches

`mater` branch : https://github.com/ballerina-platform/ballerina-distribution/pull/3109
`2201.1.x` branch : https://github.com/ballerina-platform/ballerina-distribution/pull/3108
`bbe-generation-v2` branch : https://github.com/ballerina-platform/ballerina-distribution/pull/3077

**Comment by praneesha** [comment]
Fixed as per the above comment.
