### ISSUE TITLE
Create a new BBE for reading a CSV file

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4728]
## Description
The `file read/write` BBE will not demo `How to read a CSV file`. Therefore, we will have to create a new BBE for it or describe which code snippet does the reading in code comments.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by daneshk** [comment]
Read/Write CSV BBE[1] demonstrate both read and write CSV operations. We may need to change the code comments

1. https://ballerina.io/learn/by-example/io-csv.html

**Comment by daneshk** [comment]
This issue is addressed as per the previous comment. Hence closing the issue
