### ISSUE TITLE
Font size is too small in Ballerina in action code snippet

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4730]
## Description

$subject and it seeems small compared to current live site. Since we are taking more width in the full page than the live site version, I don't see a reason to reduce the font size. 

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
As agreed increase the line height in the code snippet instead of the font size to avoid a horizontal scroll bar.

**Comment by sm1990** [comment]
To do as discussed:

- [ ] Check whether we can reduce the line length (content) in samples. eg:- grpc.
- [ ] Update tests to match the changes

**Comment by sm1990** [comment]
Fixed via #5392
