### ISSUE TITLE
Create an FAQ section

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4732]
## Description
Maybe, have an FAQ section to address how-tos (e.g., https://go.dev/doc/faq#Is_Go_an_object-oriented_language).

This would help to find a way for people to search for quick things such as `Efficient Joins with Ballerina Query Expressions`.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority
