### ISSUE TITLE
Links are not working in learn more section

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4740]
## Description

$subject in [1] http://dev.ballerina.io/learn/write-a-restful-api-with-ballerina/#Add%20a%20country%20by%20the%20ISO%20code

<img width="1489" alt="image" src="https://user-images.githubusercontent.com/16300038/179506546-a200b7aa-1e83-4528-ba93-ee21b4d067a5.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in http://dev.ballerina.io/
