### ISSUE TITLE
Some links are pointing to live site

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4742]
## Description

Some links are pointing to live site

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/16300038/179508272-58c59686-fbf1-46f6-8e5e-952f755691ef.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@anupama-pathirage those links are hard coded in the md files as below 
![image](https://user-images.githubusercontent.com/7709843/179519067-01db5093-98d2-4fd6-a0ab-237a558b2380.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
