### ISSUE TITLE
Incorrect highlighting in page TOC

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4750]
## Description

$subject for [1] . See the video

[1] http://dev.ballerina.io/learn/language-basics/#Programs%20and%20modules

https://user-images.githubusercontent.com/16300038/179663630-a30a8482-6153-4df2-b30f-45840648bf1b.mov

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/ with a workaround.

**Comment by YasithD** [comment]
Incorrect highlighting in Page Toc is fixed via #4975

**Comment by praneesha** [comment]
Closing as per the above comment.
