### ISSUE TITLE
Mismatching page title and box title for specifications

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4751]
## Description

$subject as button says "Ballerina specifications" while page [1]  title is "platform specifications"

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/16300038/179664198-54068d1c-8435-440e-b25d-8f2e2d585db4.png">

[1] http://dev.ballerina.io/learn/platform-specifications/

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/l
