### ISSUE TITLE
Text on the buttons are not consistent

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4758]
## Description

This is regarding the texts in the boxes.

1. Shouldn't we use videos instead of video?
2. First box starts with verb “watch”. Second one starts with word “Complete” which is not a verb. So can we have some similarity on both boxes?

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/16300038/179666916-03c43a1f-cb41-42e4-8abf-355d4b3694e1.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
