### ISSUE TITLE
Learn the platform section categories heights

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#4759]
## Description
> Should we align Learn the platform section categories heights to same level without keeping spaces

<img width="945" alt="Screenshot 2022-07-19 at 10 25 44" src="https://user-images.githubusercontent.com/2918812/179668213-5c9b9982-335a-4c0b-a997-3f94c6a1325e.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
