### ISSUE TITLE
Inconsistency in the use of term

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4780]
## Description
The website uses the term "cloud native" (without hyphen)  as well as "cloud-native" (with hyphen). 

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
For example, [1] uses "cloud-native" and [2] uses "cloud native".

[1] https://ballerina.io/community/newsletter/2021-4/#templateHeader
[2] https://ballerina.io/why-ballerina/cloud-native/

## Describe your solution(s)
It is better to stick to one format to be consistent. 

## Suggested label(s) (optional)
website revamp

**Comment by praneesha** [comment]
The hyphen is added when the term is used as an adjective as `cloud-native programming`. 

In the Why Ballerina section, it is used without the hyphen as a noun/phrase to be consistent with the other features/page titles to explain `why Ballerina should be used`.

**Comment by RukshiW** [comment]
But even when used in titles, this word (as well as other features such as "data-oriented" and "flexibly-typed) are adjectives and therefore the adjective is needed? Let's put this question to the TC team and get another opinion?

**Comment by praneesha** [comment]
> But even when used in titles, this word (as well as other features such as "data-oriented" and "flexibly-typed) are adjectives and therefore the adjective is needed? Let's put this question to the TC team and get another opinion?

Got it confirmed that we need the hyphen when we have the words as adjectives.

**Comment by praneesha** [comment]
Closing as the fixes are done.
