### ISSUE TITLE
A suggestion to improve subheadings for clauses

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4781]
## Description
In [1] single quotes are used in subheadings for clauses. 

[1] https://dev.ballerina.io/why-ballerina/data-oriented/#Query%20clauses

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Describe the problem(s)
Style guides generally recommend to avoid using punctuation in headings, and it is better to avoid repeating the word "clause" in all the subtitles.

## Describe your solution(s)
Shall we have just the clause names as the subheadings?

e.g., "from", "where", "let"

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
@anupama-pathirage these should be highlighted as code right? In that case we have to change them to backticks.

**Comment by anupama-pathirage** [comment]
Yes, these should be backticks.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
