### ISSUE TITLE
Backticks are shown instead of highligted texts in page toc

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4785]
## Description

<img width="432" alt="image" src="https://user-images.githubusercontent.com/16300038/180186910-d223b737-b0b2-429d-bdaf-aea0dd57fc69.png">

**Comment by YasithD** [comment]
Backticks rendering in Page Toc is fixed via #4975

**Comment by praneesha** [comment]
Closing as per the above comment.
