### ISSUE TITLE
The links in the Download page are broken

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4787]
## Description
All the links in the **Other installation options** section in [1] return a 404 error.

[1] https://dev.ballerina.io/downloads/

## Steps to reproduce
Click on any link in [1] https://dev.ballerina.io/downloads/

## Affected version(s)
> [The versions that are affected by the issue.](https://dev.ballerina.io/downloads/)

## Related website/documentation area

Area/CommonPages

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/.
Links related to 1.2.x will be fixed when deployed via github pages
