### ISSUE TITLE
Some links in the new Ballerina website point to the live site

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4789]
## Description
Some links in the  new Ballerina website point to the live site. The following are a few.

- [Community/Get Invoved](https://dev.ballerina.io/community/#get-involved) -> **Contribute to Ballerina Central** -> **creating and publishing** link
- [Learn/Configure Ballerina Programs/Provide values to configurable variables](https://dev.ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/#Provide%20via%20command%20line%20arguments) -> **Define Test Specific Configurations** link.

## Affected version(s)
[> The versions that are affected by the issue.](https://dev.ballerina.io/community/#get-involved)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
