### ISSUE TITLE
Use Cases page has links that do not work and a misspelt word

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4790]
## Description
The links in [1] are not working and "Websocket" is misspelt

[1] https://dev.ballerina.io/learn/use-cases/

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
[> Add/Uncomment the relevant area label out of the following. ](https://dev.ballerina.io)

Area/LearnPages

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
This page will not go live in the 1st cut. Hence deprioritizing

**Comment by sm1990** [comment]
Fixed the typo in https://dev.ballerina.io/

**Comment by anupama-pathirage** [comment]
Closing as we don't have such a page now
