### ISSUE TITLE
Issues in the Network Interaction page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4791]
## Description
The following issues were noted in the Network Interaction page [1]

1. When you click the GitHub icon to edit the page, it opens a private Git repository.
2. Heavy language is used and the tone contrasts with the some other parts of the website where a very casual tone is used.

[1] https://dev.ballerina.io/learn/distinctive-language-features/network-interaction/

Area/LearnPages

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
Issue 1 is fixed in https://dev.ballerina.io/learn/distinctive-language-features/network-interaction/

**Comment by MaryamZi** [comment]
> 2. Heavy language is used and the tone contrasts with the some other parts of the website where a very casual tone is used.
> 
> [1] https://dev.ballerina.io/learn/distinctive-language-features/network-interaction/

I believe there isn't much of a difference compared to the rest of the lang guides. We may have to revisit all of it if we are to do any changes.
