### ISSUE TITLE
Mismatching titles in installing ballerina section in the learn pages

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4792]
## Description
Clicking on `Install Ballerina` option on the https://dev.ballerina.io/learn/ page will be directed to the `https://dev.ballerina.io/learn/install-ballerina/set-up-ballerina/` url and and the title is also shown as `Set up Ballerina` as shown below. Shouldn't we align the page title with the link title that we have in the learn homepage?

<img width="428" alt="Screenshot 2022-07-22 at 11 01 00" src="https://user-images.githubusercontent.com/29032600/180369568-26482e0c-5bc1-42bc-a28c-cc2b627619e8.png">

Also, when trying to access https://dev.ballerina.io/learn/install-ballerina/ it ends up with 404 error.
## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
We do not have a separate page called `Install Ballerina`. It's just a broader topic that covers both, setting up ballerina & installation options.

**Comment by praneesha** [comment]
Links that are expected to be broken by the redesigning:

1. https://ballerina.io/learn/install-ballerina/set-up-ballerina/
2. https://ballerina.io/learn/install-ballerina/installation-options/
3. https://ballerina.io/learn/get-started-with-ballerina/
4. https://ballerina.io/learn/install-ballerina/
5. https://ballerina.io/learn/get-started

**Comment by sm1990** [comment]
This was fixed along with https://github.com/ballerina-platform/ballerina-dev-website/issues/4799
