### ISSUE TITLE
Provide a way for users to obtain the link of the home page examples

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4797]
## Description
Currently, if I want to point to a specific example from the home page, I can provide the following links: 
- https://ballerina.io/#working-with-data
- https://dev.ballerina.io/#consuming-services
- https://dev.ballerina.io/#restful-api
- https://dev.ballerina.io/#grpc-api
- https://ballerina.io/#graphql-api
- https://dev.ballerina.io/#kafka-consumer-producer ( I am not sure about this one. When I type this, all the examples disappear)
- https://dev.ballerina.io/#working-with-databases

##Problems
1. I got these links from Praneesha sometime back. But if I'm a new user who wants to share specific examples on Twitter or elsewhere I don't know how to get these links. 
2. Even when I go to these links, the view focus is not on the problem. IMO, the website should scroll down to the example area skipping the top parts.  

## Related website/documentation area
Home Page Examples

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
