### ISSUE TITLE
Inconsistency in getting started sections on the learn page?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4799]
## Description

Not sure if these were intentional, but

![learn_landing](https://user-images.githubusercontent.com/8376983/180600646-a21baa2d-a0d4-4f15-bee7-b336cb7ba617.png)

1. Shouldn't we have a subheading like "Get started" (similar to "Learn the language") before the first section? Right now it kinda looks like they come under "Learn Ballerina".
2. The descriptions for "Install Ballerina" and "Get started with Ballerina" start with verbs while those for the other 3 don't. Shouldn't these be consistent?

## Related website/documentation area
Area/LearnPages

**Comment by sm1990** [comment]
The idea behind the 1st section was to create a section with a set of quick links. Therefore, we did not use a section title. @anupama-pathirage or @praneesha what is your opinion regarding the text on buttons?

**Comment by praneesha** [comment]
+1 to have a separate `Get started` section at the top as this is something common in any product website and will be what anyone would look for to start with.

I don't think we need descriptions for the Install and Get started buttons as they are quite self-explanatory.

**Comment by praneesha** [comment]
@sm1990 - We need to improve the placement of the boxes at the top and implement the design below.

![new-learn-design](https://user-images.githubusercontent.com/11707273/224305345-367b0e6d-6ad3-421d-acb2-7d8a8dfd8008.png)

**Comment by sm1990** [comment]
@praneesha @anupama-pathirage Please share your thoughts on the new design 
![image](https://user-images.githubusercontent.com/7709843/232703717-597b4957-ec0b-4d0a-8c2d-1fc6a93169f7.png)

**Comment by praneesha** [comment]
+1 for this.

**Comment by anupama-pathirage** [comment]
- Text in `Get started with Ballerina` is incorrect. I guess that is a copy-paste error in mock.
- I feel the boxes are a bit too big. 
- What is the meaning of color here? Is it only the first box dark grey as shown the image, or are all boxes becoming dark grey when hovering? 
My preference is to keep them all in dark grey and make them teal color when hovering (Similar to level 2 boxes on current learn page)

**Comment by praneesha** [comment]
- This is dummy text added just for the demo of the design. Will review the text later.
- Shall we remove the description texts altogether? The labels seem to be self-explanatory and the descriptions seem to be redundant.
- The color should be added to highlight the `Get started` option to make it stand out from the rest.

**Comment by sm1990** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/6799
