### ISSUE TITLE
Fallacies of distributed computing should be fallacies of distributed computing

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4802]
Since the link is part of the text, let's follow the same rules of capitalization? Please check with Praneesha. 

https://dev.ballerina.io/why-ballerina/cloud-native/#Network-friendly%20type%20system

<img width="1076" alt="Screenshot 2022-07-25 at 09 34 58" src="https://user-images.githubusercontent.com/11885043/180696929-eb56f629-e78f-4a4c-bda0-3c626a4f148c.png">

**Comment by dakshitha** [comment]
Also found here - https://dev.ballerina.io/why-ballerina/reliable-maintainable/

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/11885043/180723109-4bd4063e-c56c-4de9-a173-8df9a5de6c88.png">

**Comment by sm1990** [comment]
@praneesha pls share your thoughts on the rules of capitalization

**Comment by praneesha** [comment]
+to remove capitalization of the first letter `f` when used in the normal text within the paragraph.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
