### ISSUE TITLE
HTML tags are shown in the HTTP Client BBE

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4803]
https://dev.ballerina.io/learn/by-example/http-client-endpoint/

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/11885043/180697668-1407863d-0476-418d-9ac4-189068ffc941.png">

**Comment by sm1990** [comment]
This will be fixed after BBE hackathon.

**Comment by ayeshLK** [comment]
This has been fixed with [#3024](https://github.com/ballerina-platform/ballerina-distribution/pull/3024)
