### ISSUE TITLE
HTML tags are displayed in the NATS BBE

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4805]
https://dev.ballerina.io/learn/by-example/nats-basic-pub-sub/

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/11885043/180698284-2866c1d7-dab3-4b74-bf84-3ca22dad8e68.png">

**Comment by sm1990** [comment]
This will be fixed after BBE hackathon

**Comment by dilanSachi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-distribution/pull/3014
