### ISSUE TITLE
Navigation Issue: Right-hand-side ToC in Why Ballerina -> Cloud Native

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4806]
Issues with 
1. Services -> Get started (Takes you to the previous Get started)
2. Async network protocol -> Get started (Takes you to the first Get started)
3. Client objects -> Get started (same as above)

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/11885043/180699692-54e5dd56-aa9f-4af2-8fd1-05563916590e.png">

**Comment by YasithD** [comment]
Unique ids for Page Toc is added via #4975

**Comment by praneesha** [comment]
Closing as per the above comment.
