### ISSUE TITLE
Capitalization Issue: Github actions to Github Actions

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4807]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/11885043/180700102-da41b907-04d5-4097-bba8-be475b95d978.png">

https://dev.ballerina.io/why-ballerina/cloud-native/#From%20code%20to%20Azure%20Functions

**Comment by sm1990** [comment]
@praneesha please share your thoughts.

**Comment by praneesha** [comment]
> @praneesha please share your thoughts.

+1 to say `GitHub Actions`.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
