### ISSUE TITLE
Navigation doesn't seem to work for "Install Ballerina" in "On this page" of "Set up Ballerina"

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4813]
## Description
https://dev.ballerina.io/learn/install-ballerina/set-up-ballerina/

## Steps to reproduce
Click on "Install Ballerina". The rest seem to be OK.

**Comment by YasithD** [comment]
This is fixed via #5015

**Comment by praneesha** [comment]
Closing as per the above comment.
