### ISSUE TITLE
Issues in Deploy Ballerina on Kubernetes page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4814]
## Description
The following issues were noted in [1]
1. The first sentence uses two tenses. It also uses the word "service" as well and "application" to refer to the same thing. Can we change it as follows?

" In this section, you will write a simple Ballerina service, Dockerize it, and deploy it in Kubernetes."

2. The right navigator of the page does not match the introductory sentence because out of the things mentioned, it only shows a subheading for creating the Ballerina service. It does not show any subheadings for Dockerizing or deploying. Shall we have seperate subheadings for Dockerizing and deploying?

3. The **Code to Cloud Deployment** link is broken.

[1] https://dev.ballerina.io/learn/deploy-ballerina-on-kubernetes/#Writing%20the%20Ballerina%20service

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
[> The versions that are affected by the issue.](https://dev.ballerina.io/learn/deploy-ballerina-on-kubernetes/#Writing%20the%20Ballerina%20service)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
website revamp

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/

**Comment by sm1990** [comment]
Re-opening as there are content related issues.

**Comment by praneesha** [comment]
1. Fixed the tense of the first sentence as follows: `This guide walks you through the steps of writing a simple Ballerina service, dockerizing the application, and deploying it in Kubernetes.`
2.

**Comment by praneesha** [comment]
The content updates are done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5437.
