### ISSUE TITLE
Record type link returns a 404

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4817]
Appears in - https://dev.ballerina.io/why-ballerina/flexibly-typed/#Shapes%20in%20Ballerina
Points to - https://dev.ballerina.io/learn/by-example/records.html

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/11885043/180715090-3e110b9a-e7b5-48cf-af79-698fc397a80a.png">

**Comment by dakshitha** [comment]
Another broken link on the same page:

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/11885043/180722475-9f254e7d-943c-4386-b689-2057034711ee.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
