### ISSUE TITLE
Too much spacing around BBE descriptions

### ISSUE THREAD

**Issue by dakshitha** [ballerina-platform/ballerina-dev-website#4818]
<img width="1386" alt="Screenshot 2022-07-25 at 12 19 44" src="https://user-images.githubusercontent.com/11885043/180716239-d1a4c85e-656b-4c02-a6b9-4065805f2062.png">

See screenshot. 

Link - https://dev.ballerina.io/learn/by-example/query-expressions/

**Comment by YasithD** [comment]
This is fixed with the BBE hackathon.
![image](https://user-images.githubusercontent.com/59837420/183824430-d4bad061-138c-4a3d-b2f2-474d8c1248a9.png)

**Comment by praneesha** [comment]
Closing as per the above comment.
