### ISSUE TITLE
Inconsistencies in the Featured Use Cases section

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4819]
## Description
Some inconsistencies can be noted in the Featured Use Cases section in terms of structure and language

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
This is a list of inconsistencies noted:
1. Some use case pages use simple present tense in subheadings (e.g., [1]), and some use present continuous tense (e.g., [2]).
2. Most use case pages have an introductory sentence after the main heading, but [1] and [3] don't.
3. All the subheadings in [1] use the imperative tone except **The complete code**. Also, none of the other use case pages have this subheading under which they show the complete implementation.
4. Only [1] and [3] have a subheading named **Understand the implementation**

[1] https://dev.ballerina.io/learn/write-a-restful-api-with-ballerina/#Add%20a%20country%20by%20the%20ISO%20code
[2] https://dev.ballerina.io/learn/deploy-ballerina-on-kubernetes/
[3] https://dev.ballerina.io/learn/write-a-grpc-service-with-ballerina/

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

 

## Suggested label(s) (optional)
website revamp

**Comment by praneesha** [comment]
1. Removed the `-ing` form on the Kubernetes guide.
2. That should be fine.
3. Need to add it.
4. That should be fine as these are independent tutorials from each other.

**Comment by praneesha** [comment]
Closing as per the fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4819#issuecomment-1206339521.
