### ISSUE TITLE
Can we improve the contrast between the headings and the BBEs?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4820]
## Description
$title in https://dev.ballerina.io/learn/by-example/. I feel like what we have on the live site atm is better in terms of contrast and reading through.

**Comment by YasithD** [comment]
Improved the contrast by reducing the `font weight` of the BBE names in the BBE landing page.
![image](https://user-images.githubusercontent.com/59837420/183824158-e5ac0f76-eaf5-48c5-8253-867aef490438.png)

**Comment by praneesha** [comment]
Closing as per the above comment.
