### ISSUE TITLE
Issue in some of the lang specs on the dev site

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4821]
## Description
$title.

![spec_issue](https://user-images.githubusercontent.com/8376983/180722621-62969d0e-3165-4165-82e6-7ecd20838863.png)

For at least
- [2020R1](https://dev.ballerina.io/spec/lang/2020R1/)
- 2019R3
- 2019R2
- 2019R1

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
