### ISSUE TITLE
Issues noticed in the Advanced, general-purpose language features page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4822]
## Description
In [1], the following was noticed

1. The terms "read-only" and "readonly" are used interchangeably. "readonly" would be wrong unless it is a standard term used in code. However, in this page, "readonly" is also used as an adjective which is incorrect. For example, it should not be used in the subheading.
2. Although sub-headings that include words in code -format (formatted with black-ticks) are rendered correctly in the body of the page, they are rendered with black-ticks in the right navigator. Clicking on such sub-heading in the right navigator does not take you to the relevant section on the page. (This issue is there also in the other pages under **Distinctive language features**.)

[1] Advanced, general-purpose language features

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
website revamp

**Comment by MaryamZi** [comment]
> 2\. Although sub-headings that include words in code -format (formatted with black-ticks) are rendered correctly in the body of the page, they are rendered with black-ticks in the right navigator. Clicking on such sub-heading in the right navigator does not take you to the relevant section on the page. (This issue is there also in the other pages under **Distinctive language features**.)

@sm1990, @praneesha, please note.

**Comment by praneesha** [comment]
> > 2. Although sub-headings that include words in code -format (formatted with black-ticks) are rendered correctly in the body of the page, they are rendered with black-ticks in the right navigator. Clicking on such sub-heading in the right navigator does not take you to the relevant section on the page. (This issue is there also in the other pages under **Distinctive language features**.)
> 
> @sm1990, @praneesha, please note.

The titles within backticks are rendered and navigated properly on the RHS page TOCs now as shown below. See [1] for example.

<img width="1677" alt="Screenshot 2022-08-09 at 15 27 51" src="https://user-images.githubusercontent.com/11707273/183621148-3786cf23-0c4b-4681-b996-735d8a921a8d.png">


[1] https://dev.ballerina.io/learn/distinctive-language-features/data/#limit-clause

**Comment by praneesha** [comment]
CHanges with respect to the first point are updated via https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
