### ISSUE TITLE
Inconsistent fonts/formatting on learn landing page?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4826]
## Description
$title. Note the difference between the sections under "Learn the language" and those under "Featured use cases".

![learn_landing_page_1](https://user-images.githubusercontent.com/8376983/180731924-5ef2da87-30d2-412a-a87c-beed9c91c1bd.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
