### ISSUE TITLE
Inconsistencies noted in the Ballerina Tooling section

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4828]
## Description
The following inconsistencies were noted in the Ballerina Tooling section:

1. The first link under this section (i.e., **Visual Studio Code Extention** opens the relevant extension page in the Visual Studio website whereas all the other links open pages that belong to the Ballerina website.

2. The pages for **OpenAPI tool** [1] and **AsyncAPI tool** [2] use future tense in the opening sentence (e.g. "The Ballerina AsyncAPI tool will make it easy for you to start the development... ". A lot of future tense is used in the other sections of the two pages as well. This makes it sound as if the tool is not yet released. 

3. Suggesting the introduction of [3] to be rewritten as follows:

```suggestion
The Ballerina shell allows you to evaluate code snippets, eliminating the need to write complete programs.

This tool is particularly useful if you want to try out the language and its new features. It is also useful also for debugging purposes.

**Notes**

- Ballerina Shell currently supports a subset of the language features. 
- Ballerina Shell does not support services and isolation features. 
- Also, Ballerina Shell provides limited feature support for worker-related implementations.

```

[1] https://dev.ballerina.io/learn/openapi-tool/
[2] https://dev.ballerina.io/learn/asyncapi-tool/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
website_revamp

**Comment by praneesha** [comment]
1. That is intentional as we have the VSCode extension docs on its marketplace.
2. Fixed all occurrences.
3. Updated as per the suggestion.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5052.
