### ISSUE TITLE
Logos in the footer should be links

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#4830]
## Description
The logos in the website footer seems to be buttons, not links. When we hover over them, mouse is not changed to pointer. When clicked, I get redirected to the corresponding site (twitter, youtube, etc) on the same tab. IMO, they should open up in a separate tab.

![Screenshot from 2022-07-25 14-50-08](https://user-images.githubusercontent.com/11285165/180743628-a5be5bbc-84ee-457c-851e-59db617d0f5f.png)

## Affected version(s)
dev.ballerina.io

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
