### ISSUE TITLE
Improve how the language guide videos and slides are listed

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#4833]
## Description
Currently it is as follows

![learn_landing_page_2](https://user-images.githubusercontent.com/8376983/180742256-c3fd5f53-812a-4205-8628-1a4a2e077325.png)

1. I feel like it's not quite clear what the video is.
2. For the slides too, I feel like the description should be consistent with what we use for the video (e.g., "View slides ...")

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
