### ISSUE TITLE
`Submit tech talk` and `submit a use case` modals overlap with the secondary navigation bar in community page

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#4839]
## Description
$subject
![Screenshot from 2022-07-25 15-39-11](https://user-images.githubusercontent.com/11285165/180752937-ad1a14df-8ac8-47ae-8be5-19b04e7f8975.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
