### ISSUE TITLE
Switch the colors of the buttons

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4845]
## Description

$subject for below highlighed buttons to match with the top 5 buttons.

Since we are using gray/black when non-hovering, and convert to teal on hovering, we better follow  a similar pattern to these buttons too. 

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/16300038/180771137-43c7bb77-e070-4399-b6fd-189dded5bc37.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
