### ISSUE TITLE
Open the VSCode page in a new tab

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4846]
## Description

$subject as it is navigating away from the ballerina.io

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/16300038/180771544-5f02756f-e8ef-4897-b11a-5a8c6e3cb0f8.png">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/

**Comment by anupama-pathirage** [comment]
Still, it is getting open in the current tab when we use left navigation.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/16300038/180934369-1a564985-e483-4b19-b467-6b07521e7e40.png">

**Comment by sm1990** [comment]
@anupama-pathirage do we need the VS Code extension link in the left nav? We removed other external links such as API docs from there. Shall I do the same?

**Comment by anupama-pathirage** [comment]
+1 to remove

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
