### ISSUE TITLE
Titles in the landing page should match the corresponding page title

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#4856]
## Description
In the `Featured use cases` section, when you click on `Work with databases` it points to `Build a data service in Ballerina`. Shouldn't we change text in the landing page to match that?

**Comment by sm1990** [comment]
@anupama-pathirage please share your thoughts on this

**Comment by anupama-pathirage** [comment]
Yes, all titles should match.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
