### ISSUE TITLE
Missing introduction in learn guides

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4865]
**Description:**
I'm not sure whether $subject is intentional, but introduction section seems to be missing in all the learn guides after the revamp. 

As a reference, refer to the prod and dev versions of the `Organize Ballerina Code` learn guide below. 

## Old
<img width="875" alt="Screenshot 2022-07-26 at 16 38 45" src="https://user-images.githubusercontent.com/29032600/180993733-feb0efcb-621b-4e85-a4a4-01aa89171263.png">

## New
<img width="1073" alt="Screenshot 2022-07-26 at 16 38 56" src="https://user-images.githubusercontent.com/29032600/180992475-ce249dfb-c408-49a8-9ecc-20882ec50916.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
