### ISSUE TITLE
Suggestions to improve the Publish packages to Ballerina Central page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4866]
## Description
This is a list of suggestions to improve [1]

[1] https://dev.ballerina.io/learn/publish-packages-to-ballerina-central/#Create%20a%20library%20package

## Related website/documentation area
[> Add/Uncomment the relevant area label out of the following. ](https://dev.ballerina.io/learn/publish-packages-to-ballerina-central/#Create%20a%20library%20package)

Area/LearnPages

## Describe the problem(s)

1. The introductory sentence includes the sentence "Use the `bal new` command to create a library package.". Then the section that follows is about creating a library package, and that instructs the user to use another command (i.e., `bal new -t lib`) for the same purpose. This can be confusing. 

**Suggestion**: Shall we update the introductory sentence to describe what a package is and to state why a user would need to publish one?

2. Shall we re-organize the **Create a library package** section? Currently, there are the following issues:

- The file list is unnecessarily repeated.
- The **Package layout** link is repeated.
- It is not clear what the correct command to create a new library package is. Is `bal new -t lib` the format of the command, and `bal new --template lib hello` an example? If so, let's clearly state that?
- It is not clear what the last two code blocks are for.

**Suggestion**
Let's structure this section as follows?

    1.  Explain how to create a library package. If you want to provide both the command format and an example, first give the command format and explain each part of it (e.g., whether "t" represents the template name). Then provide an example.
    2. Have the sentence "This creates the following files:" and have the code block with the file structure under it.
    3. Under the code block which shows the file structure, explain each file in point format (as already done).
    4. Have the sentence "For more information about these files, see [Package layout](https://dev.ballerina.io/learn/package-references/#package-layout). ".
    5. If you are having the code block that starts with [package], state what it is.
    6. Change the next sentence to "To generate the Ballerina archive, issue the following command:" The give the command below it. (This is because it is a recommended practice to state the purpose before the action).
    7. If the next code block shows the resulting logs, include a sentence to state that.

3. Under the **Organizations** heading, there is a missing space after a fullstop (" package.If").
4. Replace "don't" with "do not because it is not recommended to use contractions.
5. The **Organizations** heading seems out of place because all other subheadings are in imperative tone.

## Suggested label(s) (optional)
website_revamp

**Comment by praneesha** [comment]
1. Updated according to the suggestions.
2. Updated the following.

- 2.1: Updated.
- 2.2: Done.
- 2.3: Already done.
- 2.4: Already done.
- 2.5: Removed the `Ballerina.toml` file content as it is out of place.
- 2.6: Updated.
- 2.7: Updated.

3. Added the missing space.
4. Fixed.
5. Renamed the `Organizations` heading to `Define the organization`.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5051.
