### ISSUE TITLE
Text in BBE contains <br/><br/>

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4872]
## Description
Two HTML tags  <br/><br/> are mistakenly displayed in the rendered text of a published BBE [1].

[1] https://dev.ballerina.io/learn/by-example/http-absolute-path-and-path/

## Affected version(s)
[ The versions that are affected by the issue.
](https://dev.ballerina.io/learn/by-example/http-absolute-path-and-path/)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

 

## Suggested label(s) (optional)
website_revamp

**Comment by sm1990** [comment]
This will be fixed after BBE hackathon.

**Comment by RukshiW** [comment]
Noticed that this issue is present in all the BBEs ion the REST APIcategory except https://dev.ballerina.io/learn/by-example/http-resource-returns/

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3026/files#diff-613b1932910d2d8ba3bba8796cc03e6668edd71d5c916c9eded51a468ec04a65R5
