### ISSUE TITLE
Broken link in 1.2.x download section

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#4874]
## Description
Following text under 1.2.x section in download page  "Installing Ballerina" hyperlink is broken

To download the VSCode and IntelliJ Ballerina extensions, see [Setting up Visual Studio Code](https://dev.ballerina.io/1.2/learn/setting-up-visual-studio-code/) and[ Setting up IntelliJ IDEA](https://dev.ballerina.io/1.2/learn/setting-up-intellij-idea/), and for installation instructions, see[ Installing Ballerina](https://dev.ballerina.io/1.2/learn/installing-ballerina/).

**Comment by sm1990** [comment]
@keizer619 These links will work after publishing via github pages.
