### ISSUE TITLE
Vertical alignment issues in learn guides when focusing/navigating using right hand side ToC

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4875]
## Description
Refer to the below samples and note that the sub topics are not getting top-aligned when using RHS ToC and due to that, content of the previous topic is also visible. (note that the sub topics are getting top-aligned as expected in the prod site.)

## Dev
<img width="1117" alt="Screenshot 2022-07-27 at 10 54 03" src="https://user-images.githubusercontent.com/29032600/181168403-f699496a-1005-449a-971d-fc2e22f5268e.png">
## Prod
<img width="1176" alt="Screenshot 2022-07-27 at 10 56 49" src="https://user-images.githubusercontent.com/29032600/181168413-931011a3-51a4-4bef-bb1c-a0926f5fe574.png">

**Comment by YasithD** [comment]
Vertical alignment issues are fixed via #4975

**Comment by praneesha** [comment]
Closing as per the above comment.
