### ISSUE TITLE
Note Sections aren't styled in the spec page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4876]
## Description
We do not have the note sections styled correctly on the spec Learn page[1] as shown below.

<img width="1402" alt="Screenshot 2022-07-27 at 11 05 42" src="https://user-images.githubusercontent.com/11707273/181169315-b0f0e4dd-a9f8-4b1e-84a8-a84c7697ebbb.png">

[1] https://dev.ballerina.io/learn/ballerina-specifications/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
