### ISSUE TITLE
Incorrect highlighting within Ballerina code blocks in learn guides

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4877]
## Description
Note $subject in [Organize Ballerina code Guide](https://dev.ballerina.io/learn/organize-ballerina-code/#Import%20a%20module%20from%20the%20same%20package) and refer to below Ballerina code sample which is incorrectly highlighted.
<img width="851" alt="Screenshot 2022-07-27 at 11 05 26" src="https://user-images.githubusercontent.com/29032600/181169411-66fd4029-577c-4175-a933-8174fea4641d.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@NipunaRanasinghe in the live site also the code is highlighted in the same manner. 
![image](https://user-images.githubusercontent.com/7709843/181174355-98a8e747-d517-4c6c-abd9-77c916424ac2.png)

**Comment by sm1990** [comment]
@praneesha & @keizer619  it seems adding `[` & `]` to show optional items is conflicting with language grammar.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5054.
