### ISSUE TITLE
Issues in Build a data service in Ballerina page

### ISSUE THREAD

**Issue by samisa-abeysinghe** [ballerina-platform/ballerina-dev-website#4880]
## Description
I have tried to get the data services working with the latest release using https://ballerina.io/learn/build-a-data-service-in-ballerina/
I ran into a few issues/challenges

## Affected version(s)
Swan Lake

## Related website/documentation area
Area/LearnPages

1. MySQL drive version mentioned is version = "8.0.26" to be set in Ballerina.toml. However, the latest is 8.0.30. If I have that driver in my machine, I suppose this setting would not work 
2. What is the recommended link to download the driver JAR manually? 
3. Path variable sample to be set in Ballerina.toml is given as path = "/path/to/mysql/driver.jar”. What should a sample be for a Windows machine? 
4. It is mentioned to place Config.toml in package directory. What is package directory here? bal new command does not create a package directory in project folder 
5. In the mid tutorial, it instructs to  bal run to check if the db connection works. However, the code up to that throws an error due to  unused import ballerina/sql;
6. It is instructed to test the service, you can accessed via a browser by visiting http://locahost:8080/employees after executing the command bal run. If you copy the URL given in the text, there is a typo there 'locahost' and no l as in "localhost"
7. The curl command given  to test add employee does not work on Windows 
8. The curl command's Conten-type header is given as text/palin. However, I kept getting a data binding failure until I changed it to  application/json

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5041.
