### ISSUE TITLE
The Build from Source link in the Installation Options page is broken

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4881]
## Description
The **Build from Source** link in [1] is broken.

[1] https://dev.ballerina.io/learn/install-ballerina/installation-options/#Install%20on%20Linux

## Affected version(s)
[> The versions that are affected by the issue.](https://dev.ballerina.io/learn/install-ballerina/installation-options/#Install%20on%20Linux)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
website_revamp

**Comment by sm1990** [comment]
@keizer619 or @anupama-pathirage need the correct url for the above. Currently its pointed to https://github.com/ballerina-platform/ballerina-distribution/blob/master/docs/build-from-source.md

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5030.
