### ISSUE TITLE
Upto which heading level should be supported in the right hand side ToC?

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4883]
**Description:**
This is up for discussion as even though we support only up to H3 headers in the left navigation panel in the live site, there seem to be no such restriction for the right hand side ToC layout, in the new design. (Refer to the H5 headings in the below learn guide ToC)
<img width="254" alt="Screenshot 2022-07-27 at 11 56 39" src="https://user-images.githubusercontent.com/29032600/181176577-fac687e1-5994-44c5-ab87-22de82c3bf26.png">

Should we have a similar restriction for the new ToC as well? @anupama-pathirage Any thoughts?

**Comment by sm1990** [comment]
@NipunaRanasinghe currently it goes up to H6.

**Comment by praneesha** [comment]
We will be supporting up to H6 in both Learn pages and BBE TOCs on the new site.
