### ISSUE TITLE
Incorrect block highlighting in "Manage Dependencies" Guide

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4884]
## Description
Note $subject in https://dev.ballerina.io/learn/manage-dependencies/#Version%20compatibility and refer to below block which is incorrectly highlighted (Note that the `in` word is highlighted in red for some reason).

<img width="770" alt="Screenshot 2022-07-27 at 13 20 11" src="https://user-images.githubusercontent.com/29032600/181192576-288a6302-a525-4fa5-93fc-d0efd73381de.png">

**Comment by NipunaRanasinghe** [comment]
Also in https://dev.ballerina.io/learn/manage-dependencies/#Use%20dependencies%20from%20the%20local%20repository the Ballerina CLI commands seem to have highlighted in an unusual way 
![Uploading Screenshot 2022-07-27 at 13.25.26.png…]()

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5055.
