### ISSUE TITLE
Spacing issues in the left nav

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4886]
## Description
There are horizontal and vertical spacing issues in the left nav as shown below.

<img width="1375" alt="Screenshot 2022-07-27 at 13 31 39" src="https://user-images.githubusercontent.com/11707273/181194703-063d16c5-6fef-4b0a-9477-f0b2fac6ac2d.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
