### ISSUE TITLE
Block quotes are not getting rendered in learn guides

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4887]
## Description
$subject. Refer to below blocks in https://dev.ballerina.io/learn/manage-dependencies/#Specify%20dependency%20versions

## Dev 
<img width="767" alt="Screenshot 2022-07-27 at 13 37 23" src="https://user-images.githubusercontent.com/29032600/181195763-f70a0b67-c8d8-462e-bfc7-7764c3bfb847.png">

## Prod
![Screenshot 2022-07-27 at 13 37 01](https://user-images.githubusercontent.com/29032600/181195802-35e89939-3778-4219-92ed-62b789e7711f.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
