### ISSUE TITLE
The `.proto` code snippet not rendered on the gRPC use case page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4888]
## Description
The `.proto` code snippet is not rendered correctly on the gRPC use case page[1].

<img width="1425" alt="Screenshot 2022-07-27 at 13 35 02" src="https://user-images.githubusercontent.com/11707273/181196045-ba5b5b71-ee84-4253-8d6a-5c95132aa846.png">

[1] https://dev.ballerina.io/learn/write-a-grpc-service-with-ballerina/#Create%20the%20service%20definition

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
