### ISSUE TITLE
Bullet styling is not consistent

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4890]
## Description
Bullet styling is not consistent on the same page[1].

**Bullet style 1**

<img width="1398" alt="Screenshot 2022-07-27 at 13 44 40" src="https://user-images.githubusercontent.com/11707273/181197368-16ac73f3-413c-47d8-9f4f-dbf34cc7c603.png">

**Bullet style 2**

<img width="1378" alt="Screenshot 2022-07-27 at 13 44 33" src="https://user-images.githubusercontent.com/11707273/181197519-c3b64709-aa2c-42d2-838c-83863fa55e48.png">

[1] https://dev.ballerina.io/learn/write-a-grpc-service-with-ballerina/#Update%20the%20service%20template%20file

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
