### ISSUE TITLE
Some code blocks are not properly rendered in configurations learn guide

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4891]
## Description
$subject in https://dev.ballerina.io/learn/configure-ballerina-programs/configure-values/#Command%20line%20argument%20syntax 

## Dev
<img width="675" alt="Screenshot 2022-07-27 at 13 49 57" src="https://user-images.githubusercontent.com/29032600/181198315-191f2d1a-90e9-40c1-99a3-16d7d63cc15b.png">

## Prod
![Screenshot 2022-07-27 at 13 50 04](https://user-images.githubusercontent.com/29032600/181198359-81ebd547-e17c-41c6-91e4-37090368f6af.png)

**Comment by NipunaRanasinghe** [comment]
Also in https://dev.ballerina.io/learn/configure-ballerina-programs/configure-a-sample-ballerina-service/

![Uploading Screenshot 2022-07-27 at 13.52.35.png…]()

**Comment by NipunaRanasinghe** [comment]
Also in https://dev.ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/#Provide%20via%20command%20line%20arguments
<img width="757" alt="Screenshot 2022-07-27 at 13 56 43" src="https://user-images.githubusercontent.com/29032600/181199667-3179ba71-f49d-493b-a169-9037ca8aa218.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
