### ISSUE TITLE
Open the Learn pages edit option in a new tab

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4892]
## Description
It will be better if the edit option of the learn pages can be directed to a new tab as it goes out of the website and opens up the GitHub repo.

<img width="1342" alt="Screenshot 2022-07-27 at 13 49 52" src="https://user-images.githubusercontent.com/11707273/181198439-b6cc3d78-ab2f-4e8e-8e7c-1e735f4e331e.png">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
