### ISSUE TITLE
Have the full page width for Learn pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4894]
## Description
It is better if we can have the full page width for Learn pages as done in the example[1] below unless we have a justification to have the white space on both sides we currently have e.g., in [2].

These white spaces make the view too compact.

<img width="1680" alt="Screenshot 2022-07-27 at 13 59 54" src="https://user-images.githubusercontent.com/11707273/181200618-abf1069e-6499-4f88-82b6-e44abff71569.png">

<img width="1680" alt="Screenshot 2022-07-27 at 13 59 34" src="https://user-images.githubusercontent.com/11707273/181200697-954f0b38-f6c5-4b3e-b5b4-b17fcfe83112.png">

[1] https://wso2.com/choreo/docs/scheduled-tasks/
[2] https://dev.ballerina.io/learn/build-a-data-service-in-ballerina/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
