### ISSUE TITLE
Rename "Test & document the code" title

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4895]
## Description
Shall rename the above title as "Test, debug and Document the code", since we have included the debugging guide as well in there? @praneesha WDYT?
<img width="427" alt="Screenshot 2022-07-27 at 13 59 19" src="https://user-images.githubusercontent.com/29032600/181201280-acb3facf-e506-4d64-bc56-3f73086684be.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
