### ISSUE TITLE
Code snippet not rendered correctly in K8S Use Case page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4897]
## Description
> A code snippet is not rendered correctly in the K8S use case page[1] as shown below.

<img width="1389" alt="Screenshot 2022-07-27 at 14 11 41" src="https://user-images.githubusercontent.com/11707273/181202946-46851bfb-ffb7-4bea-a959-1d3b4184e23e.png">

[1] https://dev.ballerina.io/learn/deploy-ballerina-on-kubernetes/#Code%20to%20Cloud

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
