### ISSUE TITLE
Code block rendering issues in observability learn guide

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4899]
## Description
Please note $subject and refer to the below code blocks in https://dev.ballerina.io/learn/observe-ballerina-programs/#Set%20up%20Elastic%20Stack which are not properly rendered.

## case 1
<img width="774" alt="Screenshot 2022-07-27 at 14 22 10" src="https://user-images.githubusercontent.com/29032600/181206077-06e39f2c-b192-482c-9916-ce3c1e817524.png">

## case 2
<img width="723" alt="Screenshot 2022-07-27 at 14 22 33" src="https://user-images.githubusercontent.com/29032600/181206098-f46d8b7d-b9a6-4a96-8ebd-aa2c0e860a86.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
