### ISSUE TITLE
Code snippet not rendered correctly on C2C page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4900]
## Description
> A code snippet is not rendered correctly on the C2C page[1] as shown below.

<img width="1458" alt="Screenshot 2022-07-27 at 14 31 13" src="https://user-images.githubusercontent.com/11707273/181207634-32a50d4a-f014-4e53-b01b-ea19e7a2bd46.png">

[1] https://dev.ballerina.io/learn/run-in-the-cloud/code-to-cloud/code-to-cloud-deployment/#How%20Code%20to%20Cloud%20works

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
