### ISSUE TITLE
Inconsistencies when rendering comments within code snippets in learn guides

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4901]
## Description
Note $subject in https://dev.ballerina.io/learn/call-java-code-from-ballerina/#Create%20the%20FileInputStream (note the difference between dev and live site renderings.)

## Dev
<img width="774" alt="Screenshot 2022-07-27 at 14 31 02" src="https://user-images.githubusercontent.com/29032600/181207966-c8ced1f9-cb7c-43e7-a2d1-89062782eacc.png">

## Prod
![Screenshot 2022-07-27 at 14 30 57](https://user-images.githubusercontent.com/29032600/181208012-fc2d9b5f-8260-4a01-96aa-9ed778db55bd.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
