### ISSUE TITLE
Add Next/Previous option on Learn pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4902]
## Description
It will provide easier navigation between the Learn pages if we can provide a next/previous option[1] as shown below.

<img width="1680" alt="Screenshot 2022-07-27 at 14 37 31" src="https://user-images.githubusercontent.com/11707273/181208860-4754b4ad-3dbf-4b87-bbd6-e6bed0d1fdd4.png">

[1] https://wso2.com/choreo/docs/get-started/what-is-choreo/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by Nipun-Milinda** [comment]
Hi. Can I get this assigned to me

**Comment by sm1990** [comment]
@Nipun-Milinda any update on this issue?

**Comment by s-vamshi** [comment]
@sm1990 if no one is working on this issue, can I pick up this?

**Comment by sm1990** [comment]
@Nipun-Milinda since there is no update from you, we assigning this to @s-vamshi .
@s-vamshi you can start working on this.

**Comment by sm1990** [comment]
@s-vamshi you can use this component. https://github.com/ballerina-platform/ballerina-dev-website/blob/master/components/common/prev-next/PrevNext.js

**Comment by s-vamshi** [comment]
Sure will start working on it.
