### ISSUE TITLE
Address inconsistencies in navigator topics

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4904]
## Description
Most navigator topics/page titles in the Learn section are presented as nouns, but occasionally, there are headings presented as sentences in present continuous format. Some examples are marked in the attached image. This creates an inconsistency.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
Website Revamp

<img width="209" alt="Screen Shot 2022-07-27 at 14 30 19" src="https://user-images.githubusercontent.com/26239861/181210045-b60136af-b139-4fb9-a7f6-1d56843b15d5.png">

**Comment by praneesha** [comment]
- `Error handling` is a principle and it should be acceptable to have it as a noun.
- `Ignoring return values and errors` is renamed to `Ignore return values and errors` via https://github.com/ballerina-platform/ballerina-distribution/pull/2983/files.
- `Work over the network` is renamed to `Network libraries` via https://github.com/ballerina-platform/ballerina-distribution/pull/3044.
