### ISSUE TITLE
Captcha section hides when there is an error message

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#4905]
## Description
> Captcha section hides when there is an error message

<img width="693" alt="Screenshot 2022-07-27 at 14 42 07" src="https://user-images.githubusercontent.com/2918812/181210028-d6244427-3d81-4612-8113-4dcaeefddf93.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
