### ISSUE TITLE
subscribe-to-newsletter link does not focus the section

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#4906]
## Description
> Following subscribe-to-newsletter link is referred in several places its not focusing the section

https://dev.ballerina.io/community/#subscribe-to-newsletter

<img width="1315" alt="Screenshot 2022-07-27 at 14 46 02" src="https://user-images.githubusercontent.com/2918812/181210637-a14ca6af-6a42-4105-ada6-8755359b887f.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
