### ISSUE TITLE
The link to Troubleshooting does not work

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4907]
## Description
The **Troubleshooting** link is broken in most Release Notes. [1] and [2] are examples.

[1] https://dev.ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.0.5
[2] https://dev.ballerina.io/downloads/swan-lake-release-notes/2201-0-0-swan-lake/#troubleshooting

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
[> The versions that are affected by the issue.](https://dev.ballerina.io/)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Suggested label(s) (optional)
Website_Revamp

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
