### ISSUE TITLE
Incorrect image aspect ratio in Java interoperability guide

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-dev-website#4912]
## Description
$subject in https://dev.ballerina.io/learn/java-interoperability-guide/java-interoperability/#Ballerina%20bindings%20to%20Java%20code

## Dev
<img width="760" alt="Screenshot 2022-07-27 at 15 59 00" src="https://user-images.githubusercontent.com/29032600/181226141-87fb1123-e821-4d76-b7a4-e750e888e44f.png">

## Prod
![Screenshot 2022-07-27 at 16 01 48](https://user-images.githubusercontent.com/29032600/181226331-05089631-0e60-415d-93bb-57505ac4a7ac.png)

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
