### ISSUE TITLE
Suggestions to improve the Java interoperability page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4917]
## Description
A few suggestions to improve [1]

[1] https://dev.ballerina.io/learn/java-interoperability-guide/java-interoperability/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)

The tone used does not address the reader and might not give the feeling that we are addressing reader's requirements

## Describe your solution(s)

Replace the image so that it does not look stretched.

The following is a suggested update to the text after the image to improve the tone.

```suggestion
The next section of this reference guide explains the [Bindgen Tool](https://dev.ballerina.io/learn/java-interoperability/the-bindgen-tool/) that you can use to generate these bindings automatically while eliminating the need for understanding the [Ballerina FFI](https://dev.ballerina.io/learn/java-interoperability/ballerina-ffi/) layer.

The Ballerina FFI section explains how to write these bindings manually. By learning to write them manually, you can understand the inner workings of calling Java from Ballerina. It can also help you if you want to customize the bindings generated by the `bindgen` tool.
```

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by praneesha** [comment]
@dinushan20 - Shall we redraw the diagram to improve it?

**Comment by praneesha** [comment]
The text will be improved via https://github.com/ballerina-platform/ballerina-dev-website/pull/5029.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5029

**Comment by praneesha** [comment]
The diagram is fixed in [1] via https://github.com/ballerina-platform/ballerina-dev-website/pull/5038 as shown below.

[1] https://pre-prod.ballerina.io/learn/java-interoperability-guide/java-interoperability/

<img width="1680" alt="Screenshot 2022-08-05 at 12 22 32" src="https://user-images.githubusercontent.com/11707273/183019408-9dca074b-e158-45aa-9e95-16c473f78759.png">
