### ISSUE TITLE
Add a `Request docs changes` option to B.io

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#4920]
## Description
Add a `Request docs changes` option to B.io similar to the below in [1]. This will help to gather more feedback on B.io on what should be improved as reporting website and doc-related issues will be easier.

<img width="1678" alt="Screenshot 2022-07-27 at 19 34 40" src="https://user-images.githubusercontent.com/11707273/181267536-54a94b97-62f0-4f07-ae2d-e545095b09cb.png">

[1] https://docs.docker.com/desktop/extensions-sdk/quickstart/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority
