### ISSUE TITLE
L5 headings are more significant than L4 headings

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4928]
## Description

$subject in [1]

[1] https://dev.ballerina.io/learn/test-ballerina-code/write-tests/#Values%20with%20different%20types

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/16300038/181423443-5403ea50-3292-4ed3-9762-7818877e0717.png">

**Comment by sm1990** [comment]
Fixed in https://dev.ballerina.io/
