### ISSUE TITLE
Suggestions to improve The Bindgen tool page

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4932]
## Description
This is a list of changes to improve [1]

[1] https://dev.ballerina.io/learn/java-interoperability-guide/the-bindgen-tool/#The%20bindgen%20command

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)

1. Change the introductory sentence as follows:

```suggestion
The `bindgen` tool is a CLI tool that generates Ballerina bindings for Java classes.
```

This is because:
1. We need to use "that" instead of "which" here. (see [2] for more information.
2. The "bidgen tool" is formatted in different ways in different places. Suggesting code format because I noticed it used more often. If the team has agreed on a different way of formatting, change as relevant.

2. In the **The bindgen command** section, let's use bullet points for each parameter, and give the description below the parameter name. This would make it easier for the users to select the commands to copy them if they wish to.

3. There is a lot of future tense used in this page. Can we convert it to present tense?

4. One sentence has the phrase "When referring to a Java code to figure out the imported classes". Is "a" needed here? Are you referring to a specific segment of code? Or is is a "Java class"?

5. In the sentence "E.g., the generated Ballerina class of the java.util.ArrayDeque class will be as follows.", the first letter after "E.g.," should be capital.

[2] [2] https://writing-fundamentals-guide.readthedocs.io/en/latest/lesson2-commas/#using-that-vs-which

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by praneesha** [comment]
1. Updated to `The Bindgen Tool is a CLI tool that generates Ballerina bindings for Java classes.`.
2. Updated all the occurrences to: `the Bindgen Tool` (without backticks as they are not supported on the description and intro in the front matter.
3. Added a table for more clarity.
4. Updated all the future tense occurrences to present tense.
5. Changed to `When referring to java code to figure out the imported classes,....`.
6. It shouldn't be capital. "E.g.," will basically translate to "For example," so the sentence has already started.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5049.
