### ISSUE TITLE
Suggestions for the Language basics page: Introduction

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4935]
## Description
Suggesting some improvements to the introductory sentence and the **Familiar subset of Ballerina** section of the Language basics page.

1. The introductory sentence and the **Familiar subset of Ballerina** section use two words (i.e., "page" and "guide") to refer to the same thing. Since "guide" is more commonly used in the website, shall we stick to that?

2. Suggesting simplifying the introductory sentence as follows:

```suggestion
This guide introduces the Ballerina language to help you get started with basics that are common to all C-Family programming languages.
```

A general question: Is it intentional that none of the examples given in the sub sections are described? For example in the ** Booleans and conditionals**, it does not have a description like  "`1` is printed when the `foo` parameter is flagged and `2` is printed when it is not.

## Affected version(s)
[> The versions that are affected by the issue.](https://dev.ballerina.io/learn/language-basics/#Familiar%20subset%20of%20Ballerina)

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
> Suggesting some improvements to the introductory sentence and the **Familiar subset of Ballerina** section of the Language basics page.
> 
> 1. The introductory sentence and the **Familiar subset of Ballerina** section use two words (i.e., "page" and "guide") to refer to the same thing. Since "guide" is more commonly used in the website, shall we stick to that?
> 2. Suggesting simplifying the introductory sentence as follows:
> 
> ```
> This guide introduces the Ballerina language to help you get started with basics that are common to all C-Family programming languages.
> ```

@praneesha, these are related to front matter. Will you be checking these? May have to check others too.

> 
> A general question: Is it intentional that none of the examples given in the sub sections are described? For example in the ** Booleans and conditionals**, it does not have a description like "`1` is printed when the `foo` parameter is flagged and `2` is printed when it is not.

I believe it is because it is self-explanatory and kinda aimed towards people who already know the basics of programming/a programming language. If we were to go into that level of detail, it may become lengthy and look crowded, IMO.

**Comment by praneesha** [comment]
1. Changed `page` to `guide` in the front matter. 
2. Updated the intro and description of the front matter with the given suggestion.
3. The general question is answered in https://github.com/ballerina-platform/ballerina-dev-website/issues/4935#issuecomment-1207755891.

**Comment by praneesha** [comment]
3. Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5076.
