### ISSUE TITLE
Suggestions for the Language basics page: Functions, Syntax, and Integers sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4936]
## Description
The following suggestions are for the **Functions**, **Syntax**, and **Integer** sections of [1]

[1] https://dev.ballerina.io/learn/language-basics/#Syntax

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
- In the **Functions** section, shall we change the last sentence as follows to avoid passive voice?

```suggestion
The `return` statement returns the value assigned to `**sum**`.
```

- In the **Syntax** section, the first sentence might sound too colloquial. Shall we change it as follows?

```suggestion
The overall syntax is C-like, where comments start with `//` and end at the end of the line.
```

- In the **Integer section**, shall we change the "The int keyword is used to declare an integer." as follows to avoid passive voice?

```suggestion
The `int` keyword declares an integer.
```

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
> * In the **Syntax** section, the first sentence might sound too colloquial. Shall we change it as follows?
> 
> ```
> The overall syntax is C-like, where comments start with `//` and end at the end of the line.
> ```

This is currently 

```
The overall syntax is pretty-much C-like.
```

Instead of removing "pretty-much", can we replace it with something else? Maybe "more or less"?

cc @praneesha

**Comment by MaryamZi** [comment]
> * In the **Integer section**, shall we change the "The int keyword is used to declare an integer." as follows to avoid passive voice?
> 
> ```
> The `int` keyword declares an integer.
> ```

This doesn't convey the same meaning. We are basically trying to say that when we are defining an integer variable we use the `int` keyword.

**Comment by praneesha** [comment]
1. Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5073/files.
2. Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5073/files.
3. Will not be changed as per https://github.com/ballerina-platform/ballerina-dev-website/issues/4936#issuecomment-1207763281.
