### ISSUE TITLE
Suggestions for the Language basics page: Floating point numbers and Booleans and conditionals sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4937]
## Description
The following suggestions are for the **Floating point numbers** and **Booleans and conditionals** sections of [1].

[1] https://dev.ballerina.io/learn/language-basics/#Floating%20point%20numbers

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

1. In the **Floating point numbers** section, shall we rephrase "Variables of the float type are declared with the float keyword and they support all operations similar to integers except bitwise operators." as follows?

```suggestion
The `float` keyword declares a variable of the `float` type that supports all operations that are similar to integers except bitwise operators.
```
2. In the **Booleans** section, sentences "Booleans are also used in conditional expressions like:" and "As usual, booleans can be used in if-else statements like:" may sound colloquial due to the word "like". Shall we change this section as follows?

```suggestion
You can use booleans in  `if-else` statements as well as conditional expressions.

In this example, a boolean is used in an  `if-else` statement:

<CODE_BLOCK>

In this example, a boolean is used in a conditional expression:

<CODE_BLOCK>
```

3. Shall we change "Curly braces are required in if-else statements and all compound statements in Ballerina." as follows to avoid passive voice?

```suggestion
You are required to use curly braces  in `if-else` statements and all compound statements in Ballerina.
```

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
> 1. In the **Floating point numbers** section, shall we rephrase "Variables of the float type are declared with the float keyword and they support all operations similar to integers except bitwise operators." as follows?
> 
> ```
> The `float` keyword declares a variable of the `float` type that supports all operations that are similar to integers except bitwise operators.
> ```

Kinda similar to https://github.com/ballerina-platform/ballerina-dev-website/issues/4936#issuecomment-1207763281

**Comment by MaryamZi** [comment]
> 3\. In the **Booleans** section, sentences "Booleans are also used in conditional expressions like:" and "As usual, booleans can be used in if-else statements like:" may sound colloquial due to the word "like". Shall we change this section as follows?
> 
> ```
> You can use booleans in  `if-else` statements as well as conditional expressions.
> 
> In this example, a boolean is used in an  `if-else` statement:
> 
> <CODE_BLOCK>
> 
> In this example, a boolean is used in a conditional expression:
> 
> <CODE_BLOCK>
> ```

Can't we just remove "like" from the sentences and leave the rest as is. Just wondering if with the suggestion there's some repetition.

**Comment by MaryamZi** [comment]
> 5\. Shall we change "Curly braces are required in if-else statements and all compound statements in Ballerina." as follows to avoid passive voice?
> 
> ```
> You are required to use curly braces  in `if-else` statements and all compound statements in Ballerina.
> ```

How about 

```
If-else statements and all compound statements in Ballerina require curly braces.
```

**Comment by MaryamZi** [comment]
Applicable changes were introduced in https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
