### ISSUE TITLE
Invalid content on page TOC

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4938]
## Description

$subject in [1]

[1] https://dev.ballerina.io/learn/generate-code-documentation/#Generate%20Ballerina%20documentation
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/16300038/181501160-004af081-fa8c-487a-ae75-03f9692c334d.png">

**Comment by YasithD** [comment]
Page Toc invalid content rendering fixed via #4975

**Comment by praneesha** [comment]
Closing as per the above comment.
