### ISSUE TITLE
Placement of version sementics of the specifications

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#4941]
## Description

We follow the highlighted pattern only for language specifications. So we need to move it under the language specification.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/16300038/181504020-539cdce8-716e-4299-939c-8dcc5e1c7ab3.png">

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/5014.
