### ISSUE TITLE
Suggestions for the Language basics page: Nil and Langlib functions sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4942]
## Description
These suggestions are for the **Nil** and **Langlib functions**  sections of [1]

[1] https://dev.ballerina.io/learn/language-basics/#Nil

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

1. In the **Nil** section, should not `nil` be in code format (same as `int`)?

2. In the **Nil** section, let's change the "Therefore, a function can be written as:" phrase as follows?

```suggestion
Therefore, you can write a function as follows:
```

3. Under **Langlib functions**, shall we change "the length of the string value can also be found" as follows to avoid passive voice?

```suggestion
you can find the length of the string value"

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
> 1. In the **Nil** section, should not `nil` be in code format (same as `int`)?

No, we emphasize only keywords, names of constructs, etc. `int` is a keyword, but nil isn't.

**Comment by MaryamZi** [comment]
Fixed the rest in https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
