### ISSUE TITLE
Suggestions for the Language basics page: Arrays and foreach statement sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4956]
## Description
The following suggestions are for the **Arrays** and **foreach statement** sections of [1].

[1] https://dev.ballerina.io/learn/language-basics/#Arrays

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)

1. In the **Arrays** section, shall we reword "Ordering is supported based on a lexicographical ordering of members." as follows if it is correct to avoid passive voice?

```suggestion
Ballerina supports ordering based on a lexicographical ordering of members.
```

2. In the **foreach statement section**, shall we rephrase "The foreach statement can also be constructed using a range expression such as" as follows to avoid passive voice?

```suggestion
You can construct the foreach statement using a range expression such as ` ..<`.
```

3. In the **foreach statement section**, shall we rephrase the last paragraph as follows to avoid passive voice and to change "ranges" to "range"? About the latter, this correction needs to be made because this verb applies to "numbers" rather than "sequence".

```suggestion
The above statement sets the `i` variable of the `int` type to a sequence of linearly incrementing numbers that range from zero to the length of the array `v`. Therefore, the `foreach` statement iterates over the length of the array and increments `i` during each iteration.
```

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
