### ISSUE TITLE
Suggestions for the Language basics page: Maps and Structural typing sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4957]
## Description
The following suggestions are for the **Maps** and **Structural typing** sections of [1].

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)

1. In the **Maps** section shall we change "The use of comparison operators == and != on a map will perform a deep comparison." as follows to simplify it? Please ignore this suggestion if it changes the meaning.

```suggestion
You can perform a deep comparison by using the `==` and `!= ` comparison operators on a map.
```

2. In the **Structural typing** section, shall we reword "In this way, the universe of all values is partitioned into the basic types supported by Ballerina such as nil, boolean, integer, floating point, and string." as follows if it gives the same meaning?

```suggestion
Ballerina partitions the universe of all values into the basic types it supports such as  nil, boolean, integer, floating point, and string.
```

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
