### ISSUE TITLE
Suggestions for the Language basics page: Union and Error Reporting  sections

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4958]
## Description
In the **Union** and **Error Reporting** sections of [1], the following was noted:

 The sentence "You have already seen this with the T? notation where a variable of type T? can hold a value of type T or nil." assumes that the user has read this information somewhere, which may not be the case. It is better to avoid phrases such as "You have already seen this" and link to the relevant section instead.

```suggestion
 A variable of type T? can hold a value of type T or `nil` as explained in <LINKED_TEXT>.
```

2. In the Error Reporting section, shall we reword the following section to avoid passive voice and use "that" instead of "which" where relevant?

"There are a few mechanisms for handling errors, which are centered around an error type. The error type is a basic type in Ballerina, and error values can be passed around just like values of any other type."

```suggestion
Ballerina supports a few mechanisms that are centered around error types to handle errors. The error type is a basic type in Ballerina. This allows Ballerina programs to pass around error values the same way they pass values of any other type.
```

This section has a few other instances where passive voice is used. Let's try to minimise it as much as possible.

[1] https://dev.ballerina.io/learn/language-basics/#Unions

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Suggested label(s) (optional)
BallerinaRewrite

**Comment by MaryamZi** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/5073.
