### ISSUE TITLE
Suggestions for the Language basics page: check expression section

### ISSUE THREAD

**Issue by RukshiW** [ballerina-platform/ballerina-dev-website#4959]
## Description
The **check expression** section of [1] is unclear. 

[1] https://dev.ballerina.io/learn/language-basics/#Error%20handling

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)

1. "Instead of using the is operator within the regular conditional flow to check for errors, Ballerina has a shorthand method available. Using the check keyword, error handling and return statements are much more concise." Regarding this section, is using the `check` keyword the shorthand method? If so, can we rephrase this section as follows:

```suggestion
Instead of using the is operator within the regular conditional flow to check for errors, Ballerina allows you to use the `check` keyword. This allows you to define `return` statements in a more concise manner.
```

2. "So the intFromBytes() function defined in the previous section can now be written as:"

Although the section you are referring to is immediately before this section, it is a better practice to refer to the section by the name and link it via a bookmark.

```suggestions
For example, you can write the `intFromBytes()` function defined in the [Error handling](#error-handling) as follows:
```

3. "In this case, the expression following the check keyword is evaluated and the intFromBytes function returns immediately if the string:fromBytes() function returns an error."

Here, it is not clear what the `intFromBytes` function returns. 

## Suggested label(s) (optional)
WebsiteRewrite

**Comment by MaryamZi** [comment]
> 1. "Instead of using the is operator within the regular conditional flow to check for errors, Ballerina has a shorthand method available. Using the check keyword, error handling and return statements are much more concise." Regarding this section, is using the `check` keyword the shorthand method? If so, can we rephrase this section as follows:
> 
> ```
> Instead of using the is operator within the regular conditional flow to check for errors, Ballerina allows you to use the `check` keyword. This allows you to define `return` statements in a more concise manner.
> ```

How about 

```
Instead of using the ``is`` operator within the regular conditional flow to check for errors, Ballerina supports the ``check`` keyword as a shorthand method. Error handling and return statements become much more concise when using the ``check`` keyword.
```

**Comment by praneesha** [comment]
The above are addressed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5073/files.
