### ISSUE TITLE
Jump to section by clicking any heading in the left side navigation bar

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-dev-website#4969]
## Description
> A brief description of the improvement.

Currently when I click on a heading in the left side navigation bar which has subsections or subpages,  I can't jump to that section/page (the place where the heading starts) by clicking that heading. It only expands and collapses.

Eg:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/33286289/182092346-9a84321e-e644-49e5-9f61-e34ec302fad1.png">
In the above learn page only the H3 headings would take me the relevant section when clicking.

So the improvement suggestion is for those types of headings is:
to expand or collapse only when a user clicks on the up/down icon next to the heading. Otherwise jump to the section of that heading.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

Area/UIUX

**Comment by sm1990** [comment]
The issue will be fixed in the new website rewrite.
