### ISSUE TITLE
News letter subscription section not displayed correctly

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-dev-website#5018]
## Description
Chrome:
![image](https://user-images.githubusercontent.com/1496990/182625465-62418ff6-e3c6-4aa3-8a99-a81533293bbe.png)

Firefox:
![image](https://user-images.githubusercontent.com/1496990/182625700-62af0502-e16b-4006-b1bc-928f3fed8985.png)

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
@rdhananjaya - This should be a network connectivity issue as the forms in both pages [1] and [2] load fine for me as shown below.

<img width="1354" alt="Screenshot 2022-08-04 at 15 55 59" src="https://user-images.githubusercontent.com/11707273/182826290-535dd027-8ec3-40e2-a739-c815ef372a40.png">
<img width="1324" alt="Screenshot 2022-08-04 at 15 56 10" src="https://user-images.githubusercontent.com/11707273/182826297-dea17f47-8543-4389-a5f9-319897379241.png">

Please reopen if the issue persists.

[1] https://ballerina.io/community/
[2] https://ballerina.io/community/ballerina-newsletter/
