### ISSUE TITLE
Add learn examples for rollback statement 

### ISSUE THREAD

**Issue by gayalkuruppu** [ballerina-platform/ballerina-dev-website#5064]
## Description
> In rollback learn [page](https://ballerina.io/learn/by-example/rollback.html) the example contains a scenario of a implicit rollback but I could not find an example which uses the `rollback` keyword.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs
Area/LearnPages

## Describe the problem(s)
> $Description

## Describe your solution(s)
> Add learn example or improve existing to explain the usage of `rollback` keyword.

**Comment by gimantha** [comment]
PR merged : https://github.com/ballerina-platform/ballerina-distribution/pull/3098
