### ISSUE TITLE
The "Play" buttons on the videos on the landing page are jumbled

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#5099]
## Description
>  $subject 

## Steps to reproduce
> Open home page in safari browser

**Comment by praneesha** [comment]
Fixed in the Safari browser as shown below.

<img width="1680" alt="Screenshot 2022-08-17 at 14 12 45" src="https://user-images.githubusercontent.com/11707273/185075169-ed91ab03-354d-430e-a8ee-38d73969bd56.png">

**Comment by praneesha** [comment]
Reopening to test the responsiveness of the UI.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5547.
