### ISSUE TITLE
Add a BBE to show SQL column mapping

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#5145]
## Description
We can specify the column names when a Ballerina record is mapped to a database row as below:
```
type User record {|
    // No change in column name
    string id;
    @sql:Column {name: "first_name"}
    string firstName;
|};
```
Right now, there's no BBE showing this capability. Can we add one?

**Comment by IMS94** [comment]
Corresponding stdlib issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2652

**Comment by niveathika** [comment]
This is already added with Update 2 BBE revamp. https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/mysql-query-column-mapping/mysql_query_column_mapping.bal
