### ISSUE TITLE
Ballerina Playground outputs `A new version of Ballerina is available` log in the top of the program execution results

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-dev-website#5149]
The following text will output in the Ballerina playground just before the program execution results.
```
A new version of Ballerina is available: 2201.1.1
Use 'bal dist pull 2201.1.1' to download and use the distribution
```

![Screenshot 2022-08-15 at 15 46 38](https://user-images.githubusercontent.com/47134066/184618347-f5c74e5c-988a-42ed-8aa1-697b1bea4972.png)

**Comment by SasinduDilshara** [comment]
However, if we run the following code in the playground, then it does not show the above log.
```
import ballerina/io;

public function main() {
    io:println("Hello world");
}
```

**Comment by anupama-pathirage** [comment]
Closing as this has happened due to late update of playground to latest version and not appearing now.
