### ISSUE TITLE
Remove the BBE Go Tool from the `ballerina-release` repo

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5152]
## Description
After the new BBE implementation is published live on the new site, need to remove the BBE gen Go Tool from the `ballerina-release` repo and from all of its other occurrences.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

Area/Backend

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by keizer619** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-release/pull/2115

**Comment by anupama-pathirage** [comment]
Closing as done in above PR
