### ISSUE TITLE
Automate the BBE on-demand workflow

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5153]
## Description
When the new BBE implementation is published live on the new site and when the trigger[1] for this workflow is also implemented, need to update its automation by adding the corresponding branches properly.

[1] [https://github.com/ballerina-platform/ballerina-dev-website/issues/5151](https://www.google.com/url?q=https://github.com/ballerina-platform/ballerina-dev-website/issues/5151&sa=D&source=docs&ust=1660564040908588&usg=AOvVaw2ssllVxLcjqmIPOlkXX7GQ)
[2] https://github.com/ballerina-platform/ballerina-dev-website/blob/website-revamp/.github/workflows/ballerina_by_example_auto_update.yml

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
We can use the existing workflows to generate BBEs on demand from any branch in distribution.
