### ISSUE TITLE
Rewrite the link checker workflow for NextJS

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5175]
## Description
Need to remove the Jekyll build action and rewrite the link checker[1] workflow for NextJS. It was simplified to just pass via [2] until the `website-revamp` branch was synced with the `master` branch as it was failing due to the Jekyll build references.

[1] https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/add_link_checker.yml
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/5157/commits/454fc74e36cbbefdf24007d81795af4c70baf72c

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/Workflows

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by keizer619** [comment]
will be addressed by this https://github.com/ballerina-platform/ballerina-dev-website/issues/5552
