### ISSUE TITLE
Auto update pre-prod site with master branch

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5190]
## Description
Need to automate the updating of the pre-prod site when changes are merged to the master branch of the dev website repo.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/Backend

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
`ghpages` of the pre-prod to `ghpages` of the live is the only workflow needed now.

**Comment by sm1990** [comment]
Fixed via #5565
