### ISSUE TITLE
Update the `Ballerina In Action` workflows for the new site

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5191]
## Description
Need to fix and update the `Ballerina In Action` workflows for the new site. Currently, the checks of them on the PRs are failing.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/HomePageSamples

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by udda1996** [comment]
Closing since this is fixed with [this](https://github.com/ballerina-guides/ballerina-in-action-samples/pull/2).
