### ISSUE TITLE
Add new lines on the BBE `.out` files

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5277]
## Description
Currently, the new lines added on the BBE source are not rendered on the BBE `.out` files as shown below. This is because the BBE gen tool reads line-by-line and ignores the new lines. We need to fix this.

**BBE source:**
<img width="441" alt="Screenshot 2022-08-20 at 09 23 19 (1)" src="https://user-images.githubusercontent.com/11707273/185772040-1adf9407-3921-408b-8d96-6a75ac6c9ff6.png">

**BBE `.out` file displaying**
<img width="1318" alt="Screenshot 2022-08-18 at 16 30 42 (1)" src="https://user-images.githubusercontent.com/11707273/185772030-1682e071-3e60-424d-80b9-1faf6711041e.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5285.

**Comment by Ibaqu** [comment]
This issue has since been fixed and is live. Hence closing
