### ISSUE TITLE
Remove breadcrumbs on the blog

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5278]
## Description
Need to remove breadcrumbs from the blog also to be consistent with the other components of the website?

<img width="1256" alt="Screenshot 2022-08-20 at 06 59 45" src="https://user-images.githubusercontent.com/11707273/185772065-2aea46b7-db86-4196-845b-4ba2652b3fb7.png">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://blog.ballerina.io/
