### ISSUE TITLE
Installing sections on different OSs are not similar

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#528]
**Description:**
We have 3 sections under "[Installing Ballerina via Installers](Installing Ballerina via Installers)" section. 

"Installing on OS x" and "Installing on Windows" has followed a same pattern and similar wordings. But "Installing on Linux" is completely different.

Ex: 
First two has used the file type and the last one asks to download the latest version. First two don't have bullets but the last one has used bullets to present a similar information.
<img width="718" alt="image" src="https://user-images.githubusercontent.com/16300038/81399996-bb587c80-9149-11ea-8475-e59c6e8c8e43.png">

Since they are related topics make all of them consistent.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Yes we might need to change it something like "Download the DEB file or RPM file"
