### ISSUE TITLE
Incorrect link to language walkthrough video and slides

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#5286]
## Description
$subject as both the buttons are linking to the page top instead of each section. We need to have two sub titles in the page [1] and then point to each of them from the landing page buttons. 

[1] https://ballerina.io/learn/language-walkthrough/

 
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/16300038/185888232-d3f6b018-ba9b-48a3-aa6f-875dd34709e1.png">

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/
