### ISSUE TITLE
Search in the new website is redirected to BBE home page

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-dev-website#5306]
## Description

Searching a BBE in the new website is redirected to new BBE home page rather than the actual BBE

## Steps to reproduce

See the following recording :

https://user-images.githubusercontent.com/63336800/186074142-23ef7884-ee8f-4be4-81f7-f3ac5a6c12d8.mov

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5311
