### ISSUE TITLE
Add RSS Feed to Ballerina Blog

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#531]
**Description:**
Based on a request on Twitter to add an RSS feed to help them track progress.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Thimuth** [comment]
Add the feed link https://blog.ballerina.io/feed.xml to the website layout
