### ISSUE TITLE
Blockquotes in BBE are not rendering correctly

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#5342]
## Description
> $subject

**Comment by praneesha** [comment]
Blockquotes are not rendered properly in BBEs as shown below.

<img width="1672" alt="Screenshot 2022-08-24 at 14 22 42" src="https://user-images.githubusercontent.com/11707273/186442508-51497ec0-2978-4002-bc39-a8959a3f50d6.png">

They should be rendered correctly as shown below.

<img width="1672" alt="Screenshot 2022-08-24 at 14 22 42" src="https://user-images.githubusercontent.com/11707273/186442590-42da2f4c-09c3-4af6-b585-b649004b11f4.png">

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/learn/by-example/raw-templates/
