### ISSUE TITLE
List items not rendering properly in BBEs

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#5344]
## Description
> $subject

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Numbered bullet points are not rendered properly as shown below.

<img width="1669" alt="Screenshot 2022-08-24 at 14 25 34" src="https://user-images.githubusercontent.com/11707273/186441998-2aad63b1-56fb-4ebc-8548-b27184c56572.png">

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/learn/by-example/providing-services/
