### ISSUE TITLE
Indent Elements after bullet points

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5351]
## Description
Need to indent all elements that are added after numbered / unordered bullet lists in BBEs.

<img width="1671" alt="Screenshot 2022-08-24 at 21 34 04" src="https://user-images.githubusercontent.com/11707273/186467641-16767d5d-cbe4-417f-8822-f57530e82f8b.png">

This is done correctly in learn pages as shown below. For example, see [1].

<img width="1672" alt="Screenshot 2022-08-24 at 21 36 03" src="https://user-images.githubusercontent.com/11707273/186468149-e4003ee9-12b9-49d3-a2cc-6b80ca060014.png">

[1] https://ballerina.io/learn/observe-ballerina-programs/
## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/
