### ISSUE TITLE
Unnecessary - in blog.ballerina.io title

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#5354]
## Description
> Unnecessary - in blog.ballerina.io title

<img width="424" alt="Screenshot 2022-08-25 at 12 18 25" src="https://user-images.githubusercontent.com/2918812/186594786-e2464fa9-acbf-4391-a493-8e65a6d2faab.png">

**Comment by sm1990** [comment]
Fixed in https://blog.ballerina.io/
