### ISSUE TITLE
Downloads page does not contain the ZIP file of the latest Ballerina version

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-dev-website#5355]
## Description
> [Ballerina.io downloads page](https://ballerina.io/downloads/) does not have the ZIP archive of the latest Ballerina version (`2201.1.1`).
And it looks like the link to the Zip file installation guide also not working.
![Screenshot from 2022-08-25 17-28-50](https://user-images.githubusercontent.com/35595065/186660007-63aedb0f-110f-466e-a98e-5296ac30ab55.png)

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

**Comment by sm1990** [comment]
Fixed the broken links except the link to download zip.asc. It will be handled via #5362.

**Comment by praneesha** [comment]
Closing as per the above comment.
