### ISSUE TITLE
Link for more download options is broken on website

### ISSUE THREAD

**Issue by shaikan** [ballerina-platform/ballerina-dev-website#5385]
## Description
> The download link after "For more download options, see" on https://ballerina.io/learn/install-ballerina/set-up-ballerina/ page is broken/ wrong it points to https://ballerina.io/download/ which results in 404 error while the actual link should be https://ballerina.io/downloads/

## Steps to reproduce
> Go to https://ballerina.io/learn/install-ballerina/set-up-ballerina/  page and click on the Download link after "For more download options, see" 

## Affected version(s)
> ballerina.io website
## Related website/documentation area
https://ballerina.io/learn/install-ballerina/set-up-ballerina/

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/learn/install-ballerina/set-up-ballerina/
