### ISSUE TITLE
Links in observability BBEs does not work

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-dev-website#5391]
## Description
https://ballerina.io/learn/by-example/tracing/  when you click observe ballerina code link, it redirect to 404 page. same with other observability samples as we..

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3157/files.

**Comment by praneesha** [comment]
Fixed via the above PRs.
