### ISSUE TITLE
Incorrect image in the Java interoperability guide

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#5398]
## Description
In the description of the Java interoperability it explains about the `FFI` layer. But in the diagram it shows `FEI` layer. 
[Link](https://ballerina.io/learn/java-interoperability-guide/java-interoperability/)

**Comment by sm1990** [comment]
Fixed in pre-prod (https://pre-prod.ballerina.io/learn/java-interoperability-guide/java-interoperability/)
