### ISSUE TITLE
Content issues in the "Installing Ballerina" learn page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#540]
**Description:**
Few issues as below.

1. Some text which is within the angle brackets are missing.

- The text "<BALLERINA_PROJECT_ROOT>" is missing in the 1st point of "Building the Source" sub topic.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/16300038/81540300-116a3180-938f-11ea-8cb8-2834f9ae6c4a.png">

- The text "<YOUR-GITHUB-USERNAME>" is missing in the "Tip" of the "Obtaining Source Code" section.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/16300038/81549172-f225d100-939b-11ea-9bb9-1b6ae9c7250d.png">

2. Shall we change the link text "Setting up IntelliJ" at the bottem of the page to "Setting up IntelliJ IDEA"
<img width="713" alt="image" src="https://user-images.githubusercontent.com/16300038/81540088-c3552e00-938e-11ea-89c4-6e1b0b539b36.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/537.
