### ISSUE TITLE
Link in configurable BBE broken

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#5408]
https://ballerina.io/learn/by-example/configurable-variables/

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3157/files.

**Comment by pubudu91** [comment]
Can we please double check the links in all the BBEs? Didn't we have an automated checker for broken links? So far 2 out 2 BBEs I came across had broken links in them.

**Comment by praneesha** [comment]
> Can we please double check the links in all the BBEs? Didn't we have an automated checker for broken links? So far 2 out 2 BBEs I came across had broken links in them.

Unfortunately, the link checkers do not catch these broken links on BBEs as shown below. Therefore, we will check them manually.

<img width="1134" alt="Screenshot 2022-09-02 at 11 44 12" src="https://user-images.githubusercontent.com/11707273/188085529-4559cd62-95f2-4eab-a37c-61bc8a752916.png">
