### ISSUE TITLE
Update the "Installing Ballerina" page with the new changes on directories

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#542]
**Description:**
All the installation locations mentioned in the "Installing Ballerina via installers" section and "Uninstalling Ballerina" section are still not updated with the recent chagnes done for the installation locations. 

For ex in mac : It is given as `/Library/Ballerina` , but it should be `/Library/Ballerina/distributions/jballerina-x-x-x`

**Comment by praneesha** [comment]
@keizer619 - Can you provide the list of all changes that were done?

**Comment by keizer619** [comment]
@anupama-pathirage 
I am thinking whether is it possible to leave it as removing `/Library/Ballerina` directory?
Removing that directory clean the whole installation (multiple jballerina versions)

We can think of a way to incorporate `ballerina dist remove` to remove each jballerina version from the `/Library/Ballerina/distributions/`

**Comment by praneesha** [comment]
@keizer619 @hevayo - What are the other installation directories that got changed as @anupama-pathirage mentioned?

**Comment by anupama-pathirage** [comment]
> @anupama-pathirage
> I am thinking whether is it possible to leave it as removing `/Library/Ballerina` directory?
> Removing that directory clean the whole installation (multiple jballerina versions)

@keizer619 It is ok. But IMO, we need to specifically say it in this doc (removing `/Library/Ballerina` directory will delete multiple ballerina versions). Otherwise, users will get confused on whether to delete whole `/Library/Ballerina` directory or one directory within the `distributions` folder.
> 
> We can think of a way to incorporate `ballerina dist remove` to remove each jballerina version from the `/Library/Ballerina/distributions/`

**Comment by praneesha** [comment]
The above points are addressed in https://github.com/ballerina-platform/ballerina-dev-website/pull/652.
