### ISSUE TITLE
Check whether the Ballerina code snippets are formatted properly in Guides

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-dev-website#5423]
## Description
Some code snippet are not properly formatted as suggested by VS Code. It is good to have the consistency in every page of the website and follow the VSCode formatting rules.

Example: 
![image](https://user-images.githubusercontent.com/9362271/188138392-43c77362-1378-43aa-942f-0abd481e11d3.png)

If this would have been formatted using VSCode, there should be `[1, 2, 3]` not `[1,2,3]`

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@gimantha @praneesha the space should be added in the markdown.

**Comment by praneesha** [comment]
@MaryamZi - Shall we review all the code snippets on the same?

**Comment by MaryamZi** [comment]
We will work on this in an upcoming sprint. Reduced the priority since it isn't a blocker (not invalid code).

**Comment by sm1990** [comment]
This was fixed via #5710
