### ISSUE TITLE
Issues in configurable related learn pages

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#5424]
In the following, 3rd point is misleading. It tells to create the Config.toml in the package root directory when in reality it should be the current working directory. This is an issue when you create a Config.toml file in the package root and try to run it using `bal run` from outside the package root.
https://ballerina.io/learn/configure-ballerina-programs/configure-a-sample-ballerina-service/

In https://ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/, there's a sentence: 

>  If an environment variable is not specified, the file will be located in the current working directory with the file name Config.toml by default.

This needs to be rephrased a bit. Maybe something like: *If an environment variable is not specified, the file needs to be located in the current working directory with the file name Config.toml*
or: *If an environment variable is not specified, it will look for a file named Config.toml in the current working directory*.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5438.
