### ISSUE TITLE
Inconsistencies in page titles and links

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#544]
**Description:**
In the learn page navigation links and page topics we haven't follow the same topics/wordings

For ex: 

[VS Code plugin page](https://ballerina.io/learn/vscode-plugin/) [1] has the topic as "The Visual Studio Code Extension" and the left side navigation bar link has the text as "Setting up Visual Studio Code" and the "What's next" section of "[Installing Ballerina](https://ballerina.io/learn/installing-ballerina/)" page has linked the same page with the text "Setting up VS Code". IMO, we should have a single topic in all these places. 

<img width="972" alt="image" src="https://user-images.githubusercontent.com/16300038/81557166-25bb2800-93a9-11ea-9e08-310c9bcaa448.png">

<img width="623" alt="image" src="https://user-images.githubusercontent.com/16300038/81557219-39668e80-93a9-11ea-851d-4579f34c0ab2.png">

Check for other topics too. 

[1] https://ballerina.io/learn/vscode-plugin/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Is there a strong reason why we should have the same in the title and the menu?

Currently, the left nav is organized in a way to start with an "ing" verb, which is a common best practice in navigation menus.

Also, as per @Samallama, there is an SEO aspect of having the same URL and the title of the page. Therefore, if we need to change the title, then we need to change all the MD files also.

I think it is fine to have the flexibility in having a title, which is different to the left nav menu item.

**Comment by anupama-pathirage** [comment]
> Is there a strong reason why we should have the same in the title and the menu?
> 
IMV if we have a similar name it is easier to follow the content. Otherwise having different texts in different links gives the impression that we are referring to different pages. 

> Currently, the left nav is organized in a way to start with an "ing" verb, which is a common best practice in navigation menus.
> 
> Also, as per @Samallama, there is an SEO aspect of having the same URL and the title of the page. Therefore, if we need to change the title, then we need to change all the MD files also.

What do you mean by the URL here?
> 
> I think it is fine to have the flexibility in having a title, which is different to the left nav menu item.

**Comment by Samallama** [comment]
The URL and the title of the page should be the same for SEO purposes. And I think like Anupama mentioned it's better to have the left nav title the same as well, it makes more sense that way. Either we should rename the left nav titles to the page titles, or rename the page titles and URLs to match the left nav.

And in future, we should keep in mind what we want the left nav to look like when naming these pages.

**Comment by praneesha** [comment]
+1 Will change the left nav to match the page titles as that is the easier solution rather than changing the name of the MD files will require doing a lot of redirections in the URLs.
