### ISSUE TITLE
Remove the empty line at the top of BBE code snippets and files

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5440]
## Description
Need to remove the empty line at the top of BBE code snippets as shown below.

<img width="1680" alt="Screenshot 2022-09-05 at 22 16 44" src="https://user-images.githubusercontent.com/11707273/188491379-6a3ba0f3-581d-4fc1-9308-4e2e556ae2a1.png">

We need not keep a new line for the button panel or the copy option of code snippets. For example, see https://play.kotlinlang.org/byExample/01_introduction/04_Null%20Safety.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@praneesha that is not an empty line. The copy & github buttons are loaded there in a separate div above the code. We cannot load the buttons parallelly as it might overlap the code.

**Comment by praneesha** [comment]
@sm1990 - Can we have the buttons aligned with the first line of the code as shown below?

<img width="1114" alt="Screenshot 2022-09-07 at 21 46 04" src="https://user-images.githubusercontent.com/11707273/188928927-8d77caab-947c-40b7-b2b8-28ffdd21f664.png">

**Comment by sm1990** [comment]
@praneesha if the 1st line is too long, the icons will overlap the code. In most cases, this might work on desktop view but will break on mobile view.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority
