### ISSUE TITLE
Add a run option for the output of the BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5441]
## Description
We can give the command in a separate box and give a run button in it so that the output will be displayed only when the run button is clicked. The `Open in playground` option will be separate.

This will eliminate the need to add the $sign to the command and issues related to vomiting it when copying the command as per [1].

For example, see [2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/3962
[2] https://play.kotlinlang.org/byExample/01_introduction/04_Null%20Safety

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Omiting the `$` sign when copying the command is done. 
Also, it is good to show output even before running it. 
So closing this issue as invalid.
