### ISSUE TITLE
Instructions on reporting issues is poor

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#5450]
See the report issues section in https://ballerina.io/community/

This section should have more detailed information on where to create issues for different aspects of Ballerina. e.g.,
- For lang issues, should be the lang repo
- For language design level issues, should be the spec repo
- For std lib issues, should be the common standard lib repo
- For website, the website repo
- For Central, the central repo

Currently it just has a link to the lang repo.

**Comment by praneesha** [comment]
Closing as this is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/5420.
