### ISSUE TITLE
Remove new line spacing on spec TOC titles

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5454]
## Description
Remove the new line spacing below on spec TOC titles. For example, see [1].

<img width="287" alt="Screenshot 2022-09-07 at 12 48 33 PM" src="https://user-images.githubusercontent.com/11707273/188863678-856e747b-5ff8-454e-baf9-63dafcc34672.png">

[1] https://ballerina.io/spec/auth/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/spec/auth/
