### ISSUE TITLE
Ballerina By Example pages showing HTML code in text

### ISSUE THREAD

**Issue by Akshay-De-Silva** [ballerina-platform/ballerina-dev-website#5467]
## Description
HTML code showing in some of the ballerina by examples pages

## Steps to reproduce
Access the following pages on Ballerina By Example:
https://ballerina.io/learn/by-example/isolated-functions/
https://ballerina.io/learn/by-example/combining-isolated-functions-and-lock/
https://ballerina.io/learn/by-example/isolated-variables/
https://ballerina.io/learn/by-example/isolated-methods/
https://ballerina.io/learn/by-example/isolated-objects/
https://ballerina.io/learn/by-example/inferring-isolated/

## Affected version(s)
Tested on both Firefox,Opera browsers and on Ubuntu and Windows 10. Both have this issue

Screenshot of Issue:
![Screenshot from 2022-09-09 13-56-48](https://user-images.githubusercontent.com/78898161/189306823-40ac2c54-3561-4cdc-8865-1ef0ee79f7bf.png)

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/
