### ISSUE TITLE
Image rendering issue in grpc tutorial

### ISSUE THREAD

**Issue by menakaj** [ballerina-platform/ballerina-dev-website#5476]
## Description
> A brief description of the bug.

The diagram is rendered very large and it overflows the page and the right menu.

https://ballerina.io/learn/write-a-grpc-service-with-ballerina/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@menakaj could you please share the resolution of your display where you are experiencing the above.

**Comment by sm1990** [comment]
Fixed via #5509
