### ISSUE TITLE
Serdes BBE should be under `Network Libraries` section 

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-dev-website#5504]
## Description

In the [live website](https://ballerina.io/learn/by-example/) the serdes BBE is under a new section called `Working over the network` but it should be under `Network Libraries`. 

## Steps to reproduce

See the screenshot below :

![Screen Shot 2022-09-13 at 1 31 16 PM](https://user-images.githubusercontent.com/63336800/189848470-9f0188bf-fcda-4f7b-ab2a-a4ee8ef58568.jpg)

## Related website/documentation area

Area/BBEs

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3204
.
