### ISSUE TITLE
Website search does not suggest newly added BBEs

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-dev-website#5505]
## Description

When I search `interceptor` in the search bar it suggests the [`Request Interceptor` BBE](https://ballerina.io/learn/by-example/http-request-interceptors/). But when I search for `constraint` or `serialization` I could not get any link to the following newly added BBEs. The BBEs consist the exact words in them.

1. [Constraint BBE](https://ballerina.io/learn/by-example/constraint-validations/)
2. [SerDes BBE](https://ballerina.io/learn/by-example/serdes-simple/)

## Steps to reproduce

Search for `constraint` or `serialization` in the website

## Related website/documentation area

Area/BBEs

**Comment by sm1990** [comment]
@TharmiganK the algolia scheduled crawler ran few hours before the new BBEs went live. They will be added once the crawler runs again.

**Comment by praneesha** [comment]
Will be addressed via https://github.com/ballerina-platform/ballerina-dev-website/issues/5944.
