### ISSUE TITLE
Typo error in the `Table syntax` BBE.

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#5526]
## Description
$subject.

## Steps to reproduce
![Screenshot 2022-09-20 at 10 11 38](https://user-images.githubusercontent.com/46857198/191169133-6e3e64f1-a639-48c2-aafe-ec784a9a2b33.png)

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/learn/by-example/table-syntax/
