### ISSUE TITLE
Add redirections to bBE links with `.html`

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5551]
## Description
As we have had all the BBE links with the `.html` prefix appended at the end before the rewrite we should add a redirection now for them.

This is important as now they have already been crawled affecting SEO negatively by breaking g them now and also because they are added in external publications.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed in https://pre-prod.ballerina.io/
