### ISSUE TITLE
Find a link checker to check all links including BBEs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5552]
## Description
Currently, broken links in BBEs are not being captured by online link checkers. We need to evaluate an offline link checker such as Integrity, and write a workflow to automate checking the links at the PR-level.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Can consider checking on using https://github.com/tcort/markdown-link-check.

**Comment by keizer619** [comment]
New link checker has been included
https://github.com/ballerina-platform/ballerina-dev-website/actions/workflows/add_link_checker.yml
