### ISSUE TITLE
Incorrect output is displayed on backtick templates BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#5553]
## Description
The displayed output is incorrect in [1] as back tick is missing

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/16300038/191819226-816f0f41-c10c-4b48-a9f7-fcecd95928e5.png">

[1] https://ballerina.io/learn/by-example/backtick-templates/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed via #5580
