### ISSUE TITLE
Update learn pages with the new changes in GraphQL Tool client generation

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#5557]
## Description
There are some changes related to the client generation in GraphQL Tool with this [PR](https://github.com/ballerina-platform/graphql-tools/pull/94). These changes have to be updated in the learn page content in https://ballerina.io/learn/graphql-client-tool/. 

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/5611.
