### ISSUE TITLE
`Edit on Github` button  is not worked on some BBEs

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-dev-website#5585]
## Description
> Some BBEs in Ballerina By Examples gives `page 404` error with `The 'ballerina-platform/ballerina-distribution' repository doesn't contain the 'examples/tuples' path in 'v2201.2.0'` for `Edit on Github` button.

ex:- Tuple BBE
    :-  Destructure Tuple BBE
    :-  Rest Type in Tuple
    :- Array/Map Symmetry
    :- Interface to External Code

**Comment by praneesha** [comment]
Need to implement the logic to redirect the edit option URL to the master branch when the URL with the release tag gives a 404 error.

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/
