### ISSUE TITLE
Improve UX in ballerina by example website

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-dev-website#5586]
After navigating to a new example page by clicking the left hand side menu, the left hand side scroll bar scrolls up Automatically.
It will decrease the user experience because, the clicked topic will appear in the bottom of the lefthand side scrollbar. 

https://user-images.githubusercontent.com/47134066/192964270-0c9c50c0-19d0-4312-a661-3f356f7a51b6.mov

**Comment by atharva3333** [comment]
Hey maintainers, I'm working on this issue

**Comment by sm1990** [comment]
@atharva3333 Thank you very much for your contribution.

**Comment by sm1990** [comment]
@atharva3333 we are currently hosting a `Ballerina Hacktoberfest`. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. :smile:
