### ISSUE TITLE
Investigate the possibility of linking API docs from Ballerina central

### ISSUE THREAD

**Issue by nilminiwso2** [ballerina-platform/ballerina-dev-website#5589]
## Description
Ballerina Central [1] could have a more prominent link to the Stdlib API docs. Currently, we have API doc links under each package [2].

[1] https://central.ballerina.io/
[2] https://central.ballerina.io/ballerinax/twitter

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following.

**Comment by praneesha** [comment]
Each module has a link to go to the respective API Docs of it. If we add a link to the `lib.ballerina.io` home page from Ballerina Central, it will confuse users of third-party central modules as we do not have API Docs of them listed on the home page of `lib.ballerina.io`. The doc architecture followed here is that we have the home page designed only for API Docs of the modules managed by Ballerina (i.e., lang, standard library, and BallerinaX) and we are providing only the API Docs hosting (without listing them on the home page) for the third-party central modules.
