### ISSUE TITLE
Mobile nav doesn't show up fully

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#5626]
![Screenshot_20221007-183304.png](https://user-images.githubusercontent.com/11285165/194560383-84354b25-e4f6-49d0-8f54-fea05b81bd17.png)

As in the above screenshot, the mobile nav height is very low and it makes me want to scroll for menu items. Can we increase the height?

**Comment by sm1990** [comment]
@IMS94 did you check the search function using the mobile resolution simulator in desktop? Sometimes it does not work in the simulator. However, it works in the actual mobile device.

**Comment by IMS94** [comment]
@sm1990 I tried this on my phone. Seems like the search is working fine. Could have been an issue with the touch earlier.

However we should fix the mobile nav height

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/
