### ISSUE TITLE
Redesign the Release Notes page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5627]
## Description
Redesign the release notes page to have a nested view with the patch releases listed under the main update releases as follows.

- 2201.0.0 (Swan Lake)
      - 2201.0.1 
      - 2201.0.2
      - 2201.0.3
      - 2201.0.4
      - 2201.0.5
- 2201.1.0 (Swan Lake Update 1)
      - 2201.1.1
      - 2201.1.2
- 2201.2.0 (Swan Lake Update 1)
      - 2201.2.1
## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as this is not a priority

**Comment by Murdock9803** [comment]
Hello @sm1990, I am an aspiring frontend developer as I am interested in UI design. Can I work on this issue ?

**Comment by sm1990** [comment]
Sure @Murdock9803. You can work on this issue. I'll assign it to you.

**Comment by Murdock9803** [comment]
Sure! Thank you very much 🙌

**Comment by sm1990** [comment]
Hi @Murdock9803 ,
Any update on this issue? Let me know if you have any questions.

**Comment by Murdock9803** [comment]
Hello @sm1990, I apologize for the delay, I am going to open the PR very soon. Just wanted to confirm, can you provide the link to this page which the issue targets to redesign ? Also, any specific points to remember while designing ? you can also share your thoughts @praneesha 🙌

**Comment by sm1990** [comment]
Hi @Murdock9803 ,
Here's a link to one of our release notes: https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.10.1.
Design-wise, make sure the latest is always at the top. Also, the existing sections, e.g.:- 'Swan Lake release notes,' should be there.

**Comment by sm1990** [comment]
@Murdock9803 Any update on this issue? Let me know if you have any questions.

**Comment by Murdock9803** [comment]
Hello @sm1990, I apologize for delaying the work, I got some engagements in my university suddenly, and couldn't give sufficient time to the issue. I am trying to raise the PR soon, but in the meantime I believe @Jaagrav can also Open one. The work in the attached video looks promising.

**Comment by Jaagrav** [comment]
Thanks @Murdock9803, PTAL at my PR #9563
cc @sm1990
