### ISSUE TITLE
Ballerina contributor Code of Conduct link is broken.

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-dev-website#5667]
## Description
> Ballerina contributor code-of-conduct URL (https://ballerina.io/code-of-conduct) is broken. The URL is used in almost all ReadMe docs of Ballerina-Platform repos. And the link to contributor code-of-conduct can also be found here. https://github.com/ballerina-platform/ballerina-lang/blob/master/CODE_OF_CONDUCT.md

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/
