### ISSUE TITLE
Output Not Displayed in the Strands BBE

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#5742]
## Description
The output isn't shown properly in the `Run strands safely on a separate thread based on isolation` BBE[1] as shown below.

<img width="1680" alt="Screenshot 2022-10-31 at 12 10 43" src="https://user-images.githubusercontent.com/11707273/198946998-6f6f5428-aa63-4b47-ab2b-eeadcbf9de08.png">

[1] https://ballerina.io/learn/by-example/run-strands-safely-on-separate-threads/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/BBEs

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Will be fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3228/files.

**Comment by sm1990** [comment]
Fixed in https://ballerina.io/learn/by-example/run-strands-safely-on-separate-threads/
