### ISSUE TITLE
Write tests for Ballerina tutorials

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#5751]
## Description
> Write tests similar to [1] for Ballerina tutorials [2]

[1] [https://github.com/ballerina-platform/ballerina-dev-website/blob/e57b9e0fe6746de1b80dcc9d9741edc1c26fef28/.github/workflows/bal_in_action.yml](https://github.com/ballerina-platform/ballerina-dev-website/blob/e57b9e0fe6746de1b80dcc9d9741edc1c26fef28/.github/workflows/bal_in_action.yml)

[2] ([https://www.youtube.com/watch?v=NxyIKoHl3Dw&t=7s](https://www.youtube.com/watch?v=NxyIKoHl3Dw&t=7s))

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Need to update the `Tutorial: Creating a service in Ballerina` video on the home to Swan Lake. Currently, it is based on Ballerina 1.2.x.
