### ISSUE TITLE
Incorrect wording for VS Code

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#586]
**Description:**
Instead of `VS Code` the word `VSCode` is used in [1] (Space is missing). 

<img width="867" alt="image" src="https://user-images.githubusercontent.com/16300038/82155771-d4250880-9894-11ea-819c-29f22d1809bb.png">

[1] https://ballerina.io/learn/vscode-plugin/#using-the-extension

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Same issue is there in breadcrumbs too. 

  
<img width="857" alt="image" src="https://user-images.githubusercontent.com/16300038/82156262-c1f89980-9897-11ea-9e79-8ed68099e3dc.png">

**Comment by praneesha** [comment]
Fixes for the term "VS Code" are done via [1].

[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/649

**Comment by praneesha** [comment]
Reopening since we need to fix the breadcrumbs.

**Comment by praneesha** [comment]
Closing this since the breadcrumbs related issue will be addressed in https://github.com/ballerina-platform/ballerina-dev-website/issues/587.
