### ISSUE TITLE
`<br>` tag is visible in `JDBC, Simple query` BBE

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-dev-website#5863]
## Description
![Screenshot from 2022-11-23 11-28-56](https://user-images.githubusercontent.com/26381349/203482036-abfad95c-46fc-42d8-97c7-184d5efff61e.png)

Note the `<br>` tags at the end

**Comment by niveathika** [comment]
Closing this as this is now fixed
