### ISSUE TITLE
Improvements to the "Installing Ballerina" page

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#591]
Currently we list the following OS in the https://ballerina.io/learn/installing-ballerina/ page as supported platforms:
- Windows Vista SP2 x64 or later
- Ubuntu Linux 12.04 x64 - LTS and above
- OS X 10.8.3 x64 and above

I think we need to update this list. The following are my concerns:
- Vista is a heavily outdated OS and Microsoft ended support for it in 2017. I suggest that we make make this Windows 7 instead (reason: although its support also ended this year, it's still widely in use)
- Ubuntu is not the only Linux OS on which we can run Ballerina. Currently the above mentioned page only contains information on how to install using the `.deb` file. But we provide a `.rpm` file as well. Therefore, I think we should include that as well. 

In addition to the above, there are a couple of more issues as well:
- There is no information on how to setup Ballerina using the ZIP distribution. I think we should add a section with information on setting up the ZIP distribution for development work. It should include details like recommended locations for  installation, which env variables to setup etc.
- The building from source section does not contain information on building a complete distribution i.e., a distribution you'd get from installing from a installer or the ZIP. This section should be expanded to include detailed information about how to build a complete ZIP distribution from the source.

**Comment by praneesha** [comment]
The last bullet point about the "Building from source" section will be addressed in [1].

All the other issues mentioned here are addressed in [2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/659
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/652
