### ISSUE TITLE
Wrong terminology usage in learn pages

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#5913]
Double check and correct the wrong terminology in the GraphQL learn page: https://ballerina.io/learn/write-a-graphql-api-with-ballerina/

The page uses the terms "resource function" and "remote function" when it actually should be "resource method" and "remote method".

**Comment by pubudu91** [comment]
Actually looks like the other learn pages have this as well: 
https://ballerina.io/learn/write-a-restful-api-with-ballerina/
https://ballerina.io/learn/write-a-grpc-service-with-ballerina
https://ballerina.io/learn/build-a-data-service-in-ballerina

**Comment by ThisaruGuruge** [comment]
This is related to learn pages content. Unassigning myself from this. Let us know if there is anything to be done from our side.
