### ISSUE TITLE
Improve Algolia search result experience

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#5944]
## Description
Currently we don't get Ballerina.io search results due to some results prioritization issue. We need to update the configs and improve the results ranking

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/UIUX

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

**Comment by praneesha** [comment]
Need to address the items mentioned in https://github.com/ballerina-platform/ballerina-dev-website/issues/4726 also.

**Comment by praneesha** [comment]
Should address [this](https://github.com/ballerina-platform/ballerina-dev-website/issues/5505) also.

**Comment by praneesha** [comment]
We won't be addressing the below out of the items in https://github.com/ballerina-platform/ballerina-dev-website/issues/5944#issuecomment-1332002270.

1.  Implement the search hierarchy below.
2.  Crawl BAL file code comments in Algolia (e.g., mime, quoted identifiers)
