### ISSUE TITLE
Update documentation on configurable variables to include how to pass them to docker containers

### ISSUE THREAD

**Issue by IMS94** [ballerina-platform/ballerina-dev-website#5999]
## Description
$subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
As of now, configurable variables section of the ballerina.io docs describe how to set values for configurable variables via different approaches. But, it's not straightforward if you are running the ballerina program in a container. Need to update the documentation to reflect that as well.

**Comment by HindujaB** [comment]
For using a configurable variable in a container, we set the `BAL_CONFIG_DATA` env variable in the YAML files where they are retrieved when running the container. 
The `BAL_CONFIG_DATA` environment variable information is already included in the configurable learn page [1].
As this is specific to containers, IMO it should be included in the c2c learn pages. We can refer to that link in the configurable learn page as a note. 

[1] https://ballerina.io/learn/configure-ballerina-programs/provide-values-to-configurable-variables/
