### ISSUE TITLE
Change the SM banner of B.io

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6021]
## Description
Need to change thSM banner image of B.io. It still shows the Swan Lake GA image for releases, BBEs, and news letters as shown below.

<img width="580" alt="Screenshot 2022-12-06 at 12 31 46" src="https://user-images.githubusercontent.com/11707273/206387040-586dccd2-76c7-4546-a3dd-78c9b18031ac.png">

<img width="571" alt="Screenshot 2022-12-06 at 12 31 03" src="https://user-images.githubusercontent.com/11707273/206387087-bd9310d5-91f5-4c3d-a834-edf41df62a65.png">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Need to update the image added in https://github.com/ballerina-platform/ballerina-dev-website/issues/6036.

**Comment by dinushan20** [comment]
Closed with this PR https://github.com/ballerina-platform/ballerina-dev-website/pull/6372
