### ISSUE TITLE
Rethink and reorganize the flow of the content in the interop guide

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#606]
I think we need to reevaluate the order of the content in the [interop guide](https://ballerina.io/learn/how-to-call-java-code-from-ballerina/). It seems to jump straight in to code and explain that particular code without first introducing the basic elements of interop. For example, I wanted to know how to map a Ballerina `int` param to its counterpart in the native implementation. That info should've been basic and introduced right at the beginning IMO, because without that knowledge you can't really play around with the example code introduced in the previous sections. This section is included right towards the end under "How Java types are mapped to Ballerina types and vice versa".

**Comment by praneesha** [comment]
Closing as this is addressed in https://github.com/ballerina-platform/ballerina-dev-website/pull/3311.
