### ISSUE TITLE
Remove `redirect_from` fields from .md files

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-dev-website#6069]
## Description
$Subject. 
As `redirect_from` is not supported with new nextJS site. Having this in .md files might mislead devs thinking redirections are still supported. 

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
@sm1990 - Reopening to remove the `redirect_from` field added to the `liquid.json` file of all BBEs via the BBE generation tool.
