### ISSUE TITLE
Tooltip given for API docs tab shows `null` as the org name

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#61]
Refer to the screenshot below
![Screenshot from 2019-09-07 00-25-14](https://user-images.githubusercontent.com/6260009/64453521-5d7d1c00-d106-11e9-96d4-4795b97ec7c2.png)

The text should read `ballerina/lang.array`

**Comment by kaviththiranga** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/20218/
