### ISSUE TITLE
Tables in `BBE`s not rendered properly

### ISSUE THREAD

**Issue by rdulmina** [ballerina-platform/ballerina-dev-website#6204]
## Description
The table in the [filler values BBE](https://pre-prod.ballerina.io/learn/by-example/filler-values-of-a-list/) is not rendered correctly in the pre-prod website.

![image](https://user-images.githubusercontent.com/26381349/212280987-531cb62d-bf72-468f-b36c-4ef5f5f511db.png)

It renders correctly in the `IntelliJ` preview.

![image](https://user-images.githubusercontent.com/26381349/212280598-eddad383-82af-4c35-ae03-58b09bd5cfa7.png)

I tried both the markdown format and HTML format neither works

[Link](https://github.com/ballerina-platform/ballerina-distribution/blob/bbe-revamp/examples/filler-values-of-a-list/filler_values_of_a_list.md) to the `.md` file.

**Comment by sm1990** [comment]
Currently the BBEs are generated by reading the .md  line by line. Therefore the tables are not rendered properly. We will let you know of a work around or a fix.

**Comment by anupama-pathirage** [comment]
Closing as this table is not in the new BBE content.

**Comment by rdulmina** [comment]
The table needs to be added to this BBE. It is removed temporarily until this issue is fixed. Hence reopening the issue.

**Comment by praneesha** [comment]
Closing as currently we don't have tables in BBEs.
