### ISSUE TITLE
Revisit Deployment Learn/BBE structure

### ISSUE THREAD

**Issue by xlight05** [ballerina-platform/ballerina-dev-website#6344]
## Description
$Subject. Since the practice is now to have smaller BBE,learn pages, we need a way to have multiple sections inside pages of packages like Azure functions. We are already maxed out on the left nav(4levels) in Learn pages.
![image](https://user-images.githubusercontent.com/23274047/218787654-0b652d22-ef3d-482c-bde6-cf76490ecf20.png)

In BBEs also  Azure functions is inside Deployment->Function as a service in BBEs. we don't have a way of providing multiple samples without having one long page. 

![image](https://user-images.githubusercontent.com/23274047/218787865-1017de34-669b-486f-8397-1aef47302013.png)

We need to think if we are gonna support more levels of hierarchy or are we gonna change the current organization structure.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Fixed in [1] as shown below.

<img width="1728" alt="Screenshot 2023-05-09 at 22 37 18" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/ce585caa-36bf-4593-9b4b-d3bc5183be63">

[1] https://github.com/ballerina-platform/ballerina-distribution/tree/revamp-aws-azure-bbes
