### ISSUE TITLE
Fix download links on archive page in pre-prod environment

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-dev-website#6356]
## Description
> $title.
The download links on the archive version page(https://pre-prod.ballerina.io/downloads/archived/#swan-lake-archived-versions) in pre-prod environment should be updated to point to `https://dist-dev.ballerina.io/downloads/...` instead of `https://dist.ballerina.io/downloads/...`

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/CommonPages

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Can verify the artifacts on the pre-prod site after transferring them from `dist-dev` to `dist` manually.
