### ISSUE TITLE
Move the existing crawler to public repo

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#6371]
## Description
Currently the crawler for VS Code docs page is hosted in a private repo. This is to avoid exposing some API keys to public. We need to add these keys to repo secrets and move the crawler to vscode plugin repo.

**Comment by praneesha** [comment]
This is moved to the VS Code docs repo via https://github.com/wso2/docs-ballerina-vscode-extension/issues/148.
