### ISSUE TITLE
All the API Docs links are broken in BBEs and other places

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#6376]
## Description
$subect after the API Docs revamp effort.
Some reasons are 
- `/latest` URLs are not working : https://github.com/ballerina-platform/ballerina-central/issues/25
- Sub URL Paths were changed : Similar to https://github.com/wso2/ballerina-plugin-vscode/issues/434

**Comment by sm1990** [comment]
Closing as https://github.com/ballerina-platform/ballerina-central/issues/25 & https://github.com/wso2/ballerina-plugin-vscode/issues/434 are fixed
