### ISSUE TITLE
BBE Incorrect Links in Github Icons

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#64]
**Description:**
Four of the BBEs on the website link to the wrong Github URLs through the Github icon:

- [AWS Lambda](https://ballerina.io/learn/by-example/awslambda-deployment.html): Icon should link to https://github.com/ballerinax/awslambda/tree/master/awslambda-examples/examples/aws-lambda-deployment

- [Kubernetes] (https://ballerina.io/learn/by-example/kubernetes-deployment.html): Icon should link to https://github.com/ballerinax/kubernetes/tree/master/kubernetes-extension-examples/examples/kubernetes-deployment

- [Openshift] (https://ballerina.io/learn/by-example/openshift-deployment.html): Icon should link to https://github.com/ballerinax/kubernetes/tree/master/kubernetes-extension-examples/examples/openshift-deployment

- [Docker] (https://ballerina.io/learn/by-example/docker-deployment.html): Icon should link to https://github.com/ballerinax/docker/tree/master/docker-extension-examples/examples/docker-deployment

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Checked the links and now they are being directed properly as mentioned above.
