### ISSUE TITLE
Github link to file in the examples 404

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#641]
**Description:**
The Github link in the examples go to the master site which results in 404

**Affected Product Version:**
1.2 website

**Steps to reproduce:**
In the following site:
https://ballerina.io/learn/by-example/hello-world-parallel.html
Go to the github link which goes to 
https://github.com/ballerina-platform/ballerina-lang/tree/master/examples/hello-world-parallel
which leads to a non existent location resulting in a 404

**Comment by praneesha** [comment]
This is fixed and redirected to [1] now.

[1] https://github.com/ballerina-platform/ballerina-lang/tree/ballerina-1.2.x/examples/hello-world-parallel/
