### ISSUE TITLE
Fix sentence case in newsletter titles

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6506]
## Description
Need to check and fix sentence case in all issues of the newsletter.

This needs to be updated in the newsletter template as well via https://github.com/ballerina-platform/ballerina-dev-website/issues/6485.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by ashweni** [comment]
All done @praneesha

**Comment by ashweni** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/pull/6523
https://github.com/ballerina-platform/ballerina-dev-website/pull/6522
https://github.com/ballerina-platform/ballerina-dev-website/pull/6521
https://github.com/ballerina-platform/ballerina-dev-website/pull/6520
https://github.com/ballerina-platform/ballerina-dev-website/pull/6519
https://github.com/ballerina-platform/ballerina-dev-website/pull/6518 
https://github.com/ballerina-platform/ballerina-dev-website/pull/6517
