### ISSUE TITLE
Fix typos in the integration page diagram

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6515]
## Description
Need to fix the typos below in the diagram in [1].

They should be: `cloud-native` and `general-purpose`.

<img width="798" alt="Screenshot 2023-03-10 at 18 51 23" src="https://user-images.githubusercontent.com/11707273/224327090-7e038d00-ea29-41aa-b251-a0a15ccb5983.png">

[1] https://ballerina.io/usecases/integration/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sanjiva** [comment]
+1.
