### ISSUE TITLE
Rendering issues in the website

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-dev-website#6526]
## Description

Some code segments on Ballerina Guides are missing the first letter of each new line as follows.

1.1. 

<img width="632" alt="Screenshot 2023-03-08 at 11 29 47" src="https://user-images.githubusercontent.com/27485094/224638531-6137f4a3-ec92-4ca8-af4c-bd86367be942.png">

1.2.

<img width="632" alt="Screenshot 2023-03-13 at 11 34 36" src="https://user-images.githubusercontent.com/27485094/224638865-175c453f-414d-494e-8e9e-0220a7598ae2.png">

1.3.

<img width="633" alt="Screenshot 2023-03-13 at 11 51 12" src="https://user-images.githubusercontent.com/27485094/224638836-ed85ad11-7ac2-4f7f-9bec-501d9bc82ea3.png">

## Related website/documentation area

Ballerina Guides

> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
https://github.com/ballerina-platform/ballerina-dev-website/issues/5423

**Comment by sm1990** [comment]
The issue occurred due to trailing white spaces after the language class in code snippets. Fixed via #6531.

**Comment by praneesha** [comment]
Done via https://github.com/ballerina-platform/ballerina-dev-website/pull/6531..
