### ISSUE TITLE
Incorrect syntax highlighting on Ballerina Guides

### ISSUE THREAD

**Issue by TharushiJay** [ballerina-platform/ballerina-dev-website#6527]
## Description

1.
<img width="633" alt="Screenshot 2023-03-13 at 12 22 48" src="https://user-images.githubusercontent.com/27485094/224639012-6a8ba618-70d7-495a-bd77-b1bb1f320ef7.png">

2.
<img width="632" alt="Screenshot 2023-03-08 at 11 31 49" src="https://user-images.githubusercontent.com/27485094/224638739-de775d4a-fff3-45c2-8369-972c6d4927c1.png">

3.
<img width="633" alt="Screenshot 2023-03-13 at 12 09 45" src="https://user-images.githubusercontent.com/27485094/224638936-4dd2abf4-4dbb-4870-a1b0-6c6be2482ca0.png">

## Related website/documentation area
Ballerina Guides

## Related issue(s) (optional)
https://github.com/ballerina-platform/ballerina-dev-website/issues/5423

**Comment by sm1990** [comment]
@praneesha  & @azinneera the language class [here](https://github.com/ballerina-platform/ballerina-dev-website/blob/f01fa636e5ca60f4fc3ef6f3c79c19910f60c252/swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/test-services-and-clients.md?plain=1#L143) should be `ballerina` instead of `bal`

**Comment by sm1990** [comment]
@praneesha shiki does not support nested code snippets [here](https://github.com/ballerina-platform/ballerina-dev-website/blob/f01fa636e5ca60f4fc3ef6f3c79c19910f60c252/swan-lake/learn-the-platform/test-document-the-code/generate-code-documentation.md?plain=1#L170).  
![image](https://user-images.githubusercontent.com/7709843/224689009-edba8797-d981-4ea1-8a7f-c7fa7e717143.png)

**Comment by sm1990** [comment]
Regarding image [2] Shiki expects a `;` at the end of 
```ballerina
type Person record {
    string name;
    int...;
}
```

(after `}`). Hence the incorrect color of comments. If adding a `;` at the end is wrong, we might need to update the language grammar files at shiki end. WDYT @praneesha @keizer619

**Comment by praneesha** [comment]
Reopening as per the revert done in https://github.com/ballerina-platform/ballerina-dev-website/pull/6649.

**Comment by sm1990** [comment]
Issue 1 will be handled via https://github.com/ballerina-platform/ballerina-dev-website/issues/6656
