### ISSUE TITLE
Cannot access curl after following Code to Cloud example in Dockerfile

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-dev-website#6567]
## Description
> A brief description of the bug.
Following example to create Dockerfile helloWorld endpoint from below, but cannot access

curl http://localhost:9090/helloWorld/sayHello
curl: (7) Failed to connect to localhost port 9090 after 5 ms: Connection refused

## Steps to reproduce
> The steps to be followed to reproduce the issue.
https://ballerina.io/learn/run-in-the-cloud/code-to-cloud/code-to-cloud-deployment/

main_docker.bal
```

import ballerina/http;

listener http:Listener helloEP = new (9090);

configurable string name = ?;

service /helloWorld on helloEP {
    resource function get sayHello() returns string {
        return string `Hello, ${name}!`;
    }

}

```

Ballerina.toml

```
[package]
org = "scheung"
name = "hello_docker"
version = "0.1.0"
distribution = "2201.4.0"

[build-options]
observabilityIncluded = true
cloud = "docker"
```

Dockerfile
Manually added since this seems to be missing line?

`COPY scheung-hello_docker-0.1.0.jar /home/ballerina
`
in:

```
WORKDIR /home/ballerina

COPY scheung-hello_docker-0.1.0.jar /home/ballerina

EXPOSE  9090
USER ballerina

```

target/Cloud.toml
```
[container.name]
repository="scheung" # "wso2inc" # Docker hub name
name="hello" # container name
tag="v0.1.0"

[settings]
buildImage=true # you can make this false if you don't want to build the image and you just need the Dockerfile
```

Config.toml
`name="Docker"
`

where should Cloud.toml go?
I placed it inside target 

But when placed in root of project says

<img width="947" alt="Screenshot 2023-03-17 at 18 16 22" src="https://user-images.githubusercontent.com/1273014/225986112-2b4d488c-cd1b-4df7-b24b-e0c5c490a995.png">

## Affected version(s)
> The versions that are affected by the issue.
bal version
Ballerina 2201.4.0 (Swan Lake Update 4)
Language specification 2022R4
Update Tool 1.3.13

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anuruddhal** [comment]
@scheung38 The Cloud.toml file should go inside the root folder. Please refer https://ballerina.io/learn/run-in-the-cloud/code-to-cloud/code-to-cloud-deployment/#package-layout

**Comment by anuruddhal** [comment]
Also the content of Cloud.toml should be like this

```
[container.image]
repository="wso2inc" # Ex - Docker hub repository name.
name="hello-k8s" # Container name
tag="v0.1.0"
```

Noticed that you have `[container.image.name]` in the Cloud.toml which in incorrect.

**Comment by praneesha** [comment]
Closing the issue as per the above reply.

Please reopen if any further information is required.
