### ISSUE TITLE
How to increase timeoutSeconds: from default 1 to new value?

### ISSUE THREAD

**Issue by scheung38** [ballerina-platform/ballerina-dev-website#6577]
## Description
> A brief description of the bug.
Getting:

Liveness probe failed: Get "http://10.1.0.56:9091/probes/healthz": read tcp 10.1.0.1:50238->10.1.0.56:9091: read: connection reset by peer

I checked:
https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/troubleshooting-guides/liveness-readiness-probe-failure-on-master-provisioning

But not sure where to increase this value in which? timeoutSeconds I see it is default to
timeoutSeconds: 1 in Pods YAML?

## Steps to reproduce
> The steps to be followed to reproduce the issue.
from https://ballerina.io/learn/run-in-the-cloud/code-to-cloud/code-to-cloud-deployment/
kubectl apply -f target/kubernetes/hello_k8s/ 

## Affected version(s)
> The versions that are affected by the issue.

**Comment by anuruddhal** [comment]
@scheung38 It is not supported by the c2c library. You have to use [kutomize](https://kustomize.io/) to update the generated yaml file.

**Comment by praneesha** [comment]
Closing the issue as per the above reply.

Please reopen if any further information is required.
