### ISSUE TITLE
Add syntax highlighting to nested code blocks

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#6656]
## Description
> ![image](https://user-images.githubusercontent.com/7709843/227876159-ed320301-50cf-4b18-852f-9c07fb4c4ec1.png)

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by Ln11211** [comment]
Hello @sm1990 Is this a documentation issue?, if yes, can I take up this task?

Can you also please link the docs that need the change?

**Comment by sm1990** [comment]
> Hello @sm1990 Is this a documentation issue?, if yes, can I take up this task?
> 
> Can you also please link the docs that need the change?

Hi @Ln11211,

First of all, thank you for choosing to contribute to Ballerina website.

This issue is related to the rendering of code snippets through out our website and you can work on this issue.

Please note that this issue is eligible for both `Ballerina Hacktoberfest` and `Digital Ocean Hacktoberfest`.

The issue occurs in the following page:
https://ballerina.io/learn/generate-code-documentation/#generate-ballerina-documentation

Let me know if you need anything else.

Happy coding!!!!!

**Comment by sm1990** [comment]
Hi @Ln11211, Any update on this issue?. Let me know if you have any questions.

**Comment by ashutuptiwari** [comment]
Hi @sm1990 ,does this issue needs to assigned or is it open for PR's? Also, please specify how should it ideally look like. Thank you!

**Comment by s-vamshi** [comment]
@sm1990 can I work on this issue

**Comment by s-vamshi** [comment]
@sm1990 can I work on this issue?

**Comment by sm1990** [comment]
@Ln11211 & @ashutuptiwari  any update on this issue?

**Comment by ashutuptiwari** [comment]
I've tried but it doesn't seem to work. Any help would be appreciated @sm1990

**Comment by Ln11211** [comment]
> I've tried but it doesn't seem to work. Any help would be appreciated @sm1990

so, a regex expression is used to match the occurrence of triple backticks and language. so if there is a nested occurrence, it is failing to syntax highlight. A fix would be like this-

maintain a counter to count the number of ` ```ballerina` you encounter and decrement the counter every time a ` ``` ` is encountered and once the counter is zero, do that syntax highlighting using the Highlighter.

**Comment by ashutuptiwari** [comment]
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/106370097/9e6c340f-2adc-492b-91ed-ca079bb9812e)
Is this fine?
In this I've updated the .md to have a space after the  ending ``` of the outer syntax and updated the regex expression to match with regard to that extra space.

**Comment by ashutuptiwari** [comment]
@sm1990 @keizer619 , any feedback?

**Comment by sm1990** [comment]
> ![image](https://user-images.githubusercontent.com/106370097/277557149-9e6c340f-2adc-492b-91ed-ca079bb9812e.png) Is this fine? In this I've updated the .md to have a space after the ending ``` of the outer syntax and updated the regex expression to match with regard to that extra space. @sm1990

Can you share the screenshot of the code showing the beginning of each line?
Also, if you updated the .md file, did you add the space after all the code snippets? 
Can you send a PR so that I can test locally.
