### ISSUE TITLE
Incorrect content is displayed when reloading the page or using the same URL on another page

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-dev-website#6668]
## Description
$Subject

## Steps to reproduce

- Go to the [SQL module API doc](https://lib.ballerina.io/ballerina/sql/1.7.0) and click `ConnectionPool` in the `records`. This will point to the correct content to display.
 <img width="1418" alt="Screenshot 2023-03-28 at 14 01 20" src="https://user-images.githubusercontent.com/12771261/228177268-5925b3e0-58c4-47ff-a469-ecb8e11cd649.png">
 
- Reload the page or open this link on another page. This will point to incorrect content.
<img width="1439" alt="Screenshot 2023-03-28 at 14 02 44" src="https://user-images.githubusercontent.com/12771261/228177622-5f89a1a6-fa58-4e47-9a70-ae7b76d87f88.png">

## Affected version(s)
latest

## Related website/documentation area

> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed via https://github.com/wso2-enterprise/ballerina-central/pull/847
