### ISSUE TITLE
Improve the community page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#6775]
## Description

$subject https://ballerina.io/community/

- [x] Remove unnecessary forms
- [ ] The page is less catchy for first visitors. Need to have overall better design for the page.
- [ ] Every blade has sub pages to see all, that might be painful for visitors as hard to see information at first glance. 
- [ ] Revisit the [resources](https://ballerina.io/community/resources/) section.  Information is hard to find without proper search etc.
- [ ] Tabbed design in [events](https://ballerina.io/community/events/) and [resources](https://ballerina.io/community/resources/) makes it hard to find details

**Comment by bhimeshagrawal** [comment]
Hi 
I'd like to work on this issue if it's available.

**Comment by ThisaruGuruge** [comment]
👋 Welcome, @bhimeshagrawal! 🚀

We're thrilled to have you join the Ballerina Lang community! Whether you're a seasoned developer or just starting your journey with Ballerina, we value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

1. Understanding Ballerina Platform:
Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
2. How to Contribute:
Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
3. Contributing to the Ballerina library:
If you're interested in contributing to our library, here are the guidelines: [Library Contribution Guide](https://github.com/ballerina-platform/ballerina-standard-library/blob/main/CONTRIBUTING.md)
4. Learn Ballerina:
If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
5. Get Help and Connect:
Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!
Happy coding! 🎉

**Comment by bhimeshagrawal** [comment]
Hey @ThisaruGuruge do we have a figma design to improve overall design for the page or replace the tabbed design which makes the information hard to find ?

**Comment by sm1990** [comment]
Hi @bhimeshagrawal,
We will update the thread with the finalized figma design.

**Comment by bhimeshagrawal** [comment]
> Hi @bhimeshagrawal, We will update the thread with the finalized figma design.

Sure @sm1990 waiting for the finalised design... Excited to build something great!

**Comment by JayPokale** [comment]
Would you assign this task to me?
And also let me know whether to use GSAP animation or keep a simple design.
For GSAP demo, visit my website [jaypokale.vercel.app](jaypokale.vercel.app)

**Comment by sm1990** [comment]
> > Hi @bhimeshagrawal, We will update the thread with the finalized figma design.
> 
> Sure @sm1990 waiting for the finalized design... Excited to build something great!

Hi @bhimeshagrawal,

I have shared the [mockup](https://app.moqups.com/wNHZupukdPkgVi9K44Kdl0X7qH21x4pI/view/page/ad64222d5) with you. We have reorganized the structure of the page. You'll be able to re-use most of the existing components.

Since this is a major revamp, I have created a separate feature branch called `community-revamp`. Please send your pull requests to that branch. Also do not forget to attach a screenshot of the new `Community page` to your pull request.

Let me know if you have any questions.

Happy coding!!!!

**Comment by bhimeshagrawal** [comment]
> > > Hi @bhimeshagrawal, We will update the thread with the finalized figma design.
> > 
> > 
> > Sure @sm1990 waiting for the finalized design... Excited to build something great!
> 
> Hi @bhimeshagrawal,
> 
> I have shared the [mockup](https://app.moqups.com/wNHZupukdPkgVi9K44Kdl0X7qH21x4pI/view/page/ad64222d5) with you. We have reorganized the structure of the page. You'll be able to re-use most of the existing components.
> 
> Since this is a major revamp, I have created a separate feature branch called `community-revamp`. Please send your pull requests to that branch. Also do not forget to attach a screenshot of the new `Community page` to your pull request.
> 
> Let me know if you have any questions.
> 
> Happy coding!!!!

Sure @sm1990 , I will create pull requests in new `community-revamp` branch

**Comment by bhimeshagrawal** [comment]
@sm1990 the mockup doesn't have few sections such as "Ballerina Tech Talk", "Blog". Shall I remove them from community page and replace "Discord" section to "Join with us" section

**Comment by sm1990** [comment]
> What if GSAP is used in this page? Just an idea...

@JayPokale are you referring to this issue? @bhimeshagrawal is already working on this and following a mock-up we have shared.

**Comment by bhimeshagrawal** [comment]
Sure, thanks for letting me know

**Comment by bhimeshagrawal** [comment]
@sm1990 I have raised a pull request #8013 , please review and suggest changes. I am attaching the screenshot here also to look for.

![New Community Page](https://github.com/ballerina-platform/ballerina-dev-website/assets/65838772/0aabd3dc-d232-4a01-9eca-ea99f0f2897e)

**Comment by bhimeshagrawal** [comment]
> @sm1990 I have raised a pull request #8013 , please review and suggest changes. I am attaching the screenshot here also to look for.
> 

In case we want to change the Discord section to Join with Us section as mentioned in mockup, could you please clarify the content below the `Join with us` heading and also the meaning of `m` logo in that section as shown in mockup

**Comment by sm1990** [comment]
Hi @bhimeshagrawal,
I reviewed your PR. Coding wise there weren't any issues :clap: . Content/Design wise you need to do the following.

**Blade 3**
- [ ] Change the heading `Ballerina Discord community` to `Join with us`.
- [ ] Add all the icons I've shared in the mockup. (`m` is for `meetup` ).
- [ ] Do not worry about urls. Put `#` for now.
- [ ] Use dummy text as main text.

**Blade 4**
- [ ] Use dummy text as main text.
- [ ] Remove the existing 3 cards and add the boxes with shared icons in the mockup. 
- [ ] Do not worry about urls. Put `#` for now.

**Blade 5**
- [ ] `View all newsletters` link should have an `arrow` icon at the end.

**Blade 6**
- [ ] Remove `Report issues` & `Active proposals for Ballerina`.


Let me know if you have any doubts about the mockup.

**Comment by bhimeshagrawal** [comment]
Hi @sm1990 
I have updated the pull request to update the design as suggested by you.

###Checklist

Blade 3
 - [x] Change the heading Ballerina Discord community to Join with us.
 - [x] Add all the icons I've shared in the mockup. (m is for meetup ).
 - [x] Do not worry about urls. Put # for now.
 - [x] Use dummy text as main text.

Blade 4
 - [x] Use dummy text as main text.
 - [x] Remove the existing 3 cards and add the boxes with shared icons in the mockup.
 - [x] Do not worry about urls. Put # for now.

Blade 5
- [x] View all newsletters link should have an arrow icon at the end.

Blade 6
- [x] Remove Report issues & Active proposals for Ballerina.

Please review them and Let me know if you have any suggestions. I am attaching the screenshot of web page below for your reference


![New Community Page](https://github.com/ballerina-platform/ballerina-dev-website/assets/65838772/4660bff3-cf06-49dd-8d4e-687a8301991c)

**Comment by sm1990** [comment]
@bhimeshagrawal Thank you for your contribution. We are currently hosting a Ballerina Hacktoberfest. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄

**Comment by bhimeshagrawal** [comment]
> @bhimeshagrawal Thank you for your contribution. We are currently hosting a Ballerina Hacktoberfest. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄

Thanks @sm1990 for guiding this whole time. I have submitted the form in order to participate in the event
