### ISSUE TITLE
Ballerina specifications appear in wrong location in learn left nav

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#6836]
## Description

$subject in [1] 

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/16300038/236301571-7cc02cac-967c-43d3-840f-2cac3d69eb4f.png">

[1] https://ballerina.io/learn/ballerina-specifications/

**Comment by sm1990** [comment]
@anupama-pathirage `Ballerina specification` is in the position where it has always been. We haven't changed that. Let me know where to move it if it needs to change.

**Comment by sm1990** [comment]
The issue is no longer valid as we have changes the structure of the learn page content.
