### ISSUE TITLE
Footer 'Subscribe via RSS` option is broken

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6840]
## Description
The 'Subscribe via RSS` option needs to be fixed in the B.io footer.

<img width="1437" alt="Screenshot 2023-05-07 at 08 49 40" src="https://user-images.githubusercontent.com/11707273/236655900-725597b7-10c1-4d65-a3fc-40ff58edd19d.png">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Fixed via https://github.com/ballerina-platform/blog/pull/179
