### ISSUE TITLE
Realign `Common libraries` section of BBES

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6891]
## Description
Need to realign the `Common libraries` section of BBES to make the length of the 4 columns equal as much as possible.

<img width="1728" alt="Screenshot 2023-05-10 at 13 35 25" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/80ef7021-c27c-4487-80d2-0eea99f0587e">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
This is fixed. 
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/883bbb35-4f21-45e9-9c6a-1d7af70012f2)
