### ISSUE TITLE
Add BBEs to the Learn left nav

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6892]
## Description
> Add an element named `Ballerina by Examples` to the Learn left nav and display the view in [1] once it is clicked.

<img width="1728" alt="Screenshot 2023-05-10 at 13 41 31" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/73d24c09-6eed-4634-9234-700a769cf4aa">

[1] https://ballerina.io/learn/by-example/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/f180a3d8-999e-4f2e-9027-387b45fe29f8)
This is done.
