### ISSUE TITLE
Add API Docs to the Learn left nav

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6894]
## Description
Need to add API Docs to the Learn left nav and redirect to 'lib.ballerina.io` once it is clicked.

This may follow a similar design as below in [1].

<img width="1728" alt="Screenshot 2023-05-10 at 13 46 56" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/8b45aa4b-42d8-4512-91b0-1c95fa2b6fc3">

[1] https://kotlinlang.org/docs/basic-syntax.html

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/87773ee0-58b0-41db-bbdc-a1bdbfa7f4bb)
This is complete.
