### ISSUE TITLE
Redesign the drop down arrow in Learn left nav

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#6895]
## Description
Need to do the changes below to the drop-down arrow of the learn left nav. Currently, it appears only when the element is hovered over. Therefore, it doesn't imply the depth (levels) of the content.

- [ ] Make it static
- [ ] Change the teal color to a gray color shade
- [ ] Change the icon
- [ ] Move it to the start of the text or position it in a better way.

For example, see the designs below.

**Design Example 1**

<img width="257" alt="Screenshot 2023-05-10 at 13 53 28" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/d10668f5-1347-4fb7-9d2e-bb504a7d3c42">

**Design Example 2**

<img width="223" alt="Screenshot 2023-05-10 at 13 54 04" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/9ced2955-374a-4641-95d5-92d26b650262">

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as not a priority .
