### ISSUE TITLE
Refactor the code in Release notes page slugs

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#6964]
## Description
 $subject.
Refactor the code by adding existing reusable components.
Eg:- https://github.com/ballerina-platform/ballerina-dev-website/blob/master/pages/learn/integration/%5B...slug%5D.js

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by JayPokale** [comment]
I want to work on this issue

**Comment by Abhi132004** [comment]
Can I work on this issue

**Comment by sm1990** [comment]
Hi @JayPokale any update on this issue. Let me know if you have any questions.

**Comment by JayPokale** [comment]
> Hi @JayPokale any update on this issue. Let me know if you have any questions.

Sorry for the delay, I was working on [https://github.com/ballerina-platform/ballerina-lang/issues/36790](https://github.com/ballerina-platform/ballerina-lang/issues/36790) this issue. Now that issue is solved.
I visited this issue and cloned the project too. It will be completed soon.

**Comment by sm1990** [comment]
> > Hi @JayPokale any update on this issue. Let me know if you have any questions.
> 
> Sorry for the delay, I was working on [ballerina-platform/ballerina-lang#36790](https://github.com/ballerina-platform/ballerina-lang/issues/36790) this issue. Now that issue is solved. I visited this issue and cloned the project too. It will be completed soon.

Thank you @JayPokale. 

@Abhi132004 since @JayPokale is working on this issue, you can visit https://github.com/ballerina-platform/ballerina-dev-website/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest and check out other available issues to work on.

Happy coding!!!! :smile:
