### ISSUE TITLE
Support copy to clipboard for code snippets in ballerina usecase page

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#6983]
## Description
$subject

**Comment by LakshanWeerasinghe** [comment]
@praneesha @sm1990 This functionality is missing in the ballerina-in-action section as well.

**Comment by Ishad-M-I-M** [comment]
Hi. @sm1990 
Can I get this issue assigned to me

**Comment by keizer619** [comment]
@Ishad-M-I-M We have assigned this issue for you

**Comment by sm1990** [comment]
Hi @Ishad-M-I-M , 
Any update on the issue? Let me know if you have questions.

**Comment by Ishad-M-I-M** [comment]
> Hi @Ishad-M-I-M , 
> Any update on the issue? Let me know if you have questions.
> 

I'm working on it.
Is it okay to update the `shiki` package version to `1.21` from `0.14`?
Have some breaking changes. But can use the shiki transformers to add the copy button. It didn't worked with current version

**Comment by sm1990** [comment]
> > Hi @Ishad-M-I-M ,
> > Any update on the issue? Let me know if you have questions.
> 
> I'm working on it. Is it okay to update the `shiki` package version to `1.21` from `0.14`? Have some breaking changes need to fix them. But can use the shiki transformers to add the copy button. It didn't worked with current version

Sure. But test all the other places as well.
