### ISSUE TITLE
Library spec pages are missing page titles in the header

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#6999]
## Description
$subject
e.g. :- https://ballerina.io/spec/cache/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by aman44444** [comment]
@keizer619 i want to work on this issue can you please assign this to me?

**Comment by sm1990** [comment]
Hi @aman44444 

First of all, thank you for choosing to contribute to Ballerina website.

I am happy to let you know that you can work on this issue.

Please note that this issue is eligible for both `Ballerina Hacktoberfest` and `Digital Ocean Hacktoberfest`.

Let me know if you need anything else.

Happy coding!!!!!

**Comment by Sa24miksha** [comment]
@sm1990 can you brief me the description of the issue ?

**Comment by sm1990** [comment]
@aman44444 any update on this issue? Let me know if you have any questions.

**Comment by aman44444** [comment]
@sm1990 hey i am preparing for interview i can't work on this you can assign this to someone else.

**Comment by s-vamshi** [comment]
@sm1990 Can I would like to work on this issue as @Sa24miksha got assigned to another issue?

**Comment by sm1990** [comment]
@s-vamshi I have assigned the issue to you. Happy coding!!!! :smile:

**Comment by s-vamshi** [comment]
@sm1990 can you please describe some more about this issue?

**Comment by sm1990** [comment]
@s-vamshi issue occurs in the following file, which we use to render the page using `md`s.
https://github.com/ballerina-platform/ballerina-dev-website/blob/master/pages/spec/%5Bslug%5D.js

We have added the `<title>` tag in the `<head>` and have used `frontmatter.title` as the value. However, the `md` files generated by each module don't have a `title` field in the frontmatter. Thus making `frontmatter.title` null.

Since updating the `md`s might take some time, we need a quick fix from the front-end. Each page should have the library name in the page title. E.g.: `Specification: Ballerina Cache Library` for https://ballerina.io/spec/cache/

You need to figure out a method to get the library name.

Make sure to update all the relevant `meta` tags as well.

Let me know if you have any questions.

**Comment by s-vamshi** [comment]
@sm1990 so if formatter.title is null then we need to use library name right?

**Comment by aman44444** [comment]
@sm1990 hey can you explain what should be the color and position of title?

**Comment by s-vamshi** [comment]
@aman44444 I am already working on this issue 🙂

**Comment by sm1990** [comment]
@s-vamshi Thank you for your contribution. We are currently hosting a `Ballerina Hacktoberfest` Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄
