### ISSUE TITLE
Fix error in "manage-data-persistence-with-bal-persist" learn page

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-dev-website#7253]
## Description
> In the page, [manage-data-persistence-with-bal-persist](https://ballerina.io/learn/manage-data-persistence-with-bal-persist/) in https://ballerina.io/learn/, `bal persist init` command is executed with `store` as the `module`. But the folder structure shown after `bal persist generate` gives different information as shown below.
```
rainier
│   ├── generated
│   │  └── **db**
│   │  │   ├── persist_client.bal
```

This should be corrected as, 
```
rainier
│   ├── generated
│   │  └── **store**
│   │  │   ├── persist_client.bal
```

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by daneshk** [comment]
This issue is fixed. hence closing
