### ISSUE TITLE
Update the "release.json" File Based on the New "/downloads" Layout

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#741]
**Description:**
Need to update the "release.json" file based on the new "/downloads" layout[1].

[1] http://ballerina.io/downloads/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Thimuth** [comment]
Release JSON file is updated
