### ISSUE TITLE
Add Content of the AWS Lambda Module in API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#742]
**Description:**
We need to add content of the AWS Lambda Module in API Docs in [1] & [2].

[1] http://dev.ballerina.io/learn/api-docs/ballerina/
[2] http://dev.ballerina.io/learn/api-docs/ballerina/awslambda/index.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hemikak** [comment]
Fixed with https://github.com/ballerina-platform/module-ballerinax-aws.lambda/pull/173/
