### ISSUE TITLE
Incorrect SQL statements in the MYSQL BBE prerequisites sample code.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#7453]
## Description

$subject in https://github.com/ballerina-platform/ballerina-distribution/blob/master/examples/mysql-prerequisite/setup_database.bal#L65

This is reffered from MySQL BBEs , e.g. https://ballerina.io/learn/by-example/mysql-query-operation/

<img width="996" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/a2f5f2ae-de55-4e6c-a068-5c57c8227d54">

Comment says to sales_order table, but seems sql line is to add to inventory table, which is incorrect.

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/4955.
