### ISSUE TITLE
No Runtime Layer for 1.0 yet?

### ISSUE THREAD

**Issue by ergo70** [ballerina-platform/ballerina-dev-website#75]
**Description:**
No Runtime Layer for 1.0 yet?

Apparently there is no matching runtime layer for Ballerina 1.0 available yet? At least it is not mentioned on the AWS Layers page: https://v1-0.ballerina.io/deployment/aws-lambda/

I can confirm that 1.0 code does not work with 0.99x layers.

**Comment by praneesha** [comment]
Closing this as per the above comment. Please reopen if necessary.
