### ISSUE TITLE
Redesign the Community Page

### ISSUE THREAD

**Issue by Samallama** [ballerina-platform/ballerina-dev-website#758]
**Description:**
We need to redesign the community page according to this content [1] and the design below.

![community-bio](https://user-images.githubusercontent.com/11707273/121778405-5ffe8680-cbb4-11eb-8cfc-38855d2fde7e.jpg)

[1] https://docs.google.com/document/d/1qPuGB00_sNWMJ5v4u95J6-8CL__nm-Q-s7B4Q0m5d8Y/edit#

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is the design we finalized.

![community-bio](https://user-images.githubusercontent.com/11707273/111243739-949b8a00-8627-11eb-80be-917ef2509053.jpg)

**Comment by Samallama** [comment]
Some comments and changes to this design can be found as comments in this doc: https://docs.google.com/document/d/1qPuGB00_sNWMJ5v4u95J6-8CL__nm-Q-s7B4Q0m5d8Y/edit#

- Add YouTube and Reddit under 'How to Engage with the Community' section
- Add the 'Community Call' section
- Ass 'Submit Your Contribution' form

**Comment by praneesha** [comment]
Closing since now this is done in https://dev.ballerina.io/community/.
