### ISSUE TITLE
Guides redirecting to the Ballerina home page

### ISSUE THREAD

**Issue by IrushiL** [ballerina-platform/ballerina-dev-website#76]
**Description:**
When you Google search for a simple example such as "Restful services in Ballerina" it shows a guide "RESTful Service - Ballerina.io" as the topmost result. But when you click on it redirects to the Ballerina home page. This is the case for most of the guides. 

We should redirect it to the correct page, since this could have a significant impact on user experience.

**Affected Versions:**
Ballerina 1.0.0

**Comment by praneesha** [comment]
Currently, searching for "Restful services in Ballerina" in Google directs to the respective repo of the BBG in the ballerina-guides organisation[1] as shown below.

<img width="982" alt="Screenshot 2019-11-29 at 12 26 45" src="https://user-images.githubusercontent.com/11707273/69849767-99f28b00-12a3-11ea-9feb-f3ceb4b1d4d2.png">

[1] https://github.com/ballerina-guides/restful-service

**Comment by praneesha** [comment]
Closing as the guide is properly redirected to [1] now.

[1] https://github.com/ballerina-guides/restful-service
