### ISSUE TITLE
Automate updating the VS Code home page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#7654]
## Description
Currently, we have to regenerate the VS code home page by executing `npm run build` and `npm run export` commands and manually update the folder paths of all the icons and images in the generated files when updating the [VS Code home page](https://wso2.com/ballerina/vscode/).

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
The task is no longer needed as we have moved the VS Code docs into B.io.
