### ISSUE TITLE
Testarina Learn page need to be Updated on how Services behavs during tests

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-dev-website#77]
**Description:**
Currently Ballerina test learn page does not explain about how the services behaves during testing. Also the current implementation is different from how the services are started in previous releases ( behavior has been changed in 0.9... release ) thus the articles and blogs explain the previous behavior.  

We need to update the Ballerina test learn page so that users can refer and understand how services behaves during testing.

**Affected Product Version:**
1.0.0

**Comment by azinneera** [comment]
Closing this since the learn pages are updated.
