### ISSUE TITLE
Incorrect error logs on the Ballerina playground

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-dev-website#7711]
## Description

```
//import ballerina/io;
public function main() {    
    xml a = xml `<soap:Envelope><soap:Header></soap:Header> <soap:Body> <a>b</a> </soap:Body> </soap:Envelope>`;  
}
```

When executing the above method in the Ballerina playground, the following error log is displayed.

```Error while compiling. .{ballerina/io}GenericError```

This should be correct as,
```Error while compiling. Invalid identifier soap```

**Comment by keizer619** [comment]
We have discontinued Ballerina playground. Hence i will be closing this issue
