### ISSUE TITLE
Incorrect new line in persist BBE

### ISSUE THREAD

**Issue by KavinduZoysa** [ballerina-platform/ballerina-dev-website#7771]
## Description
Please check https://ballerina.io/learn/by-example/persist-get-all/

The first paragraph of the description contains an invalid new line at the end.

![Screenshot from 2023-09-11 12-05-16](https://github.com/ballerina-platform/ballerina-dev-website/assets/28332708/4372588d-fc13-47f5-b673-be4083d417eb)

**Comment by praneesha** [comment]
Fixed via  https://github.com/ballerina-platform/ballerina-distribution/pull/4917.

Fixed in both master and 2201.8.x branches.
