### ISSUE TITLE
Make it mandatory for users to install Ballerina with installer for GraalVM applications

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#7774]
## Description
We need to mention that users need use Ballerina installer for Mac users when they do any GraalVM application. This is since we pull mac-os x86 architecture compatible JRE when we use update tool to update the distribution and it would break the GraalVM applications. 

This needs to be updated in the following pages in dev-website

- [ ] ~https://ballerina.io/learn/build-the-executable-in-a-container/#prerequisites~
- [x] https://ballerina.io/learn/build-the-executable-locally/#prerequisites

**Comment by TharmiganK** [comment]
It is not required to update the cloud page since it does not require users to install GraalVM. In addition to that, since the JAR build and the native executable build happens in two different processes there wont be a tool chain conflict.

**Comment by TharmiganK** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/7775
