### ISSUE TITLE
Update the new Twitter logo

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#7781]
## Description
The Twitter logo needs to be replaced with the `X` logo in the [b.io](http://b.io/) footer and on the first blade of the home page based on [1].

[1] https://about.twitter.com/en/who-we-are/brand-toolkit

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by bhimeshagrawal** [comment]
Hi,
I'd like to work on this issue if it's available.

**Comment by sm1990** [comment]
> Hi, I'd like to work on this issue if it's available.

Hi @bhimeshagrawal,
Thank you for selecting this issue and contributing. However this is issue not eligible for `Ballerina Hacktoberfest`. But it is eligible for `Digital Ocean Hacktoberfest`. As I mentioned before, we are happy with your contribution and will merge your PR once the review comments are addressed.

Please note that the issue #6775, which you have assigned to yourself is eligible for both Hacktoberfests. You can select the eligible ones using the `Hacktoberfest` label.

Let me know if you have any further questions.

**Comment by sm1990** [comment]
@bhimeshagrawal Thank you very much for your contribution. :smile:
