### ISSUE TITLE
Search function is not available in Bio website

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-dev-website#78]
**Description:**
The search functionality which was very useful for navigating through the website is not there in the 1.0.0 website. It would be very nice to have it back.

**Affected Product Version:**
JBallerina 1.0.0

**Comment by NipunaMarcus** [comment]
Added the feature and created a branch for test purposes.

https://github.com/ballerina-platform/ballerina-dev-website/tree/site-search

**Comment by riyafa** [comment]
It's a very useful feature. Seems like it has been dropped from the 1.2 release as well.

**Comment by praneesha** [comment]
This is implemented in https://ballerina.io/ now other than for the API Docs[1]. A search bar will be added to API Docs via [2].

[1] https://ballerina.io/learn/api-docs/ballerina/
[2] https://github.com/ballerina-platform/ballerina-dev-website/issues/273
