### ISSUE TITLE
`Page not found` error for some links in `https://pre-prod.ballerina.io`

### ISSUE THREAD

**Issue by Nadeeshan96** [ballerina-platform/ballerina-dev-website#7870]
## Description
> A brief description of the bug.

Below two links are not working.
<img width="431" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/33286289/5fd7e550-8d85-4947-9158-155844700d78">
https://pre-prod.ballerina.io/learn/strand-dump-tool
https://pre-prod.ballerina.io/learn/ballerina-profiler

https://pre-prod.ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.8.0#ballerina-profiler-experimental
<img width="471" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/33286289/f0bab17d-beef-4631-8869-ce28eb89bdf3">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Closing as these are fixed now.
