### ISSUE TITLE
Nested code blocks in library specs aren't displayed correctly

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-dev-website#7884]
## Description
When a codeblock has a nested block like below 
```ballerina
# Gets invoked during the module initialization to initialize the listener.
# ```ballerina
# listener websocket:Listener securedEP = new(9090,
#   secureSocket = {
#       key: {
#           certFile: "../resource/path/to/public.crt",
#           keyFile: "../resource/path/to/private.key"
#       }
#   }
# );
# ```
#
# + port - Listening port of the WebSocket service listener
# + config - Configurations for the WebSocket service listener
public isolated function init(int|http:Listener 'listener, *ListenerConfiguration config) returns Error? {
```

the site renders it without any code style
<img width="991" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/43032716/b2d22f91-c583-42f4-af67-d56da3a25bdc">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
This will be fixed along with https://github.com/ballerina-platform/ballerina-dev-website/issues/6656
