### ISSUE TITLE
VS code and IDEA help pages are shown as sub pages of "Tools and IDEs" 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#79]
**Description:**

We don't have a "Tools and IDEs" page now. But the VScode help page [1] and IDEA plugin help page [2]  (Which are linked from learn page [3]) are shown as sub pages of "Tools and IDEs" 

<img width="660" alt="image" src="https://user-images.githubusercontent.com/16300038/64756663-53677d00-d54d-11e9-99be-a706ad923c5b.png">

[1] https://v1-0.ballerina.io/learn/tools-ides/vscode-plugin/
[2] https://v1-0.ballerina.io/learn/tools-ides/intellij-plugin/
[3] https://v1-0.ballerina.io/learn/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing as now these are correctly redirected to [1] and [2] respectively.

[1] https://ballerina.io/v1-2/learn/vscode-plugin/
[2] https://ballerina.io/v1-2/learn/intellij-plugin/
