### ISSUE TITLE
Rearrange backward incompatible changes in release notes

### ISSUE THREAD

**Issue by chiranSachintha** [ballerina-platform/ballerina-dev-website#7911]
## Description
Currently, we list backwards incompatible changes at the beginning of our release notes, which may lead to negative feedback for users.

We have fixed this in the 2201.8.0 release note. We need to fix those in the previous releases like 2201.7.0(https://ballerina.io/downloads/swan-lake-release-notes/swan-lake-2201.7.0), 2201.6.0, 2201.5.0 etc.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
Closing as this is updated in the latest release note and updating the previous release notes will not be prioritized at the moment.
