### ISSUE TITLE
Add a copy code button to Ballerina in Action samples

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8001]
## Description
$subject 

<img width="1065" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/0c8e706b-5ba6-4ec3-8437-36d1a8b6da98">

**Comment by aman44444** [comment]
@anupama-pathirage i want to work on this feature can please assign this to me ?

**Comment by Sa24miksha** [comment]
@anupama-pathirage i am working on this issue , assign this to me .

**Comment by sm1990** [comment]
@aman44444 are you working on this issue and #6999 both?

**Comment by aman44444** [comment]
@sm1990  you can assign #6999 to @Sa24miksha if you want

**Comment by sm1990** [comment]
Thank you @aman44444.

@Sa24miksha you can start working on this issue. Happy Coding!!!! :smile:

**Comment by sm1990** [comment]
@Sa24miksha any update on this issue?

**Comment by s-vamshi** [comment]
@sm1990 can I work on this issue as if now one is working?

**Comment by Pinaka-Pani-18** [comment]
Hi @sm1990 ,

I would like to work on this issue. could you please assign it to me?

**Comment by aman44444** [comment]
hey @sm1990 can i work on this now?

**Comment by sm1990** [comment]
@Sa24miksha any update on this? If you're not working on it can you please assign it to @s-vamshi.

@s-vamshi  please send the pr.
