### ISSUE TITLE
Images are not rendered properly in Firefox- Pre-built example pages

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8025]
## Description

$subject in Firefox for

https://ballerina.io/learn/pre-built-integrations/google-sheets-to-salesforce-integration/

<img width="1461" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/e1d7282e-173f-4144-887b-e0ecef54e652">

**Comment by Ishad-M-I-M** [comment]
Hi. Can I get this assigned to me

**Comment by sm1990** [comment]
@Ishad-M-I-M Thank you for your contribution. We are currently hosting a Ballerina Hacktoberfest. Since this issue is eligible for our event, please visit https://ballerina.io/hacktoberfest/#rules & submit the form. 😄
