### ISSUE TITLE
Google search of 'Ballerina ffi' gives a link with page not found error

### ISSUE THREAD

**Issue by gabilang** [ballerina-platform/ballerina-dev-website#8032]
## Description
> Searching `ballerina ffi` gives a link which is ended up with 404 page not found error. 

## Steps to reproduce
> Search on google chrome with the word `ballerina ffi`
![Screenshot from 2023-10-13 12-40-24](https://github.com/ballerina-platform/ballerina-dev-website/assets/35595065/574c240a-c02a-4982-9d0e-8d1c2eabeeda)
![Screenshot from 2023-10-13 12-39-38](https://github.com/ballerina-platform/ballerina-dev-website/assets/35595065/4bf97741-8c94-474e-92cc-d1c1660b3858)

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by yash240408** [comment]
I would like to work on this issue could you please elaborate more on this ?

**Comment by sm1990** [comment]
This is an old url. I have cleared it from Google index.

**Comment by sm1990** [comment]
> I would like to work on this issue could you please elaborate more on this ?

Hi @yash240408, this issue requires access to our Google console. So we fixed it from our end. Also this issue is not eligible for Hacktoberfest. Check [here](https://github.com/ballerina-platform/ballerina-dev-website/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest) to see the issues you can work on.
