### ISSUE TITLE
Implement filter card feature

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-dev-website#8052]
## Description
Currently there are tabs displayed in following pages. Those tags should be clickable to filter and remove filter

https://ballerina.io/learn/integration-tutorials/
https://ballerina.io/learn/pre-built-integrations/
https://ballerina.io/learn/enterprise-integration-patterns/

<img width="1698" alt="Screenshot 2023-10-17 at 23 04 59" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/2918812/d1405761-0404-4f5d-af94-3affbc519f89">

**Comment by LG-blip** [comment]
I would like to work on this project

**Comment by sm1990** [comment]
Hi @LG-blip 

First of all, thank you for choosing to contribute to Ballerina website. 

This issue is related to the rendering of code snippets through out our website and you can work on this issue.

Please note that this issue is eligible for both Ballerina Hacktoberfest and Digital Ocean Hacktoberfest.

Let me know if you need anything else.

Happy coding!!!!! :smile:

**Comment by LG-blip** [comment]
Those tags should be clickable to "filter and remove filter" ? i couldn't understand this part could you explain?

**Comment by sm1990** [comment]
> Those tags should be clickable to "filter and remove filter" ? i couldn't understand this part could you explain?

Yes. Currently they're just some text inside a `span`. Make the whole `span/badge` clickable.
Once you click, It should filter the items and show the current filter above the cards as below.
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/9d91b211-a589-4f1c-a9fc-7c90b9306f50)

The new badge should have a close button (denoted by the `X` in the image) to remove the filter.

Let me know if there are anymore questions.

**Comment by Pinaka-Pani-18** [comment]
Hi @sm1990 ,

I've worked on this issue, and now it works as follows. 
https://github.com/ballerina-platform/ballerina-dev-website/assets/102857774/0263de75-32fb-4fc3-a9aa-b6acc1b3587d

If you're okay with it, I'll proceed with the remaining part and create a PR. 

If you have any suggestions for improvements, please let me know.

**Comment by sm1990** [comment]
@LG-blip any update on this issue? If you are not working on this can you assign it to @Pinaka-Pani-18 as his solution seems to be correct.

**Comment by LG-blip** [comment]
Okay

**Comment by sm1990** [comment]
@Pinaka-Pani-18 can you send the PR
