### ISSUE TITLE
Events getting loaded under Learn

### ISSUE THREAD

**Issue by Bhashinee** [ballerina-platform/ballerina-dev-website#81]
**Description:**
When you click on the 'Events' you will be redirected to following page which shows 

Home>>Learn>>Events

![image](https://user-images.githubusercontent.com/11239305/64609429-880ef380-d3ea-11e9-903b-07d5418cc82a.png)

And when you click on the Learn, nothing happens.

**Comment by praneesha** [comment]
Closing since "Events" are properly loaded in [1] in the new design.

[1] https://ballerina.io/events/
