### ISSUE TITLE
[Integration Tutorials] Sending messages to a service

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#8114]
## Description
This issue contains several improvement requests to the above-mentioned tutorial. Here is the link to the tutorial. 
https://github.com/ballerina-platform/ballerina-dev-website/blob/master/swan-lake/integration-tutorials/sending-a-message-to-a-service.md

These suggestions apply to the version deployed in the pre-pod environment. Here is the PDF of what's on the pre-pod environment. 
[Sending a message to a service.pdf](https://github.com/ballerina-platform/ballerina-dev-website/files/13183458/Sending.a.message.to.a.service.pdf)

### Suggestion 1
The developer flow described in `Step 2` is unnatural, at least to me. Could you define the backend service URL and then define the client 5 steps later? I recommend defining the client and the configurable URL in `Step 6`.

Also, I would remove `Step 2.3` altogether. Is there a need to introduce a configurable variable for the port in this simple tutorial? Let's start with `Step 2.4.`

### Suggestion 2
I would prefer to understand why we generate a record in `Step 2.4`. It does tell you why we are generating a record from the JSON sample. It would be helpful for anyone reading if we could briefly tell why. This suggestion applies to other steps as well.

### Suggestion 3
I would encourage you to create Ballerina record types using the `+ Component > Record` combination. It's more natural to use than the VSCode command. We've already asked the developer to open the integration designer in `Step 2.2`.  You don't have to come to the code editor to rename the generated record. You can do it in the UI itself. 

### Suggestion 4
In `Step 2.7`, the code returns a `404` if the error is of type `http:ClientRequestError `. Is that accurate?  @shafreenAnfar FYI. 

This is what I can see in API docs. 
```
# Represents an error that occurred due to bad syntax or incomplete info in the client request(4xx HTTP response).
public type ClientRequestError distinct (ApplicationResponseError & error<Detail>);
```

**Comment by MaryamZi** [comment]
> ### Suggestion 4
> In `Step 2.7`, the code returns a `404` if the error is of type `http:ClientRequestError `. Is that accurate? @shafreenAnfar FYI.

In this particular case, the backend will return only a 404 response in the 4xx range, thus this check and response.

**Comment by MaryamZi** [comment]
We've incorporated changes accordingly - https://ballerina.io/learn/integration-tutorials/sending-a-message-to-a-service/.
