### ISSUE TITLE
Add tabbed content in learn pages

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#8176]
## Description
Need to enable adding tabbed content in Learn pages. The requirement initiated with [1] to add 2 tabs for the Windows and Linux environments.

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/8137

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
Closing as this is no longer needed.
