### ISSUE TITLE
Improve EDI tool Learn page

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-dev-website#8178]
## Description
$subject

https://ballerina.io/learn/edi-tool/

## Related website/documentation area
Area/LearnPages

## Describe the problem(s)
The current learn page can be improved to be more informative to the user.

## Describe your solution(s)
The following factors need to be considered. 
1. There is no mention of pulling the `edi` tool before executing the sample. We need to add something similar to this. 
https://ballerina.io/learn/health-tool/#install-the-tool
2. The ballerina syntax is wrong in step 4 of the sample.
https://ballerina.io/learn/edi-tool/#code-generation-example 
3. The package generation sample is too abstract. We didn't mention what the json schemas contain. It's more clear if we provide at least one json schema Eg. :  `850.json`
https://ballerina.io/learn/edi-tool/#create-the-package

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
1. Fixed
2. Fixed
3. Will be addressed via https://github.com/ballerina-platform/ballerina-dev-website/issues/7613.
