### ISSUE TITLE
Review and improve the content in the Learn page

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#83]
In the "Build, test & run programs" section it says the following:

> These everyday commands are for the very basics of being a Ballerina programmer: from compiling and running programs to testing them to generating their documentation.

This reads odd. Better if we can rephrase this.

There are multiple other places where the content needs to be improved. And came across a typo or two as well.

**Comment by praneesha** [comment]
This is fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/73.
