### ISSUE TITLE
Review suggestions for BFF usecase page.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8356]
**1.** Be consistent on frontend vs front-end wording. Recheck all places along with `backend` as well. This is what ChatGPT says. But pls revalidate. 

```

"Frontend," "front end," and "front-end" essentially refer to the same thing in the context of web development, but the choice of spelling can vary. These terms are used to describe the client-side of a web application or website, which is the part that users interact with directly.

Here's a breakdown:

Frontend: This is a compound word where "front" and "end" are joined together. It's a more general way of referring to the user interface and user experience components of a website or application.

Front end: In this version, "front" and "end" are separated by a space. It's also a correct way to express the same concept. This style is often used when writing in a more formal or traditional context.

Front-end: In this version, "front" and "end" are connected with a hyphen. This is a common style in technical documentation and discussions, especially in the context of web development. It's often used as an adjective to describe technologies, frameworks, or skills related to the frontend of a web application.

So, all three are correct, and the choice often depends on the specific style guide or personal preference. In casual conversation or writing, you'll often see "frontend" or "front end," while "front-end" is frequently used in more technical or formal contexts.
```

**2.** Add `BFF` for Explore menu.
**3.**  First image is too big. Can we have an image which aligns with the red-highlighted box below? i.e. align with the download button? Also image seems bit blurred
<img width="1363" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/b4615556-433c-4262-b5d8-4447333d7ecc">

4. Use only sentence case for sub titles. Check all places.
e.g. 
<img width="986" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/3ce86572-1967-4b2c-b873-9d88c7d4bce9">

6.  Fix the view code in Github links once the sample PRs are merged. 
7. Better to reword the following text as having two `with` seems confusing.
<img width="1033" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/0dbb5d5c-c86d-4de1-afe5-c7283cc0dd81">
Suggestion:
```
Ballerina's inherent JSON capabilities enable the direct mapping of JSON data into Ballerina records, incorporating functionalities such as constraint validations.
```

**Comment by SasinduDilshara** [comment]
Closing this issue since the suggstions are added
