### ISSUE TITLE
Remove duplicated page descriptions to improve SEO

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#8380]
## Description
> $subject

The following pages need new page descriptions

- [x] https://ballerina.io/community/
- [x] https://ballerina.io/license-of-site/
- [x] https://ballerina.io/terms-of-service/
- [x] https://ballerina.io/privacy-policy/
- [x] https://ballerina.io/cookie-policy/
- [x] https://ballerina.io/security-policy/
- [x] https://ballerina.io/trademark-usage-policy/
- [x] https://ballerina.io/downloads/
- [x] https://ballerina.io/downloads/archived/
- [x] https://ballerina.io/learn/by-example/graphql-client-error-handling/ (Check all graphql BBEs)
- [x] https://ballerina.io/learn/by-example/http-client-self-signed-jwt-authentication/ (Check http client BBEs)
- [x] https://ballerina.io/learn/by-example/kafka-consumer-sasl/ (Check all kafka BBEs)
- [x] https://ballerina.io/learn/by-example/nats-basic-pub/ (Check all nats BBEs)
- [x] https://ballerina.io/learn/by-example/rabbitmq-client-basic-auth/ (Check all rabbitmq BBEs)
- [x] https://ballerina.io/learn/by-example/sftp-client-receive-file/ (Check all sftp BBEs)
- [x] https://ballerina.io/learn/enterprise-integration-patterns/ (+ all the sub pages of that section)
- [x] https://ballerina.io/learn/pre-built-integrations/ (+ all the sub pages of that section)
- [x] https://ballerina.io/learn/integration-tutorials/
- [x] https://ballerina.io/learn/vs-code-extension/
- [x] https://ballerina.io/usecases/ai/
- [x] https://ballerina.io/usecases/data-oriented-programming/
- [x] https://ballerina.io/usecases/integration/ballerina-vs-java-for-data-oriented-programming/
- [x] https://blog.ballerina.io/

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by praneesha** [comment]
The SEO description of https://blog.ballerina.io/ is fixed via https://github.com/ballerina-platform/blog/pull/243.
