### ISSUE TITLE
Suggestions for improvements in Salesforce page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8391]
**1.** `Connect Salesforce with e-commerce platforms` blade. Can we link to [Ballerina library](https://central.ballerina.io/ballerina-library) also, so the readers can quickly check on various connector availability. 

**2.** Reword `Make sales staff aware of customer issues` blade title. 

     Making the sales staff aware is one example of usage/interconnections right?  Can we make the title more generic and then use this scenario as the sample? 

    e.g. Integrate your internal operations seamlessly, Seamlessly connect your back office systems etc

**3.** Instead of linking to GitHub directly from each blade, can we add those samples to [Pre-buit Integrations](https://ballerina.io/learn/pre-built-integrations/)  and then link that one. That will give a good overview via picture too. 

**4.** Can we simplify the code samples? For example the sample in `Utilize AI to extract sales information` has lots of stuff with gmail connector which is not that important for the message we need to communicate. Can we either think of different scenario with less work from the given connector or simplify this code?

**5.** Copy edit the page. There are few punctuation errors etc.

**Comment by chathurace** [comment]
1) +1

2) IMO, it's better to use more concrete titles than a generic title that readers may not be able to quickly relate to a real scenario.

3) For this, we need to put all samples under a separate folder. Even though we do that, still I think it's better to give a link for the sample being discussed in each blade.

4) We need samples that make sense as well. So IMO, code length is reasonable.

**Comment by anupama-pathirage** [comment]
> 1. +1
> 2. IMO, it's better to use more concrete titles than a generic title that readers may not be able to quickly relate to a real scenario.
> 3. For this, we need to put all samples under a separate folder. Even though we do that, still I think it's better to give a link for the sample being discussed in each blade.

@chathurace I didn't get `we need to put all samples under a separate folder`. What I meant is not to remove the link. Instead of pointing to github directly can we point to individual sample we add to pre-built integrations?

i.e. Having the link in the box below as https://pre-prod.ballerina.io/learn/pre-built-integrations/mysql-to-salesforce-integration/ instead of https://github.com/chathurace/integration-samples/blob/main/salesforce_api/mysql-record-to-sfdc-new-product/main.bal


<img width="1341" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/5676dc90-b6ec-4abc-97b7-69f37ba0eef4">

> 4. We need samples that make sense as well. So IMO, code length is reasonable.

**Comment by sahanHe** [comment]
> **5.** Copy edit the page. There are few punctuation errors etc.
Updated the github links. I went through the descriptions again and passed them through gramarly. but couldn't find any issue

**Comment by anupama-pathirage** [comment]
Few more comments. @chathurace / @sahanHe 

6. https://pre-prod.ballerina.io/usecases/salesforce/#custom-edi - Utilizing AI blade is not showing any code related to openAI chat client as it is hidden inside function call. Can we refactor the code a bit to move some of the email logic to separate functions and show the openAI usage in the code of the blade as it is the main highlight here.

<img width="1301" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/2d840542-973c-43eb-9003-7ffe934dd99a">

7. Check the Blade URLs. 
e.g. https://pre-prod.ballerina.io/usecases/salesforce/#custom-edi is the URL for `Utilize AI to extract sales information
` which is incorrect as `custom-edi` is not the highlight here, but AI.

8.  Incorrect to say libraries. See https://github.com/ballerina-platform/ballerina-dev-website/pull/7782#issuecomment-1723704068

<img width="1174" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/d8ce0816-b0c8-4e38-ab9f-af0c54a8104f">

**Comment by sahanHe** [comment]
branch [sahan-salesforce-usecases](https://github.com/ballerina-platform/ballerina-dev-website/tree/sahan-salesforce-usecases) is updated with changes. @sm1990 can you push to the pre-prod?

**Comment by anupama-pathirage** [comment]
Closing as this done and page is live. https://ballerina.io/usecases/salesforce/
