### ISSUE TITLE
Difficult to view the website when Javascript is turned off

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-dev-website#84]
**Description:**
Originally reported here. [https://news.ycombinator.com/item?id=20926602](https://news.ycombinator.com/item?id=20926602)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
As shown below, some of the features of the B.io such as the main menu or the BBEs do not load when JavaScript is turned off in Google Chrome.
<img width="1379" alt="Screenshot 2019-11-25 at 14 06 07" src="https://user-images.githubusercontent.com/11707273/69524888-0bbd9280-0f8d-11ea-925e-0822718773a1.png">
<img width="1278" alt="Screenshot 2019-11-25 at 14 06 17" src="https://user-images.githubusercontent.com/11707273/69524889-0bbd9280-0f8d-11ea-88bc-8f7a3948d97e.png">
<img width="1226" alt="Screenshot 2019-11-25 at 14 06 29" src="https://user-images.githubusercontent.com/11707273/69524890-0c562900-0f8d-11ea-8c79-670bce12c2f9.png">

**Comment by Samallama** [comment]
The menu structure and other parts of the website use Javascript, we will have to do a complete redesign if we are moving away from JS. Will put this as a requirement in the next iteration of the website design.

**Comment by iamsameeraliyanage** [comment]
To fix this issue I have referred [https://stackoverflow.com/](url) when it turn off.

![image](https://user-images.githubusercontent.com/67787442/128985938-2146c22d-3b85-4eea-b12c-d2a3523a22cd.png)

**Comment by iamsameeraliyanage** [comment]
This is how it will looks after #2700 
![image](https://user-images.githubusercontent.com/67787442/129018826-4c16cc6b-422a-47c5-8327-0f782cb4dabb.png)
