### ISSUE TITLE
Adjust the column width of tables automatically

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#8422]
## Description
Need to adjust the column width of tables automatically based on the content in occurrences[1] as shown in the image below.

![column-width](https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/70f2a825-e81e-4736-8521-b281003fb6ed)

[1] https://ballerina.io/learn/health-tool/#command-options

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as not a priority.
