### ISSUE TITLE
Google result does not show proper discription

### ISSUE THREAD

**Issue by rdhananjaya** [ballerina-platform/ballerina-dev-website#85]
**Description:**
When I search `ballerina lang` on google, wrong description is shown for ballerina.
(I'm talking about the description under the link, not the right side pane extracted from wikipedia in other 2 screenshots)

<img width="811" alt="Screen Shot 2019-09-10 at 2 27 17 PM" src="https://user-images.githubusercontent.com/1496990/64599742-8f78d180-d3d7-11e9-941d-553e0d226e1b.png">

Reference.
<img width="1211" alt="Screen Shot 2019-09-10 at 2 27 32 PM" src="https://user-images.githubusercontent.com/1496990/64599743-8f78d180-d3d7-11e9-9209-e25dd9573b76.png">
<img width="1170" alt="Screen Shot 2019-09-10 at 2 27 48 PM" src="https://user-images.githubusercontent.com/1496990/64599744-8f78d180-d3d7-11e9-8150-f4351f82b779.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Samallama** [comment]
We wrote to GitHub, and they asked us to raise the issue with the Google support team. It's not something we can fix, Google crawls the pages depending on the search term and populates the description. If you search for ballerina lang GitHub, this issue doesn't happen.

Question raised here: https://support.google.com/webmasters/thread/21449212?hl=en#

**Comment by praneesha** [comment]
Closing the issue as per the above comment.
