### ISSUE TITLE
Community page improvements

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8500]
## Description

1. Update the images of the first blade.
2. Block Design of [Join with us](https://pre-prod.ballerina.io/community/#join-with-us) should be improved. The boxes look so primitive, and with different sizes of boxes, the design does not look good.  
3. Medium tech blog link in [Resources](https://pre-prod.ballerina.io/community/#resources) is empty. 
4. Since we decided to add https://blog.ballerina.io/ to the top nav, do we still need it in the resources section?
5. Why do we need to open [Events page](https://pre-prod.ballerina.io/community/events/) and [newsletter page](https://pre-prod.ballerina.io/community/ballerina-newsletter/) in new tabs?
6. Since the subscription box is removed from the [newsletter page](https://pre-prod.ballerina.io/community/ballerina-newsletter/), do we need the following text?
<img width="1109" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/63f91e66-f9b0-4ef6-bb4c-054f6c69e89f">

**Comment by anuruddhal** [comment]
The `Join with Us` block can be improved by removing buttons and making icons as links. 
<img width="1728" alt="Screenshot 2024-01-05 at 7 34 30 AM" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11031042/09326a1e-d991-481b-8515-e9a7825725c5">

**Comment by sm1990** [comment]
When we had just the logos, it was decided that is was too empty. WDYT about the design below?
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/c510de77-1bb7-4576-8eab-cb7c48353516)

**Comment by sm1990** [comment]
Closing as the new community page is live https://ballerina.io/community/
