### ISSUE TITLE
Fix the Version Drop Down in the Swan Lake API Docs

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#852]
**Description:**
Fix the version drop down in the API Docs of the Swan Lake release. It gives a 404 if we select any other version from the drop down from any API Doc page in the Swan Lake version.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, Browser, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Thimuth** [comment]
This has been fixed with introducing /ballerina directory to Swan Lake API docs

**Comment by praneesha** [comment]
We need to fix this for 0.991 docs. For e.g., [1] gives a 404 error, ATM.

[1] https://ballerina.io/0.991/learn/api-docs/ballerina/cache/

**Comment by praneesha** [comment]
Closing since 0.991 docs will be removed with the EOL on 30th June 2020.
