### ISSUE TITLE
Create mockups for Usecases and Case studies landing pages

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#8531]
## Description
> $subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@anupama-pathirage  & @keizer619 please share your feedback on the following designs

![screencapture-localhost-3000-case-studies-2024-01-18-15_01_18](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/69d5f2fb-cd3b-4bbf-8850-9484b74f8e56)
![screencapture-localhost-3000-usecases-2024-01-18-15_00_33](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/173a5574-5d92-4ead-8702-83ca6dc474e8)

**Comment by anupama-pathirage** [comment]
LGTM.

@sm1990 Can you share how the top nav `Explore` menu will look like with this change?

**Comment by sm1990** [comment]
@anupama-pathirage please review the explore menu.

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/71c7d33e-2ffe-4e02-b34e-8a75efb96ec5)

**Comment by sm1990** [comment]
> @anupama-pathirage please review the explore menu.
> 
> ![image](https://private-user-images.githubusercontent.com/7709843/297957066-71c7d33e-2ffe-4e02-b34e-8a75efb96ec5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTU4OTUsIm5iZiI6MTcwNjI1NTU5NSwicGF0aCI6Ii83NzA5ODQzLzI5Nzk1NzA2Ni03MWM3ZDMzZS0yZmZlLTRlMDItYjM0ZS04YTc1ZWZiOTZlYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMDc1MzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGMxNDMyM2FiOGNhYzQyOTJjYjRmNjA2N2MwYjM0MWNiODU4Zjg1MDJlMGEwMDU4Nzk4MzUxMWYyNDYyZGM2ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PdpvC2480789DEy07pLPTT0hihcqZ0Kbl1mt1SFI_CY)

@anupama-pathirage any thoughts on the top nav design?

**Comment by sm1990** [comment]
@anupama-pathirage are you suggesting that, instead of showing links to the few individual pages under each category, we should show the category name (e.g. Use case, Case studies & Comparisons) and link them to their respective landing pages?

The problem with that approach is that there are only 2 pages under Comparisons, which is not enough to create a landing page.
We can go with that once we have more more content for comparisons. WDYT?

**Comment by sm1990** [comment]
> @anupama-pathirage are you suggesting that, instead of showing links to the few individual pages under each category, we should show the category name (e.g. Use case, Case studies & Comparisons) and link them to their respective landing pages?
> 
> The problem with that approach is that there are only 2 pages under Comparisons, which is not enough to create a landing page. We can go with that once we have more more content for comparisons. WDYT?

@anupama-pathirage any thoughts on the above?

**Comment by anupama-pathirage** [comment]
@sm1990 This is what I have in mind. Open for discussion. @sameerajayasoma Any thoughts?

<img width="1260" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/a3c77506-8af0-407a-85ac-6318da10686c">


Somewhat similar to following wso2 menu.

<img width="1103" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/c0214a85-6ff2-4fe7-b01f-2bf0f418ad77">

**Comment by sameerajayasoma** [comment]
Since we have a few case stuides and use cases, I can see the point of displaying 3-4 key ones in the navigation menu it self with a see more link.

**Comment by sm1990** [comment]
@sameerajayasoma, @anupama-pathirage @keizer619 please review the changes below.

Top nav:-
![oie_rFojFhc1ZwNx](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/f165f862-5e17-4a36-8459-9a305be74444)

Case studies:-
![screencapture-localhost-3000-case-studies-2024-04-29-11_14_31](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/91e5721c-f614-426d-ba8b-ac6a682c6c55)

Use cases:-
![screencapture-localhost-3000-usecases-2024-04-29-11_14_22](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/78e1e834-6e36-4c44-8965-35e1a96ba7e1)

**Comment by sm1990** [comment]
This is live now.
https://ballerina.io/use-cases/
https://ballerina.io/case-studies/
