### ISSUE TITLE
Create a BBE for the fork statement under the concurrency section

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#8534]
## Description
$subject

Using fork statements we can define workers in any place in the function body. This statement should be reflected through the example code and the description.

**Comment by anupama-pathirage** [comment]
@hasithaa / @MaryamZi Can we prioritize this for update 9 content?

**Comment by MaryamZi** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-distribution/issues/4945 for which there is an open PR, we should be able to get this done for U9.
