### ISSUE TITLE
Incorrect help text in CLI page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8535]
## Description

$subject in https://ballerina.io/learn/cli-commands/#use-the-ballerina-tool

1. There is additional command named tool which is not there in the output. @azinneera it seems this command is not displayed as `Other command` in help text. Is that correct? If correct, we need to update the docs. 
<img width="951" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/6c40b734-bae6-4c55-809f-67f2f34df4d7">

2. EDI command is not there.
<img width="947" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/845155b8-29ea-4678-8f46-99e3f74938fc">

**Comment by azinneera** [comment]
We moved it to 

> ## Description
> $subject in https://ballerina.io/learn/cli-commands/#use-the-ballerina-tool
> 
> 1. There is additional command named tool which is not there in the output. @azinneera it seems this command is not displayed in help text. Shouldn't we add it to help text?
> 
> <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/16300038/296947606-6c40b734-bae6-4c55-809f-67f2f34df4d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODYwMTcsIm5iZiI6MTcwNTM4NTcxNywicGF0aCI6Ii8xNjMwMDAzOC8yOTY5NDc2MDYtNmM0MGI3MzQtYmFlNi00YzU1LTgwOWYtNjdmMmYzNGRmNGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA2MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2FjODIwNDI4MWVhZjRlNDJmODc5YmZjNzIzOTM2MGMzY2U5ZDg1ZjE4NDBjODA0MGQ2ODg1Njc4ZjMxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QWVewQp0FmJQv-TwAzwO7xYcHjNW75ClRKWLuVPbfA8">
> 2. EDI command is not there.
> 
> <img alt="image" width="947" src="https://private-user-images.githubusercontent.com/16300038/296947859-845155b8-29ea-4678-8f46-99e3f74938fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODYwMTcsIm5iZiI6MTcwNTM4NTcxNywicGF0aCI6Ii8xNjMwMDAzOC8yOTY5NDc4NTktODQ1MTU1YjgtMjllYS00Njc4LThmNDYtOTllM2Y3NDkzOGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA2MTUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNTI5YjIyZmViM2I5NTAyNTAzNmY4M2QyZDRmYzE2NTRkZDQyZDcwODNhZmZjYWI0ZDYzMDdlZDI1NDMwZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BaqIzSA-35toO9Hwr5eIoKnop2X6KROoE9X5KkjxtBM">

We moved it to `Other Command` section. We have missed to update the website doc.

About the EDI Command - we didn't add it to the website since it will be shown only if the user has installed it. We might have to add an additional doc to show how the help text works for a custom tool installation.

**Comment by anupama-pathirage** [comment]
@azinneera, is it correct to have the `edi` command listed here in the help text? All the commands listed here are the ones which comes after `bal`. But `edi` comes after `bal tool`. And it is a custom tool command which is downloaded from central. So is it correct to to have it here as first level of commands here? Same applies to health command.

**Comment by gayaldassanayake** [comment]
`Tool` being listed under core commands in the website indeed is a mistake. Will fix right away.

However listing `edi` in the first level was a conscious decision since once `edi` tool is installed with `bal tool pull edi`, the user can use the edi tool with `bal edi` (and not `bal tool edi`) similar to any natively provided CLI command.

**Comment by anupama-pathirage** [comment]
I get the empty output when issuing `bal help edi`.  Shouldn't we have help text for edi tool in that case?

Note: I have already installed `edi` tool.

<img width="571" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/ab0e4128-0cb0-4808-a285-bb7bb6314e69">

**Comment by gayaldassanayake** [comment]
The `printLongDesc(StringBuilder out)` method that is provided with `BLauncherCmd` interface should append the help text to the `out` string builder. However, the method body is empty now.
https://github.com/ballerina-platform/edi-tools/blob/60ef628b6e59efea1c4efb12f338c3bf8735b98c/edi-cli/src/main/java/io/ballerina/edi/cmd/EdiCmd.java#L87

This section of the `bal tool startup guide explains this.
https://docs.google.com/document/d/19ptscl5kcmvAmzztUv8EAhsx13DUdLIJanlZt2BsZG8/edit#heading=h.r9i8aegmayof

So the method should be as below.
```java
@Override
    public void printLongDesc(StringBuilder out) {
        stringBuilder.append("Ballerina EDI tools -\n");
        stringBuilder.append("Ballerina code generation for edi schema: bal edi codegen -s <schema json path> -o <output bal file path>\n");
        stringBuilder.append("EDI library generation: bal edi libgen -O <org name> -l <library name> -s <EDI schema folder> -o <output folder>\n");
        stringBuilder.append("ESL to Ballerina EDI schema conversion: bal edi convertESL -b <Segment definitions file path> -s <ESL schema file/folder> -o <output file/folder>\n");
        stringBuilder.append("Ballerina X12 schema conversion: bal edi codegen [-H] [-c] -i <schema input path> -o <output json file/folder path> [-d] <segment details path>\n");
    }

**Comment by niveathika** [comment]
@RDPerera Lets look through and fix all possible edit text.

**Comment by RDPerera** [comment]
> @RDPerera Lets look through and fix all possible edit text.

Fix the 3rd issue + add `bal help edi` text with 0.8.6 release. In the meantime, I am working on [improving the help text](https://github.com/ballerina-platform/ballerina-library/issues/5949) of the EDI tool to match standard Ballerina CLI help texts as well.

<img width="883" alt="Screenshot 2024-01-17 at 10 48 33" src="https://github.com/ballerina-platform/ballerina-lang/assets/39415471/d4ed1313-8920-4c90-9baf-43f5d3a93fcd">
