### ISSUE TITLE
Incorrect command options given

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8543]
## Description

$subject in https://ballerina.io/learn/package-references/#the-org-field

<img width="816" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/5fffe738-29a4-4543-bcdb-68a6cf3f8eda">

Do we have a `-c` option?

**Comment by gayaldassanayake** [comment]
We do not currently have an option `-c` for `bal build`. So we can remove `-c` in this text.

**Comment by azinneera** [comment]
> We do not currently have an option `-c` for `bal build`. So we can remove `-c` in this text.

` bal build -c` equivalent now is `bal pack`

**Comment by praneesha** [comment]
> > We do not currently have an option `-c` for `bal build`. So we can remove `-c` in this text.
> 
> ` bal build -c` equivalent now is `bal pack`

Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/8583.
