### ISSUE TITLE
Copying code from learn pages removes all indentations in the code

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8552]
## Description

$subject. 

Refer to the video below. 

https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/4aee9dd3-4ecc-43cc-b04a-a088a875098b

**Comment by sm1990** [comment]
The issue is a duplicate of https://github.com/ballerina-platform/ballerina-dev-website/issues/8288

**Comment by sm1990** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/8571
