### ISSUE TITLE
Invalid group name in command 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8558]
## Description

$subject in https://ballerina.io/learn/test-ballerina-code/define-test-groups/#execute-grouped-tests

@Dilhasha Shouldnt we have the command as `al test --groups g1`

<img width="878" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/93d984fb-7c7c-48dd-8e06-df9b517a158a">

**Comment by ShammiL** [comment]
Fixed with #8559
