### ISSUE TITLE
Update login options in central learn page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8598]
## Description
We have more login options now. So update the page.

https://ballerina.io/learn/publish-packages-to-ballerina-central/#obtain-an-access-token

<img width="1498" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/6003da76-f3d9-4a21-82cb-eac34b72dc8e">

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/8626.
