### ISSUE TITLE
Getting setup heading in the Learn page need to be improved

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#86]
The heading is worded as "Getting set up to dance". IMO, this is just taking the whole Ballerina narrative too far. Kind of similar to the issue we had with the following line in the bad-sad error: `We thank you for helping make us better dancers`

**Comment by praneesha** [comment]
The most common standard used is "Getting Started". Therefore, changed the title to "Get started with Ballerina" to match the tense of the other titles (they do not have the -ing form).
