### ISSUE TITLE
Is Bal Semver tool experimental?

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8602]
## Description

$subject.

It is mentioned as experimental in :https://ballerina.io/learn/publish-packages-to-ballerina-central/#publish-a-new-version-of-a-package

<img width="1335" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/2cf572a8-b1c5-41aa-aec7-313a8830943a">

Is it correct to say experimental? @NipunaRanasinghe 

**If yes** : Need to update the `bal semver --help` text to say it is experimental tool similar to `bal shell`

<img width="702" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/d4ed1dc0-4f86-4170-8e9d-63b5b98f49d3">

**If No** : Then update the website page to remove experimental word.

**Comment by NipunaRanasinghe** [comment]
@anupama-pathirage yes, we decided to keep this as an experimental tool until we complete support for some advanced scenarios (e.g. https://github.com/ballerina-platform/ballerina-lang/issues/37017).

There we need to mention it as experimental in all of our documentation. I sent https://github.com/ballerina-platform/ballerina-lang/pull/42054 by updating the CLI help text. Thanks for pointing this out!
