### ISSUE TITLE
Improvement suggestions for ETL page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8604]
## Description
**1.** Be consistent on the wording `Realtime` vs `real-time`. It is better to use the hyphenated form "real-time," which is more commonly accepted and used in formal writing.

**2.** It seems both title case and sentence case is used in blade titles. Be consistent and use sentence case always. 

**3.** Can we use backticks to highlight the text instead of single quotes?
<img width="1156" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/07da4a54-591a-4b82-95e2-1d8fb291e7c6">

**4.** Better to use configurables?
<img width="1101" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/046c2075-2c18-409a-b93a-d3150e8cc58b">

**5.** Do we really need the retry config? As it is optional and not related to the concept explained in the blade, isn't it better to remove it?
<img width="1140" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/b7b071db-cb29-480c-8a34-a8e14f79cbf4">

**6.** Can we link to an example of data mapper too?
<img width="1088" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/345ff853-a7a6-4f3e-bf33-4f318d49f215">

**Comment by pcnfernando** [comment]
> **5.** Do we really need the retry config? As it is optional and not related to the concept explained in the blade, isn't it better to remove it? <img alt="image" width="1140" src="https://private-user-images.githubusercontent.com/16300038/299773917-b7b071db-cb29-480c-8a34-a8e14f79cbf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDc0NjMsIm5iZiI6MTcwNjI0NzE2MywicGF0aCI6Ii8xNjMwMDAzOC8yOTk3NzM5MTctYjdiMDcxZGItY2IyOS00ODBjLThhMzQtYThlMTRmNzljYmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDhjYzk1MGFkM2FjZGFlYmFjZWMzMjM3YWYyYWRkMmE0N2Q1MGZhNmEyNjE4YTFlZDM5MWQ5NWRmMWIyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8rioG9YGUsGsemK2o7rppRDufxXClbEmsim98TgTbU">

I don't see harm in removing it. But, this is coming from the [AI usecase](https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications) samples https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications
Do you think both use cases should be updated?

**Comment by anupama-pathirage** [comment]
> **2.** It seems both title case and sentence case is used in blade titles. Be consistent and use sentence case always.

This is not fixed. Check other two similar sub titles.

<img width="718" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/2a18f88f-f818-4808-a021-b8b1b6fa4c38">

> **4.** Better to use configurables?

Add `githubAccessToken` also as a configurable. 
<img width="1122" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/3150ca06-a3fe-481d-926e-d7a68f4d6f40">

**Comment by anupama-pathirage** [comment]
> > **5.** Do we really need the retry config? As it is optional and not related to the concept explained in the blade, isn't it better to remove it? <img alt="image" width="1140" src="https://private-user-images.githubusercontent.com/16300038/299773917-b7b071db-cb29-480c-8a34-a8e14f79cbf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDc0NjMsIm5iZiI6MTcwNjI0NzE2MywicGF0aCI6Ii8xNjMwMDAzOC8yOTk3NzM5MTctYjdiMDcxZGItY2IyOS00ODBjLThhMzQtYThlMTRmNzljYmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1MzI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNDhjYzk1MGFkM2FjZGFlYmFjZWMzMjM3YWYyYWRkMmE0N2Q1MGZhNmEyNjE4YTFlZDM5MWQ5NWRmMWIyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8rioG9YGUsGsemK2o7rppRDufxXClbEmsim98TgTbU">
> 
> I don't see harm in removing it. But, this is coming from the [AI usecase](https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications) samples https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications Do you think both use cases should be updated? @anupama-pathirage

It is fine to have it in AI page in that explicit sample as its main point is about `robust apis`. So retry is a good thing to explain the robustness there.

But in the `Refining data excellence` title of the ETL page, we are talking about AI capabilities. So IMO it is an overhead to have retry config here.

**Comment by anupama-pathirage** [comment]
Closing as this is done and page is live. https://ballerina.io/usecases/etl/
