### ISSUE TITLE
Improve the `bal version` command output

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#8613]
## Description
The `bal version` command output specifies constant spec and tool versions and uses a placeholder to point out the Ballerina version (https://ballerina.io/downloads/installation-options/#verify-the-installation). We need to add placeholders for tool and spec versions as well.

**Comment by praneesha** [comment]
Closing as this is done via https://github.com/ballerina-platform/ballerina-dev-website/pull/8614.
