### ISSUE TITLE
GraphQL Learn page : Add sample cURL to invoke the mutation as well. 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8640]
## Description
$subject in https://ballerina.io/learn/write-a-graphql-api-with-ballerina/

Under https://ballerina.io/learn/write-a-graphql-api-with-ballerina/#try-the-service , It has only the details on query. Add the details on how to execute the mutation as well.

**Comment by ThisaruGuruge** [comment]
There's no much difference between the cURL commands for query and mutation. It's the same request but with a different query document. Do we really need to duplicate that?

**Comment by anupama-pathirage** [comment]
The [complete code](https://ballerina.io/learn/write-a-graphql-api-with-ballerina/#the-complete-code) contains a remote method.  

```ballerina
remote function add(CovidEntry entry) returns CovidData {
        covidEntriesTable.add(entry);
        return new CovidData(entry);
    }
```

But the guide doesn't have any mention of how to invoke it. Also not anything about how the mutation gq query will look like

i.e. something like below

```ballerina
mutation {
  add(entry: {isoCode: "DC", country: "LK"}) {
    country
  }
}

```

So IMO, to make the guide complete we better include it.

**Comment by ThisaruGuruge** [comment]
Will update this.

**Comment by anupama-pathirage** [comment]
@ThisaruGuruge can we add this to the update 9 related documentation work and get it done by update 9?

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge can we add this to the update 9 related documentation work and get it done by update 9?

Okay. We will add this for Update 9.

**Comment by ThisaruGuruge** [comment]
Removed the cURL command and updated it with GraphiQL client.

**Comment by anupama-pathirage** [comment]
Closing the issue since this is done.
