### ISSUE TITLE
GraphQL try it tool details are missing in the learn page guide.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8641]
## Description

$subject in https://ballerina.io/learn/write-a-graphql-api-with-ballerina/#try-the-service

It says to use external tool to try it while we have our own one.

<img width="833" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/9ceec255-138e-4525-ba73-a53721dc4e7c">

**Comment by anupama-pathirage** [comment]
@ThisaruGuruge wdyt about this? can we add this to the update 9 related documentation work and get it done by update 9?

**Comment by ThisaruGuruge** [comment]
> @ThisaruGuruge wdyt about this? can we add this to the update 9 related documentation work and get it done by update 9?

+1. Will update the learn page with the updates. BTW, will it be okay to suggest the built-in GraphiQL client instead of the try-it tool? Try it tool is quite old and the GraphiQL tool is comparably easy to use. WDYT?

**Comment by ThisaruGuruge** [comment]
We will go ahead with GraphiQL tool.

**Comment by anupama-pathirage** [comment]
Closing as this is done.
