### ISSUE TITLE
Two samples in the AI use cases page is not working.

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#8648]
## Description
$subject

Due to an API endpoint shutdown by the Open AI below two samples are not working. Below are the two samples.
- [Write robust API powered AI applications](https://ballerina.io/usecases/ai/#write-robust-api-powered-ai-applications).
- [Bring text alive with openai chat (Sample 2)](https://ballerina.io/usecases/ai/#bring-text-alive-with-openai-chat). 

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by LakshanWeerasinghe** [comment]
@anupama-pathirage I think we have to temporally remove these two samples since we have an AI related tech talk.

**Comment by LakshanWeerasinghe** [comment]
We can update the samples accordingly once this [issue](https://github.com/ballerina-guides/ai-samples/issues/70) is addressed.

**Comment by anupama-pathirage** [comment]
Thanks for brining this up @LakshanWeerasinghe 
@malithjayasinghe / @nadheesh It seems we have to remove those blades for now?

**Comment by nadheesh** [comment]
@anupama-pathirage we will have to remove those blades, and retire those connectors. Those models are now retired. https://platform.openai.com/docs/deprecations

**Comment by anupama-pathirage** [comment]
@NipunaRanasinghe Can we now revamp these blades with the new connector release?

**Comment by DevAakif** [comment]
> @shafreenAnfar, @xlight05, and I had an offline discussion on the above and please find the meeting notes below:
> 
> - In the long run we need to rethink our AI blades, primarily to align them with the new Ballerina AI plans.
> - Until we reach that point, we'll the remove outdated blades (e.g., OpenAI text connector samples) and update the remaining blades to support the newly revamped connectors recently released to the central.
> 
> Action Items:
> 
> - [ ] Review all existing AI code samples and update them to work with the new revamped connector versions in Central - (Assignee: Aakif Ahamed)
> 

I'm currently in progress with this.  Planning to complete it this week.
