### ISSUE TITLE
Switching to Swan Lake from deafult page of a module API Doc results in 404 - Not Found

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-dev-website#865]
**Description:**
When trying to select Swan Lake documentation from the default page of a module API Doc, the resulting page is not found. This is due to a URL change in the API Docs.

URL the page is redirected to (which gives a 404 - Not Found):
http://dev.ballerina.io/swan-lake/learn/api-docs/ballerina/test/index.html

Expected URL
http://dev.ballerina.io/swan-lake/learn/api-docs/test/index.html

**Steps to reproduce:**

1. Visit the default page for test module: http://dev.ballerina.io/learn/api-docs/ballerina/test/index.html
2. Select the version _Swan Lake_ and wait till the page is loaded.

**Comment by Thimuth** [comment]
This has been fixed with introducing /ballerina directory to Swan Lake API docs
