### ISSUE TITLE
Several links provided in learn pages related to SQL databases are not working

### ISSUE THREAD

**Issue by ShammiL** [ballerina-platform/ballerina-dev-website#8671]
## Description
> In the learn pages for [`SQL`](https://central.ballerina.io/ballerina/sql/latest), [`MySQL`](https://central.ballerina.io/ballerinax/mysql/latest), [`PostgreSQL`](https://central.ballerina.io/ballerinax/postgresql/latest), [`MSSQL`](https://central.ballerina.io/ballerinax/mssql/latest) and [`Oracle`](https://central.ballerina.io/ballerinax/oracledb/latest) contain several links that are not working as expected. 

For instance,
1. Links pointing to `connectionPool` or `options` records has a URL that follows the format "https://central.ballerina.io/ballerina/<library>/latest/records/<record_name>" but instead should follow the format "https://central.ballerina.io/ballerina/sql/<version>#<record_name>"
2. Links pointing to `Client` objects has a URL that follows the format "https://central.ballerina.io/ballerinax/<library>/latest/clients/Client" but instead should follow the format "https://central.ballerina.io/ballerinax/<library>/<version>#Client"

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
@daneshk / @Bhashinee any update on this? Please get this fixed asap.
