### ISSUE TITLE
Improvement in Ballerina Persist documentation

### ISSUE THREAD

**Issue by shayanmalinda** [ballerina-platform/ballerina-dev-website#8688]
## Description
I was trying to use Bal persist by pointing out to a MySQL database.
I was referring below documentation and it says that
```
Along with the bal persist init command, you can specify the datastore that you are going to use in the application and also the module that you need to add the generated code to. Both these parameters are optional. If you don’t provide them, the datastore will be set to inmemory, and the module will be set to root module by default.
```
[https://ballerina.io/learn/manage-data-persistence-with-bal-persist/](https://ballerina.io/learn/manage-data-persistence-with-bal-persist/)

But this doesn't mention how I can specify the datastore.
It will be better if we can include that step in this documentation.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following.

**Comment by TharmiganK** [comment]
There should be link to this page: https://ballerina.io/learn/supported-data-stores/
@daneshk @sahanHe FYI
