### ISSUE TITLE
Edit on github links in the pages are broken

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#87]
**Description:**
$subject in the each of b.io page as it redirects to non-existing github branch [1] 

[1] https://github.com/ballerina-platform/ballerina-www/tree/1.0 rc1/website/two-column-pages/docs/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Checked a few GitHub edit icon links and they are properly redirected to [1] now.

[1] https://github.com/ballerina-platform/ballerina-platform.github.io/tree/master/learn
