### ISSUE TITLE
Table has incorrect styles

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#8701]
## Description
> 

The table in https://pre-prod.ballerina.io/learn/test-ballerina-code/write-tests/#use-assertions has incorrect styles.

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/719d827c-5a5e-4e13-a9bb-e6966b000d25)

Refer the styles used at https://pre-prod.ballerina.io/learn/openapi-tool/#openapi-to-ballerina-command-options

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
@Dilhasha Please check and get this fixed asap
