### ISSUE TITLE
Incomplete line in bal persist documentation

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-dev-website#8704]
## Description
> $subject. Please refer to the screenshot below.

<img width="1400" alt="Screenshot 2024-02-20 at 15 06 36" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/5234641/ec655417-eb0b-4ef7-bfeb-700d492ce009">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
@daneshk / @Bhashinee Any update on this? Please get this fixed asap
