### ISSUE TITLE
Improvement in Ballerina FFI documentation

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-dev-website#8708]
## Description
> I was trying to write the ballerina external function that has Java implementation with my own class instead of the java pre build class. I was referring below documentation and it says that
```
The @java:Method annotation instructs the jBallerina compiler to link to the doSomethingInJava static method in the a.b.c.Foo Java class. 
```
https://ballerina.io/learn/ballerina-ffi/ 
But this doesn't mention where I need to put my own Java implementation (a.b.c.Foo java class) to have bindings. It would be helpful if it could be mentioned within the documentation.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

**Comment by anupama-pathirage** [comment]
@HindujaB / @warunalakshitha Any update on this, Please check and fix it asap.

**Comment by HindujaB** [comment]
The external java dependencies can be defined in the `Ballerina.toml` which is mentioned in here.
https://ballerina.io/learn/manage-dependencies/#manage-platform-dependencies
We need to add a link to this page in the FFI documentation.
