### ISSUE TITLE
Asert Function signatures listed in learn page is not matching with actual assert equal signatures

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8722]
## Description
$subject in https://pre-prod.ballerina.io/learn/test-ballerina-code/write-tests/#use-assertions

It does not match with the assert function signatures in API docs: https://central.ballerina.io/ballerina/test/2201.8.2

For ex check below functions. But check all the other functions too. 

<img width="807" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/492674a4-5ad3-4c8e-a971-91f4a3ff833b">

<img width="962" alt="image" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/f4a84620-b66a-46ac-8464-16a16c325522">

**Comment by Dilhasha** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-dev-website/pull/8730
