### ISSUE TITLE
Move proxy configuration to a separate page

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-dev-website#8728]
## Description
> Currently, the proxy configuration is under `Publish a package to Ballerina Central` page. Instead, we should have a separate page for ease of search.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

Area/LearnPages

**Comment by anupama-pathirage** [comment]
@anuruddhal / @azinneera Any update on this? @keizer619 This will allow us to add documentation of proxy related things of update tool as well?

**Comment by azinneera** [comment]
This is not done yet. Will move it to a separate page with the update 9 release.
