### ISSUE TITLE
Fix explanation on `.` in the `REST service - Service and resource paths` BBE

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#8734]
## Description
Need to fix the explanation below on `.` in the [`REST service - Service and resource paths` BBE](https://ballerina.io/learn/by-example/http-service-and-resource-paths/).

`    // The `.` represents the current resource that is `/info`.`

<img width="1331" alt="Screenshot 2024-02-26 at 15 40 14" src="https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/f5cf44b5-6ffb-45e0-8769-1c0caaba6cdd">

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
@TharmiganK any update on this?

**Comment by TharmiganK** [comment]
> @TharmiganK any update on this?

@anupama-pathirage I could not be able to work on this since I am working on some priority features with Update 9. Is it ok to fix this after the code freeze (4th April, 2024)?

**Comment by anupama-pathirage** [comment]
> > @TharmiganK any update on this?
> 
> @anupama-pathirage I could not be able to work on this since I am working on some priority features with Update 9. Is it ok to fix this after the code freeze (4th April, 2024)?

Yes, lets get it fixed after code freeze.

**Comment by TharmiganK** [comment]
Fixed with the above PRs
