### ISSUE TITLE
Improve the `Healthcare` use cases page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#8742]
## Description
Need to do the improvement below in the [`Healthcare` use cases page](https://ballerina.io/usecases/healthcare/).

**Improvements for the Healthcare Page**

1. We can say the below in a better way, like “Develop your healthcare solutions with Ballerina and make a difference in the healthcare sector today”.
![unnamed](https://github.com/ballerina-platform/ballerina-dev-website/assets/11707273/5fcbfe5b-e384-4c67-9dfc-79619dee9ece)
2. Can improve the `Why is Ballerina the way to write healthcare applications?` to say,  `What makes Ballerina the ideal choice for developing healthcare applications?`
3. Better to add the link to the official HAPI website in the first occurrence: [https://hapi.dev/](https://hapi.dev/)
4. Add links to all third-party technologies in their first occurrence.
5. Should be `cloud-native` in `However, cloud native healthcare application development goes beyond`.
6. Should be `first-class` in `as first class citizens`.
7. This phrase should be connected to a sentence: `Go below the hood and connect directly to a database as well if that is the only way to fetch data.`
8. Should be `out-of-the-box` in `out of the box handling`.
9. The long version of the FHIR abbreviation is introduced in https://ballerina.io/usecases/healthcare/#ballerina-is-fhir. Better to introduce it in the first occurrence of the page.
10. Need to add the Oxford comma in: `Ballerina is a language built from ground up for building healthcare applications, quickly, easily and securely`.
11. Need to add the fullstop in this code comment: `// The following example is a simple serialized Patient resource to parse`
12. Need to add the fullstop in this code comment:  `// Access the parsed data`
13. Can add links to FHIR and HL7 from the respective sections.
14. Need to review language issues in code comments.
15. Should be `connectors for` in `Ballerina has 100s of connectors to well-known Health Systems such as…`
16. Is it correct to say `non-health systems`?
17. Should `region specific` be `regional-specific` in: `more region specific standards`
18. The word `code gen` doesn’t sound correct here: `AI code gen like Github Copilot knows Ballerina.`
19. Need to add the Oxford comma here: `Java, .Net and Python`

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by isuruuy429** [comment]
https://github.com/ballerina-platform/ballerina-dev-website/pull/9506

**Comment by MaryamZi** [comment]
Done in #9506.
