### ISSUE TITLE
Typo in "Interface to External Code" BBE

### ISSUE THREAD

**Issue by DimuthuMadushan** [ballerina-platform/ballerina-dev-website#8798]
## Description
>$subject

https://ballerina.io/learn/by-example/interface-to-external-code/

![Screenshot from 2024-03-13 13-35-42](https://github.com/ballerina-platform/ballerina-dev-website/assets/35717653/64c76a28-f7a7-4ebf-ada7-36b598402d16)

**Comment by anupama-pathirage** [comment]
@hasithaa / @MaryamZi Please check and get this fixed asap.
