### ISSUE TITLE
Incorrect wording on Quick Start Link in the learn page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#88]
**Description:**
$subject with the learn page [1]

Shall we rename that to "Quick Tour"?

<img width="754" alt="image" src="https://user-images.githubusercontent.com/16300038/64597839-39eef580-d3d4-11e9-906d-6880e4611ed4.png">

[1] https://v1-0.ballerina.io/learn/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing as this is addressed in [1] via [2].

[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/47
[2] https://github.com/ballerina-platform/ballerina-dev-website/pull/53
