### ISSUE TITLE
Improve configurable learn page to include env variable based configuration

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-dev-website#8862]
## Description
$subject

## Related website/documentation area
Area/LearnPages

## Describe the problem(s)
https://github.com/ballerina-platform/ballerina-lang/issues/42083

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by anupama-pathirage** [comment]
Closing as this is done.
