### ISSUE TITLE
Getting corrupted page when try to download macOs installer

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-dev-website#89]
**Description:**
1) $Subject when try to download from here https://v1-0.ballerina.io/downloads/

![image](https://user-images.githubusercontent.com/4163165/64587497-38fe9980-d3bd-11e9-960a-cce281e233c9.png)

**Environment:**

Chrome

**Comment by praneesha** [comment]
Checked [1] and the issue is resolved now. Please reopen if the issue prevails.

[1] https://ballerina.io/
