### ISSUE TITLE
Omit empty mapping constructors from annotations in the style guide

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-dev-website#8928]
## Description
As specified in the spec https://ballerina.io/spec/lang/master/#section_9.1, the annotation value can be optional. Therefore, it is valid to write `@test:Config` for the following source code.

https://github.com/ballerina-platform/ballerina-dev-website/blob/d11afb0dcdf6b4b121c4bc5440a937aaf604d8d6/swan-lake/development-tutorials/source-code-dependencies/style-guide/annotations-documentation-and-comments.md?plain=1#L30-L37

IMO, omitting the mapping constructor when the value is absent should be considered best practice since it simplifies writing and improves readability.

**Comment by azinneera** [comment]
This was fixed in https://github.com/ballerina-platform/ballerina-dev-website/pull/8966
