### ISSUE TITLE
Include the best practice for documenting a Ballerina record in the style guide

### ISSUE THREAD

**Issue by nipunayf** [ballerina-platform/ballerina-dev-website#8929]
## Description
ATM, the style guide does not specify what the best practice is for documenting a record: https://ballerina.io/learn/style-guide/annotations-documentation-and-comments/#documentation. Currently, there are two approaches to document a record.

1. Attach the documentation at the top of the type.

```ballerina
# Represents a user.
#
# + id - id of the user
# + name - name of the user  
# + isMember - whether the user is a member
type User record {|
    int id;
    string name;
    boolean isMember;
|};
```

2. Include the documentation along with the record field.

```ballerina
# Represents a user.
type User record {|
    # Id of the user
    int id;
    # Name of the user
    string name;
    # Whether the user is a member
    boolean isMember;
|};
```

The **latter approach** is used as a best practice within the Ballerina team. Even with the considered approach, it is yet unclear whether to leave a space between the fields for better readability. IMO, when a node has more metadata, having a space in between can enhance the readability of the code.

```ballerina
// Approach 1: Without the spaces in between
# Represents a user.
type User1 record {|
    # Id of the user
    @constraint:Int {
        maxDigits: 10
    }
    int id;
    # Name of the user
    @constraint:String {
        minLength: 5,
        maxLength: 20
    }
    string name;
    # Address of the user
    @constraint:String {
        minLength: 20,
        maxLength: 100
    }
    string address;
|};


// Approach 2: With the spaces in between
# Represents a user.
type User2 record {|
    # Id of the user
    @constraint:Int {
        maxDigits: 10
    }
    int id;

    # Name of the user
    @constraint:String {
        minLength: 5,
        maxLength: 20
    }
    string name;

    # Address of the user
    @constraint:String {
        minLength: 20,
        maxLength: 100
    }
    string address;
|};
```

**Comment by heshanpadmasiri** [comment]
One concern with the purposed solution is how "hover" is implemented in LS side,

<img width="512" alt="image" src="https://github.com/user-attachments/assets/6251bc9d-02c7-452d-b501-01864a699988">

<img width="343" alt="image" src="https://github.com/user-attachments/assets/a03cd46f-4ce0-40a6-9d78-2605df210e11">

Currently when you hover over the type it only shows the doc comment right above the type definition. So with the purposed approach it will not show the fields

**Comment by nipunayf** [comment]
We have decided to adopt the latter approach for both code actions and hover features. However, these changes have not yet been integrated into the LS.

https://github.com/ballerina-platform/ballerina-lang/issues/41720
