### ISSUE TITLE
Add a sample code to `HTTP API Designer` documentation

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-dev-website#8973]
## Description
In the [HTTP API Designer documentation](https://ballerina.io/learn/vs-code-extension/design-the-services/http-api-designer/), a sample http service code has not been provided. 

However in the [GraphQL API designer documentation](https://ballerina.io/learn/vs-code-extension/design-the-services/graphql-api-designer/), there is a sample that can be easily copied to create a sample project and test out the features in the documentation. 

Having a such sample code will help new developers to learn the API designer features quickly.

Also, the first paragraph of the documentation is duplicated twice.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by daneshk** [comment]
Related issue: https://github.com/ballerina-platform/ballerina-dev-website/issues/9346
