### ISSUE TITLE
[EDI Tool] Sentence fragment in EDI tool page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8974]
## Description
$subject in https://ballerina.io/learn/edi-tool/

Refer to the section [Define EDI Schema](https://ballerina.io/learn/edi-tool/#define-edi-schema). Is it just the full stop missing or some part missing?

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/28aa9ccf-1df0-4231-990c-2c30cbf4a6f0)

**Comment by RDPerera** [comment]
Yes, this is a mistake; I'll fix it.

**Comment by sm1990** [comment]
This was fixed via the above PRs.
