### ISSUE TITLE
Incorrect `library` terminology used in edi tool page

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#8977]
## Description

$subject in https://ballerina.io/learn/edi-tool/#library-generation

It is fine to have `libgen` as the command. But using the term `libray` in the context of ballerina package is misleading. It should be `package` or `packages`

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/606aa905-6627-47ad-9f19-14db32b38429)

Also use backticks to highlight these commands below. 

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/16300038/75c55e04-3300-4489-bcbd-547291bb9407)

**Comment by RDPerera** [comment]
Sure. Let's correct this everywhere. I'll make the necessary changes.
