### ISSUE TITLE
Can’t view the spec page table on mobile

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#90]
![7EEDA405-455A-42E5-BAF8-B132A6681670](https://user-images.githubusercontent.com/6260009/64584609-136c9280-d3b3-11e9-88fc-e720a009e417.png)
 Can’t scroll the page horizontally

**Comment by madhuramendis** [comment]
There is a horizontal scroll in the table.

**Comment by Samallama** [comment]
@praneesha as Madhura mentioned, there's a horizontal scroll in the mobile version, which you can use to scroll and view the rest of the table.

**Comment by praneesha** [comment]
+1 Let's close the issue for the moment as discussed with @pubudu91 also.
