### ISSUE TITLE
Typo in the link to AdoptOpenJDK

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#901]
It says "AdaptOpenJDK" instead of "AdoptOpenJDK" in https://ballerina.io/swan-lake/learn/installing-ballerina/#installing-via-the-ballerina-language-zip-file

Need to check and fix in all versions. Saw the same in 1.2.4

**Comment by praneesha** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-dev-website/pull/900/files.
