### ISSUE TITLE
Update Third-Party Logos Based on Usage Policy Guidelines in the Community page

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9021]
## Description
> $subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
As per the discussion we had with the Legal team, the issue with current design is that logos and the respective CTA links were all wrapped in one box to create a button.  I separated the two, and came up with the below design. @anupama-pathirage & @keizer619 please share your feedback.

![Screenshot from 2024-05-08 20-30-44](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/308f3d20-0963-461a-a28d-73f85f30238c)

**Comment by sm1990** [comment]
@anupama-pathirage & @keizer619 Please review the following designs as well.
**option 2**
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/6e6bb5b1-95e6-45fa-bdd6-1a56bdfb5914)

**option 3**
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/378d0d68-b5af-4571-aa05-0ef8b637d6fa)

**Comment by anupama-pathirage** [comment]
Do we really need these CTA text boxes? Isn't it obvious what it is about when someone see the logos?

**Comment by sm1990** [comment]
> Do we really need these CTA text boxes? Isn't it obvious what it is about when someone see the logos?

Yes. I didn't have them in my original design during the community page revamp. Everyone said that the blade looks empty with just the logos.

**Comment by anupama-pathirage** [comment]
Logos without boxes looks fine to me, but this 3 row view doesn't look correct to me. Can we either have them in 1 or 2 rows under the text?

**Comment by sm1990** [comment]
@anupama-pathirage WDYT about this design?
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/9a94ca2f-15b9-46fb-bbda-0d6c28eaf3ff)

**Comment by anupama-pathirage** [comment]
looks good. 

Can we do some reordering to have X and Linkedin in same row?

May be Discord, SO, GH and YT in first row and X, LI and Meetup on second row?

**Comment by sm1990** [comment]
@anupama-pathirage 
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/1e43c1ce-daed-4a9e-bd98-611e53c2f520)

**Comment by anupama-pathirage** [comment]
Looks good. Lets proceed.
