### ISSUE TITLE
Add best practice of using string templates longer than 120 chracters

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#9061]
## Description
$subject

Currently there is no documentation specifying how to use string templates when the character count exceeds 120. There was a [spec discussion](https://github.com/ballerina-platform/ballerina-spec/issues/1253) went previously and the team came to a conclusion on what the developer should do in such a scenario.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by gimantha** [comment]
Completed with https://github.com/ballerina-platform/ballerina-distribution/pull/5688
