### ISSUE TITLE
Improve Outline section in Student Engagement page

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9075]
## Description
>$subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@azinneera & @keizer619  please review the design
![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/dd4ab489-1072-410c-b53b-6afea488540a)

**Comment by azinneera** [comment]
+1 to Option 2

**Comment by sm1990** [comment]
> +1 to Option 2

If possible share the link for` Open source projects`. I'll share the `Project mentorship` page soon. We are tracking it via https://github.com/ballerina-platform/ballerina-dev-website/issues/9076

**Comment by azinneera** [comment]
> > +1 to Option 2
> 
> @azinneera if possible share the link for` Open source projects`. I'll share the `Project mentorship` page soon. We are tracking it via #9076

https://github.com/orgs/ballerina-platform/projects/369

**Comment by sm1990** [comment]
This is in production now - https://ballerina.io/community/student-program/
