### ISSUE TITLE
Create new Project mentorship page

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9076]
## Description
>$subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this new feature.

## Describe your solution(s)
> A detailed description of how this new feature will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@azinneera @keizer619 Please review the following design
![screencapture-localhost-3000-community-student-program-project-mentorship-2024-06-25-11_59_44](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/6f8285ec-2e7f-4f3c-9c22-1a1837fcc5c2)

**Comment by azinneera** [comment]
Can we have a format where we can show projects as much as possible so that all projects get the same level of visibility?
When we reach a point where we have 50+ projects to show (which will take a significant time), we can rethink a better view.

**Comment by sm1990** [comment]
@azinneera & @keizer619 please review the updated design below.

Instead of using blades for `Past`, `Ongoing` , & `Upcoming` the new design uses tabs. Next to the title of the tab, the number of  projects in each category is shown. Initially 8 projects are shown for each category. If there are more, a `Show more` button will appear at the bottom as shown in the screenshot below.

![screencapture-localhost-3000-community-student-program-project-mentorship-2024-07-02-21_33_54](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/d3f3009b-1b24-458b-a4c7-32420bfe0e15)

I've also added a filter to filter the projects by the technologies used.

![image](https://github.com/ballerina-platform/ballerina-dev-website/assets/7709843/5dfbee3a-9659-4110-9d83-233cac8abad5)

**Comment by azinneera** [comment]
The students must be able to share a link to their project. Also, how does the `Learn More` work? Is it a new page or an expand/collapse kind of design? Students must be able to get a shareable link for their project.

**Comment by sm1990** [comment]
> The students must be able to share a link to their project. Also, how does the `Learn More` work? Is it a new page or an expand/collapse kind of design? Students must be able to get a shareable link for their project.

@azinneera `Learn more` links to the GitHub repo of the project. The page will open in a new tab.
As for the shareable link I can add a `Share` button. But what should be the link? is it the current page in B.io or the GitHub repo?

**Comment by sm1990** [comment]
This is live. https://ballerina.io/community/student-program/project-mentorship/
