### ISSUE TITLE
SEO Improvements - Remove duplicated meta descriptions

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9115]
## Description
> $subject

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sm1990** [comment]
@anupama-pathirage @keizer619 Please review the new descriptions in https://docs.google.com/spreadsheets/d/1MZuw8yS6pArx4EogCKuUOa_N3lpX0IfryX3ye5MzmL8/edit?usp=sharing

**Comment by anupama-pathirage** [comment]
@sm1990 Descriptions are fine but a bit too lengthy. Those are a bit too lengthy for optimal SEO (ideal is 150-160 characters). Can you try to come up with a summarized version of those?

**Comment by sm1990** [comment]
> @sm1990 Descriptions are fine but a bit too lengthy. Those are a bit too lengthy for optimal SEO (ideal is 150-160 characters). Can you try to come up with a summarized version of those?

@anupama-pathirage I have the new description in the `Updated Description` column in the same sheet.
