### ISSUE TITLE
Move build from source file to website repo

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-dev-website#9191]
## Description
$subject. 

Referred from this https://ballerina.io/downloads/installation-options/#build-from-source

Current .md page is in dist repo. We need to move it to website repo and make it a webpage. 

https://github.com/ballerina-platform/ballerina-distribution/blob/master/docs/build-ballerina-from-source.md

**Comment by sm1990** [comment]
@anupama-pathirage & @keizer619 what is the preferred url:
option 1 :- https://ballerina.io/downloads/build-from-source
option 2 :- https://ballerina.io/downloads/installation-options/build-from-source

**Comment by sm1990** [comment]
> Since its not related to download i feel like https://ballerina.io/learn/build-from-source would be fine. We are treating it as a learn page

In that case, what is the section we should list it under in the landing page (https://ballerina.io/learn/)?

**Comment by anupama-pathirage** [comment]
I prefer to have  option two i.e. https://ballerina.io/downloads/installation-options/build-from-source . Reasons : 
1. It is referred from https://ballerina.io/downloads/installation-options/#build-from-source
2. In a way it is related to downloads (download the source and build)
3. Having it under learn will make it more complicated with location in learn landing page etc. And not related to learning the product. So need to categorize under learn.
