### ISSUE TITLE
Quick Tour Documentation issues

### ISSUE THREAD

**Issue by keshiha96** [ballerina-platform/ballerina-dev-website#92]
**Description:**
1.In the quick tour documentation ballerina run hello_service.bal is not highlighted as a command.
2.Step 9 says only add and subtract are implemented, but all 4 functions have been already implemented.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
Closing since these instructions are not included in the revamped Quick Tour [1]. Please reopen if any further improvements are required.

[1] https://ballerina.io/learn/quick-tour/
