### ISSUE TITLE
Expand the scope of the `Service data binding` BBE

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#9282]
The `Service data binding` example (https://pre-prod.ballerina.io/learn/by-example/http-data-binding/) does not explain the data binding capability in Ballerina.

In services and clients, data binding refers to the process of dynamically binding request or response payloads to the domain-specific types (domain model) defined in the application. 

Shall we redesign this example to explain data binding in services in general? E.g., show a get resource first, explain data binding, and move on to a post resource. Improve the BBE description as well. At the moment, it talks about receiving a POST payload.

**Comment by daneshk** [comment]
We recently revamped the BBEs and now have data binding examples for HTTP client[1] and HTTP service[2]. These examples show how response data is bound to the ballerina type in the client-side BBE and request data is bound to the ballerina type in the server-side BBE.

1. https://ballerina.io/learn/by-example/http-client-data-binding/
2. https://ballerina.io/learn/by-example/http-service-data-binding/

**Comment by daneshk** [comment]
@TharmiganK Shall we add both `get` and `post` resources in client and server BBEs to demonstrate both request and response data bindings? WDYT?

**Comment by TharmiganK** [comment]
@daneshk I think we have decided to use one resource to make the BBE simple and understandable. The client BBE represents only the response data binding in the client and the service BBE represents only the request data binding in the service

**Comment by daneshk** [comment]
As per the above comments, we already addressed those issues. Hence closing the issue.
