### ISSUE TITLE
Make `REST Client` example list comprehensive

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#9283]
Consuming services is a key area in Ballerina, but there are only two examples in the `REST Client` category. There are many commonly used features of the REST client that we can cover here. 

Here are the areas that I can think of. Feel free to slice and dice. I am not hinting at any order of examples here, just a list of ideas.
- Basic REST client (Briefly explain the client resource concept)
- Client resources functions vs. client remote functions: when to use what. 
- GET request with path params
- GET request with query params
- POST/PUT/DELETE/PATCH/HEAD requests
- Databinding in REST clients (use this examples show to sent TEXT/)
- REST client with JSON payloads
- Making requests with HTTP headers (explain `addHeader` vs `setHeader`)
- When to use `http:Request`?
- Configuring HTTP clients with `http:ClientConfiguration` for common configurations, ask them to use API docs for further information

See this query. We can convert the answer to the following query into a BBE. 
https://stackoverflow.com/questions/74469899/sending-a-post-request-from-ballerina

**Comment by daneshk** [comment]
During the latest BBE revamp, we covered most REST Client use cases. @TharmiganK, can you check and close this issue?

**Comment by TharmiganK** [comment]
| Area | BBE |
| ---- | ---- |
| Basic REST client (Briefly explain the client resource concept) | https://ballerina.io/learn/by-example/http-client-send-request-receive-response/ |
| Client resources functions vs. client remote functions: when to use what. | The BBEs only have resource functions. The remote functions are suggested in proxy services to forward requests, and when we have complex path parameters or when we have different type of query serializations(other than the default one supported in the resource methods |
| GET request with path params | https://ballerina.io/learn/by-example/http-client-path-parameter/ |
| GET request with query params |https://ballerina.io/learn/by-example/http-client-query-parameter/  |
| POST/PUT/DELETE/PATCH/HEAD requests | Explained in the client BBE: https://ballerina.io/learn/by-example/http-client-send-request-receive-response/ |
| Databinding in REST clients (use this examples show to sent TEXT/) | https://ballerina.io/learn/by-example/http-client-data-binding/ |
| REST client with JSON payloads | Explained in the client BBE: https://ballerina.io/learn/by-example/http-client-send-request-receive-response/  |
| Making requests with HTTP headers (explain addHeader vs setHeader) | https://ballerina.io/learn/by-example/http-client-header-parameter/. Here we passed the headers directly with the resource functions. We have the difference for `addHeader vs setHeader` in the API docs. In the general BBEs does not use request or response objects. We have a advanced sections which have the request or response objects  |
| When to use http:Request? | Explained in the advanced BBEs. For example: https://ballerina.io/learn/by-example/http-request-with-multiparts/ |
| Configuring HTTP clients with http:ClientConfiguration for common configurations, ask them to use API docs for further information | We have samples with SSL, Cache, Resiliency which involves the client configurations and we points to the API docs for more information. For example: https://ballerina.io/learn/by-example/http-caching-client/ |

**Comment by TharmiganK** [comment]
Since most of the points are covered in the BBE revamp closing this issue.
