### ISSUE TITLE
API documentation for graphql.subgraph submodule returns 500 error

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-dev-website#9284]
**Description:**
$subject

link: https://lib.ballerina.io/ballerina/graphql.subgraph/1.9.0

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by sm1990** [comment]
This is fixed now.
