### ISSUE TITLE
Improve Join Iterable objects BBE

### ISSUE THREAD

**Issue by LakshanWeerasinghe** [ballerina-platform/ballerina-dev-website#9285]
**Description:**
$subject

- `join-on-condition` expression in the `join-clause` have restriction for it's expressions. Where the type-binding-pattern symbol of the from-clause should be used as the first expression. This information is missing in the BBE.
- Correct the typo in the BBE description.

**Comment by rdulmina** [comment]
@LakshanWeerasinghe I could not find any typo in the description. https://ballerina.io/learn/by-example/joining-iterable-objects/

**Comment by LakshanWeerasinghe** [comment]
> @LakshanWeerasinghe I could not find any typo in the description. https://ballerina.io/learn/by-example/joining-iterable-objects/

equijoin should be equi-join
