### ISSUE TITLE
Add different query construct BBEs

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-dev-website#9296]
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rdulmina** [comment]
We already have these BBEs

https://ballerina.io/learn/by-example/create-tables-with-query/

**Comment by rdulmina** [comment]
Closing as already completed
