### ISSUE TITLE
Rename gRPC server and client BBE titles 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-dev-website#9297]
Here are my suggestions:
- Server streaming RPC -> Server-side streaming RPC
- Server streaming RPC -> Client-side streaming RPC

**Comment by daneshk** [comment]
This is already fixed. So, I'm closing this issue. Please check the screenshot below



![Image](https://github.com/user-attachments/assets/7eb6a29c-0d88-41b6-b75f-70a9fb42a902)
