### ISSUE TITLE
Add ballerina by examples for CSV data module

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-dev-website#9299]
Add ballerina by examples for CSV data module

- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9448
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9449
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9452
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9455
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9457
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/9461

**Comment by rdulmina** [comment]
Closing this issue as all the sub-tasks are completed
