### ISSUE TITLE
[Quick Start Guide] Improvements on new folder/ file creation location

### ISSUE THREAD

**Issue by Tikiri16** [ballerina-platform/ballerina-dev-website#93]
**Description:**
In all of the following screenshots, there are multiple instances where it's said to create a new file or folder by right clicking on a folder. Creating a new file by this method is not possible in linux and also more importantly, it's unclear whether the new file or folder should be created inside the existing folder or at the same level.
Screenshot 1:
![er1](https://user-images.githubusercontent.com/30475178/63280057-c3287600-c2c7-11e9-95b0-cc18211e8491.png)
Screenshot 2:
![er2](https://user-images.githubusercontent.com/30475178/63280391-55307e80-c2c8-11e9-8d4e-b285fa5d0cb4.png)
Screenshot 3:
![er3](https://user-images.githubusercontent.com/30475178/63280421-5feb1380-c2c8-11e9-8bf4-c6ae2f92e12c.png)

Therefore my suggestion is that it would be better if it is specified in a clearer way such as "Create a new file inside the calculator folder" or "Create a new folder on the same level as calculator folder".
Example solution:
![sol1](https://user-images.githubusercontent.com/30475178/63280695-eacc0e00-c2c8-11e9-92fb-a0cc6c848803.png)

**OS, DB, other environment details and versions:** 
Ubuntu 18.04.3

**Comment by praneesha** [comment]
Closing since these instructions are not included in the revamped Quick Tour [1]. Please reopen if any further improvements are required.

[1] https://ballerina.io/learn/quick-tour/
