### ISSUE TITLE
`Install via the Ballerina language ZIP file` guide is not working properly for Linux.  

### ISSUE THREAD

**Issue by udda1996** [ballerina-platform/ballerina-dev-website#9303]
**Description:**
[Install via the Ballerina language ZIP file](https://ballerina.io/downloads/installation-options/#install-via-the-ballerina-language-zip-file) guide is not complete. Following this steps does not install Ballerina correctly.

**Steps to reproduce:**
1. Download the zip file available in the Ballerina website
2. set the PATH variable to the `bin` file within the distribution downloaded (In this case we need to include the necessary commands required to do this. In the guide we just mention to set the PATH variable without a proper command). 
3. Check the ballerina version using `bal -v`

**Comment by anuruddhal** [comment]
The required steps have already added to the guide. 

https://ballerina.io/downloads/installation-options/#install-via-the-ballerina-language-zip-file
