### ISSUE TITLE
Add an example for annotation access

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#9307]
**Description:**
$title.

**Comment by gimantha** [comment]
Seems the annotation access improvement is added to the BBE. But keeping this to re-evaluate

**Comment by gimantha** [comment]
Closing since this has been fixed. At that time. annotation access was not illustrated. Shown below is the 2021 view
![Image](https://github.com/user-attachments/assets/fec35410-367e-4ba9-9f8e-b1bdb857c5ef)
