### ISSUE TITLE
Assigning the variables for MySQL configuration

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-dev-website#9312]
**Description:**
In the MySQL BBEs, we have used client initialization and database name in more than one place. If users want to run this, needs to change all the places. Therefore, better to assign variables and use them in all the places.

**Comment by daneshk** [comment]
This issue is invalid as we revamped the SQL BBEs later. DB setting up steps moved out from the BBE and moved to the prerequisite section.
