### ISSUE TITLE
Make the configurable BBE a working example

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#9319]
The current configurables BBE (https://ballerina.io/learn/by-example/configurable-variables/) doesn't feel useful. There's no instructions on how to provide the configs. In the very least, it should include how to run the given example using a Config.toml file. So instead of being able to quickly look up how to provide configurables, the user has to wade through the long learn pages to find out the relevant details.

**Comment by HindujaB** [comment]
We introduced two more BBEs to explain how to configure via TOML files and CLI arguments in https://github.com/ballerina-platform/ballerina-dev-website/issues/6019. 
Even though, the BBE https://ballerina.io/learn/by-example/configuring-via-toml/ does not display the `Config.toml` content. Added those changes via this PR : https://github.com/ballerina-platform/ballerina-distribution/pull/5708
