### ISSUE TITLE
Improve the `Typed resource responses` BBE to illustrate a proper use case

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-dev-website#9322]
See https://ballerina.io/learn/by-example/http-resource-returns.html. The example needs to be improved to illustrate the feature it's trying to explain in a better light. For example, 
- Here, it uses a 500 error as a part of the logic in the resource. 
- The API itself, needs to be improved. Currently it feels like a bunch of random stuff has been put together. e.g., the second resource method
- Typos and general improvements to the explanatory comments.

**Comment by daneshk** [comment]
This may not be valid as we revamped the BBEs recently. @TharmiganK could you please check and close it

**Comment by TharmiganK** [comment]
The mentioned BBE has been removed during the revamp effort. The following are the BBEs explaining the resource return types:
- [`REST service - Send response`](https://ballerina.io/learn/by-example/http-send-response/)
- [`REST service - Send different status codes`](https://ballerina.io/learn/by-example/http-send-different-status-codes/)
- [`REST service - Send different status codes with payload`](https://ballerina.io/learn/by-example/http-send-different-status-codes-with-payload/)
- [`REST service - Error Handling`](https://ballerina.io/learn/by-example/http-default-error-handling/)
