### ISSUE TITLE
Add a spell checker as a GitHub Action

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9536]
## Description
> Create a GitHub Action with a spell checker to review the `md` and `js` containing the website content.

The GitHub Action should send an email to the code owners with a spellcheck report.
The Action should run periodically (eg:- once a week) and on demand.
It would be nice if we can maintain a list of words to ignore as well.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by georgioupanayiotis** [comment]
@sm1990 can you assign me this issue?

**Comment by sm1990** [comment]
Sure @georgioupanayiotis . I'll assign it to you. Happy coding!!!!

**Comment by georgioupanayiotis** [comment]
@sm1990 i have created the PR here https://github.com/ballerina-platform/ballerina-dev-website/issues/9536
