### ISSUE TITLE
Ignore code snippets in the Spell checker

### ISSUE THREAD

**Issue by sm1990** [ballerina-platform/ballerina-dev-website#9553]
## Description
>The following GitHub action is used to check the spelling in our content.
https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/workflows/spell-check.yml
https://github.com/ballerina-platform/ballerina-dev-website/blob/master/.github/scripts/spellcheck.py

The final report includes, the code snippets in the `.md` files.
eg:-
`File: swan-lake/vs-code-extension/get-started.md
Misspelled words: sdk:, [multi-root, `1.60.0`, [multiple, later., command., workspace**, [ballerina](https://ballerina.io/downloads/)., multi-root, it., <img, ---, intro:, [visual, [ballerina, packages](#open-multiple-ballerina-packages), **vs, line,, workspace., keywords:, extension,, extension., ballerina,, `ballerina, corner., ###, instructions,, .`, workspace,, [single, editor](https://code.visualstudio.com/download), class="cinlineimage-half"/>, **file, description:, started,, editor,, package](#open-a-single-ballerina-package), file**, title:, <version>`, editor., properly,, package., >**info:**, folder...**,, [adding, **add, package:, `code, package,, ##, methods., time.`

Improve the spell check script so that the inline code snippets (between two single (`) backticks ) and main code snippets (between three (```) backticks) are ignored.

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related website/documentation area
> Add/Uncomment the relevant area label out of the following. 

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by Jaagrav** [comment]
May I work on this task please?

**Comment by Ishad-M-I-M** [comment]
Hi @sm1990 Can I work on this?
