### ISSUE TITLE
Playground widget: bad UX on iPhone. Page crashing

### ISSUE THREAD

**Issue by muescha** [ballerina-platform/ballerina-dev-website#96]
**Description:**
When I open the page ballerina.io on iPhone then I can not (easy) scroll through the code and read it. sometimes it goes into editor and zoom in. Pages chrashing and iOS Safari read the page

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
iPhone 6S+ 
iOS11.4.1 
Safari

**Steps to reproduce:**
- open ballerina.io on iPhone
- select an different example in playground
- not the full code is visible
- try to scroll through the source code 
- it scrolls only sometimes one line per scroll
- many times a swipe has no effecr
- many times a swipe result placing cursor in code and going to editor mode (zoom in + show keyboard) - you struggle hard to zoom out and exit the editor mode
- many times full page crashing and page is reloaded

**Quick Fix**
One very helpfullquick fix can be: autoexpand the code section to show the full code after an change to a different example. Then there is no need to scroll through the code. 

**Related Issues:**

**Comment by praneesha** [comment]
Closing since we do not have the playground widget in the new B.io design[1]. Please reopen if the issue prevails in the new design.

[1] https://ballerina.io/
