### ISSUE TITLE
[Learn] Navigation to API documentation not straightforward

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-dev-website#97]
**Description:**
API docs are listed under Reference Documentation in the https://ballerina.io/learn page.

Currently navigating to API docs is not straightforward, unless known where to look, given that the Table of Contents also contains only high level headings. Could this be improved, maybe by providing a nested ToC indicating sub-headings such as API docs, language specification, etc. at first glance?

**Comment by praneesha** [comment]
This seems to be resolved in the new design [1]. Please reopen if we need any further improvements.

[1] https://ballerina.io/
