### ISSUE TITLE
[Playground Widget] Tab selection is not persisting

### ISSUE THREAD

**Issue by jeradrutnam** [ballerina-platform/ballerina-dev-website#99]
**Description:**
After selecting a tab and change the sample, it's always going to the "Source" tab. Need to persist users selection.

![playground_widget_ux](https://user-images.githubusercontent.com/7569427/41017594-33ad32ee-6973-11e8-9e1a-91a6a4b135ae.gif)

**Affected Product Version:**
v0.9.016

**OS, DB, other environment details and versions:**    
All

**Steps to reproduce:**
Refer the screenshot above

**Comment by praneesha** [comment]
Closing since we do not have the playground widget in the new B.io design[1].

[1] https://ballerina.io/
